# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, floatmode='fixed', suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7F15C4BC2BA0

In [6]:
import torch
from tsdm.datasets import ETTh1
ETTh1.dataset

                       HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
date
2016-07-01 00:00:00   5.827  2.009  1.599  0.462  4.203  1.340  30.531000
2016-07-01 01:00:00   5.693  2.076  1.492  0.426  4.142  1.371  27.787001
2016-07-01 02:00:00   5.157  1.741  1.279  0.355  3.777  1.218  27.787001
2016-07-01 03:00:00   5.090  1.942  1.279  0.391  3.807  1.279  25.044001
2016-07-01 04:00:00   5.358  1.942  1.492  0.462  3.868  1.279  21.948000
...                     ...    ...    ...    ...    ...    ...        ...
2018-06-26 15:00:00  -1.674  3.550 -5.615  2.132  3.472  1.523  10.904000
2018-06-26 16:00:00  -5.492  4.287 -9.132  2.274  3.533  1.675  11.044000
2018-06-26 17:00:00   2.813  3.818 -0.817  2.097  3.716  1.523  10.271000
2018-06-26 18:00:00   9.243  3.818  5.472  2.097  3.655  1.432   9.778000
2018-06-26 19:00:00  10.114  3.550  6.183  1.564  3.716  1.462   9.567000

[17420 rows x 7 columns]

In [15]:
from torch.utils.data import DataLoader

,date,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
0,2016-07-01 00:00:00,5.827,2.009,1.599,0.462,4.203,1.340,30.531000
1,2016-07-01 01:00:00,5.693,2.076,1.492,0.426,4.142,1.371,27.787001
2,2016-07-01 02:00:00,5.157,1.741,1.279,0.355,3.777,1.218,27.787001
3,2016-07-01 03:00:00,5.090,1.942,1.279,0.391,3.807,1.279,25.044001
4,2016-07-01 04:00:00,5.358,1.942,1.492,0.462,3.868,1.279,21.948000
...,...,...,...,...,...,...,...,...
17415,2018-06-26 15:00:00,-1.674,3.550,-5.615,2.132,3.472,1.523,10.904000
17416,2018-06-26 16:00:00,-5.492,4.287,-9.132,2.274,3.533,1.675,11.044000
17417,2018-06-26 17:00:00,2.813,3.818,-0.817,2.097,3.716,1.523,10.271000
17418,2018-06-26 18:00:00,9.243,3.818,5.472,2.097,3.655,1.432,9.778000
17419,2018-06-26 19:00:00,10.114,3.550,6.183,1.564,3.716,1.462,9.567000

array([[Timestamp('2016-07-01 00:00:00'), 5.827000141143799,
        2.009000062942505, ..., 4.203000068664552, 1.3400000333786009,
        30.5310001373291],
       [Timestamp('2016-07-01 01:00:00'), 5.692999839782715,
        2.075999975204468, ..., 4.142000198364259, 1.371000051498413,
        27.78700065612793],
       [Timestamp('2016-07-01 02:00:00'), 5.1570000648498535,
        1.741000056266785, ..., 3.776999950408936, 1.218000054359436,
        27.78700065612793],
       ...,
       [Timestamp('2018-06-26 17:00:00'), 2.812999963760376,
        3.818000078201294, ..., 3.7160000801086426, 1.5230000019073486,
        10.270999908447266],
       [Timestamp('2018-06-26 18:00:00'), 9.243000030517578,
        3.818000078201294, ..., 3.6549999713897705, 1.4320000410079956,
        9.777999877929688],
       [Timestamp('2018-06-26 19:00:00'), 10.11400032043457,
        3.549999952316284, ..., 3.7160000801086426, 1.462000012397766,
        9.56700038909912]], dtype=object)

In [44]:
from numpy.typing import NDArray
def custom_collate(items: list[NDArray]) -> NDArray:
    return np.stack(items, axis=0)

ds = ETTh1.dataset.reset_index().values

array([[Timestamp('2016-07-01 00:00:00'), 5.827000141143799,
        2.009000062942505, ..., 4.203000068664552, 1.3400000333786009,
        30.5310001373291],
       [Timestamp('2016-07-01 01:00:00'), 5.692999839782715,
        2.075999975204468, ..., 4.142000198364259, 1.371000051498413,
        27.78700065612793],
       [Timestamp('2016-07-01 02:00:00'), 5.1570000648498535,
        1.741000056266785, ..., 3.776999950408936, 1.218000054359436,
        27.78700065612793],
       ...,
       [Timestamp('2018-06-26 17:00:00'), 2.812999963760376,
        3.818000078201294, ..., 3.7160000801086426, 1.5230000019073486,
        10.270999908447266],
       [Timestamp('2018-06-26 18:00:00'), 9.243000030517578,
        3.818000078201294, ..., 3.6549999713897705, 1.4320000410079956,
        9.777999877929688],
       [Timestamp('2018-06-26 19:00:00'), 10.11400032043457,
        3.549999952316284, ..., 3.7160000801086426, 1.462000012397766,
        9.56700038909912]], dtype=object)

In [49]:
dloader = DataLoader(ds, collate_fn=custom_collate, batch_size=7)

In [52]:
next(iter(dloader))

array([[Timestamp('2016-07-01 00:00:00'), 5.827000141143799,
        2.009000062942505, 1.5989999771118164, 0.4620000123977661,
        4.203000068664552, 1.3400000333786009, 30.5310001373291],
       [Timestamp('2016-07-01 01:00:00'), 5.692999839782715,
        2.075999975204468, 1.4919999837875366, 0.4259999990463257,
        4.142000198364259, 1.371000051498413, 27.78700065612793],
       [Timestamp('2016-07-01 02:00:00'), 5.1570000648498535,
        1.741000056266785, 1.2790000438690186, 0.3549999892711639,
        3.776999950408936, 1.218000054359436, 27.78700065612793],
       [Timestamp('2016-07-01 03:00:00'), 5.090000152587892,
        1.9420000314712524, 1.2790000438690186, 0.3910000026226044,
        3.806999921798706, 1.2790000438690186, 25.04400062561035],
       [Timestamp('2016-07-01 04:00:00'), 5.357999801635742,
        1.9420000314712524, 1.4919999837875366, 0.4620000123977661,
        3.868000030517578, 1.2790000438690186, 21.947999954223643],
       [Timestamp('2016-07-01 05:00:00'), 5.625999927520752,
        2.1429998874664307, 1.5279999971389768, 0.5329999923706055,
        4.051000118255615, 1.371000051498413, 21.173999786376957],
       [Timestamp('2016-07-01 06:00:00'), 7.166999816894531,
        2.9470000267028813, 2.131999969482422, 0.7820000052452087,
        5.026000022888184, 1.8580000400543213, 22.79199981689453]],
      dtype=object)