# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, floatmode="fixed", suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7F477882CF20

In [4]:
import pandas as pd

signal_df = pd.DataFrame({"X": [1, 2, 3], "Y": [10, 20, 30]})

big_df = pd.DataFrame(
    {
        "SimName": ["Name 1", "Name 2"],
        "Date ": [123, 456],
        "Parameter 1": ["XYZ", "XYZ"],
        "Parameter 2": ["XYZ", "XYZ"],
        "Signal 1": [signal_df, signal_df],
        "Signal 2": [signal_df, signal_df],
    }
)

big_df.loc[0, "Signal 1"]
big_df.loc[0, "Signal 1"]

   X   Y
0  1  10
1  2  20
2  3  30

In [5]:
big_df

,SimName,Date,Parameter 1,Parameter 2,Signal 1,Signal 2
0,Name 1,123,XYZ,XYZ,X Y 0 1 10 1 2 20 2 3 30,X Y 0 1 10 1 2 20 2 3 30
1,Name 2,456,XYZ,XYZ,X Y 0 1 10 1 2 20 2 3 30,X Y 0 1 10 1 2 20 2 3 30