# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

### Format


```python
dict[int, # run_id
    dict[int, # experiment_id
         dict[
             'metadata',: DataFrame,                # static
             'setpoints': DataFrame,                # static
             'measurements_reactor',: DataFrame,    # TimeTensor
             'measurements_array',: DataFrame,      # TimeTensor
             'measurements_aggregated': DataFrame,  # TimeTensor
         ]
    ]
]

```

In [19]:
import pickle
import pandas
import pandas as pd
import numpy as np
from pandas import DataFrame
from cross_validate_kiwi_runs import create_replicate_dict, ReplicateBasedSplitter

with open("kiwi_experiments_and_run_355.pk", "rb") as file:
    data = pickle.load(file)

col_run_to_exp = create_replicate_dict(data)
splitter = ReplicateBasedSplitter()

In [57]:
DATA = [(data[run][exp] | {"run_id": run, "experiment_id": exp}) for run in data for exp in data[run]]
DF = DataFrame(DATA).set_index(["run_id", "experiment_id"])

                                                               metadata  \
run_id experiment_id
355    11722             experiment_id  bioreactor_id  container_num...
       11723             experiment_id  bioreactor_id  container_num...
       11724             experiment_id  bioreactor_id  container_num...
       11725             experiment_id  bioreactor_id  container_num...
       11726             experiment_id  bioreactor_id  container_num...
...                                                                 ...
484    16349             experiment_id  bioreactor_id  container_num...
       16350             experiment_id  bioreactor_id  container_num...
       16351             experiment_id  bioreactor_id  container_num...
       16352             experiment_id  bioreactor_id  container_num...
       16353             experiment_id  bioreactor_id  container_num...

                                                              setpoints  \
run_id experiment_id
355    11722               cultivation_age  setpoint_id   unit  Puls...
       11723               cultivation_age  setpoint_id   unit  Puls...
       11724               cultivation_age  setpoint_id   unit  Puls...
       11725               cultivation_age  setpoint_id   unit  Puls...
       11726              cultivation_age  setpoint_id   unit  Puls_...
...                                                                 ...
484    16349              cultivation_age  setpoint_id    unit  Feed...
       16350              cultivation_age  setpoint_id    unit  Feed...
       16351              cultivation_age  setpoint_id    unit  Feed...
       16352              cultivation_age  setpoint_id    unit  Feed...
       16353              cultivation_age  setpoint_id    unit  Feed...

                                                   measurements_reactor  \
run_id experiment_id
355    11722                  measurement_time  measurement_id unit ...
       11723                  measurement_time  measurement_id unit ...
       11724                  measurement_time  measurement_id unit ...
       11725                  measurement_time  measurement_id unit ...
       11726                  measurement_time  measurement_id unit ...
...                                                                 ...
484    16349                  measurement_time  measurement_id unit ...
       16350                  measurement_time  measurement_id unit ...
       16351                  measurement_time  measurement_id unit ...
       16352                  measurement_time  measurement_id unit ...
       16353                  measurement_time  measurement_id unit ...

                                                     measurements_array  \
run_id experiment_id
355    11722                  measurement_time  measurement_id    un...
       11723                  measurement_time  measurement_id    un...
       11724                  measurement_time  measurement_id    un...
       11725                  measurement_time  measurement_id    un...
       11726                  measurement_time  measurement_id    un...
...                                                                 ...
484    16349                  measurement_time  measurement_id    un...
       16350                  measurement_time  measurement_id    un...
       16351                  measurement_time  measurement_id    un...
       16352                  measurement_time  measurement_id    un...
       16353                  measurement_time  measurement_id    un...

                                                measurements_aggregated
run_id experiment_id
355    11722                  measurement_time    unit  Flow_Air  Fl...
       11723                  measurement_time    unit  Flow_Air  Fl...
       11724                  measurement_time    unit  Flow_Air  Fl...
       11725                  measurement_time    unit  Flow_Air  Fl...
       11726                  measurement_time    unit  Flow_Air  Fl...
...                                                                 ...
484    16349                  measurement_time    unit  Flow_Air  Fl...
       16350                  measurement_time    unit  Flow_Air  Fl...
       16351                  measurement_time    unit  Flow_Air  Fl...
       16352                  measurement_time    unit  Flow_Air  Fl...
       16353                  measurement_time    unit  Flow_Air  Fl...

[240 rows x 5 columns]

In [75]:
tables = {}

for key in ('metadata', 'setpoints', 'measurements_reactor', 'measurements_array', 'measurements_aggregated'):
    if key == "metadata":
        tables[key] = pd.concat(iter(DF[key])).reset_index(drop=True)
    else:
        tables[key] = pd.concat(iter(DF[key]), keys=DF[key].index).reset_index(level=2, drop=True).reset_index()

tables

{'metadata':      experiment_id  bioreactor_id  container_number  profile_id  \
 0            11722            397                 9      6449.0
 1            11723            397                10      6450.0
 2            11724            397                11      6451.0
 3            11725            397                12      6452.0
 4            11726            397                13      6453.0
 ..             ...            ...               ...         ...
 235          16349            588                28     11028.0
 236          16350            588                29     11029.0
 237          16351            588                30     11030.0
 238          16352            588                31     11031.0
 239          16353            588                32     11032.0

     starter_culture_id  inactivation_method_id description_x      color  \
 0                 None                     1.0          None  #FFFF6404
 1                 None                     1.0          None  #FFFFF400
 2                 None                     1.0          None  #FFAFFF00
 3                 None                     1.0          None  #FF00FFAB
 4                 None                     1.0          None  #FF00ABFF
 ..                 ...                     ...           ...        ...
 235               None                     1.0          None  #FFE7298A
 236               None                     1.0          None  #FF66A61E
 237               None                     1.0          None  #FFE6AB02
 238               None                     1.0          None  #FFA6761D
 239               None                     1.0          None  #FF666666

     profile_name  folder_id_x  ...          start_time            end_time  \
 0             A2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 1             B2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 2             C2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 3             D2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 4             E2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 ..           ...          ...  ...                 ...                 ...
 235           D4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 236           E4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 237           F4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 238           G4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 239           H4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27

      description conclusion    container_label is_template Acetate_Dilution  \
 0           None       None  Position,Organism           0              NaN
 1           None       None  Position,Organism           0              NaN
 2           None       None  Position,Organism           0              NaN
 3           None       None  Position,Organism           0              NaN
 4           None       None  Position,Organism           0              NaN
 ..           ...        ...                ...         ...              ...
 235         None       None               None           0                1
 236         None       None               None           0                1
 237         None       None               None           0                1
 238         None       None               None           0                1
 239         None       None               None           0                1

     Feed_concentration_glc InducerConcentration pH_correction_factor
 0                      NaN                  NaN                  NaN
 1                      NaN                  NaN                  NaN
 2                      NaN                  NaN                  NaN
 3                      NaN                  NaN                  NaN
 4                      NaN                  NaN                  NaN
 ..                     ...                  ...                  ...
 235                    200                  NaN                  0.2
 236                    200                  NaN                  0.2
 237                    200                  NaN                  0.2
 238                    200                  NaN                  0.2
 239                    200                  NaN                  0.2

 [240 rows x 40 columns],
 'setpoints':        run_id  experiment_id  cultivation_age  setpoint_id   unit  \
 0         355          11722                0       470579      -
 1         355          11722                0       470581     µL
 2         355          11722                0       470582     µL
 3         355          11722                0       470675  U/min
 4         355          11722                0       470580     µL
 ...       ...            ...              ...          ...    ...
 23121     484          16353            46583       742149     µL
 23122     484          16353            47183       742150     µL
 23123     484          16353            47783       742151     µL
 23124     484          16353            48383       742152     µL
 23125     484          16353            48983       742153     µL

        Puls_AceticAcid  Puls_Glucose  Puls_Medium  StirringSpeed   pH  \
 0                  NaN           NaN          NaN            NaN  7.0
 1                  0.0           NaN          NaN            NaN  NaN
 2                  NaN           NaN          0.0            NaN  NaN
 3                  NaN           NaN          NaN         3000.0  NaN
 4                  NaN           0.0          NaN            NaN  NaN
 ...                ...           ...          ...            ...  ...
 23121              NaN           NaN          NaN            NaN  NaN
 23122              NaN           NaN          NaN            NaN  NaN
 23123              NaN           NaN          NaN            NaN  NaN
 23124              NaN           NaN          NaN            NaN  NaN
 23125              NaN           NaN          NaN            NaN  NaN

        Feed_glc_cum_setpoints  Flow_Air  InducerConcentration  Flow_Nitrogen  \
 0                         NaN       NaN                   NaN            NaN
 1                         NaN       NaN                   NaN            NaN
 2                         NaN       NaN                   NaN            NaN
 3                         NaN       NaN                   NaN            NaN
 4                         NaN       NaN                   NaN            NaN
 ...                       ...       ...                   ...            ...
 23121                   906.0       NaN                   NaN            NaN
 23122                   926.0       NaN                   NaN            NaN
 23123                   946.0       NaN                   NaN            NaN
 23124                   966.0       NaN                   NaN            NaN
 23125                   986.0       NaN                   NaN            NaN

        Flow_O2  Feed_dextrine_cum_setpoints
 0          NaN                          NaN
 1          NaN                          NaN
 2          NaN                          NaN
 3          NaN                          NaN
 4          NaN                          NaN
 ...        ...                          ...
 23121      NaN                          NaN
 23122      NaN                          NaN
 23123      NaN                          NaN
 23124      NaN                          NaN
 23125      NaN                          NaN

 [23126 rows x 16 columns],
 'measurements_reactor':         run_id  experiment_id    measurement_time  measurement_id unit  \
 0          355          11722 2019-04-09 18:32:18      18358520.0    -
 1          355          11722 2019-04-09 18:32:19      18358544.0    -
 2          355          11722 2019-04-09 18:32:28      18358568.0    -
 3          355          11722 2019-04-09 18:32:29      18358592.0    -
 4          355          11722 2019-04-09 18:32:38      18358616.0    -
 ...        ...            ...                 ...             ...  ...
 429794     484          16353 2021-07-28 22:33:26      23138083.0    -
 429795     484          16353 2021-07-28 22:33:26      23138082.0    -
 429796     484          16353 2021-07-28 22:33:38      23138131.0    -
 429797     484          16353 2021-07-28 22:33:38      23138130.0    -
 429798     484          16353 2021-07-28 17:26:22             NaN   mM

         Acetate  Acid  Base  Cumulated_feed_volume_glucose  \
 0           NaN   NaN   NaN                            NaN
 1           NaN   NaN   NaN                            NaN
 2           NaN   NaN   NaN                            NaN
 3           NaN   NaN   NaN                            NaN
 4           NaN   NaN   NaN                            NaN
 ...         ...   ...   ...                            ...
 429794      NaN   NaN   NaN                            NaN
 429795      NaN   NaN   NaN                            NaN
 429796      NaN   NaN   NaN                            NaN
 429797      NaN   NaN   NaN                            NaN
 429798      NaN   NaN   NaN                            NaN

         Cumulated_feed_volume_medium  ...  Fluo_RFP  Fluo_YFP  Glucose  OD600  \
 0                                NaN  ...       NaN       NaN      NaN    NaN
 1                                NaN  ...       NaN       NaN      NaN    NaN
 2                                NaN  ...       NaN       NaN      NaN    NaN
 3                                NaN  ...       NaN       NaN      NaN    NaN
 4                                NaN  ...       NaN       NaN      NaN    NaN
 ...                              ...  ...       ...       ...      ...    ...
 429794                           NaN  ...       NaN       NaN      NaN    NaN
 429795                           NaN  ...       NaN       NaN      NaN    NaN
 429796                           NaN  ...       NaN       NaN      NaN    NaN
 429797                           NaN  ...       NaN       NaN      NaN    NaN
 429798                           NaN  ...       NaN       NaN      NaN    NaN

         Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
 0                NaN   NaN       NaN                   NaN
 1                NaN  6.86       NaN                   NaN
 2                NaN   NaN       NaN                   NaN
 3                NaN  6.86       NaN                   NaN
 4                NaN   NaN       NaN                   NaN
 ...              ...   ...       ...                   ...
 429794           NaN  6.88       NaN                   NaN
 429795           NaN   NaN       NaN                   NaN
 429796           NaN  6.87       NaN                   NaN
 429797           NaN   NaN       NaN                   NaN
 429798           NaN   NaN       NaN                   2.0

                                                    remark  Volume
 0                                                     NaN     NaN
 1                                                     NaN     NaN
 2                                                     NaN     NaN
 3                                                     NaN     NaN
 4                                                     NaN     NaN
 ...                                                   ...     ...
 429794                                                NaN     NaN
 429795                                                NaN     NaN
 429796                                                NaN     NaN
 429797                                                NaN     NaN
 429798  value written to setpoints has been transferre...     NaN

 [429799 rows x 22 columns],
 'measurements_array':         run_id  experiment_id    measurement_time  measurement_id    unit  \
 0          355          11722 2019-04-09 18:32:12         1072518      °C
 1          355          11722 2019-04-09 18:32:21         1072521  Ln/min
 2          355          11722 2019-04-09 18:32:21         1072520  Ln/min
 3          355          11722 2019-04-09 18:32:21         1072519  Ln/min
 4          355          11722 2019-04-09 18:32:22         1072522      °C
 ...        ...            ...                 ...             ...     ...
 205987     484          16353 2021-07-28 22:33:28         1410622   U/min
 205988     484          16353 2021-07-28 22:33:42         1410625  Ln/min
 205989     484          16353 2021-07-28 22:33:42         1410624  Ln/min
 205990     484          16353 2021-07-28 22:33:42         1410626  Ln/min
 205991     484          16353 2021-07-28 22:33:43         1410627   U/min

         Flow_Air  Flow_Nitrogen  Flow_O2  StirringSpeed  Temperature
 0            NaN            NaN      NaN            NaN        36.99
 1            NaN            NaN      0.0            NaN          NaN
 2       4.997213            NaN      NaN            NaN          NaN
 3            NaN            0.0      NaN            NaN          NaN
 4            NaN            NaN      NaN            NaN        36.98
 ...          ...            ...      ...            ...          ...
 205987       NaN            NaN      NaN         2400.0          NaN
 205988  0.000000            NaN      NaN            NaN          NaN
 205989       NaN            0.0      NaN            NaN          NaN
 205990       NaN            NaN      0.0            NaN          NaN
 205991       NaN            NaN      NaN         2400.0          NaN

 [205992 rows x 10 columns],
 'measurements_aggregated':         run_id  experiment_id    measurement_time    unit  Flow_Air  \
 0          355          11722 2019-04-09 18:32:12      °C       NaN
 1          355          11722 2019-04-09 18:32:18       -       NaN
 2          355          11722 2019-04-09 18:32:19       -       NaN
 3          355          11722 2019-04-09 18:32:21  Ln/min       NaN
 4          355          11722 2019-04-09 18:32:21  Ln/min  4.997213
 ...        ...            ...                 ...     ...       ...
 635786     484          16353 2021-07-28 22:33:38       -       NaN
 635787     484          16353 2021-07-28 22:33:42  Ln/min  0.000000
 635788     484          16353 2021-07-28 22:33:42  Ln/min       NaN
 635789     484          16353 2021-07-28 22:33:42  Ln/min       NaN
 635790     484          16353 2021-07-28 22:33:43   U/min       NaN

         Flow_Nitrogen  Flow_O2  StirringSpeed  Temperature  Acetate  ...  \
 0                 NaN      NaN            NaN        36.99      NaN  ...
 1                 NaN      NaN            NaN          NaN      NaN  ...
 2                 NaN      NaN            NaN          NaN      NaN  ...
 3                 NaN      0.0            NaN          NaN      NaN  ...
 4                 NaN      NaN            NaN          NaN      NaN  ...
 ...               ...      ...            ...          ...      ...  ...
 635786            NaN      NaN            NaN          NaN      NaN  ...
 635787            NaN      NaN            NaN          NaN      NaN  ...
 635788            0.0      NaN            NaN          NaN      NaN  ...
 635789            NaN      0.0            NaN          NaN      NaN  ...
 635790            NaN      NaN         2400.0          NaN      NaN  ...

         Fluo_RFP  Fluo_YFP  Glucose  OD600  Probe_Volume    pH  Fluo_GFP  \
 0            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 1            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 2            NaN       NaN      NaN    NaN           NaN  6.86       NaN
 3            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 4            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 ...          ...       ...      ...    ...           ...   ...       ...
 635786       NaN       NaN      NaN    NaN           NaN  6.87       NaN
 635787       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635788       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635789       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635790       NaN       NaN      NaN    NaN           NaN   NaN       NaN

         InducerConcentration  remark  Volume
 0                        NaN     NaN     NaN
 1                        NaN     NaN     NaN
 2                        NaN     NaN     NaN
 3                        NaN     NaN     NaN
 4                        NaN     NaN     NaN
 ...                      ...     ...     ...
 635786                   NaN     NaN     NaN
 635787                   NaN     NaN     NaN
 635788                   NaN     NaN     NaN
 635789                   NaN     NaN     NaN
 635790                   NaN     NaN     NaN

 [635791 rows x 26 columns]}

## MetaData Preprocessing

In [76]:
def contains_no_information(series) -> bool:
    return len(series.dropna().unique()) <= 1

def contains_nan_slice(series, slices, two_enough: bool=False) -> bool:
    num_missing = 0
    for idx in slices:
        if pd.isna(series[idx]).all():
            num_missing += 1
            
    if (num_missing > 0 and not two_enough) or (num_missing >= len(slices)-1 and two_enough):
        print(f"{num_missing}/{len(slices)} missing")
        return True
    return False

def get_μ_set(s: str):
    if pd.isna(s):
        return s
    s = s.strip().lstrip("µ_set: ").strip()
    percent, s = s.split(", ")
    value = s.strip().rstrip("mM IPTG").strip()
    return percent, value

In [77]:
table = metadata = tables["metadata"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"]==run for run in runs]

useless_cols = set()

for col in table:
    s = table[col]
    if col in ("run_id", "experiment_id"):
        continue
    if contains_no_information(s):
        print(f"No information in      {col}")
        useless_cols.add(col)
    elif contains_nan_slice(s, run_masks):
        print(f"Missing for some run   {col}")
        useless_cols.add(col)

# drop the following specific columns
useless_cols |= {'folder_id_y', 'ph_Base_conc', 'ph_Ki', 'ph_Kp', 'ph_Tolerance', 'pms_id'}

No information in      starter_culture_id
No information in      inactivation_method_id
8/9 missing
Missing for some run   description_x
No information in      folder_id_x
No information in      plasmid_id
No information in      medium_id
No information in      description_y
No information in      Stir_Max_Restarts
No information in      Stir_Min_pO2
No information in      Stir_pO2_Threshold
No information in      ph_Max_ul
No information in      ph_Min_ul
No information in      ph_Timesetpoint
No information in      status_id
No information in      description
No information in      conclusion
No information in      container_label
No information in      is_template
No information in      Acetate_Dilution
1/9 missing
Missing for some run   Feed_concentration_glc
No information in      InducerConcentration
1/9 missing
Missing for some run   pH_correction_factor

{'Acetate_Dilution',
 'Feed_concentration_glc',
 'InducerConcentration',
 'Stir_Max_Restarts',
 'Stir_Min_pO2',
 'Stir_pO2_Threshold',
 'conclusion',
 'container_label',
 'description',
 'description_x',
 'description_y',
 'folder_id_x',
 'folder_id_y',
 'inactivation_method_id',
 'is_template',
 'medium_id',
 'pH_correction_factor',
 'ph_Base_conc',
 'ph_Ki',
 'ph_Kp',
 'ph_Max_ul',
 'ph_Min_ul',
 'ph_Timesetpoint',
 'ph_Tolerance',
 'plasmid_id',
 'pms_id',
 'starter_culture_id',
 'status_id'}

In [101]:
metadata_columns = {
    "bioreactor_id",
    "container_number",
    "experiment_id",
    "run_id",
    "profile_id",
    "color",
    "profile_name",
    "organism_id",
    "OD_Dilution",
    "run_name",
    "start_time",
    "end_time",
}

remaining_cols = set(metadata.columns) - useless_cols
assert metadata_columns >= set(metadata.columns) - useless_cols, f"Superfluous {metadata_columns - remaining_cols}"
assert metadata_columns <= set(metadata.columns) - useless_cols, f"You forgot to check {metadata_columns - remaining_cols}"


metadata_dtypes = {
    "experiment_id": "UInt32",
    "bioreactor_id": "UInt32", 
    "container_number": "UInt32",
    "profile_id": "UInt32",
    "color": "string", 
    "profile_name": "string",
    "organism_id": "UInt32",
    "run_id": "UInt32",
    "OD_Dilution": "float32",
    "run_name": "string",
    "start_time": "datetime64[ns]",
    "end_time": "datetime64[ns]", 
}

assert metadata_columns >= set(metadata_dtypes), f"Superfluous encoing  {set(metadata_dtypes) - metadata_columns}"
assert metadata_columns <= set(metadata_dtypes), f"You forgot to encode {metadata_columns - set(metadata_dtypes)}"

metadata_categoricals = {
    "profile_name": "category",
    "run_name": "category",
    "color": "category",
    "OD_Dilution": "Float32",
}

assert metadata_columns >= set(metadata_categoricals), f"Superfluous encoing {set(metadata_categoricals) - metadata_columns}"

AssertionError: You forgot to check {'run_id', 'experiment_id'}

In [102]:
metadata = metadata.astype(metadata_dtypes)
metadata = metadata.astype(metadata_categoricals)
metadata = metadata[metadata_columns]
metadata = metadata.set_index(["run_id", "experiment_id"])

KeyError: 'Only a column name can be used for the key in a dtype mappings argument.'

## Setpoint Preprocessing

In [113]:
table = setpoints = tables["setpoints"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"]==run for run in runs]

useless_cols = set()

for col in table:
    s = table[col]
    if col in ("run_id", "experiment_id"):
        continue
    if contains_no_information(s):
        print(f"No information in      {col}")
        useless_cols.add(col)
    elif contains_nan_slice(s, run_masks, two_enough=True):
        print(f"Missing for some run   {col}")
        useless_cols.add(col)

# drop the following specific columns
useless_cols

No information in      Puls_AceticAcid
No information in      Puls_Medium
No information in      pH
No information in      Flow_Nitrogen
No information in      Flow_O2
No information in      Feed_dextrine_cum_setpoints

{'Feed_dextrine_cum_setpoints',
 'Flow_Nitrogen',
 'Flow_O2',
 'Puls_AceticAcid',
 'Puls_Medium',
 'pH'}

In [114]:
setpoint_columns = set(setpoints.columns)
remaining_cols = setpoint_columns - useless_cols

selected_columns = {
    "experiment_id",
    "run_id",
    'cultivation_age',
    'setpoint_id',
    'unit',
    'Puls_Glucose',
    'StirringSpeed',
    'Feed_glc_cum_setpoints',
    'Flow_Air',
    'InducerConcentration',
}

assert selected_columns >= setpoint_columns - useless_cols, f"You forgot to check {remaining_cols - selected_columns}"
assert selected_columns <= setpoint_columns - useless_cols, f"Superfluous {selected_columns - remaining_cols}"

setpoints_dtypes = {
    "experiment_id"                  : "UInt32",
    "run_id"                         : "UInt32",
    "cultivation_age"                : "UInt32",
    "setpoint_id"                    : "UInt32",
    "unit"                           : "string",
    "Puls_AceticAcid"                : "Float32",
    "Puls_Glucose"                   : "Float32",
    "Puls_Medium"                    : "Float32",
    "StirringSpeed"                  : "UInt16",
    "pH"                             : "Float32",
    "Feed_glc_cum_setpoints"         : "UInt16",
    "Flow_Air"                       : "UInt8",
    "InducerConcentration"           : "Float32",
    "Flow_Nitrogen"                  : "Float32",
    "Flow_O2"                        : "Float32",
    "Feed_dextrine_cum_setpoints"    : "Float32",
}

assert set(setpoints_dtypes) <= setpoint_columns, f"Superfluous encoing  {set(setpoints_dtypes) - setpoint_columns}"
assert set(setpoints_dtypes) >= selected_columns, f"You forgot to encode {selected_columns - set(setpoints_dtypes)}"

setpoints_categoricals = {
    "unit"  : "category",
}

assert set(setpoints_categoricals) <= set(setpoints_dtypes), f"Superfluous encoing {set(setpoints_categoricals) - set(setpoints_dtypes)}"

In [115]:
setpoints["unit"] = setpoints["unit"].replace(to_replace="-", value=pd.NA)
setpoints = setpoints.astype(setpoints_dtypes)
setpoints = setpoints.astype(setpoints_categoricals)
setpoints = setpoints[selected_columns]
setpoints = setpoints.set_index(["run_id", "experiment_id"])

                      InducerConcentration  Puls_Glucose  StirringSpeed  \
run_id experiment_id
355    11722                          <NA>          <NA>           <NA>
       11722                          <NA>          <NA>           <NA>
       11722                          <NA>          <NA>           <NA>
       11722                          <NA>          <NA>           3000
       11722                          <NA>           0.0           <NA>
...                                    ...           ...            ...
484    16353                          <NA>          <NA>           <NA>
       16353                          <NA>          <NA>           <NA>
       16353                          <NA>          <NA>           <NA>
       16353                          <NA>          <NA>           <NA>
       16353                          <NA>          <NA>           <NA>

                       unit  Flow_Air  setpoint_id  Feed_glc_cum_setpoints  \
run_id experiment_id
355    11722            NaN      <NA>       470579                    <NA>
       11722             µL      <NA>       470581                    <NA>
       11722             µL      <NA>       470582                    <NA>
       11722          U/min      <NA>       470675                    <NA>
       11722             µL      <NA>       470580                    <NA>
...                     ...       ...          ...                     ...
484    16353             µL      <NA>       742149                     906
       16353             µL      <NA>       742150                     926
       16353             µL      <NA>       742151                     946
       16353             µL      <NA>       742152                     966
       16353             µL      <NA>       742153                     986

                      cultivation_age
run_id experiment_id
355    11722                        0
       11722                        0
       11722                        0
       11722                        0
       11722                        0
...                               ...
484    16353                    46583
       16353                    47183
       16353                    47783
       16353                    48383
       16353                    48983

[23126 rows x 8 columns]

run_id  experiment_id
355     11722              NaN
        11722               µL
        11722               µL
        11722            U/min
        11722               µL
                         ...
484     16353               µL
        16353               µL
        16353               µL
        16353               µL
        16353               µL
Name: unit, Length: 23126, dtype: category
Categories (4, object): ['Ln/min', 'U/min', 'mM', 'µL']

In [35]:
setpoints["unit"].unique()

array(['-', 'µL', 'U/min', 'Ln/min', 'mM'], dtype=object)

In [32]:
[col for col in setpoints if len(setpoints[col].unique())>2]

['cultivation_age',
 'setpoint_id',
 'unit',
 'Puls_Glucose',
 'StirringSpeed',
 'Feed_glc_cum_setpoints',
 'Flow_Air',
 'InducerConcentration']

In [23]:
np.allclose(setpoints["Feed_glc_cum_setpoints"], setpoints["Feed_glc_cum_setpoints"].astype("Int32").astype("float"), equal_nan=True)

True

In [33]:
setpoints["pH"].unique()

array([ 7., nan])

In [193]:
metadata["pH_correction_factor"].astype(pd.Float32Dtype())

TypeError: object cannot be converted to a FloatingDtype

In [187]:
metadata.astype(dtypes)

TypeError: object cannot be converted to a FloatingDtype

In [185]:
metadata["organism_id"].unique()

array([ 3.,  8., 21., 32., 14., 18., 22., 41.])

In [144]:
metadata['folder_id_x'].unique()

array([nan])

                             measurement_time    unit  Flow_Air  \
run_id experiment_id
355    11722         0    2019-04-09 18:32:12      °C       NaN
                     1    2019-04-09 18:32:18       -       NaN
                     2    2019-04-09 18:32:19       -       NaN
                     3    2019-04-09 18:32:21  Ln/min       NaN
                     4    2019-04-09 18:32:21  Ln/min  4.997213
...                                       ...     ...       ...
484    16353         4599 2021-07-28 22:33:38       -       NaN
                     4600 2021-07-28 22:33:42  Ln/min  0.000000
                     4601 2021-07-28 22:33:42  Ln/min       NaN
                     4602 2021-07-28 22:33:42  Ln/min       NaN
                     4603 2021-07-28 22:33:43   U/min       NaN

                           Flow_Nitrogen  Flow_O2  StirringSpeed  Temperature  \
run_id experiment_id
355    11722         0               NaN      NaN            NaN        36.99
                     1               NaN      NaN            NaN          NaN
                     2               NaN      NaN            NaN          NaN
                     3               NaN      0.0            NaN          NaN
                     4               NaN      NaN            NaN          NaN
...                                  ...      ...            ...          ...
484    16353         4599            NaN      NaN            NaN          NaN
                     4600            NaN      NaN            NaN          NaN
                     4601            0.0      NaN            NaN          NaN
                     4602            NaN      0.0            NaN          NaN
                     4603            NaN      NaN         2400.0          NaN

                           Acetate  Acid  Base  ...  Fluo_RFP  Fluo_YFP  \
run_id experiment_id                            ...
355    11722         0         NaN   NaN   NaN  ...       NaN       NaN
                     1         NaN   NaN   NaN  ...       NaN       NaN
                     2         NaN   NaN   NaN  ...       NaN       NaN
                     3         NaN   NaN   NaN  ...       NaN       NaN
                     4         NaN   NaN   NaN  ...       NaN       NaN
...                            ...   ...   ...  ...       ...       ...
484    16353         4599      NaN   NaN   NaN  ...       NaN       NaN
                     4600      NaN   NaN   NaN  ...       NaN       NaN
                     4601      NaN   NaN   NaN  ...       NaN       NaN
                     4602      NaN   NaN   NaN  ...       NaN       NaN
                     4603      NaN   NaN   NaN  ...       NaN       NaN

                           Glucose  OD600  Probe_Volume    pH  Fluo_GFP  \
run_id experiment_id
355    11722         0         NaN    NaN           NaN   NaN       NaN
                     1         NaN    NaN           NaN   NaN       NaN
                     2         NaN    NaN           NaN  6.86       NaN
                     3         NaN    NaN           NaN   NaN       NaN
                     4         NaN    NaN           NaN   NaN       NaN
...                            ...    ...           ...   ...       ...
484    16353         4599      NaN    NaN           NaN  6.87       NaN
                     4600      NaN    NaN           NaN   NaN       NaN
                     4601      NaN    NaN           NaN   NaN       NaN
                     4602      NaN    NaN           NaN   NaN       NaN
                     4603      NaN    NaN           NaN   NaN       NaN

                           InducerConcentration  remark  Volume
run_id experiment_id
355    11722         0                      NaN     NaN     NaN
                     1                      NaN     NaN     NaN
                     2                      NaN     NaN     NaN
                     3                      NaN     NaN     NaN
                     4                      NaN     NaN     NaN
...                                         ...     ...     ...
484    16353         4599                   NaN     NaN     NaN
                     4600                   NaN     NaN     NaN
                     4601                   NaN     NaN     NaN
                     4602                   NaN     NaN     NaN
                     4603                   NaN     NaN     NaN

[635791 rows x 24 columns]

In [121]:
DF['setpoints'].reset_index()

     run_id  experiment_id                                          setpoints
0       355          11722       cultivation_age  setpoint_id   unit  Puls...
1       355          11723       cultivation_age  setpoint_id   unit  Puls...
2       355          11724       cultivation_age  setpoint_id   unit  Puls...
3       355          11725       cultivation_age  setpoint_id   unit  Puls...
4       355          11726      cultivation_age  setpoint_id   unit  Puls_...
..      ...            ...                                                ...
235     484          16349      cultivation_age  setpoint_id    unit  Feed...
236     484          16350      cultivation_age  setpoint_id    unit  Feed...
237     484          16351      cultivation_age  setpoint_id    unit  Feed...
238     484          16352      cultivation_age  setpoint_id    unit  Feed...
239     484          16353      cultivation_age  setpoint_id    unit  Feed...

[240 rows x 3 columns]

                          cultivation_age  setpoint_id   unit  \
run_id experiment_id
355    11722         0                  0       470579      -
                     153                0       470581     µL
                     154                0       470582     µL
                     155                0       470675  U/min
                     1                  0       470580     µL
...                                   ...          ...    ...
484    16353         69             46583       742149     µL
                     70             47183       742150     µL
                     71             47783       742151     µL
                     72             48383       742152     µL
                     73             48983       742153     µL

                          Puls_AceticAcid  Puls_Glucose  Puls_Medium  \
run_id experiment_id
355    11722         0                NaN           NaN          NaN
                     153              0.0           NaN          NaN
                     154              NaN           NaN          0.0
                     155              NaN           NaN          NaN
                     1                NaN           0.0          NaN
...                                   ...           ...          ...
484    16353         69               NaN           NaN          NaN
                     70               NaN           NaN          NaN
                     71               NaN           NaN          NaN
                     72               NaN           NaN          NaN
                     73               NaN           NaN          NaN

                          StirringSpeed   pH  Feed_glc_cum_setpoints  \
run_id experiment_id
355    11722         0              NaN  7.0                     NaN
                     153            NaN  NaN                     NaN
                     154            NaN  NaN                     NaN
                     155         3000.0  NaN                     NaN
                     1              NaN  NaN                     NaN
...                                 ...  ...                     ...
484    16353         69             NaN  NaN                   906.0
                     70             NaN  NaN                   926.0
                     71             NaN  NaN                   946.0
                     72             NaN  NaN                   966.0
                     73             NaN  NaN                   986.0

                          Flow_Air  InducerConcentration  Flow_Nitrogen  \
run_id experiment_id
355    11722         0         NaN                   NaN            NaN
                     153       NaN                   NaN            NaN
                     154       NaN                   NaN            NaN
                     155       NaN                   NaN            NaN
                     1         NaN                   NaN            NaN
...                            ...                   ...            ...
484    16353         69        NaN                   NaN            NaN
                     70        NaN                   NaN            NaN
                     71        NaN                   NaN            NaN
                     72        NaN                   NaN            NaN
                     73        NaN                   NaN            NaN

                          Flow_O2  Feed_dextrine_cum_setpoints
run_id experiment_id
355    11722         0        NaN                          NaN
                     153      NaN                          NaN
                     154      NaN                          NaN
                     155      NaN                          NaN
                     1        NaN                          NaN
...                           ...                          ...
484    16353         69       NaN                          NaN
                     70       NaN                          NaN
                     71       NaN                          NaN
                     72       NaN                          NaN
                     73       NaN                          NaN

[23126 rows x 14 columns]

In [106]:
pd.concat(DF['setpoints'].to_dict())

               cultivation_age  setpoint_id   unit  Puls_AceticAcid  \
355 11722 0                  0       470579      -              NaN
          153                0       470581     µL              0.0
          154                0       470582     µL              NaN
          155                0       470675  U/min              NaN
          1                  0       470580     µL              NaN
...                        ...          ...    ...              ...
484 16353 69             46583       742149     µL              NaN
          70             47183       742150     µL              NaN
          71             47783       742151     µL              NaN
          72             48383       742152     µL              NaN
          73             48983       742153     µL              NaN

               Puls_Glucose  Puls_Medium  StirringSpeed   pH  \
355 11722 0             NaN          NaN            NaN  7.0
          153           NaN          NaN            NaN  NaN
          154           NaN          0.0            NaN  NaN
          155           NaN          NaN         3000.0  NaN
          1             0.0          NaN            NaN  NaN
...                     ...          ...            ...  ...
484 16353 69            NaN          NaN            NaN  NaN
          70            NaN          NaN            NaN  NaN
          71            NaN          NaN            NaN  NaN
          72            NaN          NaN            NaN  NaN
          73            NaN          NaN            NaN  NaN

               Feed_glc_cum_setpoints  Flow_Air  InducerConcentration  \
355 11722 0                       NaN       NaN                   NaN
          153                     NaN       NaN                   NaN
          154                     NaN       NaN                   NaN
          155                     NaN       NaN                   NaN
          1                       NaN       NaN                   NaN
...                               ...       ...                   ...
484 16353 69                    906.0       NaN                   NaN
          70                    926.0       NaN                   NaN
          71                    946.0       NaN                   NaN
          72                    966.0       NaN                   NaN
          73                    986.0       NaN                   NaN

               Flow_Nitrogen  Flow_O2  Feed_dextrine_cum_setpoints
355 11722 0              NaN      NaN                          NaN
          153            NaN      NaN                          NaN
          154            NaN      NaN                          NaN
          155            NaN      NaN                          NaN
          1              NaN      NaN                          NaN
...                      ...      ...                          ...
484 16353 69             NaN      NaN                          NaN
          70             NaN      NaN                          NaN
          71             NaN      NaN                          NaN
          72             NaN      NaN                          NaN
          73             NaN      NaN                          NaN

[23126 rows x 14 columns]

In [71]:
DF[['setpoints']]

                                                              setpoints
run_id experiment_id
355    11722               cultivation_age  setpoint_id   unit  Puls...
       11723               cultivation_age  setpoint_id   unit  Puls...
       11724               cultivation_age  setpoint_id   unit  Puls...
       11725               cultivation_age  setpoint_id   unit  Puls...
       11726              cultivation_age  setpoint_id   unit  Puls_...
...                                                                 ...
484    16349              cultivation_age  setpoint_id    unit  Feed...
       16350              cultivation_age  setpoint_id    unit  Feed...
       16351              cultivation_age  setpoint_id    unit  Feed...
       16352              cultivation_age  setpoint_id    unit  Feed...
       16353              cultivation_age  setpoint_id    unit  Feed...

[240 rows x 1 columns]

In [81]:
DataFrame(list(DF[['setpoints']].iteritems()))

           0                                                  1
0  setpoints  run_id  experiment_id
355     11722           ...

In [93]:
DF['setpoints']

run_id  experiment_id
355     11722                 cultivation_age  setpoint_id   unit  Puls...
        11723                 cultivation_age  setpoint_id   unit  Puls...
        11724                 cultivation_age  setpoint_id   unit  Puls...
        11725                 cultivation_age  setpoint_id   unit  Puls...
        11726                cultivation_age  setpoint_id   unit  Puls_...
                                               ...
484     16349                cultivation_age  setpoint_id    unit  Feed...
        16350                cultivation_age  setpoint_id    unit  Feed...
        16351                cultivation_age  setpoint_id    unit  Feed...
        16352                cultivation_age  setpoint_id    unit  Feed...
        16353                cultivation_age  setpoint_id    unit  Feed...
Name: setpoints, Length: 240, dtype: object

In [98]:
DF[['setpoints']].to_dict("split")

{'index': [(355, 11722),
  (355, 11723),
  (355, 11724),
  (355, 11725),
  (355, 11726),
  (355, 11727),
  (355, 11728),
  (355, 11729),
  (355, 11730),
  (355, 11731),
  (355, 11732),
  (355, 11733),
  (355, 11734),
  (355, 11735),
  (355, 11736),
  (355, 11737),
  (355, 11738),
  (355, 11739),
  (355, 11740),
  (355, 11741),
  (355, 11742),
  (355, 11743),
  (355, 11744),
  (355, 11745),
  (439, 15325),
  (439, 15326),
  (439, 15327),
  (439, 15328),
  (439, 15329),
  (439, 15330),
  (439, 15331),
  (439, 15332),
  (439, 15333),
  (439, 15334),
  (439, 15335),
  (439, 15336),
  (439, 15337),
  (439, 15338),
  (439, 15339),
  (439, 15340),
  (439, 15341),
  (439, 15342),
  (439, 15343),
  (439, 15344),
  (439, 15345),
  (439, 15346),
  (439, 15347),
  (439, 15348),
  (445, 15493),
  (445, 15494),
  (445, 15495),
  (445, 15496),
  (445, 15497),
  (445, 15498),
  (445, 15499),
  (445, 15500),
  (445, 15501),
  (445, 15502),
  (445, 15503),
  (445, 15504),
  (445, 15505),
  (445, 15506),
  (445, 15507),
  (445, 15508),
  (445, 15509),
  (445, 15510),
  (445, 15511),
  (445, 15512),
  (445, 15513),
  (445, 15514),
  (445, 15515),
  (445, 15516),
  (445, 15517),
  (445, 15518),
  (445, 15519),
  (445, 15520),
  (445, 15521),
  (445, 15522),
  (445, 15523),
  (445, 15524),
  (445, 15525),
  (445, 15526),
  (445, 15527),
  (445, 15528),
  (445, 15529),
  (445, 15530),
  (445, 15531),
  (445, 15532),
  (445, 15533),
  (445, 15534),
  (445, 15535),
  (445, 15536),
  (445, 15537),
  (445, 15538),
  (445, 15539),
  (445, 15540),
  (449, 15643),
  (449, 15644),
  (449, 15645),
  (449, 15646),
  (449, 15647),
  (449, 15648),
  (449, 15649),
  (449, 15650),
  (449, 15651),
  (449, 15652),
  (449, 15653),
  (449, 15654),
  (449, 15655),
  (449, 15656),
  (449, 15657),
  (449, 15658),
  (449, 15659),
  (449, 15660),
  (449, 15661),
  (449, 15662),
  (449, 15663),
  (449, 15664),
  (449, 15665),
  (449, 15666),
  (468, 15994),
  (468, 15995),
  (468, 15996),
  (468, 15997),
  (468, 15998),
  (468, 15999),
  (468, 16000),
  (468, 16001),
  (468, 16002),
  (468, 16003),
  (468, 16004),
  (468, 16005),
  (468, 16006),
  (468, 16007),
  (468, 16008),
  (468, 16009),
  (468, 16010),
  (468, 16011),
  (468, 16012),
  (468, 16013),
  (468, 16014),
  (468, 16015),
  (468, 16016),
  (468, 16017),
  (474, 16106),
  (474, 16107),
  (474, 16108),
  (474, 16109),
  (474, 16110),
  (474, 16111),
  (474, 16112),
  (474, 16113),
  (474, 16114),
  (474, 16115),
  (474, 16116),
  (474, 16117),
  (474, 16118),
  (474, 16119),
  (474, 16120),
  (474, 16121),
  (474, 16122),
  (474, 16123),
  (474, 16124),
  (474, 16125),
  (474, 16126),
  (474, 16127),
  (474, 16128),
  (474, 16129),
  (475, 16130),
  (475, 16131),
  (475, 16132),
  (475, 16133),
  (475, 16134),
  (475, 16135),
  (475, 16136),
  (475, 16137),
  (475, 16138),
  (475, 16139),
  (475, 16140),
  (475, 16141),
  (475, 16142),
  (475, 16143),
  (475, 16144),
  (475, 16145),
  (475, 16146),
  (475, 16147),
  (475, 16148),
  (475, 16149),
  (475, 16150),
  (475, 16151),
  (475, 16152),
  (475, 16153),
  (482, 16282),
  (482, 16283),
  (482, 16284),
  (482, 16285),
  (482, 16286),
  (482, 16287),
  (482, 16288),
  (482, 16289),
  (482, 16290),
  (482, 16291),
  (482, 16292),
  (482, 16293),
  (482, 16294),
  (482, 16295),
  (482, 16296),
  (482, 16297),
  (482, 16298),
  (482, 16299),
  (482, 16300),
  (482, 16301),
  (482, 16302),
  (482, 16303),
  (482, 16304),
  (482, 16305),
  (484, 16330),
  (484, 16331),
  (484, 16332),
  (484, 16333),
  (484, 16334),
  (484, 16335),
  (484, 16336),
  (484, 16337),
  (484, 16338),
  (484, 16339),
  (484, 16340),
  (484, 16341),
  (484, 16342),
  (484, 16343),
  (484, 16344),
  (484, 16345),
  (484, 16346),
  (484, 16347),
  (484, 16348),
  (484, 16349),
  (484, 16350),
  (484, 16351),
  (484, 16352),
  (484, 16353)],
 'columns': ['setpoints'],
 'data': [[     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470579      -              NaN           NaN
   153                0       470581     µL              0.0           NaN
   154                0       470582     µL              NaN           NaN
   155                0       470675  U/min              NaN           NaN
   1                  0       470580     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   148            49976       484229     µL              NaN          22.0
   149            50276       484230     µL              NaN          22.0
   150            50576       484231     µL              NaN          22.0
   151            50876       484232     µL              NaN          22.0
   152            51176       484233     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   153          NaN            NaN  NaN
   154          0.0            NaN  NaN
   155          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   148          NaN            NaN  NaN
   149          NaN            NaN  NaN
   150          NaN            NaN  NaN
   151          NaN            NaN  NaN
   152          NaN            NaN  NaN

   [156 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470583      -              NaN           NaN
   174                0       470585     µL              0.0           NaN
   175                0       470586     µL              NaN           NaN
   176                0       470676  U/min              NaN           NaN
   1                  0       470584     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   169            57394       487829     µL              NaN          22.0
   170            57694       487830     µL              NaN          22.0
   171            57994       487831     µL              NaN          22.0
   172            58294       487832     µL              NaN          22.0
   173            58594       487833     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   174          NaN            NaN  NaN
   175          0.0            NaN  NaN
   176          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   169          NaN            NaN  NaN
   170          NaN            NaN  NaN
   171          NaN            NaN  NaN
   172          NaN            NaN  NaN
   173          NaN            NaN  NaN

   [177 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470587      -              NaN           NaN
   148                0       470589     µL              0.0           NaN
   149                0       470590     µL              NaN           NaN
   150                0       470677  U/min              NaN           NaN
   1                  0       470588     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   143            50251       484949     µL              NaN          22.0
   144            50551       484950     µL              NaN          22.0
   145            50851       484951     µL              NaN          22.0
   146            51151       484952     µL              NaN          22.0
   147            51451       484953     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   148          NaN            NaN  NaN
   149          0.0            NaN  NaN
   150          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   143          NaN            NaN  NaN
   144          NaN            NaN  NaN
   145          NaN            NaN  NaN
   146          NaN            NaN  NaN
   147          NaN            NaN  NaN

   [151 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470591      -              NaN           NaN
   171                0       470593     µL              0.0           NaN
   172                0       470594     µL              NaN           NaN
   173                0       470678  U/min              NaN           NaN
   1                  0       470592     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   166            57650       488189     µL              NaN          22.0
   167            57950       488190     µL              NaN          22.0
   168            58250       488191     µL              NaN          22.0
   169            58550       488192     µL              NaN          22.0
   170            58850       488193     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   171          NaN            NaN  NaN
   172          0.0            NaN  NaN
   173          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   166          NaN            NaN  NaN
   167          NaN            NaN  NaN
   168          NaN            NaN  NaN
   169          NaN            NaN  NaN
   170          NaN            NaN  NaN

   [174 rows x 8 columns]],
  [    cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                 0       470595      -              NaN           NaN
   97                0       470597     µL              0.0           NaN
   98                0       470598     µL              NaN           NaN
   99                0       470679  U/min              NaN           NaN
   1                 0       470596     µL              NaN           0.0
   ..              ...          ...    ...              ...           ...
   92            33543       485612     µL              NaN          22.0
   93            33843       485613     µL              NaN          22.0
   94            34143       485614     µL              NaN          22.0
   95            34443       485615     µL              NaN          22.0
   96            34743       485616     µL              NaN          10.0

       Puls_Medium  StirringSpeed   pH
   0           NaN            NaN  7.0
   97          NaN            NaN  NaN
   98          0.0            NaN  NaN
   99          NaN         3000.0  NaN
   1           NaN            NaN  NaN
   ..          ...            ...  ...
   92          NaN            NaN  NaN
   93          NaN            NaN  NaN
   94          NaN            NaN  NaN
   95          NaN            NaN  NaN
   96          NaN            NaN  NaN

   [100 rows x 8 columns]],
  [    cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                 0       470599      -              NaN           NaN
   90                0       470601     µL              0.0           NaN
   91                0       470602     µL              NaN           NaN
   92                0       470680  U/min              NaN           NaN
   1                 0       470600     µL              NaN           0.0
   ..              ...          ...    ...              ...           ...
   85            33525       485971     µL              NaN          22.0
   86            33825       485972     µL              NaN          22.0
   87            34125       485973     µL              NaN          22.0
   88            34425       485974     µL              NaN          22.0
   89            34725       485975     µL              NaN           5.0

       Puls_Medium  StirringSpeed   pH
   0           NaN            NaN  7.0
   90          NaN            NaN  NaN
   91          0.0            NaN  NaN
   92          NaN         3000.0  NaN
   1           NaN            NaN  NaN
   ..          ...            ...  ...
   85          NaN            NaN  NaN
   86          NaN            NaN  NaN
   87          NaN            NaN  NaN
   88          NaN            NaN  NaN
   89          NaN            NaN  NaN

   [93 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470603      -              NaN           NaN
   154                0       470605     µL              0.0           NaN
   155                0       470606     µL              NaN           NaN
   156                0       470681  U/min              NaN           NaN
   1                  0       470604     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   149            51103       486389     µL              NaN          22.0
   150            51403       486390     µL              NaN          22.0
   151            51703       486391     µL              NaN          22.0
   152            52003       486392     µL              NaN          22.0
   153            52303       486393     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   154          NaN            NaN  NaN
   155          0.0            NaN  NaN
   156          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   149          NaN            NaN  NaN
   150          NaN            NaN  NaN
   151          NaN            NaN  NaN
   152          NaN            NaN  NaN
   153          NaN            NaN  NaN

   [157 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470607      -              NaN           NaN
   149                0       470609     µL              0.0           NaN
   150                0       470610     µL              NaN           NaN
   151                0       470682  U/min              NaN           NaN
   1                  0       470608     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   144            51341       486749     µL              NaN          22.0
   145            51641       486750     µL              NaN          22.0
   146            51941       486751     µL              NaN          22.0
   147            52241       486752     µL              NaN          22.0
   148            52541       486753     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   149          NaN            NaN  NaN
   150          0.0            NaN  NaN
   151          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   144          NaN            NaN  NaN
   145          NaN            NaN  NaN
   146          NaN            NaN  NaN
   147          NaN            NaN  NaN
   148          NaN            NaN  NaN

   [152 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470611      -              NaN           NaN
   153                0       470613     µL              0.0           NaN
   154                0       470614     µL              NaN           NaN
   155                0       470683  U/min              NaN           NaN
   1                  0       470612     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   148            49976       484349     µL              NaN          22.0
   149            50276       484350     µL              NaN          22.0
   150            50576       484351     µL              NaN          22.0
   151            50876       484352     µL              NaN          22.0
   152            51176       484353     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   153          NaN            NaN  NaN
   154          0.0            NaN  NaN
   155          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   148          NaN            NaN  NaN
   149          NaN            NaN  NaN
   150          NaN            NaN  NaN
   151          NaN            NaN  NaN
   152          NaN            NaN  NaN

   [156 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470615      -              NaN           NaN
   174                0       470617     µL              0.0           NaN
   175                0       470618     µL              NaN           NaN
   176                0       470684  U/min              NaN           NaN
   1                  0       470616     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   169            57394       487949     µL              NaN          22.0
   170            57694       487950     µL              NaN          22.0
   171            57994       487951     µL              NaN          22.0
   172            58294       487952     µL              NaN          22.0
   173            58594       487953     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   174          NaN            NaN  NaN
   175          0.0            NaN  NaN
   176          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   169          NaN            NaN  NaN
   170          NaN            NaN  NaN
   171          NaN            NaN  NaN
   172          NaN            NaN  NaN
   173          NaN            NaN  NaN

   [177 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470619      -              NaN           NaN
   148                0       470621     µL              0.0           NaN
   149                0       470622     µL              NaN           NaN
   150                0       470685  U/min              NaN           NaN
   1                  0       470620     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   143            50251       485069     µL              NaN          22.0
   144            50551       485070     µL              NaN          22.0
   145            50851       485071     µL              NaN          22.0
   146            51151       485072     µL              NaN          22.0
   147            51451       485073     µL              NaN          22.0

        Puls_Medium  StirringSpeed   pH
   0            NaN            NaN  7.0
   148          NaN            NaN  NaN
   149          0.0            NaN  NaN
   150          NaN         3000.0  NaN
   1            NaN            NaN  NaN
   ..           ...            ...  ...
   143          NaN            NaN  NaN
   144          NaN            NaN  NaN
   145          NaN            NaN  NaN
   146          NaN            NaN  NaN
   147          NaN            NaN  NaN

   [151 rows x 8 columns]],
  [     cultivation_age  setpoint_id   unit  Puls_AceticAcid  Puls_Glucose  \
   0                  0       470623      -              NaN           NaN
   171                0       470625     µL              0.0           NaN
   172                0       470626     µL              NaN           NaN
   173                0       470686  U/min              NaN           NaN
   1                  0       470624     µL              NaN           0.0
   ..               ...          ...    ...              ...           ...
   166            57650       488309     µL              NaN          22.0

                                                               metadata  \
run_id experiment_id
355    11722             experiment_id  bioreactor_id  container_num...
       11723             experiment_id  bioreactor_id  container_num...
       11724             experiment_id  bioreactor_id  container_num...
       11725             experiment_id  bioreactor_id  container_num...
       11726             experiment_id  bioreactor_id  container_num...
...                                                                 ...
484    16349             experiment_id  bioreactor_id  container_num...
       16350             experiment_id  bioreactor_id  container_num...
       16351             experiment_id  bioreactor_id  container_num...
       16352             experiment_id  bioreactor_id  container_num...
       16353             experiment_id  bioreactor_id  container_num...

                                                              setpoints  \
run_id experiment_id
355    11722               cultivation_age  setpoint_id   unit  Puls...
       11723               cultivation_age  setpoint_id   unit  Puls...
       11724               cultivation_age  setpoint_id   unit  Puls...
       11725               cultivation_age  setpoint_id   unit  Puls...
       11726              cultivation_age  setpoint_id   unit  Puls_...
...                                                                 ...
484    16349              cultivation_age  setpoint_id    unit  Feed...
       16350              cultivation_age  setpoint_id    unit  Feed...
       16351              cultivation_age  setpoint_id    unit  Feed...
       16352              cultivation_age  setpoint_id    unit  Feed...
       16353              cultivation_age  setpoint_id    unit  Feed...

                                                   measurements_reactor  \
run_id experiment_id
355    11722                  measurement_time  measurement_id unit ...
       11723                  measurement_time  measurement_id unit ...
       11724                  measurement_time  measurement_id unit ...
       11725                  measurement_time  measurement_id unit ...
       11726                  measurement_time  measurement_id unit ...
...                                                                 ...
484    16349                  measurement_time  measurement_id unit ...
       16350                  measurement_time  measurement_id unit ...
       16351                  measurement_time  measurement_id unit ...
       16352                  measurement_time  measurement_id unit ...
       16353                  measurement_time  measurement_id unit ...

                                                     measurements_array  \
run_id experiment_id
355    11722                  measurement_time  measurement_id    un...
       11723                  measurement_time  measurement_id    un...
       11724                  measurement_time  measurement_id    un...
       11725                  measurement_time  measurement_id    un...
       11726                  measurement_time  measurement_id    un...
...                                                                 ...
484    16349                  measurement_time  measurement_id    un...
       16350                  measurement_time  measurement_id    un...
       16351                  measurement_time  measurement_id    un...
       16352                  measurement_time  measurement_id    un...
       16353                  measurement_time  measurement_id    un...

                                                measurements_aggregated
run_id experiment_id
355    11722                  measurement_time    unit  Flow_Air  Fl...
       11723                  measurement_time    unit  Flow_Air  Fl...
       11724                  measurement_time    unit  Flow_Air  Fl...
       11725                  measurement_time    unit  Flow_Air  Fl...
       11726                  measurement_time    unit  Flow_Air  Fl...
...                                                                 ...
484    16349                  measurement_time    unit  Flow_Air  Fl...
       16350                  measurement_time    unit  Flow_Air  Fl...
       16351                  measurement_time    unit  Flow_Air  Fl...
       16352                  measurement_time    unit  Flow_Air  Fl...
       16353                  measurement_time    unit  Flow_Air  Fl...

[240 rows x 5 columns]

In [31]:
data[355][11722]['measurements_reactor']

,measurement_time,measurement_id,unit,Acetate,Acid,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Fluo_CFP,Fluo_RFP,Fluo_YFP,Glucose,OD600,Probe_Volume,pH
0,2019-04-09 18:32:18,18358520,-,NaN,NaN,NaN,NaN,NaN,89.660004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789,2019-04-09 18:32:19,18358544,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.86
1,2019-04-09 18:32:28,18358568,-,NaN,NaN,NaN,NaN,NaN,89.440002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,2019-04-09 18:32:29,18358592,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.86
2,2019-04-09 18:32:38,18358616,-,NaN,NaN,NaN,NaN,NaN,89.589996,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1575,2019-04-10 07:41:16,18422224,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.81
787,2019-04-10 07:42:15,18422248,-,NaN,NaN,NaN,NaN,NaN,1.820000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1576,2019-04-10 07:42:16,18422272,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.81
788,2019-04-10 07:43:15,18422296,-,NaN,NaN,NaN,NaN,NaN,1.460000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1577,2019-04-10 07:43:16,18422320,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.81

In [35]:
meta = [data[run][exp]["metadata"] for run in data for exp in data[run]]

[   experiment_id  bioreactor_id  container_number  profile_id  \
 0          11722            397                 9      6449.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF6404

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           A2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11723            397                10      6450.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFFF400

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           B2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11724            397                11      6451.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFAFFF00

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           C2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11725            397                12      6452.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF00FFAB

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           D2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11726            397                13      6453.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF00ABFF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           E2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11727            397                14      6454.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF0000FF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           F2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11728            397                15      6455.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF00FF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           G2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11729            397                16      6456.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF0005

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           H2          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11730            397                17      6457.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF6404

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           A3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11731            397                18      6458.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFFF400

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           B3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11732            397                19      6459.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFAFFF00

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           C3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11733            397                20      6460.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF00FFAB

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           D3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11734            397                21      6461.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF00ABFF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           E3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11735            397                22      6462.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF0000FF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           F3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11736            397                23      6463.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF00FF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           G3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11737            397                24      6464.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF0005

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           H3          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11738            397                25      6465.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF6404

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           A4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11739            397                26      6466.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFFF400

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           B4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11740            397                27      6467.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFAFFF00

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           C4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11741            397                28      6468.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF00FFAB

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           D4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11742            397                29      6469.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF00ABFF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           E4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11743            397                30      6470.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FF0000FF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           F4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11744            397                31      6471.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF00FF

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           G4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          11745            397                32      6472.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFFF0005

   profile_name  folder_id_x  ...           run_name  folder_id_y  pms_id  \
 0           H4          NaN  ...  20190409_SWORD_II           61       4

   status_id          start_time            end_time description conclusion  \
 0         3 2019-04-09 18:31:53 2019-04-10 07:43:33        None       None

      container_label is_template
 0  Position,Organism           0

 [1 rows x 36 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          15325            495                 9     10068.0

   starter_culture_id  inactivation_method_id             description_x  \
 0               None                     1.0  µ_set: 25%, 0.05 mM IPTG

        color profile_name  folder_id_x  ...         run_name  folder_id_y  \
 0  #FF1B9E77           A2          NaN  ...  20201209_01_MHE          101

    pms_id status_id          start_time            end_time description  \
 0       2         3 2020-12-09 09:09:58 2020-12-09 23:34:23        None

   conclusion container_label is_template
 0       None            None           0

 [1 rows x 35 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          15326            495                10     10069.0

   starter_culture_id  inactivation_method_id            description_x  \
 0               None                     1.0  µ_set: 25%, 0.5 mM IPTG

        color profile_name  folder_id_x  ...         run_name  folder_id_y  \
 0  #FFD95F02           B2          NaN  ...  20201209_01_MHE          101

    pms_id status_id          start_time            end_time description  \
 0       2         3 2020-12-09 09:09:58 2020-12-09 23:34:23        None

   conclusion container_label is_template
 0       None            None           0

 [1 rows x 35 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          15327            495                11     10070.0

   starter_culture_id  inactivation_method_id             description_x  \
 0               None                     1.0  µ_set: 60%, 0.05 mM IPTG

        color profile_name  folder_id_x  ...         run_name  folder_id_y  \
 0  #FF7570B3           C2          NaN  ...  20201209_01_MHE          101

    pms_id status_id          start_time            end_time description  \
 0       2         3 2020-12-09 09:09:58 2020-12-09 23:34:23        None

   conclusion container_label is_template
 0       None            None           0

 [1 rows x 35 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          15328            495                12     10071.0

   starter_culture_id  inactivation_method_id            description_x  \
 0               None                     1.0  µ_set: 60%, 0.5 mM IPTG

        color profile_name  folder_id_x  ...         run_name  folder_id_y  \
 0  #FFE7298A           D2          NaN  ...  20201209_01_MHE          101

    pms_id status_id          start_time            end_time description  \
 0       2         3 2020-12-09 09:09:58 2020-12-09 23:34:23        None

   conclusion container_label is_template
 0       None            None           0

 [1 rows x 35 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          15329            495                13     10072.0

   starter_culture_id  inactivation_method_id          description_x  \
 0               None                     1.0  µ_set: 40%, 2 mM IPTG

        color profile_name  folder_id_x  ...         run_name  folder_id_y  \
 0  #FF66A61E           E2          NaN  ...  20201209_01_MHE          101

    pms_id status_id          start_time            end_time description  \
 0       2         3 2020-12-09 09:09:58 2020-12-09 23:34:23        None

   conclusion container_label is_template
 0       None            None           0

 [1 rows x 35 columns],
    experiment_id  bioreactor_id  container_number  profile_id  \
 0          15330            495                14     10073.0

   starter_culture_id  inactivation_method_id          description_x  \
 0               None                     1.0  µ_set: 40%, 2 mM IPTG


In [39]:
pd.concat(meta)

,experiment_id,bioreactor_id,container_number,profile_id,starter_culture_id,inactivation_method_id,description_x,color,profile_name,folder_id_x,...,start_time,end_time,description,conclusion,container_label,is_template,Acetate_Dilution,Feed_concentration_glc,InducerConcentration,pH_correction_factor
0,11722,397,9,6449.0,None,1.0,None,#FFFF6404,A2,NaN,...,2019-04-09 18:31:53,2019-04-10 07:43:33,None,None,"Position,Organism",0,NaN,NaN,NaN,NaN
0,11723,397,10,6450.0,None,1.0,None,#FFFFF400,B2,NaN,...,2019-04-09 18:31:53,2019-04-10 07:43:33,None,None,"Position,Organism",0,NaN,NaN,NaN,NaN
0,11724,397,11,6451.0,None,1.0,None,#FFAFFF00,C2,NaN,...,2019-04-09 18:31:53,2019-04-10 07:43:33,None,None,"Position,Organism",0,NaN,NaN,NaN,NaN
0,11725,397,12,6452.0,None,1.0,None,#FF00FFAB,D2,NaN,...,2019-04-09 18:31:53,2019-04-10 07:43:33,None,None,"Position,Organism",0,NaN,NaN,NaN,NaN
0,11726,397,13,6453.0,None,1.0,None,#FF00ABFF,E2,NaN,...,2019-04-09 18:31:53,2019-04-10 07:43:33,None,None,"Position,Organism",0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,16349,588,28,11028.0,None,1.0,None,#FFE7298A,D4,NaN,...,2021-07-28 08:56:22,2021-07-28 22:37:27,None,None,None,0,1,200,NaN,0.2
0,16350,588,29,11029.0,None,1.0,None,#FF66A61E,E4,NaN,...,2021-07-28 08:56:22,2021-07-28 22:37:27,None,None,None,0,1,200,NaN,0.2
0,16351,588,30,11030.0,None,1.0,None,#FFE6AB02,F4,NaN,...,2021-07-28 08:56:22,2021-07-28 22:37:27,None,None,None,0,1,200,NaN,0.2
0,16352,588,31,11031.0,None,1.0,None,#FFA6761D,G4,NaN,...,2021-07-28 08:56:22,2021-07-28 22:37:27,None,None,None,0,1,200,NaN,0.2
0,16353,588,32,11032.0,None,1.0,None,#FF666666,H4,NaN,...,2021-07-28 08:56:22,2021-07-28 22:37:27,None,None,None,0,1,200,NaN,0.2

In [40]:
for train_keys, test_keys in splitter.split(col_run_to_exp):
      
    data_train = [data[k[0]][k[1]] | {"run_id":k[0], "experiment_id": k[1]} for k in train_keys]
    data_test = {k:data[k[0]][k[1]] for k in test_keys}  
    
    
#     data_train = {k:data[k[0]][k[1]] for k in train_keys}
#     data_test = {k:data[k[0]][k[1]] for k in test_keys}


```python
data_train: dict[(int, int), 
    dict[
        'metadata': DataFrame,                  # MetaData
        'setpoints': DataFrame,                 # MetaData
        'measurements_reactor': DataFrame,      # TimeTensor 
        'measurements_array': DataFrame,        # TimeTensor
        'measurements_aggregated' : DataFrame,  # TimeTensor
    ]
]
```

In [43]:
DF = DataFrame(data_train).set_index(["run_id", "experiment_id"])

                                                               metadata  \
run_id experiment_id
484    16331             experiment_id  bioreactor_id  container_num...
       16339             experiment_id  bioreactor_id  container_num...
       16347             experiment_id  bioreactor_id  container_num...
468    16001             experiment_id  bioreactor_id  container_num...
       16009             experiment_id  bioreactor_id  container_num...
...                                                                 ...
439    15337             experiment_id  bioreactor_id  container_num...
       15345             experiment_id  bioreactor_id  container_num...
355    11724             experiment_id  bioreactor_id  container_num...
       11732             experiment_id  bioreactor_id  container_num...
       11740             experiment_id  bioreactor_id  container_num...

                                                              setpoints  \
run_id experiment_id
484    16331              cultivation_age  setpoint_id    unit  Feed...
       16339              cultivation_age  setpoint_id    unit  Feed...
       16347              cultivation_age  setpoint_id    unit  Feed...
468    16001               cultivation_age  setpoint_id   unit  Feed...
       16009               cultivation_age  setpoint_id   unit  Feed...
...                                                                 ...
439    15337               cultivation_age  setpoint_id   unit  Feed...
       15345               cultivation_age  setpoint_id   unit  Feed...
355    11724               cultivation_age  setpoint_id   unit  Puls...
       11732               cultivation_age  setpoint_id   unit  Puls...
       11740               cultivation_age  setpoint_id   unit  Puls...

                                                   measurements_reactor  \
run_id experiment_id
484    16331                  measurement_time  measurement_id unit ...
       16339                  measurement_time  measurement_id unit ...
       16347                  measurement_time  measurement_id unit ...
468    16001                  measurement_time  measurement_id unit ...
       16009                  measurement_time  measurement_id unit ...
...                                                                 ...
439    15337                  measurement_time  measurement_id unit ...
       15345                  measurement_time  measurement_id unit ...
355    11724                  measurement_time  measurement_id unit ...
       11732                  measurement_time  measurement_id unit ...
       11740                  measurement_time  measurement_id unit ...

                                                     measurements_array  \
run_id experiment_id
484    16331                  measurement_time  measurement_id    un...
       16339                  measurement_time  measurement_id    un...
       16347                  measurement_time  measurement_id    un...
468    16001                 measurement_time  measurement_id    uni...
       16009                 measurement_time  measurement_id    uni...
...                                                                 ...
439    15337                 measurement_time  measurement_id    uni...
       15345                 measurement_time  measurement_id    uni...
355    11724                  measurement_time  measurement_id    un...
       11732                  measurement_time  measurement_id    un...
       11740                  measurement_time  measurement_id    un...

                                                measurements_aggregated
run_id experiment_id
484    16331                  measurement_time    unit  Flow_Air  Fl...
       16339                  measurement_time    unit  Flow_Air  Fl...
       16347                  measurement_time    unit  Flow_Air  Fl...
468    16001                  measurement_time    unit  Flow_Air  Fl...
       16009                  measurement_time    unit  Flow_Air  Fl...
...                                                                 ...
439    15337                  measurement_time    unit  Flow_Air  Fl...
       15345                  measurement_time    unit  Flow_Air  Fl...
355    11724                  measurement_time    unit  Flow_Air  Fl...
       11732                  measurement_time    unit  Flow_Air  Fl...
       11740                  measurement_time    unit  Flow_Air  Fl...

[186 rows x 5 columns]

In [48]:
pd.concat(list(DF["metadata"]))

,experiment_id,bioreactor_id,container_number,profile_id,starter_culture_id,inactivation_method_id,description_x,color,profile_name,folder_id_x,...,description,conclusion,container_label,is_template,InducerConcentration,Stir_Min_pO2,Stir_pO2_Threshold,ph_Max_ul,ph_Min_ul,ph_Timesetpoint
0,16331,588,10,11010.0,None,1.0,None,#FFD95F02,B2,NaN,...,None,None,None,0,NaN,NaN,NaN,NaN,NaN,NaN
0,16339,588,18,11018.0,None,1.0,None,#FFD95F02,B3,NaN,...,None,None,None,0,NaN,NaN,NaN,NaN,NaN,NaN
0,16347,588,26,11026.0,None,1.0,None,#FFD95F02,B4,NaN,...,None,None,None,0,NaN,NaN,NaN,NaN,NaN,NaN
0,16001,572,16,10692.0,None,1.0,None,#FF666666,H2,NaN,...,None,None,None,0,500,NaN,NaN,NaN,NaN,NaN
0,16009,572,24,10700.0,None,1.0,None,#FF666666,H3,NaN,...,None,None,None,0,500,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,15337,495,21,10080.0,None,1.0,"µ_set: 40%, 2 mM IPTG",#FF66A61E,E3,NaN,...,None,None,None,0,500,NaN,NaN,NaN,NaN,NaN
0,15345,495,29,10088.0,None,1.0,"µ_set: 40%, 0.2 mM IPTG",#FF66A61E,E4,NaN,...,None,None,None,0,500,NaN,NaN,NaN,NaN,NaN
0,11724,397,11,6451.0,None,1.0,None,#FFAFFF00,C2,NaN,...,None,None,"Position,Organism",0,NaN,0,0,10,2,600
0,11732,397,19,6459.0,None,1.0,None,#FFAFFF00,C3,NaN,...,None,None,"Position,Organism",0,NaN,0,0,10,2,600
0,11740,397,27,6467.0,None,1.0,None,#FFAFFF00,C4,NaN,...,None,None,"Position,Organism",0,NaN,0,0,10,2,600

In [5]:
single_run = data_train[(484, 16331)]

{'metadata':    experiment_id  bioreactor_id  container_number  profile_id  \
 0          16331            588                10     11010.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFD95F02

   profile_name  folder_id_x  ...            run_name  folder_id_y  pms_id  \
 0           B2          NaN  ...  20210707_MHE_MPC_6          101       2

   status_id          start_time            end_time description conclusion  \
 0         3 2021-07-28 08:56:22 2021-07-28 22:37:27        None       None

   container_label is_template
 0            None           0

 [1 rows x 34 columns],
 'setpoints':     cultivation_age  setpoint_id    unit  Feed_glc_cum_setpoints  Flow_Air  \
 0                 0       728812       -                     NaN       NaN
 1                 0       728813      µL                     NaN       NaN
 2                 0       728814      µL                     NaN       NaN
 3                 0       728815      µL                     NaN       NaN
 11                0       735387  Ln/min                     NaN       NaN
 ..              ...          ...     ...                     ...       ...
 68            46830       741259      µL                  2137.0       NaN
 69            47430       741260      µL                  2187.0       NaN
 70            48030       741261      µL                  2237.0       NaN
 71            48630       741262      µL                  2287.0       NaN
 72            49230       741263      µL                  2337.0       NaN

     Flow_Nitrogen  Flow_O2  InducerConcentration  Puls_AceticAcid  \
 0             NaN      NaN                   NaN              NaN
 1             NaN      NaN                   NaN              NaN
 2             NaN      NaN                   NaN              0.0
 3             NaN      NaN                   NaN              NaN
 11            0.0      NaN                   NaN              NaN
 ..            ...      ...                   ...              ...
 68            NaN      NaN                   NaN              NaN
 69            NaN      NaN                   NaN              NaN
 70            NaN      NaN                   NaN              NaN
 71            NaN      NaN                   NaN              NaN
 72            NaN      NaN                   NaN              NaN

     Puls_Glucose  Puls_Medium  StirringSpeed   pH
 0            NaN          NaN            NaN  7.0
 1            0.0          NaN            NaN  NaN
 2            NaN          NaN            NaN  NaN
 3            NaN          0.0            NaN  NaN
 11           NaN          NaN            NaN  NaN
 ..           ...          ...            ...  ...
 68           NaN          NaN            NaN  NaN
 69           NaN          NaN            NaN  NaN
 70           NaN          NaN            NaN  NaN
 71           NaN          NaN            NaN  NaN
 72           NaN          NaN            NaN  NaN

 [74 rows x 13 columns],
 'measurements_reactor':         measurement_time  measurement_id unit  Acetate  Base  \
 0    2021-07-28 08:57:50      23058217.0    -      NaN   NaN
 1    2021-07-28 08:57:50      23058218.0    -      NaN   NaN
 2    2021-07-28 08:58:23      23058266.0    -      NaN   NaN
 3    2021-07-28 08:58:23      23058265.0    -      NaN   NaN
 4    2021-07-28 08:58:56      23058313.0    -      NaN   NaN
 ...                  ...             ...  ...      ...   ...
 3375 2021-07-28 22:33:26      23138039.0    -      NaN   NaN
 3376 2021-07-28 22:33:26      23138038.0    -      NaN   NaN
 3377 2021-07-28 22:33:38      23138087.0    -      NaN   NaN
 3378 2021-07-28 22:33:38      23138086.0    -      NaN   NaN
 3379 2021-07-28 17:26:22             NaN   mM      NaN   NaN

       Cumulated_feed_volume_glucose  Cumulated_feed_volume_medium    DOT  \
 0                               NaN                           NaN  68.71
 1                               NaN                           NaN    NaN
 2                               NaN                           NaN    NaN
 3                               NaN                           NaN  78.61
 4                               NaN                           NaN  81.91
 ...                             ...                           ...    ...
 3375                            NaN                           NaN    NaN
 3376                            NaN                           NaN  19.53
 3377                            NaN                           NaN    NaN
 3378                            NaN                           NaN   9.35
 3379                            NaN                           NaN    NaN

       Fluo_GFP  Glucose  OD600  Probe_Volume  Volume    pH  \
 0          NaN      NaN    NaN           NaN     NaN   NaN
 1          NaN      NaN    NaN           NaN     NaN  6.45
 2          NaN      NaN    NaN           NaN     NaN  6.50
 3          NaN      NaN    NaN           NaN     NaN   NaN
 4          NaN      NaN    NaN           NaN     NaN   NaN
 ...        ...      ...    ...           ...     ...   ...
 3375       NaN      NaN    NaN           NaN     NaN  6.86
 3376       NaN      NaN    NaN           NaN     NaN   NaN
 3377       NaN      NaN    NaN           NaN     NaN  6.86
 3378       NaN      NaN    NaN           NaN     NaN   NaN
 3379       NaN      NaN    NaN           NaN     NaN   NaN

       InducerConcentration                                             remark
 0                      NaN                                                NaN
 1                      NaN                                                NaN
 2                      NaN                                                NaN
 3                      NaN                                                NaN
 4                      NaN                                                NaN
 ...                    ...                                                ...
 3375                   NaN                                                NaN
 3376                   NaN                                                NaN
 3377                   NaN                                                NaN
 3378                   NaN                                                NaN
 3379                  0.05  value written to setpoints has been transferre...

 [3380 rows x 16 columns],
 'measurements_array':         measurement_time  measurement_id    unit  Flow_Air  Flow_Nitrogen  \
 0    2021-07-28 08:52:33         1409393      °C       NaN            NaN
 1    2021-07-28 08:52:38         1409394      °C       NaN            NaN
 2    2021-07-28 08:52:42         1409395      °C       NaN            NaN
 3    2021-07-28 08:53:02         1409396      °C       NaN            NaN
 4    2021-07-28 08:53:23         1409397      °C       NaN            NaN
 ...                  ...             ...     ...       ...            ...
 1229 2021-07-28 22:33:28         1410622   U/min       NaN            NaN
 1227 2021-07-28 22:33:42         1410625  Ln/min       0.0            NaN
 1232 2021-07-28 22:33:42         1410624  Ln/min       NaN            0.0
 1234 2021-07-28 22:33:42         1410626  Ln/min       NaN            NaN
 1230 2021-07-28 22:33:43         1410627   U/min       NaN            NaN

       Flow_O2  StirringSpeed  Temperature
 0         NaN            NaN        36.07
 1         NaN            NaN        36.09
 2         NaN            NaN        36.10
 3         NaN            NaN        36.18
 4         NaN            NaN        36.24
 ...       ...            ...          ...
 1229      NaN         2400.0          NaN
 1227      NaN            NaN          NaN
 1232      NaN            NaN          NaN
 1234      0.0            NaN          NaN
 1230      NaN         2400.0          NaN

 [1235 rows x 8 columns],
 'measurements_aggregated':         measurement_time    unit  Flow_Air  Flow_Nitrogen  Flow_O2  \
 0    2021-07-28 08:52:33      °C       NaN            NaN      NaN
 1    2021-07-28 08:52:38      °C       NaN            NaN      NaN
 2    2021-07-28 08:52:42      °C       NaN            NaN      NaN
 3    2021-07-28 08:53:02      °C       NaN            NaN      NaN
 4    2021-07-28 08:53:23      °C       NaN            NaN      NaN
 ...                  ...     ...       ...            ...      ...
 4610 2021-07-28 22:33:38       -       NaN            NaN      NaN
 4611 2021-07-28 22:33:42  Ln/min       0.0            NaN      NaN
 4612 2021-07-28 22:33:42  Ln/min       NaN            0.0      NaN
 4613 2021-07-28 22:33:42  Ln/min       NaN            NaN      0.0
 4614 2021-07-28 22:33:43   U/min       NaN            NaN      NaN

       StirringSpeed  Temperature  Acetate  Base  \
 0               NaN        36.07      NaN   NaN
 1               NaN        36.09      NaN   NaN
 2               NaN        36.10      NaN   NaN
 3               NaN        36.18      NaN   NaN
 4               NaN        36.24      NaN   NaN
 ...             ...          ...      ...   ...
 4610            NaN          NaN      NaN   NaN
 4611            NaN          NaN      NaN   NaN
 4612            NaN          NaN      NaN   NaN
 4613            NaN          NaN      NaN   NaN
 4614         2400.0          NaN      NaN   NaN

       Cumulated_feed_volume_glucose  Cumulated_feed_volume_medium  DOT  \
 0                               NaN                           NaN  NaN
 1                               NaN                           NaN  NaN
 2                               NaN                           NaN  NaN
 3                               NaN                           NaN  NaN
 4                               NaN                           NaN  NaN
 ...                             ...                           ...  ...
 4610                            NaN                           NaN  NaN
 4611                            NaN                           NaN  NaN
 4612                            NaN                           NaN  NaN
 4613                            NaN                           NaN  NaN
 4614                            NaN                           NaN  NaN

       Fluo_GFP  Glucose  OD600  Probe_Volume  Volume    pH  \
 0          NaN      NaN    NaN           NaN     NaN   NaN
 1          NaN      NaN    NaN           NaN     NaN   NaN
 2          NaN      NaN    NaN           NaN     NaN   NaN
 3          NaN      NaN    NaN           NaN     NaN   NaN
 4          NaN      NaN    NaN           NaN     NaN   NaN
 ...        ...      ...    ...           ...     ...   ...
 4610       NaN      NaN    NaN           NaN     NaN  6.86
 4611       NaN      NaN    NaN           NaN     NaN   NaN
 4612       NaN      NaN    NaN           NaN     NaN   NaN
 4613       NaN      NaN    NaN           NaN     NaN   NaN
 4614       NaN      NaN    NaN           NaN     NaN   NaN

       InducerConcentration remark
 0                      NaN    NaN
 1                      NaN    NaN
 2                      NaN    NaN
 3                      NaN    NaN
 4                      NaN    NaN
 ...                    ...    ...
 4610                   NaN    NaN
 4611                   NaN    NaN
 4612                   NaN    NaN
 4613                   NaN    NaN
 4614                   NaN    NaN

 [4615 rows x 20 columns]}

In [14]:
DataFrame.from_dict(data_train,orient='index', index=["run_id", "experiment_id"])

TypeError: from_dict() got an unexpected keyword argument 'index'

In [9]:
big_df = DataFrame(columns=single_run.keys())

Empty DataFrame
Columns: [metadata, setpoints, measurements_reactor, measurements_array, measurements_aggregated]
Index: []

In [10]:
big_df[123] = single_run
big_df

,metadata,setpoints,measurements_reactor,measurements_array,measurements_aggregated,123
metadata,NaN,NaN,NaN,NaN,NaN,metadata
setpoints,NaN,NaN,NaN,NaN,NaN,setpoints
measurements_reactor,NaN,NaN,NaN,NaN,NaN,measurements_reactor
measurements_array,NaN,NaN,NaN,NaN,NaN,measurements_array
measurements_aggregated,NaN,NaN,NaN,NaN,NaN,measurements_aggregated

In [44]:
DataFrame.from_dict(single_run, index=[(484, 16331)])

TypeError: from_dict() got an unexpected keyword argument 'index'

{'metadata':    experiment_id  bioreactor_id  container_number  profile_id  \
 0          16331            588                10     11010.0

   starter_culture_id  inactivation_method_id description_x      color  \
 0               None                     1.0          None  #FFD95F02

   profile_name  folder_id_x  ...            run_name  folder_id_y  pms_id  \
 0           B2          NaN  ...  20210707_MHE_MPC_6          101       2

   status_id          start_time            end_time description conclusion  \
 0         3 2021-07-28 08:56:22 2021-07-28 22:37:27        None       None

   container_label is_template
 0            None           0

 [1 rows x 34 columns],
 'setpoints':     cultivation_age  setpoint_id    unit  Feed_glc_cum_setpoints  Flow_Air  \
 0                 0       728812       -                     NaN       NaN
 1                 0       728813      µL                     NaN       NaN
 2                 0       728814      µL                     NaN       NaN
 3                 0       728815      µL                     NaN       NaN
 11                0       735387  Ln/min                     NaN       NaN
 ..              ...          ...     ...                     ...       ...
 68            46830       741259      µL                  2137.0       NaN
 69            47430       741260      µL                  2187.0       NaN
 70            48030       741261      µL                  2237.0       NaN
 71            48630       741262      µL                  2287.0       NaN
 72            49230       741263      µL                  2337.0       NaN

     Flow_Nitrogen  Flow_O2  InducerConcentration  Puls_AceticAcid  \
 0             NaN      NaN                   NaN              NaN
 1             NaN      NaN                   NaN              NaN
 2             NaN      NaN                   NaN              0.0
 3             NaN      NaN                   NaN              NaN
 11            0.0      NaN                   NaN              NaN
 ..            ...      ...                   ...              ...
 68            NaN      NaN                   NaN              NaN
 69            NaN      NaN                   NaN              NaN
 70            NaN      NaN                   NaN              NaN
 71            NaN      NaN                   NaN              NaN
 72            NaN      NaN                   NaN              NaN

     Puls_Glucose  Puls_Medium  StirringSpeed   pH
 0            NaN          NaN            NaN  7.0
 1            0.0          NaN            NaN  NaN
 2            NaN          NaN            NaN  NaN
 3            NaN          0.0            NaN  NaN
 11           NaN          NaN            NaN  NaN
 ..           ...          ...            ...  ...
 68           NaN          NaN            NaN  NaN
 69           NaN          NaN            NaN  NaN
 70           NaN          NaN            NaN  NaN
 71           NaN          NaN            NaN  NaN
 72           NaN          NaN            NaN  NaN

 [74 rows x 13 columns],
 'measurements_reactor':         measurement_time  measurement_id unit  Acetate  Base  \
 0    2021-07-28 08:57:50      23058217.0    -      NaN   NaN
 1    2021-07-28 08:57:50      23058218.0    -      NaN   NaN
 2    2021-07-28 08:58:23      23058266.0    -      NaN   NaN
 3    2021-07-28 08:58:23      23058265.0    -      NaN   NaN
 4    2021-07-28 08:58:56      23058313.0    -      NaN   NaN
 ...                  ...             ...  ...      ...   ...
 3375 2021-07-28 22:33:26      23138039.0    -      NaN   NaN
 3376 2021-07-28 22:33:26      23138038.0    -      NaN   NaN
 3377 2021-07-28 22:33:38      23138087.0    -      NaN   NaN
 3378 2021-07-28 22:33:38      23138086.0    -      NaN   NaN
 3379 2021-07-28 17:26:22             NaN   mM      NaN   NaN

       Cumulated_feed_volume_glucose  Cumulated_feed_volume_medium    DOT  \
 0                               NaN                           NaN  68.71
 1                               NaN                           NaN    NaN
 2                               NaN                           NaN    NaN
 3                               NaN                           NaN  78.61
 4                               NaN                           NaN  81.91
 ...                             ...                           ...    ...
 3375                            NaN                           NaN    NaN
 3376                            NaN                           NaN  19.53
 3377                            NaN                           NaN    NaN
 3378                            NaN                           NaN   9.35
 3379                            NaN                           NaN    NaN

       Fluo_GFP  Glucose  OD600  Probe_Volume  Volume    pH  \
 0          NaN      NaN    NaN           NaN     NaN   NaN
 1          NaN      NaN    NaN           NaN     NaN  6.45
 2          NaN      NaN    NaN           NaN     NaN  6.50
 3          NaN      NaN    NaN           NaN     NaN   NaN
 4          NaN      NaN    NaN           NaN     NaN   NaN
 ...        ...      ...    ...           ...     ...   ...
 3375       NaN      NaN    NaN           NaN     NaN  6.86
 3376       NaN      NaN    NaN           NaN     NaN   NaN
 3377       NaN      NaN    NaN           NaN     NaN  6.86
 3378       NaN      NaN    NaN           NaN     NaN   NaN
 3379       NaN      NaN    NaN           NaN     NaN   NaN

       InducerConcentration                                             remark
 0                      NaN                                                NaN
 1                      NaN                                                NaN
 2                      NaN                                                NaN
 3                      NaN                                                NaN
 4                      NaN                                                NaN
 ...                    ...                                                ...
 3375                   NaN                                                NaN
 3376                   NaN                                                NaN
 3377                   NaN                                                NaN
 3378                   NaN                                                NaN
 3379                  0.05  value written to setpoints has been transferre...

 [3380 rows x 16 columns],
 'measurements_array':         measurement_time  measurement_id    unit  Flow_Air  Flow_Nitrogen  \
 0    2021-07-28 08:52:33         1409393      °C       NaN            NaN
 1    2021-07-28 08:52:38         1409394      °C       NaN            NaN
 2    2021-07-28 08:52:42         1409395      °C       NaN            NaN
 3    2021-07-28 08:53:02         1409396      °C       NaN            NaN
 4    2021-07-28 08:53:23         1409397      °C       NaN            NaN
 ...                  ...             ...     ...       ...            ...
 1229 2021-07-28 22:33:28         1410622   U/min       NaN            NaN
 1227 2021-07-28 22:33:42         1410625  Ln/min       0.0            NaN
 1232 2021-07-28 22:33:42         1410624  Ln/min       NaN            0.0
 1234 2021-07-28 22:33:42         1410626  Ln/min       NaN            NaN
 1230 2021-07-28 22:33:43         1410627   U/min       NaN            NaN

       Flow_O2  StirringSpeed  Temperature
 0         NaN            NaN        36.07
 1         NaN            NaN        36.09
 2         NaN            NaN        36.10
 3         NaN            NaN        36.18
 4         NaN            NaN        36.24
 ...       ...            ...          ...
 1229      NaN         2400.0          NaN
 1227      NaN            NaN          NaN
 1232      NaN            NaN          NaN
 1234      0.0            NaN          NaN
 1230      NaN         2400.0          NaN

 [1235 rows x 8 columns],
 'measurements_aggregated':         measurement_time    unit  Flow_Air  Flow_Nitrogen  Flow_O2  \
 0    2021-07-28 08:52:33      °C       NaN            NaN      NaN
 1    2021-07-28 08:52:38      °C       NaN            NaN      NaN
 2    2021-07-28 08:52:42      °C       NaN            NaN      NaN
 3    2021-07-28 08:53:02      °C       NaN            NaN      NaN
 4    2021-07-28 08:53:23      °C       NaN            NaN      NaN
 ...                  ...     ...       ...            ...      ...
 4610 2021-07-28 22:33:38       -       NaN            NaN      NaN
 4611 2021-07-28 22:33:42  Ln/min       0.0            NaN      NaN
 4612 2021-07-28 22:33:42  Ln/min       NaN            0.0      NaN
 4613 2021-07-28 22:33:42  Ln/min       NaN            NaN      0.0
 4614 2021-07-28 22:33:43   U/min       NaN            NaN      NaN

       StirringSpeed  Temperature  Acetate  Base  \
 0               NaN        36.07      NaN   NaN
 1               NaN        36.09      NaN   NaN
 2               NaN        36.10      NaN   NaN
 3               NaN        36.18      NaN   NaN
 4               NaN        36.24      NaN   NaN
 ...             ...          ...      ...   ...
 4610            NaN          NaN      NaN   NaN
 4611            NaN          NaN      NaN   NaN
 4612            NaN          NaN      NaN   NaN
 4613            NaN          NaN      NaN   NaN
 4614         2400.0          NaN      NaN   NaN

       Cumulated_feed_volume_glucose  Cumulated_feed_volume_medium  DOT  \
 0                               NaN                           NaN  NaN
 1                               NaN                           NaN  NaN
 2                               NaN                           NaN  NaN
 3                               NaN                           NaN  NaN
 4                               NaN                           NaN  NaN
 ...                             ...                           ...  ...
 4610                            NaN                           NaN  NaN
 4611                            NaN                           NaN  NaN
 4612                            NaN                           NaN  NaN
 4613                            NaN                           NaN  NaN
 4614                            NaN                           NaN  NaN

       Fluo_GFP  Glucose  OD600  Probe_Volume  Volume    pH  \
 0          NaN      NaN    NaN           NaN     NaN   NaN
 1          NaN      NaN    NaN           NaN     NaN   NaN
 2          NaN      NaN    NaN           NaN     NaN   NaN
 3          NaN      NaN    NaN           NaN     NaN   NaN
 4          NaN      NaN    NaN           NaN     NaN   NaN
 ...        ...      ...    ...           ...     ...   ...
 4610       NaN      NaN    NaN           NaN     NaN  6.86
 4611       NaN      NaN    NaN           NaN     NaN   NaN
 4612       NaN      NaN    NaN           NaN     NaN   NaN
 4613       NaN      NaN    NaN           NaN     NaN   NaN
 4614       NaN      NaN    NaN           NaN     NaN   NaN

       InducerConcentration remark
 0                      NaN    NaN
 1                      NaN    NaN
 2                      NaN    NaN
 3                      NaN    NaN
 4                      NaN    NaN
 ...                    ...    ...
 4610                   NaN    NaN
 4611                   NaN    NaN
 4612                   NaN    NaN
 4613                   NaN    NaN
 4614                   NaN    NaN

 [4615 rows x 20 columns]}

In [32]:
pd.concat(data_train)

TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

In [27]:
len(list(splitter.split(col_run_to_exp)))

5

In [25]:
data_train[(484,16331)]['measurements_aggregated']

,measurement_time,unit,Flow_Air,Flow_Nitrogen,Flow_O2,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Fluo_GFP,Glucose,OD600,Probe_Volume,Volume,pH,InducerConcentration,remark
0,2021-07-28 08:52:33,°C,NaN,NaN,NaN,NaN,36.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-07-28 08:52:38,°C,NaN,NaN,NaN,NaN,36.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-07-28 08:52:42,°C,NaN,NaN,NaN,NaN,36.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-07-28 08:53:02,°C,NaN,NaN,NaN,NaN,36.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-07-28 08:53:23,°C,NaN,NaN,NaN,NaN,36.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4610,2021-07-28 22:33:38,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.86,NaN,NaN
4611,2021-07-28 22:33:42,Ln/min,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612,2021-07-28 22:33:42,Ln/min,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4613,2021-07-28 22:33:42,Ln/min,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4614,2021-07-28 22:33:43,U/min,NaN,NaN,NaN,2400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Data Validation

Format

```python
data: tuple[
    dict[
        'description': set[str],
        'variables': list[dict[str, str]],
        'time_format': str,
        'series': dict[int, 
            dict['generating_parameters': 
                 dict[
                     'qsmax': float,
                     'qm': float,
                     'qamax': float,
                     'Yem': float,
                     'Yxsof': float,
                     'Yxa': float,
                     'Yos': float,
                     'Yoa': float,
                     'Yas': float,
                     'Kia': float,
                     'Ks': float,
                     'Ko': float,
                     'Kap': float,
                     'Kis': float,
                     'Ksa': float,
                     'Pamax': float,
                     'F0': float,
                     'mu_set': float,
                     'C_feed': float,
                     'Kp': float,
                ]
            ],
        ],
    ], 
    dict[int, DataFrame[columns=['X', 'S', 'A', 'DOTm', 'V', 'pulse', 'kLa']]]
]
```

In [28]:
data[0]['series'][4882]['generating_parameters']

{'qsmax': 0.7197797304149138,
 'qm': 0.014888769306035027,
 'qamax': 0.8960064674267967,
 'Yem': 0.46538347845571143,
 'Yxsof': 0.340534444208402,
 'Yxa': 0.7781277566424536,
 'Yos': 1.6401753137003867,
 'Yoa': 0.611153872735589,
 'Yas': 0.4134534103781927,
 'Kia': 1.603495736198795,
 'Ks': 0.15845942072876604,
 'Ko': 1.6135374441324517,
 'Kap': 0.2449559453171731,
 'Kis': 2.7095816868132783,
 'Ksa': 0.048757748897362695,
 'Pamax': 0.20723445191327067,
 'F0': 0.0087,
 'mu_set': 0.222,
 'C_feed': None,
 'Kp': 15.230442160485438}

AttributeError: 'tuple' object has no attribute 'keys'

In [9]:
data[0]['variables']

[{'name': 'X', 'unit': 'g/L', 'dtype': float, 'control': False},
 {'name': 'S', 'unit': 'g/L', 'dtype': float, 'control': False},
 {'name': 'A', 'unit': '%', 'dtype': float, 'control': False},
 {'name': 'DOTm', 'unit': '%', 'dtype': float, 'control': False},
 {'name': 'kLa', 'unit': 'h^(-1)', 'dtype': float, 'control': True},
 {'name': 'pulse', 'unit': 'ml', 'dtype': float, 'control': True}]