## Testing Implementation

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
logging.basicConfig(level=logging.INFO)

In [2]:
from tsdm.datasets import KIWI_RUNS

INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:tsdm.config._config:Available Models: {'N-BEATS', 'SET-TS', 'TFT', 'NODE', 'mTAN', 'M-RNN', 'IP-Net', 'GRU-ODE-Bayes', 'Informer', 'NCDE', 'ODE-RNN', 'Latent-ODE', 'BRITS', 'TPA'}
INFO:tsdm.config._config:Available Datasets: {'M5', 'Physionet 2012', 'MuJoCo', 'USHCN', 'tourism1', 'UWAVE', 'Air Quality Multi-Site', 'M4', 'Air Quality', 'M3', 'Traffic', 'Household Consumption', 'Electricity', 'tourism2', 'Human Activity', 'Character Trajectories', 'Physionet 2019'}
INFO:tsdm.config._config:Initializing folder structure
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/datasets
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/models
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/logs
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/rawdata
INFO:tsdm.config._config:Created folder structure in /home/rscholz/.tsdm
WARNING:tsdm.datasets.ushcn:Using Modin with Ray Backend

In [4]:
ds = KIWI_RUNS()

INFO:tsdm.datasets.base._base:KIWI_RUNS: START cleaning dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/units already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE cleaning dataset
INFO:tsdm.datasets.base._base:KIWI_RUNS: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE loading dataset!

KIWI_RUNS['timeseries', 'metadata', 'units']

In [7]:
ds.units

                                   unit
variable
Flow_Air                         Ln/min
StirringSpeed                     U/min
Temperature                          °C
Acetate                             g/L
Base                                 uL
Cumulated_feed_volume_glucose        uL
Cumulated_feed_volume_medium         uL
DOT                                   %
Glucose                             g/L
OD600                                 %
Probe_Volume                         uL
pH                             -log[H⁺]
Fluo_GFP                            RFU
InducerConcentration                 mM
Volume                               mL

INFO:tsdm.datasets.base._base:KIWI_RUNS: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE loading dataset!

KIWI_RUNS['timeseries', 'metadata', 'units']

In [26]:
ds.metadata

                      Feed_concentration_glc  OD_Dilution  bioreactor_id  \
run_id experiment_id
355    11722                            <NA>        100.0            397
       11723                            <NA>        100.0            397
       11724                            <NA>        100.0            397
       11725                            <NA>        100.0            397
       11726                            <NA>        100.0            397
...                                      ...          ...            ...
510    16867                             200         50.0            614
       16868                             200         50.0            614
       16869                             200         50.0            614
       16870                             200         50.0            614
       16871                             200         50.0            614

                          color  container_number            end_time  \
run_id experiment_id
355    11722          #FFFF6404                 9 2019-04-10 07:43:33
       11723          #FFFFF400                10 2019-04-10 07:43:33
       11724          #FFAFFF00                11 2019-04-10 07:43:33
       11725          #FF00FFAB                12 2019-04-10 07:43:33
       11726          #FF00ABFF                13 2019-04-10 07:43:33
...                         ...               ...                 ...
510    16867          #FFE7298A                28 2021-10-26 23:14:23
       16868          #FF66A61E                29 2021-10-26 23:14:23
       16869          #FFE6AB02                30 2021-10-26 23:14:23
       16870          #FFA6761D                31 2021-10-26 23:14:23
       16871          #FF666666                32 2021-10-26 23:14:23

                      organism_id  pH_correction_factor  profile_id  \
run_id experiment_id
355    11722                    3                  <NA>        6449
       11723                    8                  <NA>        6450
       11724                   21                  <NA>        6451
       11725                   32                  <NA>        6452
       11726                   14                  <NA>        6453
...                           ...                   ...         ...
510    16867                   41                   0.3       11527
       16868                   41                   0.3       11528
       16869                   41                   0.3       11529
       16870                   41                   0.3       11530
       16871                   41                   0.3       11531

                     profile_name                      run_name  \
run_id experiment_id
355    11722                   A2             20190409_SWORD_II
       11723                   B2             20190409_SWORD_II
       11724                   C2             20190409_SWORD_II
       11725                   D2             20190409_SWORD_II
       11726                   E2             20190409_SWORD_II
...                           ...                           ...
510    16867                   D4  20211020_Pre_experiment_KIWI
       16868                   E4  20211020_Pre_experiment_KIWI
       16869                   F4  20211020_Pre_experiment_KIWI
       16870                   G4  20211020_Pre_experiment_KIWI
       16871                   H4  20211020_Pre_experiment_KIWI

                              start_time
run_id experiment_id
355    11722         2019-04-09 18:31:53
       11723         2019-04-09 18:31:53
       11724         2019-04-09 18:31:53
       11725         2019-04-09 18:31:53
       11726         2019-04-09 18:31:53
...                                  ...
510    16867         2021-10-26 09:13:47
       16868         2021-10-26 09:13:47
       16869         2021-10-26 09:13:47
       16870         2021-10-26 09:13:47
       16871         2021-10-26 09:13:47

[264 rows x 12 columns]

In [21]:
ds._load(key="timeseries")

variable                                  Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       0.0            0.0
                     2019-04-09 18:32:18       0.0            0.0
                     2019-04-09 18:32:19       0.0            0.0
                     2019-04-09 18:32:21  4.997213            0.0
                     2019-04-09 18:32:22  4.997213            0.0
...                                            ...            ...
510    16871         2021-10-26 22:41:26       5.0            0.0
                     2021-10-26 22:42:11       5.0            0.0
                     2021-10-26 22:42:20       5.0            0.0
                     2021-10-26 22:43:22       5.0            0.0
                     2021-10-26 22:43:31       5.0            0.0

variable                                  Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    36.990002     <NA>  <NA>
                     2019-04-09 18:32:18         <NA>     <NA>  <NA>
                     2019-04-09 18:32:19         <NA>     <NA>  <NA>
                     2019-04-09 18:32:21         <NA>     <NA>  <NA>
                     2019-04-09 18:32:22        36.98     <NA>  <NA>
...                                               ...      ...   ...
510    16871         2021-10-26 22:41:26         <NA>     <NA>  <NA>
                     2021-10-26 22:42:11    37.450001     <NA>  <NA>
                     2021-10-26 22:42:20         <NA>     <NA>  <NA>
                     2021-10-26 22:43:22    37.439999     <NA>  <NA>
                     2021-10-26 22:43:31         <NA>     <NA>  <NA>

variable                                  Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                            0.0
                     2019-04-09 18:32:18                            0.0
                     2019-04-09 18:32:19                            0.0
                     2019-04-09 18:32:21                            0.0
                     2019-04-09 18:32:22                            0.0
...                                                                 ...
510    16871         2021-10-26 22:41:26                         1061.0
                     2021-10-26 22:42:11                         1061.0
                     2021-10-26 22:42:20                         1061.0
                     2021-10-26 22:43:22                         1061.0
                     2021-10-26 22:43:31                         1061.0

variable                                  Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                           0.0
                     2019-04-09 18:32:18                           0.0
                     2019-04-09 18:32:19                           0.0
                     2019-04-09 18:32:21                           0.0
                     2019-04-09 18:32:22                           0.0
...                                                                ...
510    16871         2021-10-26 22:41:26                   3787.307373
                     2021-10-26 22:42:11                   3787.307373
                     2021-10-26 22:42:20                   3787.307373
                     2021-10-26 22:43:22                   3787.307373
                     2021-10-26 22:43:31                   3787.307373

variable                                        DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>     <NA>   <NA>
                     2019-04-09 18:32:18  89.660004     <NA>   <NA>
                     2019-04-09 18:32:19       <NA>     <NA>   <NA>
                     2019-04-09 18:32:21       <NA>     <NA>   <NA>
                     2019-04-09 18:32:22       <NA>     <NA>   <NA>
...                                             ...      ...    ...
510    16871         2021-10-26 22:41:26       <NA>     <NA>   <NA>
                     2021-10-26 22:42:11       <NA>     <NA>   <NA>
                     2021-10-26 22:42:20  79.459999     <NA>   <NA>
                     2021-10-26 22:43:22       <NA>     <NA>   <NA>
                     2021-10-26 22:43:31  78.860001     <NA>   <NA>

variable                                  Probe_Volume        pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12           0.0      <NA>      <NA>
                     2019-04-09 18:32:18           0.0      <NA>      <NA>
                     2019-04-09 18:32:19           0.0      6.86      <NA>
                     2019-04-09 18:32:21           0.0      <NA>      <NA>
                     2019-04-09 18:32:22           0.0      <NA>      <NA>
...                                                ...       ...       ...
510    16871         2021-10-26 22:41:26        5500.0      <NA>      <NA>
                     2021-10-26 22:42:11        5500.0      <NA>      <NA>
                     2021-10-26 22:42:20        5500.0  7.320229      <NA>
                     2021-10-26 22:43:22        5500.0      <NA>      <NA>
                     2021-10-26 22:43:31        5500.0  7.336412      <NA>

variable                                  InducerConcentration      Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                   0.0        <NA>
                     2019-04-09 18:32:18                   0.0        <NA>
                     2019-04-09 18:32:19                   0.0        <NA>
                     2019-04-09 18:32:21                   0.0        <NA>
                     2019-04-09 18:32:22                   0.0        <NA>
...                                                        ...         ...
510    16871         2021-10-26 22:41:26                   0.0 -312.692749
                     2021-10-26 22:42:11                   0.0        <NA>
                     2021-10-26 22:42:20                   0.0        <NA>
                     2021-10-26 22:43:22                   0.0        <NA>
                     2021-10-26 22:43:31                   0.0        <NA>

[440912 rows x 15 columns]

In [2]:
md = KIWI_RUNS.metadata

In [57]:
# remove run_id 355
md = md.drop(355)

                      Feed_concentration_glc  OD_Dilution  bioreactor_id  \
run_id experiment_id
439    15325                             400         50.0            495
       15326                             400         50.0            495
       15327                             400         50.0            495
       15328                             400         50.0            495
       15329                             400         50.0            495
...                                      ...          ...            ...
510    16867                             200         50.0            614
       16868                             200         50.0            614
       16869                             200         50.0            614
       16870                             200         50.0            614
       16871                             200         50.0            614

                          color  container_number            end_time  \
run_id experiment_id
439    15325          #FF1B9E77                 9 2020-12-09 23:34:23
       15326          #FFD95F02                10 2020-12-09 23:34:23
       15327          #FF7570B3                11 2020-12-09 23:34:23
       15328          #FFE7298A                12 2020-12-09 23:34:23
       15329          #FF66A61E                13 2020-12-09 23:34:23
...                         ...               ...                 ...
510    16867          #FFE7298A                28 2021-10-26 23:14:23
       16868          #FF66A61E                29 2021-10-26 23:14:23
       16869          #FFE6AB02                30 2021-10-26 23:14:23
       16870          #FFA6761D                31 2021-10-26 23:14:23
       16871          #FF666666                32 2021-10-26 23:14:23

                      organism_id  pH_correction_factor  profile_id  \
run_id experiment_id
439    15325                   41                   0.5       10068
       15326                   41                   0.5       10069
       15327                   41                   0.5       10070
       15328                   41                   0.5       10071
       15329                   41                   0.5       10072
...                           ...                   ...         ...
510    16867                   41                   0.3       11527
       16868                   41                   0.3       11528
       16869                   41                   0.3       11529
       16870                   41                   0.3       11530
       16871                   41                   0.3       11531

                     profile_name                      run_name  \
run_id experiment_id
439    15325                   A2               20201209_01_MHE
       15326                   B2               20201209_01_MHE
       15327                   C2               20201209_01_MHE
       15328                   D2               20201209_01_MHE
       15329                   E2               20201209_01_MHE
...                           ...                           ...
510    16867                   D4  20211020_Pre_experiment_KIWI
       16868                   E4  20211020_Pre_experiment_KIWI
       16869                   F4  20211020_Pre_experiment_KIWI
       16870                   G4  20211020_Pre_experiment_KIWI
       16871                   H4  20211020_Pre_experiment_KIWI

                              start_time
run_id experiment_id
439    15325         2020-12-09 09:09:58
       15326         2020-12-09 09:09:58
       15327         2020-12-09 09:09:58
       15328         2020-12-09 09:09:58
       15329         2020-12-09 09:09:58
...                                  ...
510    16867         2021-10-26 09:13:47
       16868         2021-10-26 09:13:47
       16869         2021-10-26 09:13:47
       16870         2021-10-26 09:13:47
       16871         2021-10-26 09:13:47

[240 rows x 12 columns]

In [58]:
# now there are no missing values!
pandas.isna(md).sum()

Feed_concentration_glc    0
OD_Dilution               0
bioreactor_id             0
color                     0
container_number          0
end_time                  0
organism_id               0
pH_correction_factor      0
profile_id                0
profile_name              0
run_name                  0
start_time                0
dtype: int64

In [50]:
# almost all data is highly compressible.
Series({col: len(md[col].unique()) for col in md})

Feed_concentration_glc      3
OD_Dilution                 3
bioreactor_id              10
color                      22
container_number           48
end_time                   10
organism_id                 8
pH_correction_factor        5
profile_id                264
profile_name               48
run_name                   10
start_time                 10
dtype: int64

In [49]:
md.dtypes

Feed_concentration_glc             Int16
OD_Dilution                      Float32
bioreactor_id                     UInt32
color                           category
container_number                  UInt32
end_time                  datetime64[ns]
organism_id                       UInt32
pH_correction_factor             Float32
profile_id                        UInt32
profile_name                    category
run_name                        category
start_time                datetime64[ns]
dtype: object

In [51]:
pd.isna(md).sum()

Feed_concentration_glc    24
OD_Dilution                0
bioreactor_id              0
color                      0
container_number           0
end_time                   0
organism_id                0
pH_correction_factor      24
profile_id                 0
profile_name               0
run_name                   0
start_time                 0
dtype: int64

In [48]:
Regarding  # We see that profile_id is useless however, since
# it is a categorical that is different for every input

In [39]:
[len]KIWI_RUNS.metadata["profile_name"].unique()

['A2', 'B2', 'C2', 'D2', 'E2', ..., 'D6', 'E6', 'F6', 'G6', 'H6']
Length: 48
Categories (48, object): ['A1', 'A2', 'A3', 'A4', ..., 'H3', 'H4', 'H5', 'H6']

Feed_concentration_glc             Int16 → convert to float
OD_Dilution                      Float32 → keep as-is
bioreactor_id                     UInt32 → drop / One-Hot
color                           category → drop / One-Hot
container_number                  UInt32 → drop
end_time                  datetime64[ns] → drop, but use for time-scaling
organism_id                       UInt32 → One-Hot
pH_correction_factor             Float32 → keep as-is
profile_id                        UInt32 → drop
profile_name                    category → drop
run_name                        category → drop
start_time                datetime64[ns] → drop, but use for time-scaling