# Importing KIWI dataset

### Data Validation

Format

```python
data: tuple[
    dict[
        'description': set[str],
        'variables': list[dict[str, str]],
        'time_format': str,
        'series': dict[int, 
            dict['generating_parameters': 
                 dict[
                     'qsmax': float,
                     'qm': float,
                     'qamax': float,
                     'Yem': float,
                     'Yxsof': float,
                     'Yxa': float,
                     'Yos': float,
                     'Yoa': float,
                     'Yas': float,
                     'Kia': float,
                     'Ks': float,
                     'Ko': float,
                     'Kap': float,
                     'Kis': float,
                     'Ksa': float,
                     'Pamax': float,
                     'F0': float,
                     'mu_set': float,
                     'C_feed': float,
                     'Kp': float,
                ]
            ],
        ],
    ], 
    dict[int, DataFrame[columns=['X', 'S', 'A', 'DOTm', 'V', 'pulse', 'kLa']]]
]
```

In [127]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [178]:
import pickle

import numpy as np
import pandas
import pandas as pd
from pandas import DataFrame, Series, Interval, Period, Timestamp, Timedelta

## Data Encoding

Problem: Columns are encoded in wrong data-types (e.g. categoricals as int or string, floats as string, ints as floats etc.)

Solution: Sequentially figure out data types

Data Type Hirarchy:
1. String-Like (`np.flexible`)
    - strings
    - bytes
2. TimeLike types
    - Timestamp (np.datetime64)
    - Timedelta (np.timedelta64)
3. Numerical (`np.number`)
   - floating (`np.floating`)
       - float
       - complex
   - integer (`np.integer`)
       - signed
       - unsigned
4. Boolean (np.bool_)
5. Pandas special types
    - CategoricalDtype
    - DatetimeTZDtype
    - PeriodDtype
    - IntervalDtype

End goal: whenever it is appropriate to do so, perform the following conversions:

1. Get appropriate Nullable Pandas type
2. Downcast int → uint
3. Downcast int64 → int32 → int16 → int8
3. Downcast float64 → float32
4. Downcast complex128 → complex64
5. Convert to categorical datatype

In [162]:
def subdtypes(dtype):
    subs = dtype.__subclasses__()
    if not subs:
        return dtype
    return [dtype, [subdtypes(dt) for dt in subs]]

subdtypes(np.generic)

[numpy.generic,
 [[numpy.number,
   [[numpy.integer,
     [[numpy.signedinteger,
       [numpy.int8,
        numpy.int16,
        numpy.int32,
        numpy.int64,
        numpy.longlong,
        numpy.timedelta64]],
      [numpy.unsignedinteger,
       [numpy.uint8,
        numpy.uint16,
        numpy.uint32,
        numpy.uint64,
        numpy.ulonglong]]]],
    [numpy.inexact,
     [[numpy.floating,
       [numpy.float16, numpy.float32, numpy.float64, numpy.float128]],
      [numpy.complexfloating,
       [numpy.complex64, numpy.complex128, numpy.complex256]]]]]],
  [numpy.flexible,
   [[numpy.character, [numpy.bytes_, numpy.str_]],
    [numpy.void, [numpy.record]]]],
  numpy.bool_,
  numpy.datetime64,
  numpy.object_]]

In [172]:
type(pandas.Series([1.3]).dtype)

numpy.dtype[float64]

### Format


```python
dict[int, # run_id
    dict[int, # experiment_id
         dict[
             'metadata',: DataFrame,                # static
             'setpoints': DataFrame,                # static
             'measurements_reactor',: DataFrame,    # TimeTensor
             'measurements_array',: DataFrame,      # TimeTensor
             'measurements_aggregated': DataFrame,  # TimeTensor
         ]
    ]
]

```

In [2]:
with open("kiwi_experiments_and_run_355.pk", "rb") as file:
    data = pickle.load(file)

col_run_to_exp = create_replicate_dict(data)
splitter = ReplicateBasedSplitter()

In [3]:
DATA = [
    (data[run][exp] | {"run_id": run, "experiment_id": exp})
    for run in data
    for exp in data[run]
]
DF = DataFrame(DATA).set_index(["run_id", "experiment_id"])

                                                               metadata  \
run_id experiment_id
355    11722             experiment_id  bioreactor_id  container_num...
       11723             experiment_id  bioreactor_id  container_num...
       11724             experiment_id  bioreactor_id  container_num...
       11725             experiment_id  bioreactor_id  container_num...
       11726             experiment_id  bioreactor_id  container_num...
...                                                                 ...
484    16349             experiment_id  bioreactor_id  container_num...
       16350             experiment_id  bioreactor_id  container_num...
       16351             experiment_id  bioreactor_id  container_num...
       16352             experiment_id  bioreactor_id  container_num...
       16353             experiment_id  bioreactor_id  container_num...

                                                              setpoints  \
run_id experiment_id
355    11722               cultivation_age  setpoint_id   unit  Puls...
       11723               cultivation_age  setpoint_id   unit  Puls...
       11724               cultivation_age  setpoint_id   unit  Puls...
       11725               cultivation_age  setpoint_id   unit  Puls...
       11726              cultivation_age  setpoint_id   unit  Puls_...
...                                                                 ...
484    16349              cultivation_age  setpoint_id    unit  Feed...
       16350              cultivation_age  setpoint_id    unit  Feed...
       16351              cultivation_age  setpoint_id    unit  Feed...
       16352              cultivation_age  setpoint_id    unit  Feed...
       16353              cultivation_age  setpoint_id    unit  Feed...

                                                   measurements_reactor  \
run_id experiment_id
355    11722                  measurement_time  measurement_id unit ...
       11723                  measurement_time  measurement_id unit ...
       11724                  measurement_time  measurement_id unit ...
       11725                  measurement_time  measurement_id unit ...
       11726                  measurement_time  measurement_id unit ...
...                                                                 ...
484    16349                  measurement_time  measurement_id unit ...
       16350                  measurement_time  measurement_id unit ...
       16351                  measurement_time  measurement_id unit ...
       16352                  measurement_time  measurement_id unit ...
       16353                  measurement_time  measurement_id unit ...

                                                     measurements_array  \
run_id experiment_id
355    11722                  measurement_time  measurement_id    un...
       11723                  measurement_time  measurement_id    un...
       11724                  measurement_time  measurement_id    un...
       11725                  measurement_time  measurement_id    un...
       11726                  measurement_time  measurement_id    un...
...                                                                 ...
484    16349                  measurement_time  measurement_id    un...
       16350                  measurement_time  measurement_id    un...
       16351                  measurement_time  measurement_id    un...
       16352                  measurement_time  measurement_id    un...
       16353                  measurement_time  measurement_id    un...

                                                measurements_aggregated
run_id experiment_id
355    11722                  measurement_time    unit  Flow_Air  Fl...
       11723                  measurement_time    unit  Flow_Air  Fl...
       11724                  measurement_time    unit  Flow_Air  Fl...
       11725                  measurement_time    unit  Flow_Air  Fl...
       11726                  measurement_time    unit  Flow_Air  Fl...
...                                                                 ...
484    16349                  measurement_time    unit  Flow_Air  Fl...
       16350                  measurement_time    unit  Flow_Air  Fl...
       16351                  measurement_time    unit  Flow_Air  Fl...
       16352                  measurement_time    unit  Flow_Air  Fl...
       16353                  measurement_time    unit  Flow_Air  Fl...

[240 rows x 5 columns]

## Raw-Data

In [ ]:
from cross_validate_kiwi_runs import ReplicateBasedSplitter, create_replicate_dict

In [4]:
tables = {}

for key in (
    "metadata",
    "setpoints",
    "measurements_reactor",
    "measurements_array",
    "measurements_aggregated",
):
    if key == "metadata":
        tables[key] = pd.concat(iter(DF[key])).reset_index(drop=True)
    else:
        tables[key] = (
            pd.concat(iter(DF[key]), keys=DF[key].index)
            .reset_index(level=2, drop=True)
            .reset_index()
        )

tables

{'metadata':      experiment_id  bioreactor_id  container_number  profile_id  \
 0            11722            397                 9      6449.0
 1            11723            397                10      6450.0
 2            11724            397                11      6451.0
 3            11725            397                12      6452.0
 4            11726            397                13      6453.0
 ..             ...            ...               ...         ...
 235          16349            588                28     11028.0
 236          16350            588                29     11029.0
 237          16351            588                30     11030.0
 238          16352            588                31     11031.0
 239          16353            588                32     11032.0

     starter_culture_id  inactivation_method_id description_x      color  \
 0                 None                     1.0          None  #FFFF6404
 1                 None                     1.0          None  #FFFFF400
 2                 None                     1.0          None  #FFAFFF00
 3                 None                     1.0          None  #FF00FFAB
 4                 None                     1.0          None  #FF00ABFF
 ..                 ...                     ...           ...        ...
 235               None                     1.0          None  #FFE7298A
 236               None                     1.0          None  #FF66A61E
 237               None                     1.0          None  #FFE6AB02
 238               None                     1.0          None  #FFA6761D
 239               None                     1.0          None  #FF666666

     profile_name  folder_id_x  ...          start_time            end_time  \
 0             A2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 1             B2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 2             C2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 3             D2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 4             E2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 ..           ...          ...  ...                 ...                 ...
 235           D4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 236           E4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 237           F4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 238           G4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 239           H4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27

      description conclusion    container_label is_template Acetate_Dilution  \
 0           None       None  Position,Organism           0              NaN
 1           None       None  Position,Organism           0              NaN
 2           None       None  Position,Organism           0              NaN
 3           None       None  Position,Organism           0              NaN
 4           None       None  Position,Organism           0              NaN
 ..           ...        ...                ...         ...              ...
 235         None       None               None           0                1
 236         None       None               None           0                1
 237         None       None               None           0                1
 238         None       None               None           0                1
 239         None       None               None           0                1

     Feed_concentration_glc InducerConcentration pH_correction_factor
 0                      NaN                  NaN                  NaN
 1                      NaN                  NaN                  NaN
 2                      NaN                  NaN                  NaN
 3                      NaN                  NaN                  NaN
 4                      NaN                  NaN                  NaN
 ..                     ...                  ...                  ...
 235                    200                  NaN                  0.2
 236                    200                  NaN                  0.2
 237                    200                  NaN                  0.2
 238                    200                  NaN                  0.2
 239                    200                  NaN                  0.2

 [240 rows x 40 columns],
 'setpoints':        run_id  experiment_id  cultivation_age  setpoint_id   unit  \
 0         355          11722                0       470579      -
 1         355          11722                0       470581     µL
 2         355          11722                0       470582     µL
 3         355          11722                0       470675  U/min
 4         355          11722                0       470580     µL
 ...       ...            ...              ...          ...    ...
 23121     484          16353            46583       742149     µL
 23122     484          16353            47183       742150     µL
 23123     484          16353            47783       742151     µL
 23124     484          16353            48383       742152     µL
 23125     484          16353            48983       742153     µL

        Puls_AceticAcid  Puls_Glucose  Puls_Medium  StirringSpeed   pH  \
 0                  NaN           NaN          NaN            NaN  7.0
 1                  0.0           NaN          NaN            NaN  NaN
 2                  NaN           NaN          0.0            NaN  NaN
 3                  NaN           NaN          NaN         3000.0  NaN
 4                  NaN           0.0          NaN            NaN  NaN
 ...                ...           ...          ...            ...  ...
 23121              NaN           NaN          NaN            NaN  NaN
 23122              NaN           NaN          NaN            NaN  NaN
 23123              NaN           NaN          NaN            NaN  NaN
 23124              NaN           NaN          NaN            NaN  NaN
 23125              NaN           NaN          NaN            NaN  NaN

        Feed_glc_cum_setpoints  Flow_Air  InducerConcentration  Flow_Nitrogen  \
 0                         NaN       NaN                   NaN            NaN
 1                         NaN       NaN                   NaN            NaN
 2                         NaN       NaN                   NaN            NaN
 3                         NaN       NaN                   NaN            NaN
 4                         NaN       NaN                   NaN            NaN
 ...                       ...       ...                   ...            ...
 23121                   906.0       NaN                   NaN            NaN
 23122                   926.0       NaN                   NaN            NaN
 23123                   946.0       NaN                   NaN            NaN
 23124                   966.0       NaN                   NaN            NaN
 23125                   986.0       NaN                   NaN            NaN

        Flow_O2  Feed_dextrine_cum_setpoints
 0          NaN                          NaN
 1          NaN                          NaN
 2          NaN                          NaN
 3          NaN                          NaN
 4          NaN                          NaN
 ...        ...                          ...
 23121      NaN                          NaN
 23122      NaN                          NaN
 23123      NaN                          NaN
 23124      NaN                          NaN
 23125      NaN                          NaN

 [23126 rows x 16 columns],
 'measurements_reactor':         run_id  experiment_id    measurement_time  measurement_id unit  \
 0          355          11722 2019-04-09 18:32:18      18358520.0    -
 1          355          11722 2019-04-09 18:32:19      18358544.0    -
 2          355          11722 2019-04-09 18:32:28      18358568.0    -
 3          355          11722 2019-04-09 18:32:29      18358592.0    -
 4          355          11722 2019-04-09 18:32:38      18358616.0    -
 ...        ...            ...                 ...             ...  ...
 429794     484          16353 2021-07-28 22:33:26      23138083.0    -
 429795     484          16353 2021-07-28 22:33:26      23138082.0    -
 429796     484          16353 2021-07-28 22:33:38      23138131.0    -
 429797     484          16353 2021-07-28 22:33:38      23138130.0    -
 429798     484          16353 2021-07-28 17:26:22             NaN   mM

         Acetate  Acid  Base  Cumulated_feed_volume_glucose  \
 0           NaN   NaN   NaN                            NaN
 1           NaN   NaN   NaN                            NaN
 2           NaN   NaN   NaN                            NaN
 3           NaN   NaN   NaN                            NaN
 4           NaN   NaN   NaN                            NaN
 ...         ...   ...   ...                            ...
 429794      NaN   NaN   NaN                            NaN
 429795      NaN   NaN   NaN                            NaN
 429796      NaN   NaN   NaN                            NaN
 429797      NaN   NaN   NaN                            NaN
 429798      NaN   NaN   NaN                            NaN

         Cumulated_feed_volume_medium  ...  Fluo_RFP  Fluo_YFP  Glucose  OD600  \
 0                                NaN  ...       NaN       NaN      NaN    NaN
 1                                NaN  ...       NaN       NaN      NaN    NaN
 2                                NaN  ...       NaN       NaN      NaN    NaN
 3                                NaN  ...       NaN       NaN      NaN    NaN
 4                                NaN  ...       NaN       NaN      NaN    NaN
 ...                              ...  ...       ...       ...      ...    ...
 429794                           NaN  ...       NaN       NaN      NaN    NaN
 429795                           NaN  ...       NaN       NaN      NaN    NaN
 429796                           NaN  ...       NaN       NaN      NaN    NaN
 429797                           NaN  ...       NaN       NaN      NaN    NaN
 429798                           NaN  ...       NaN       NaN      NaN    NaN

         Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
 0                NaN   NaN       NaN                   NaN
 1                NaN  6.86       NaN                   NaN
 2                NaN   NaN       NaN                   NaN
 3                NaN  6.86       NaN                   NaN
 4                NaN   NaN       NaN                   NaN
 ...              ...   ...       ...                   ...
 429794           NaN  6.88       NaN                   NaN
 429795           NaN   NaN       NaN                   NaN
 429796           NaN  6.87       NaN                   NaN
 429797           NaN   NaN       NaN                   NaN
 429798           NaN   NaN       NaN                   2.0

                                                    remark  Volume
 0                                                     NaN     NaN
 1                                                     NaN     NaN
 2                                                     NaN     NaN
 3                                                     NaN     NaN
 4                                                     NaN     NaN
 ...                                                   ...     ...
 429794                                                NaN     NaN
 429795                                                NaN     NaN
 429796                                                NaN     NaN
 429797                                                NaN     NaN
 429798  value written to setpoints has been transferre...     NaN

 [429799 rows x 22 columns],
 'measurements_array':         run_id  experiment_id    measurement_time  measurement_id    unit  \
 0          355          11722 2019-04-09 18:32:12         1072518      °C
 1          355          11722 2019-04-09 18:32:21         1072521  Ln/min
 2          355          11722 2019-04-09 18:32:21         1072520  Ln/min
 3          355          11722 2019-04-09 18:32:21         1072519  Ln/min
 4          355          11722 2019-04-09 18:32:22         1072522      °C
 ...        ...            ...                 ...             ...     ...
 205987     484          16353 2021-07-28 22:33:28         1410622   U/min
 205988     484          16353 2021-07-28 22:33:42         1410625  Ln/min
 205989     484          16353 2021-07-28 22:33:42         1410624  Ln/min
 205990     484          16353 2021-07-28 22:33:42         1410626  Ln/min
 205991     484          16353 2021-07-28 22:33:43         1410627   U/min

         Flow_Air  Flow_Nitrogen  Flow_O2  StirringSpeed  Temperature
 0            NaN            NaN      NaN            NaN        36.99
 1            NaN            NaN      0.0            NaN          NaN
 2       4.997213            NaN      NaN            NaN          NaN
 3            NaN            0.0      NaN            NaN          NaN
 4            NaN            NaN      NaN            NaN        36.98
 ...          ...            ...      ...            ...          ...
 205987       NaN            NaN      NaN         2400.0          NaN
 205988  0.000000            NaN      NaN            NaN          NaN
 205989       NaN            0.0      NaN            NaN          NaN
 205990       NaN            NaN      0.0            NaN          NaN
 205991       NaN            NaN      NaN         2400.0          NaN

 [205992 rows x 10 columns],
 'measurements_aggregated':         run_id  experiment_id    measurement_time    unit  Flow_Air  \
 0          355          11722 2019-04-09 18:32:12      °C       NaN
 1          355          11722 2019-04-09 18:32:18       -       NaN
 2          355          11722 2019-04-09 18:32:19       -       NaN
 3          355          11722 2019-04-09 18:32:21  Ln/min       NaN
 4          355          11722 2019-04-09 18:32:21  Ln/min  4.997213
 ...        ...            ...                 ...     ...       ...
 635786     484          16353 2021-07-28 22:33:38       -       NaN
 635787     484          16353 2021-07-28 22:33:42  Ln/min  0.000000
 635788     484          16353 2021-07-28 22:33:42  Ln/min       NaN
 635789     484          16353 2021-07-28 22:33:42  Ln/min       NaN
 635790     484          16353 2021-07-28 22:33:43   U/min       NaN

         Flow_Nitrogen  Flow_O2  StirringSpeed  Temperature  Acetate  ...  \
 0                 NaN      NaN            NaN        36.99      NaN  ...
 1                 NaN      NaN            NaN          NaN      NaN  ...
 2                 NaN      NaN            NaN          NaN      NaN  ...
 3                 NaN      0.0            NaN          NaN      NaN  ...
 4                 NaN      NaN            NaN          NaN      NaN  ...
 ...               ...      ...            ...          ...      ...  ...
 635786            NaN      NaN            NaN          NaN      NaN  ...
 635787            NaN      NaN            NaN          NaN      NaN  ...
 635788            0.0      NaN            NaN          NaN      NaN  ...
 635789            NaN      0.0            NaN          NaN      NaN  ...
 635790            NaN      NaN         2400.0          NaN      NaN  ...

         Fluo_RFP  Fluo_YFP  Glucose  OD600  Probe_Volume    pH  Fluo_GFP  \
 0            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 1            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 2            NaN       NaN      NaN    NaN           NaN  6.86       NaN
 3            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 4            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 ...          ...       ...      ...    ...           ...   ...       ...
 635786       NaN       NaN      NaN    NaN           NaN  6.87       NaN
 635787       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635788       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635789       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635790       NaN       NaN      NaN    NaN           NaN   NaN       NaN

         InducerConcentration  remark  Volume
 0                        NaN     NaN     NaN
 1                        NaN     NaN     NaN
 2                        NaN     NaN     NaN
 3                        NaN     NaN     NaN
 4                        NaN     NaN     NaN
 ...                      ...     ...     ...
 635786                   NaN     NaN     NaN
 635787                   NaN     NaN     NaN
 635788                   NaN     NaN     NaN
 635789                   NaN     NaN     NaN
 635790                   NaN     NaN     NaN

 [635791 rows x 26 columns]}

# Preprocessing

In [5]:
np.number?

Init signature: np.number()
Docstring:      Abstract base class of all numeric scalar types.
File:           ~/miniconda3/envs/kiwi/lib/python3.9/site-packages/numpy/__init__.py
Type:           type
Subclasses:     integer, inexact

In [416]:
metadata["OD_Dilution"]

0      100
1      100
2      100
3      100
4      100
      ...
235     20
236     20
237     20
238     20
239     20
Name: OD_Dilution, Length: 240, dtype: object

In [420]:
BOOLS = [
    {"f": False, "t": True},
    {"false": False, "true": True},
    {"n": False, "y": True},
    {"no": False, "yes": True},
    {"-": False, "+": True},
    {0: False, 1: True},
    {-1: False, +1: True},
    {0.0: False, 1.0: True},
    {-1.0: False, +1.0: True},
]

[{'f': False, 't': True},
 {'false': False, 'true': True},
 {'n': False, 'y': True},
 {'no': False, 'yes': True},
 {'-': False, '+': True},
 {0: False, 1: True},
 {-1: False, 1: True},
 {0.0: False, 1.0: True},
 {-1.0: False, 1.0: True}]

In [435]:
x, y = np.random.randn(2, 1000)

In [436]:
x.dot(y)/(np.linalg.norm(x)*np.linalg.norm(y))

-0.01790395896226697

In [428]:
%%timeit

Series(np.random.rand(10**7))

56.8 ms ± 155 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [429]:
%%timeit

Series(np.random.rand(10**7)).unique()

1.38 s ± 3.36 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [425]:
Series([+1, -1, +1, -1]).astype("boolean")

TypeError: Need to pass bool-like values

In [422]:
any({0, 1} <= pair.keys() for pair in BOOLS)

True

In [417]:
pandas.api.types.is_string_dtype(metadata["OD_Dilution"])

True

In [410]:
Series([1, -1, 1]).astype("Int8").unique()

<IntegerArray>
[1, -1]
Length: 2, dtype: Int8

In [47]:
def contains_no_information(series) -> bool:
    return len(series.dropna().unique()) <= 1


def contains_nan_slice(series, slices, two_enough: bool = False) -> bool:
    num_missing = 0
    for idx in slices:
        if pd.isna(series[idx]).all():
            num_missing += 1

    if (num_missing > 0 and not two_enough) or (
        num_missing >= len(slices) - 1 and two_enough
    ):
        print(f"{series.name}: data missing in {num_missing}/{len(slices)} slices!")
        return True
    return False

def float_is_int(series) -> bool:
    mask = pd.notna(series)
    return series[mask].apply(float.is_integer).all()

def is_bool(vals) -> bool:
    if len(vals) > 2: 
        return False
    
    if np.issubdtype(vals.dtype, np.bool_):
        print(f"Boolean column                       : {col}")
        return True
    elif np.issubdtype(vals.dtype, np.integer):
        # print(vals==0 ^ vals==1)
        if ((vals==0) ^ (vals==1)).all() or ((vals==-1) ^ (vals==1)).all():
            print(f"Boolean column pretending to be integer: {col}")
            return Ture
    elif np.issubdtype(vals.dtype, np.floating):
        if ((vals==0) ^ (vals==1)).all() or ((vals==-1) ^ (vals==1)).all():
            print(f"Boolean column pretending to be float: {col}")
            return True
    elif np.issubdtype(vals.dtype, pandas.StringDtype):
        val1, val2 = set(vals)
        val1 = str(val1).lower()
        val2 = str(val2).lower()
        if {val1, val2} in ({"0", "1"}, {"-1", "+1"}, {"-1", "1"}, {"t", "f"}, {"true", "false"}, {"y", "n"}, {"yes", "no"}):
            print(f"Boolean column pretending to be string: {col}")
            return True
    return False

def get_true_column_dtypes(table) -> dict[str, str]:
    dtypes = {}
    for col in table:
        series = table[col]
        mask = pd.notna(series)
        vals = series[mask].unique()

def get_boolean_cols(df) -> set[str]:
    cols = set()
    for col in table:
        series = table[col]
        mask = pd.notna(series)
        vals = series[mask].unique()
        if is_bool(vals):
            cols.add(col)
    return cols
        
def get_integer_cols(df) -> set[str]:
    cols = set()
    for col in table:
        if np.issubdtype(table[col].dtype, np.integer):
            print(f"Integer column                       : {col}")
            cols.add(col)
        elif np.issubdtype(table[col].dtype, np.floating) and float_is_int(table[col]):
            print(f"Integer column pretending to be float: {col}")
            cols.add(col)
    return cols

def get_useless_cols(df, strict: bool=False) -> set[str]:
    useless_cols = set()
    for col in table:
        s = table[col]
        if col in ("run_id", "experiment_id"):
            continue
        if contains_no_information(s):
            print(f"No information in      {col}")
            useless_cols.add(col)
        elif contains_nan_slice(s, run_masks, two_enough=(not strict)):
            print(f"Missing for some run   {col}")
            useless_cols.add(col)
    return useless_cols

def get_μ_set(s: str):
    if pd.isna(s):
        return s
    s = s.strip().lstrip("µ_set: ").strip()
    percent, s = s.split(", ")
    value = s.strip().rstrip("mM IPTG").strip()
    return percent, value

In [148]:
np.datetime64

numpy.datetime64

In [157]:
pandas.Series([pandas.Interval(0, 1)]).dtype == pandas.IntervalDtype()

True

In [152]:
np.issubdtype( pandas.Series([pandas.Interval(0, 1)]).dtype, pandas.IntervalDtype)

TypeError: Cannot interpret 'interval[int64, right]' as a data type

In [189]:
pandas.api.types.is_datetime64_dtype(Series(["2021"]).dtype)

False

In [193]:
pandas.api.types.is_datetime64_dtype(Series([Timestamp("2021")]).unique())

True

In [202]:
pandas.api.types.is_unsigned_integer_dtype(pandas.Series([1,2,3,4,5]))

False

In [211]:
isinstance(Series([1,2,3]).astype("Int64").dtype, pandas.Int64Dtype)

True

In [212]:
PANDAS_DTYPES = {
    pandas.BooleanDtype: "boolean",
    pandas.CategoricalDtype: "category",
    pandas.DatetimeTZDtype: "datetime64",  # datetime64[ns, <tz>]
    pandas.Float32Dtype: "Float32",
    pandas.Float64Dtype: "Float64",
    pandas.Int16Dtype: "Int16",
    pandas.Int32Dtype: "Int32",
    pandas.Int64Dtype: "Int64",
    pandas.Int8Dtype: "Int8",
    pandas.IntervalDtype: "interval",  # e.g. to denote ranges of variables
    pandas.PeriodDtype: "period",  # period[<freq>]
    pandas.SparseDtype: "Sparse",
    pandas.StringDtype: "string",
    pandas.UInt16Dtype: "UInt16",
    pandas.UInt32Dtype: "UInt32",
    pandas.UInt64Dtype: "UInt64",
    pandas.UInt8Dtype: "UInt8",
}
r"""Dictionary of all :mod:`pandas` data types."""

'Dictionary of all :mod:`pandas` data types.'

In [218]:
Series([(1,2), (3,4)]).astype("interval")

TypeError: type <class 'tuple'> with value (1, 2) is not an interval

In [371]:
s = pandas.to_numeric(metadata["experiment_id"], downcast="unsigned")

0      11722
1      11723
2      11724
3      11725
4      11726
       ...
235    16349
236    16350
237    16351
238    16352
239    16353
Name: experiment_id, Length: 240, dtype: UInt16

In [376]:
pandas.to_numeric(s.append(Series([70000])), downcast="unsigned") - 70000

0      4294909018
1      4294909019
2      4294909020
3      4294909021
4      4294909022
          ...
236    4294913646
237    4294913647
238    4294913648
239    4294913649
0               0
Length: 241, dtype: UInt32

In [358]:
metadata["OD_Dilution"].unique()

array(['100', '50', '20'], dtype=object)

In [393]:
Series([True, False, pd.NA]).astype("boolean")

0     True
1    False
2     <NA>
dtype: boolean

In [346]:
s = pandas.Series([None, "2", "NaN"]).convert_dtypes()

0    <NA>
1       2
2     NaN
dtype: string

In [348]:
mask = pandas.isna(s)

0     True
1    False
2    False
dtype: bool

In [350]:
type(pd.NaT)

pandas._libs.tslibs.nattype.NaTType

In [327]:
metadata.convert_dtypes().dtypes

experiment_id                      Int64
bioreactor_id                      Int64
container_number                   Int64
profile_id                         Int64
starter_culture_id                object
inactivation_method_id             Int64
description_x                     string
color                             string
profile_name                      string
folder_id_x                        Int64
organism_id                        Int64
plasmid_id                         Int64
medium_id                          Int64
description_y                     object
run_id                             Int64
OD_Dilution                       string
Stir_Max_Restarts                 string
Stir_Min_pO2                      string
Stir_pO2_Threshold                string
ph_Base_conc                      string
ph_Ki                             string
ph_Kp                             string
ph_Max_ul                         string
ph_Min_ul                         string
ph_Timesetpoint                   string
ph_Tolerance                      string
run_name                          string
folder_id_y                        Int64
pms_id                             Int64
status_id                          Int64
start_time                datetime64[ns]
end_time                  datetime64[ns]
description                       string
conclusion                        object
container_label                   string
is_template                        Int64
Acetate_Dilution                  string
Feed_concentration_glc            string
InducerConcentration              string
pH_correction_factor              string
dtype: object

In [320]:
Series(["123", "456"]).astype("string").unique()

<StringArray>
['123', '456']
Length: 2, dtype: string

In [325]:
for col in metadata:
    pandas.to_numeric(metadata[col])

ValueError: Unable to parse string "µ_set: 25%, 0.05 mM IPTG" at position 24

In [ ]:
def infer_dtype(series: Series):
    """Tries to infer data type    """
    mask = pandas.notna(series)
    values = series[mask]
    uniques = values.unqiue()
    dtype = series.dtype
    dtype_type = type(dtype)
    if type(dtype) in PANDAS_DTYPES:
        return dtype
    if

In [308]:
from pandas.api.extensions import ExtensionDtype

In [258]:
pandas.api.types.is_

AttributeError: module 'pandas.api' has no attribute 'type'

In [259]:
pandas.api.type.issubdtype

AttributeError: module 'pandas.api' has no attribute 'type'

In [136]:
def infer_datatypes(table: DataFrame) -> dict(str, np.dtype):
    """This is a utility function that tries to infer the datatypes of the columns of a DataFrame.
    
    In particular, it tries to identify ill-specified columns:
    
    - columns that contains booleans  but are formatter as integers
    - columns that contains integers  but are formatted as floating
    - columns that contains floating  but are formatted as strings
    """
    
    dtypes = dict(table.dtypes)
    new_dtypes = dtypes.copy()
    
    
    for col, dtype in dtypes.items():
        series = table[col]
        # Leave pandas specific columns alone
        if type(dtype) in PANDAS_DTYPES:
            continue
        if pandas.api.types.is_datetime64_ns_dtype(dtype):
            continue
        if pandas.api.types.is_timedelta64_ns_dtype(dtype):
            continue

        if pandas.api.types.is_object_dtype(dtype):
            

            
        if dtype == np.datetime64
        if np.issubdtype(dtype, numpy.datetime64):
            continue
        
        
        if np.issubdtype(dtype, pandas.DatetimeTZDtype):
            continue
        if np.issubdtype(dtype, pandas.DatetimeTZDtype):
            continue

        if np.issubdtype(dtype, numpy.timedelta64):
            continue
        if np.issubdtype(dtype, numpy.timedelta64):
            continue

IndentationError: expected an indented block (671868391.py, line 22)

In [68]:
set("111,5156_44")

{',', '1', '4', '5', '6', '_'}

In [67]:
s = s.strip()  # remove leading and trailing whitespace

chars = set(s)

assert chars <= {".", ",", "_", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"}

if 

s.replace("_", "")

ValueError: could not convert string to float: '10,000.0'

### MetaData Preprocessing

In [54]:
np.array([1.0,2.0]) == {1,2}

array([False, False])

In [48]:
get_boolean_cols(table)

set()

In [62]:
pd.to_numeric("10_000", errors="coerce")

nan

In [76]:
s = table["ph_Timesetpoint"]

0      600
1      600
2      600
3      600
4      600
      ...
235    NaN
236    NaN
237    NaN
238    NaN
239    NaN
Name: ph_Timesetpoint, Length: 240, dtype: object

In [82]:
s.unique()

array(['600', nan], dtype=object)

In [84]:
mask = pd.notna(s)

0       True
1       True
2       True
3       True
4       True
       ...
235    False
236    False
237    False
238    False
239    False
Name: ph_Timesetpoint, Length: 240, dtype: bool

In [87]:
pandas.to_numeric(s, downcast=True)

ValueError: invalid downcasting method provided

In [85]:
pd.api.types.is_numeric_dtype(s[mask])

False

In [196]:
for col in metadata:
    series = metadata[col]
    mask = pandas.notna(series)
    values = series[mask]
    print(pandas.api.types.infer_dtype(values))

integer
integer
integer
floating
empty
floating
string
string
string
floating
floating
floating
floating
empty
floating
string
string
string
string
string
string
string
string
string
string
string
string
integer
integer
integer
datetime64
datetime64
string
empty
string
integer
string
string
string
string

In [195]:
metadata.dtypes

experiment_id                      Int64
bioreactor_id                      int64
container_number                   int64
profile_id                       float64
starter_culture_id                object
inactivation_method_id           float64
description_x                     object
color                             object
profile_name                      object
folder_id_x                      float64
organism_id                      float64
plasmid_id                       float64
medium_id                        float64
description_y                     object
run_id                           float64
OD_Dilution                       object
Stir_Max_Restarts                 object
Stir_Min_pO2                      object
Stir_pO2_Threshold                object
ph_Base_conc                      object
ph_Ki                             object
ph_Kp                             object
ph_Max_ul                         object
ph_Min_ul                         object
ph_Timesetpoint                   object
ph_Tolerance                      object
run_name                          object
folder_id_y                        int64
pms_id                             int64
status_id                          int64
start_time                datetime64[ns]
end_time                  datetime64[ns]
description                       object
conclusion                        object
container_label                   object
is_template                        int64
Acetate_Dilution                  object
Feed_concentration_glc            object
InducerConcentration              object
pH_correction_factor              object
dtype: object

In [71]:
metadata.dtypes

experiment_id                      int64
bioreactor_id                      int64
container_number                   int64
profile_id                       float64
starter_culture_id                object
inactivation_method_id           float64
description_x                     object
color                             object
profile_name                      object
folder_id_x                      float64
organism_id                      float64
plasmid_id                       float64
medium_id                        float64
description_y                     object
run_id                           float64
OD_Dilution                       object
Stir_Max_Restarts                 object
Stir_Min_pO2                      object
Stir_pO2_Threshold                object
ph_Base_conc                      object
ph_Ki                             object
ph_Kp                             object
ph_Max_ul                         object
ph_Min_ul                         object
ph_Timesetpoint                   object
ph_Tolerance                      object
run_name                          object
folder_id_y                        int64
pms_id                             int64
status_id                          int64
start_time                datetime64[ns]
end_time                  datetime64[ns]
description                       object
conclusion                        object
container_label                   object
is_template                        int64
Acetate_Dilution                  object
Feed_concentration_glc            object
InducerConcentration              object
pH_correction_factor              object
dtype: object

In [65]:
float("10.000")

10.0

In [59]:
for x in table["ph_Ki"]:
    pd.to_numeric(x)

ValueError: Unable to parse string "0,769" at position 0

In [103]:
def is_numeric(series):
    mask = pd.notna(series)

    try:
        pd.to_numeric(series)
    except:
        return False
    else:
        return True

In [ ]:
def get_unqiues(series, uniques = None, mask = None):

In [ ]:
def is_categorical(series, ratio=0.01, uniques= None, mask=None):
    """Test whether a column could be categorical
    Test 1: if number of unique values < ratio*number of recorded values
    Test 2: if integer and unique values = range()
    """

In [126]:
table["OD_Dilution"].astype(pd.Int64Dtype())

TypeError: object cannot be converted to an IntegerDtype

In [ ]:
def is_empty(series):
    return pd.isna(series).all()

In [118]:
for col in table:
    series = table[col]
    dtype = series.dtype
    if np.issubdtype(dtype, pandas.StringDtype):
        if is_numeric(series):
            print(f"Numerical column pretending to be string: {col=}")

Numerical column pretending to be string: col='starter_culture_id'
Numerical column pretending to be string: col='description_y'
Numerical column pretending to be string: col='OD_Dilution'
Numerical column pretending to be string: col='Stir_Max_Restarts'
Numerical column pretending to be string: col='Stir_Min_pO2'
Numerical column pretending to be string: col='Stir_pO2_Threshold'
Numerical column pretending to be string: col='ph_Max_ul'
Numerical column pretending to be string: col='ph_Min_ul'
Numerical column pretending to be string: col='ph_Timesetpoint'
Numerical column pretending to be string: col='conclusion'
Numerical column pretending to be string: col='Acetate_Dilution'
Numerical column pretending to be string: col='Feed_concentration_glc'
Numerical column pretending to be string: col='InducerConcentration'
Numerical column pretending to be string: col='pH_correction_factor'

dtype('O')

In [88]:
table = metadata = tables["metadata"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

useless_cols = set()

for col in table:
    s = table[col]
    if col in ("run_id", "experiment_id"):
        continue
    if contains_no_information(s):
        print(f"No information in      {col}")
        useless_cols.add(col)
    elif contains_nan_slice(s, run_masks):
        print(f"Missing for some run   {col}")
        useless_cols.add(col)

# drop the following specific columns
useless_cols |= {
    "folder_id_y",
    "ph_Base_conc",
    "ph_Ki",
    "ph_Kp",
    "ph_Tolerance",
    "pms_id",
}

No information in      starter_culture_id
No information in      inactivation_method_id
description_x: data missing in 8/9 slices!
Missing for some run   description_x
No information in      folder_id_x
No information in      plasmid_id
No information in      medium_id
No information in      description_y
No information in      Stir_Max_Restarts
No information in      Stir_Min_pO2
No information in      Stir_pO2_Threshold
No information in      ph_Max_ul
No information in      ph_Min_ul
No information in      ph_Timesetpoint
No information in      status_id
No information in      description
No information in      conclusion
No information in      container_label
No information in      is_template
No information in      Acetate_Dilution
Feed_concentration_glc: data missing in 1/9 slices!
Missing for some run   Feed_concentration_glc
No information in      InducerConcentration
pH_correction_factor: data missing in 1/9 slices!
Missing for some run   pH_correction_factor

{'Acetate_Dilution',
 'Feed_concentration_glc',
 'InducerConcentration',
 'Stir_Max_Restarts',
 'Stir_Min_pO2',
 'Stir_pO2_Threshold',
 'conclusion',
 'container_label',
 'description',
 'description_x',
 'description_y',
 'folder_id_x',
 'folder_id_y',
 'inactivation_method_id',
 'is_template',
 'medium_id',
 'pH_correction_factor',
 'ph_Base_conc',
 'ph_Ki',
 'ph_Kp',
 'ph_Max_ul',
 'ph_Min_ul',
 'ph_Timesetpoint',
 'ph_Tolerance',
 'plasmid_id',
 'pms_id',
 'starter_culture_id',
 'status_id'}

In [95]:
table["OD_Dilution"].unique()

array(['100', '50', '20'], dtype=object)

In [101]:
float("100.0")

100.0

In [98]:
pd.isna(table["OD_Dilution"])

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Name: OD_Dilution, Length: 240, dtype: bool

In [93]:
table["OD_Dilution"].astype("int32")

0      100
1      100
2      100
3      100
4      100
      ...
235     20
236     20
237     20
238     20
239     20
Name: OD_Dilution, Length: 240, dtype: int32

In [11]:
metadata_columns = {
    "bioreactor_id",
    "container_number",
    "experiment_id",
    "run_id",
    "profile_id",
    "color",
    "profile_name",
    "organism_id",
    "OD_Dilution",
    "run_name",
    "start_time",
    "end_time",
}

remaining_cols = set(metadata.columns) - useless_cols
assert (
    metadata_columns >= set(metadata.columns) - useless_cols
), f"Superfluous {metadata_columns - remaining_cols}"
assert (
    metadata_columns <= set(metadata.columns) - useless_cols
), f"You forgot to check {metadata_columns - remaining_cols}"


metadata_dtypes = {
    "experiment_id": "UInt32",
    "bioreactor_id": "UInt32",
    "container_number": "UInt32",
    "profile_id": "UInt32",
    "color": "string",
    "profile_name": "string",
    "organism_id": "UInt32",
    "run_id": "UInt32",
    "OD_Dilution": "float32",
    "run_name": "string",
    "start_time": "datetime64[ns]",
    "end_time": "datetime64[ns]",
}

assert metadata_columns >= set(
    metadata_dtypes
), f"Superfluous encoing  {set(metadata_dtypes) - metadata_columns}"
assert metadata_columns <= set(
    metadata_dtypes
), f"You forgot to encode {metadata_columns - set(metadata_dtypes)}"

metadata_categoricals = {
    "profile_name": "category",
    "run_name": "category",
    "color": "category",
    "OD_Dilution": "Float32",
}

assert metadata_columns >= set(
    metadata_categoricals
), f"Superfluous encoing {set(metadata_categoricals) - metadata_columns}"

In [12]:
metadata = metadata.astype(metadata_dtypes)
metadata = metadata.astype(metadata_categoricals)
metadata = metadata[metadata_columns]
metadata = metadata.set_index(["run_id", "experiment_id"])

                      container_number            run_name  organism_id  \
run_id experiment_id
355    11722                         9   20190409_SWORD_II            3
       11723                        10   20190409_SWORD_II            8
       11724                        11   20190409_SWORD_II           21
       11725                        12   20190409_SWORD_II           32
       11726                        13   20190409_SWORD_II           14
...                                ...                 ...          ...
484    16349                        28  20210707_MHE_MPC_6           41
       16350                        29  20210707_MHE_MPC_6           41
       16351                        30  20210707_MHE_MPC_6           41
       16352                        31  20210707_MHE_MPC_6           41
       16353                        32  20210707_MHE_MPC_6           41

                                end_time          start_time profile_name  \
run_id experiment_id
355    11722         2019-04-10 07:43:33 2019-04-09 18:31:53           A2
       11723         2019-04-10 07:43:33 2019-04-09 18:31:53           B2
       11724         2019-04-10 07:43:33 2019-04-09 18:31:53           C2
       11725         2019-04-10 07:43:33 2019-04-09 18:31:53           D2
       11726         2019-04-10 07:43:33 2019-04-09 18:31:53           E2
...                                  ...                 ...          ...
484    16349         2021-07-28 22:37:27 2021-07-28 08:56:22           D4
       16350         2021-07-28 22:37:27 2021-07-28 08:56:22           E4
       16351         2021-07-28 22:37:27 2021-07-28 08:56:22           F4
       16352         2021-07-28 22:37:27 2021-07-28 08:56:22           G4
       16353         2021-07-28 22:37:27 2021-07-28 08:56:22           H4

                      profile_id  OD_Dilution      color  bioreactor_id
run_id experiment_id
355    11722                6449        100.0  #FFFF6404            397
       11723                6450        100.0  #FFFFF400            397
       11724                6451        100.0  #FFAFFF00            397
       11725                6452        100.0  #FF00FFAB            397
       11726                6453        100.0  #FF00ABFF            397
...                          ...          ...        ...            ...
484    16349               11028         20.0  #FFE7298A            588
       16350               11029         20.0  #FF66A61E            588
       16351               11030         20.0  #FFE6AB02            588
       16352               11031         20.0  #FFA6761D            588
       16353               11032         20.0  #FF666666            588

[240 rows x 10 columns]

## Setpoint Preprocessing

In [13]:
table = setpoints = tables["setpoints"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

useless_cols = set()

for col in table:
    s = table[col]
    if col in ("run_id", "experiment_id"):
        continue
    if contains_no_information(s):
        print(f"No information in      {col}")
        useless_cols.add(col)
    elif contains_nan_slice(s, run_masks, two_enough=True):
        print(f"Missing for some run   {col}")
        useless_cols.add(col)

# drop the following specific columns
useless_cols

No information in      Puls_AceticAcid
No information in      Puls_Medium
No information in      pH
No information in      Flow_Nitrogen
No information in      Flow_O2
No information in      Feed_dextrine_cum_setpoints

{'Feed_dextrine_cum_setpoints',
 'Flow_Nitrogen',
 'Flow_O2',
 'Puls_AceticAcid',
 'Puls_Medium',
 'pH'}

In [14]:
setpoint_columns = set(setpoints.columns)
remaining_cols = setpoint_columns - useless_cols

selected_columns = {
    "experiment_id",
    "run_id",
    "cultivation_age",
    "setpoint_id",
    "unit",
    "Puls_Glucose",
    "StirringSpeed",
    "Feed_glc_cum_setpoints",
    "Flow_Air",
    "InducerConcentration",
}

assert (
    selected_columns >= setpoint_columns - useless_cols
), f"You forgot to check {remaining_cols - selected_columns}"
assert (
    selected_columns <= setpoint_columns - useless_cols
), f"Superfluous {selected_columns - remaining_cols}"

setpoints_dtypes = {
    "experiment_id": "UInt32",
    "run_id": "UInt32",
    "cultivation_age": "UInt32",
    "setpoint_id": "UInt32",
    "unit": "string",
    "Puls_AceticAcid": "Float32",
    "Puls_Glucose": "Float32",
    "Puls_Medium": "Float32",
    "StirringSpeed": "UInt16",
    "pH": "Float32",
    "Feed_glc_cum_setpoints": "UInt16",
    "Flow_Air": "UInt8",
    "InducerConcentration": "Float32",
    "Flow_Nitrogen": "Float32",
    "Flow_O2": "Float32",
    "Feed_dextrine_cum_setpoints": "Float32",
}

assert (
    set(setpoints_dtypes) <= setpoint_columns
), f"Superfluous encoing  {set(setpoints_dtypes) - setpoint_columns}"
assert (
    set(setpoints_dtypes) >= selected_columns
), f"You forgot to encode {selected_columns - set(setpoints_dtypes)}"

setpoints_categoricals = {
    "unit": "category",
}

assert set(setpoints_categoricals) <= set(
    setpoints_dtypes
), f"Superfluous encoing {set(setpoints_categoricals) - set(setpoints_dtypes)}"

In [15]:
setpoints["unit"] = setpoints["unit"].replace(to_replace="-", value=pd.NA)
setpoints = setpoints.astype(setpoints_dtypes)
setpoints = setpoints.astype(setpoints_categoricals)
setpoints = setpoints[selected_columns]
setpoints = setpoints.set_index(["run_id", "experiment_id"])

                      setpoint_id   unit  cultivation_age  Puls_Glucose  \
run_id experiment_id
355    11722               470579    NaN                0          <NA>
       11722               470581     µL                0          <NA>
       11722               470582     µL                0          <NA>
       11722               470675  U/min                0          <NA>
       11722               470580     µL                0           0.0
...                           ...    ...              ...           ...
484    16353               742149     µL            46583          <NA>
       16353               742150     µL            47183          <NA>
       16353               742151     µL            47783          <NA>
       16353               742152     µL            48383          <NA>
       16353               742153     µL            48983          <NA>

                      Flow_Air  StirringSpeed  InducerConcentration  \
run_id experiment_id
355    11722              <NA>           <NA>                  <NA>
       11722              <NA>           <NA>                  <NA>
       11722              <NA>           <NA>                  <NA>
       11722              <NA>           3000                  <NA>
       11722              <NA>           <NA>                  <NA>
...                        ...            ...                   ...
484    16353              <NA>           <NA>                  <NA>
       16353              <NA>           <NA>                  <NA>
       16353              <NA>           <NA>                  <NA>
       16353              <NA>           <NA>                  <NA>
       16353              <NA>           <NA>                  <NA>

                      Feed_glc_cum_setpoints
run_id experiment_id
355    11722                            <NA>
       11722                            <NA>
       11722                            <NA>
       11722                            <NA>
       11722                            <NA>
...                                      ...
484    16353                             906
       16353                             926
       16353                             946
       16353                             966
       16353                             986

[23126 rows x 8 columns]

##  Measurements Reactor

In [ ]:
table = measurements_reactor = tables["measurements_reactor"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

useless_cols = get_useless_cols(table)
integer_cols = get_integer_cols(table)

In [ ]:
table_columns = set(table.columns)
remaining_cols = table_columns - useless_cols

In [ ]:
selected_columns = {
    "Acetate",
    "Base",
    "Cumulated_feed_volume_glucose",
    "Cumulated_feed_volume_medium",
    "DOT",
    "Fluo_GFP",
    "Glucose",
    "InducerConcentration",
    "OD600",
    "Probe_Volume",
    "Volume",
    "experiment_id",
    "measurement_id",
    "measurement_time",
    "pH",
    "run_id",
    "unit",
}

assert (
    selected_columns >= table_columns - useless_cols
), f"You forgot to check {remaining_cols - selected_columns}"
assert (
    selected_columns <= table_columns - useless_cols
), f"Superfluous {selected_columns - remaining_cols}"

In [ ]:
table[selected_columns].dtypes.sort_index()

In [ ]:
table["Base"].unique()

In [ ]:
table.dtyp

In [ ]:
reactor_dtypes = {
    "Acetate"                       : "Float32",
    "Base"                          : "Int32",
    "Cumulated_feed_volume_glucose" : "",
    "Cumulated_feed_volume_medium"  : "",
    "DOT"                           : "",
    "Fluo_GFP"                      : "",
    "Glucose"                       : "",
    "InducerConcentration"          : "",
    "OD600"                         : "",
    "Probe_Volume"                  : "",
    "Volume"                        : "",
    "experiment_id"                 : "",
    "measurement_id"                : "",
    "measurement_time"              : "",
    "pH"                            : "",
    "run_id"                        : "",
    "unit"                          : "",
}

assert (
    set(setpoints_dtypes) <= setpoint_columns
), f"Superfluous encoing  {set(setpoints_dtypes) - setpoint_columns}"
assert (
    set(setpoints_dtypes) >= selected_columns
), f"You forgot to encode {selected_columns - set(setpoints_dtypes)}"

setpoints_categoricals = {
    "unit": "category",
}

assert set(setpoints_categoricals) <= set(
    setpoints_dtypes
), f"Superfluous encoing {set(setpoints_categoricals) - set(setpoints_dtypes)}"

In [ ]:
metadata = metadata.astype(metadata_dtypes)
metadata = metadata.astype(metadata_categoricals)
metadata = metadata[metadata_columns]
metadata = metadata.set_index(["run_id", "experiment_id"])

## Measurements_Array

## Measurements Aggregated