# Importing KIWI dataset

### Data Validation

Format

```python
data: tuple[
    dict[
        'description': set[str],
        'variables': list[dict[str, str]],
        'time_format': str,
        'series': dict[int, 
            dict['generating_parameters': 
                 dict[
                     'qsmax': float,
                     'qm': float,
                     'qamax': float,
                     'Yem': float,
                     'Yxsof': float,
                     'Yxa': float,
                     'Yos': float,
                     'Yoa': float,
                     'Yas': float,
                     'Kia': float,
                     'Ks': float,
                     'Ko': float,
                     'Kap': float,
                     'Kis': float,
                     'Ksa': float,
                     'Pamax': float,
                     'F0': float,
                     'mu_set': float,
                     'C_feed': float,
                     'Kp': float,
                ]
            ],
        ],
    ], 
    dict[int, DataFrame[columns=['X', 'S', 'A', 'DOTm', 'V', 'pulse', 'kLa']]]
]
```

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import pickle

import numpy as np
import pandas
import pandas as pd
from pandas import DataFrame, Series, Interval, Period, Timestamp, Timedelta

## Data Encoding

Problem: Columns are encoded in wrong data-types (e.g. categoricals as int or string, floats as string, ints as floats etc.)

Solution: Sequentially figure out data types

Data Type Hirarchy:
1. String-Like (`np.flexible`)
    - strings
    - bytes
2. TimeLike types
    - Timestamp (np.datetime64)
    - Timedelta (np.timedelta64)
3. Numerical (`np.number`)
   - floating (`np.floating`)
       - float
       - complex
   - integer (`np.integer`)
       - signed
       - unsigned
4. Boolean (np.bool_)
5. Pandas special types
    - CategoricalDtype
    - DatetimeTZDtype
    - PeriodDtype
    - IntervalDtype

End goal: whenever it is appropriate to do so, perform the following conversions:

1. Get appropriate Nullable Pandas type
2. Downcast int → uint
3. Downcast int64 → int32 → int16 → int8
3. Downcast float64 → float32
4. Downcast complex128 → complex64
5. Convert to categorical datatype

In [3]:
def subdtypes(dtype):
    subs = dtype.__subclasses__()
    if not subs:
        return dtype
    return [dtype, [subdtypes(dt) for dt in subs]]

subdtypes(np.generic)

[numpy.generic,
 [[numpy.number,
   [[numpy.integer,
     [[numpy.signedinteger,
       [numpy.int8,
        numpy.int16,
        numpy.int32,
        numpy.int64,
        numpy.longlong,
        numpy.timedelta64]],
      [numpy.unsignedinteger,
       [numpy.uint8,
        numpy.uint16,
        numpy.uint32,
        numpy.uint64,
        numpy.ulonglong]]]],
    [numpy.inexact,
     [[numpy.floating,
       [numpy.float16, numpy.float32, numpy.float64, numpy.float128]],
      [numpy.complexfloating,
       [numpy.complex64, numpy.complex128, numpy.complex256]]]]]],
  [numpy.flexible,
   [[numpy.character, [numpy.bytes_, numpy.str_]],
    [numpy.void, [numpy.record]]]],
  numpy.bool_,
  numpy.datetime64,
  numpy.object_]]

In [4]:
type(pandas.Series([1.3]).dtype)

numpy.dtype[float64]

### Format


```python
dict[int, # run_id
    dict[int, # experiment_id
         dict[
             'metadata',: DataFrame,                # static
             'setpoints': DataFrame,                # static
             'measurements_reactor',: DataFrame,    # TimeTensor
             'measurements_array',: DataFrame,      # TimeTensor
             'measurements_aggregated': DataFrame,  # TimeTensor
         ]
    ]
]

```

## Raw-Data

### Stefans key selection

In [5]:
from cross_validate_kiwi_runs import ReplicateBasedSplitter, create_replicate_dict

with open("kiwi_experiments_and_run_355.pk", "rb") as f:
    experiments_per_run = pickle.load(f)

col_run_to_exp = create_replicate_dict(experiments_per_run)

splitter = ReplicateBasedSplitter()

for train_keys, test_keys in splitter.split(col_run_to_exp):
    data_train = [experiments_per_run[k[0]][k[1]] for k in train_keys]
    data_test = [experiments_per_run[k[0]][k[1]] for k in test_keys]

### Randolf's data preprocessing

In [6]:
with open("kiwi_experiments_and_run_355.pk", "rb") as file:
    data = pickle.load(file)

col_run_to_exp = create_replicate_dict(data)
splitter = ReplicateBasedSplitter()

DATA = [
    (data[run][exp] | {"run_id": run, "experiment_id": exp})
    for run in data
    for exp in data[run]
]
DF = DataFrame(DATA).set_index(["run_id", "experiment_id"])

                                                               metadata  \
run_id experiment_id
355    11722             experiment_id  bioreactor_id  container_num...
       11723             experiment_id  bioreactor_id  container_num...
       11724             experiment_id  bioreactor_id  container_num...
       11725             experiment_id  bioreactor_id  container_num...
       11726             experiment_id  bioreactor_id  container_num...
...                                                                 ...
484    16349             experiment_id  bioreactor_id  container_num...
       16350             experiment_id  bioreactor_id  container_num...
       16351             experiment_id  bioreactor_id  container_num...
       16352             experiment_id  bioreactor_id  container_num...
       16353             experiment_id  bioreactor_id  container_num...

                                                              setpoints  \
run_id experiment_id
355    11722               cultivation_age  setpoint_id   unit  Puls...
       11723               cultivation_age  setpoint_id   unit  Puls...
       11724               cultivation_age  setpoint_id   unit  Puls...
       11725               cultivation_age  setpoint_id   unit  Puls...
       11726              cultivation_age  setpoint_id   unit  Puls_...
...                                                                 ...
484    16349              cultivation_age  setpoint_id    unit  Feed...
       16350              cultivation_age  setpoint_id    unit  Feed...
       16351              cultivation_age  setpoint_id    unit  Feed...
       16352              cultivation_age  setpoint_id    unit  Feed...
       16353              cultivation_age  setpoint_id    unit  Feed...

                                                   measurements_reactor  \
run_id experiment_id
355    11722                  measurement_time  measurement_id unit ...
       11723                  measurement_time  measurement_id unit ...
       11724                  measurement_time  measurement_id unit ...
       11725                  measurement_time  measurement_id unit ...
       11726                  measurement_time  measurement_id unit ...
...                                                                 ...
484    16349                  measurement_time  measurement_id unit ...
       16350                  measurement_time  measurement_id unit ...
       16351                  measurement_time  measurement_id unit ...
       16352                  measurement_time  measurement_id unit ...
       16353                  measurement_time  measurement_id unit ...

                                                     measurements_array  \
run_id experiment_id
355    11722                  measurement_time  measurement_id    un...
       11723                  measurement_time  measurement_id    un...
       11724                  measurement_time  measurement_id    un...
       11725                  measurement_time  measurement_id    un...
       11726                  measurement_time  measurement_id    un...
...                                                                 ...
484    16349                  measurement_time  measurement_id    un...
       16350                  measurement_time  measurement_id    un...
       16351                  measurement_time  measurement_id    un...
       16352                  measurement_time  measurement_id    un...
       16353                  measurement_time  measurement_id    un...

                                                measurements_aggregated
run_id experiment_id
355    11722                  measurement_time    unit  Flow_Air  Fl...
       11723                  measurement_time    unit  Flow_Air  Fl...
       11724                  measurement_time    unit  Flow_Air  Fl...
       11725                  measurement_time    unit  Flow_Air  Fl...
       11726                  measurement_time    unit  Flow_Air  Fl...
...                                                                 ...
484    16349                  measurement_time    unit  Flow_Air  Fl...
       16350                  measurement_time    unit  Flow_Air  Fl...
       16351                  measurement_time    unit  Flow_Air  Fl...
       16352                  measurement_time    unit  Flow_Air  Fl...
       16353                  measurement_time    unit  Flow_Air  Fl...

[240 rows x 5 columns]

In [7]:
tables = {}

for key in (
    "metadata",
    "setpoints",
    "measurements_reactor",
    "measurements_array",
    "measurements_aggregated",
):
    if key == "metadata":
        tables[key] = pd.concat(iter(DF[key])).reset_index(drop=True)
    else:
        tables[key] = (
            pd.concat(iter(DF[key]), keys=DF[key].index)
            .reset_index(level=2, drop=True)
            .reset_index()
        )

tables

{'metadata':      experiment_id  bioreactor_id  container_number  profile_id  \
 0            11722            397                 9      6449.0
 1            11723            397                10      6450.0
 2            11724            397                11      6451.0
 3            11725            397                12      6452.0
 4            11726            397                13      6453.0
 ..             ...            ...               ...         ...
 235          16349            588                28     11028.0
 236          16350            588                29     11029.0
 237          16351            588                30     11030.0
 238          16352            588                31     11031.0
 239          16353            588                32     11032.0

     starter_culture_id  inactivation_method_id description_x      color  \
 0                 None                     1.0          None  #FFFF6404
 1                 None                     1.0          None  #FFFFF400
 2                 None                     1.0          None  #FFAFFF00
 3                 None                     1.0          None  #FF00FFAB
 4                 None                     1.0          None  #FF00ABFF
 ..                 ...                     ...           ...        ...
 235               None                     1.0          None  #FFE7298A
 236               None                     1.0          None  #FF66A61E
 237               None                     1.0          None  #FFE6AB02
 238               None                     1.0          None  #FFA6761D
 239               None                     1.0          None  #FF666666

     profile_name  folder_id_x  ...          start_time            end_time  \
 0             A2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 1             B2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 2             C2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 3             D2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 4             E2          NaN  ... 2019-04-09 18:31:53 2019-04-10 07:43:33
 ..           ...          ...  ...                 ...                 ...
 235           D4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 236           E4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 237           F4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 238           G4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27
 239           H4          NaN  ... 2021-07-28 08:56:22 2021-07-28 22:37:27

      description conclusion    container_label is_template Acetate_Dilution  \
 0           None       None  Position,Organism           0              NaN
 1           None       None  Position,Organism           0              NaN
 2           None       None  Position,Organism           0              NaN
 3           None       None  Position,Organism           0              NaN
 4           None       None  Position,Organism           0              NaN
 ..           ...        ...                ...         ...              ...
 235         None       None               None           0                1
 236         None       None               None           0                1
 237         None       None               None           0                1
 238         None       None               None           0                1
 239         None       None               None           0                1

     Feed_concentration_glc InducerConcentration pH_correction_factor
 0                      NaN                  NaN                  NaN
 1                      NaN                  NaN                  NaN
 2                      NaN                  NaN                  NaN
 3                      NaN                  NaN                  NaN
 4                      NaN                  NaN                  NaN
 ..                     ...                  ...                  ...
 235                    200                  NaN                  0.2
 236                    200                  NaN                  0.2
 237                    200                  NaN                  0.2
 238                    200                  NaN                  0.2
 239                    200                  NaN                  0.2

 [240 rows x 40 columns],
 'setpoints':        run_id  experiment_id  cultivation_age  setpoint_id   unit  \
 0         355          11722                0       470579      -
 1         355          11722                0       470581     µL
 2         355          11722                0       470582     µL
 3         355          11722                0       470675  U/min
 4         355          11722                0       470580     µL
 ...       ...            ...              ...          ...    ...
 23121     484          16353            46583       742149     µL
 23122     484          16353            47183       742150     µL
 23123     484          16353            47783       742151     µL
 23124     484          16353            48383       742152     µL
 23125     484          16353            48983       742153     µL

        Puls_AceticAcid  Puls_Glucose  Puls_Medium  StirringSpeed   pH  \
 0                  NaN           NaN          NaN            NaN  7.0
 1                  0.0           NaN          NaN            NaN  NaN
 2                  NaN           NaN          0.0            NaN  NaN
 3                  NaN           NaN          NaN         3000.0  NaN
 4                  NaN           0.0          NaN            NaN  NaN
 ...                ...           ...          ...            ...  ...
 23121              NaN           NaN          NaN            NaN  NaN
 23122              NaN           NaN          NaN            NaN  NaN
 23123              NaN           NaN          NaN            NaN  NaN
 23124              NaN           NaN          NaN            NaN  NaN
 23125              NaN           NaN          NaN            NaN  NaN

        Feed_glc_cum_setpoints  Flow_Air  InducerConcentration  Flow_Nitrogen  \
 0                         NaN       NaN                   NaN            NaN
 1                         NaN       NaN                   NaN            NaN
 2                         NaN       NaN                   NaN            NaN
 3                         NaN       NaN                   NaN            NaN
 4                         NaN       NaN                   NaN            NaN
 ...                       ...       ...                   ...            ...
 23121                   906.0       NaN                   NaN            NaN
 23122                   926.0       NaN                   NaN            NaN
 23123                   946.0       NaN                   NaN            NaN
 23124                   966.0       NaN                   NaN            NaN
 23125                   986.0       NaN                   NaN            NaN

        Flow_O2  Feed_dextrine_cum_setpoints
 0          NaN                          NaN
 1          NaN                          NaN
 2          NaN                          NaN
 3          NaN                          NaN
 4          NaN                          NaN
 ...        ...                          ...
 23121      NaN                          NaN
 23122      NaN                          NaN
 23123      NaN                          NaN
 23124      NaN                          NaN
 23125      NaN                          NaN

 [23126 rows x 16 columns],
 'measurements_reactor':         run_id  experiment_id    measurement_time  measurement_id unit  \
 0          355          11722 2019-04-09 18:32:18      18358520.0    -
 1          355          11722 2019-04-09 18:32:19      18358544.0    -
 2          355          11722 2019-04-09 18:32:28      18358568.0    -
 3          355          11722 2019-04-09 18:32:29      18358592.0    -
 4          355          11722 2019-04-09 18:32:38      18358616.0    -
 ...        ...            ...                 ...             ...  ...
 429794     484          16353 2021-07-28 22:33:26      23138083.0    -
 429795     484          16353 2021-07-28 22:33:26      23138082.0    -
 429796     484          16353 2021-07-28 22:33:38      23138131.0    -
 429797     484          16353 2021-07-28 22:33:38      23138130.0    -
 429798     484          16353 2021-07-28 17:26:22             NaN   mM

         Acetate  Acid  Base  Cumulated_feed_volume_glucose  \
 0           NaN   NaN   NaN                            NaN
 1           NaN   NaN   NaN                            NaN
 2           NaN   NaN   NaN                            NaN
 3           NaN   NaN   NaN                            NaN
 4           NaN   NaN   NaN                            NaN
 ...         ...   ...   ...                            ...
 429794      NaN   NaN   NaN                            NaN
 429795      NaN   NaN   NaN                            NaN
 429796      NaN   NaN   NaN                            NaN
 429797      NaN   NaN   NaN                            NaN
 429798      NaN   NaN   NaN                            NaN

         Cumulated_feed_volume_medium  ...  Fluo_RFP  Fluo_YFP  Glucose  OD600  \
 0                                NaN  ...       NaN       NaN      NaN    NaN
 1                                NaN  ...       NaN       NaN      NaN    NaN
 2                                NaN  ...       NaN       NaN      NaN    NaN
 3                                NaN  ...       NaN       NaN      NaN    NaN
 4                                NaN  ...       NaN       NaN      NaN    NaN
 ...                              ...  ...       ...       ...      ...    ...
 429794                           NaN  ...       NaN       NaN      NaN    NaN
 429795                           NaN  ...       NaN       NaN      NaN    NaN
 429796                           NaN  ...       NaN       NaN      NaN    NaN
 429797                           NaN  ...       NaN       NaN      NaN    NaN
 429798                           NaN  ...       NaN       NaN      NaN    NaN

         Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
 0                NaN   NaN       NaN                   NaN
 1                NaN  6.86       NaN                   NaN
 2                NaN   NaN       NaN                   NaN
 3                NaN  6.86       NaN                   NaN
 4                NaN   NaN       NaN                   NaN
 ...              ...   ...       ...                   ...
 429794           NaN  6.88       NaN                   NaN
 429795           NaN   NaN       NaN                   NaN
 429796           NaN  6.87       NaN                   NaN
 429797           NaN   NaN       NaN                   NaN
 429798           NaN   NaN       NaN                   2.0

                                                    remark  Volume
 0                                                     NaN     NaN
 1                                                     NaN     NaN
 2                                                     NaN     NaN
 3                                                     NaN     NaN
 4                                                     NaN     NaN
 ...                                                   ...     ...
 429794                                                NaN     NaN
 429795                                                NaN     NaN
 429796                                                NaN     NaN
 429797                                                NaN     NaN
 429798  value written to setpoints has been transferre...     NaN

 [429799 rows x 22 columns],
 'measurements_array':         run_id  experiment_id    measurement_time  measurement_id    unit  \
 0          355          11722 2019-04-09 18:32:12         1072518      °C
 1          355          11722 2019-04-09 18:32:21         1072521  Ln/min
 2          355          11722 2019-04-09 18:32:21         1072520  Ln/min
 3          355          11722 2019-04-09 18:32:21         1072519  Ln/min
 4          355          11722 2019-04-09 18:32:22         1072522      °C
 ...        ...            ...                 ...             ...     ...
 205987     484          16353 2021-07-28 22:33:28         1410622   U/min
 205988     484          16353 2021-07-28 22:33:42         1410625  Ln/min
 205989     484          16353 2021-07-28 22:33:42         1410624  Ln/min
 205990     484          16353 2021-07-28 22:33:42         1410626  Ln/min
 205991     484          16353 2021-07-28 22:33:43         1410627   U/min

         Flow_Air  Flow_Nitrogen  Flow_O2  StirringSpeed  Temperature
 0            NaN            NaN      NaN            NaN        36.99
 1            NaN            NaN      0.0            NaN          NaN
 2       4.997213            NaN      NaN            NaN          NaN
 3            NaN            0.0      NaN            NaN          NaN
 4            NaN            NaN      NaN            NaN        36.98
 ...          ...            ...      ...            ...          ...
 205987       NaN            NaN      NaN         2400.0          NaN
 205988  0.000000            NaN      NaN            NaN          NaN
 205989       NaN            0.0      NaN            NaN          NaN
 205990       NaN            NaN      0.0            NaN          NaN
 205991       NaN            NaN      NaN         2400.0          NaN

 [205992 rows x 10 columns],
 'measurements_aggregated':         run_id  experiment_id    measurement_time    unit  Flow_Air  \
 0          355          11722 2019-04-09 18:32:12      °C       NaN
 1          355          11722 2019-04-09 18:32:18       -       NaN
 2          355          11722 2019-04-09 18:32:19       -       NaN
 3          355          11722 2019-04-09 18:32:21  Ln/min       NaN
 4          355          11722 2019-04-09 18:32:21  Ln/min  4.997213
 ...        ...            ...                 ...     ...       ...
 635786     484          16353 2021-07-28 22:33:38       -       NaN
 635787     484          16353 2021-07-28 22:33:42  Ln/min  0.000000
 635788     484          16353 2021-07-28 22:33:42  Ln/min       NaN
 635789     484          16353 2021-07-28 22:33:42  Ln/min       NaN
 635790     484          16353 2021-07-28 22:33:43   U/min       NaN

         Flow_Nitrogen  Flow_O2  StirringSpeed  Temperature  Acetate  ...  \
 0                 NaN      NaN            NaN        36.99      NaN  ...
 1                 NaN      NaN            NaN          NaN      NaN  ...
 2                 NaN      NaN            NaN          NaN      NaN  ...
 3                 NaN      0.0            NaN          NaN      NaN  ...
 4                 NaN      NaN            NaN          NaN      NaN  ...
 ...               ...      ...            ...          ...      ...  ...
 635786            NaN      NaN            NaN          NaN      NaN  ...
 635787            NaN      NaN            NaN          NaN      NaN  ...
 635788            0.0      NaN            NaN          NaN      NaN  ...
 635789            NaN      0.0            NaN          NaN      NaN  ...
 635790            NaN      NaN         2400.0          NaN      NaN  ...

         Fluo_RFP  Fluo_YFP  Glucose  OD600  Probe_Volume    pH  Fluo_GFP  \
 0            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 1            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 2            NaN       NaN      NaN    NaN           NaN  6.86       NaN
 3            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 4            NaN       NaN      NaN    NaN           NaN   NaN       NaN
 ...          ...       ...      ...    ...           ...   ...       ...
 635786       NaN       NaN      NaN    NaN           NaN  6.87       NaN
 635787       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635788       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635789       NaN       NaN      NaN    NaN           NaN   NaN       NaN
 635790       NaN       NaN      NaN    NaN           NaN   NaN       NaN

         InducerConcentration  remark  Volume
 0                        NaN     NaN     NaN
 1                        NaN     NaN     NaN
 2                        NaN     NaN     NaN
 3                        NaN     NaN     NaN
 4                        NaN     NaN     NaN
 ...                      ...     ...     ...
 635786                   NaN     NaN     NaN
 635787                   NaN     NaN     NaN
 635788                   NaN     NaN     NaN
 635789                   NaN     NaN     NaN
 635790                   NaN     NaN     NaN

 [635791 rows x 26 columns]}

# Preprocessing

In [8]:
def contains_no_information(series) -> bool:
    return len(series.dropna().unique()) <= 1


def contains_nan_slice(series, slices, two_enough: bool = False) -> bool:
    num_missing = 0
    for idx in slices:
        if pd.isna(series[idx]).all():
            num_missing += 1

    if (num_missing > 0 and not two_enough) or (
        num_missing >= len(slices) - 1 and two_enough
    ):
        print(f"{series.name}: data missing in {num_missing}/{len(slices)} slices!")
        return True
    return False

def float_is_int(series) -> bool:
    mask = pd.notna(series)
    return series[mask].apply(float.is_integer).all()

def is_bool(vals) -> bool:
    if len(vals) > 2: 
        return False
    
    if np.issubdtype(vals.dtype, np.bool_):
        print(f"Boolean column                       : {col}")
        return True
    elif np.issubdtype(vals.dtype, np.integer):
        # print(vals==0 ^ vals==1)
        if ((vals==0) ^ (vals==1)).all() or ((vals==-1) ^ (vals==1)).all():
            print(f"Boolean column pretending to be integer: {col}")
            return Ture
    elif np.issubdtype(vals.dtype, np.floating):
        if ((vals==0) ^ (vals==1)).all() or ((vals==-1) ^ (vals==1)).all():
            print(f"Boolean column pretending to be float: {col}")
            return True
    elif np.issubdtype(vals.dtype, pandas.StringDtype):
        val1, val2 = set(vals)
        val1 = str(val1).lower()
        val2 = str(val2).lower()
        if {val1, val2} in ({"0", "1"}, {"-1", "+1"}, {"-1", "1"}, {"t", "f"}, {"true", "false"}, {"y", "n"}, {"yes", "no"}):
            print(f"Boolean column pretending to be string: {col}")
            return True
    return False

def get_true_column_dtypes(table) -> dict[str, str]:
    dtypes = {}
    for col in table:
        series = table[col]
        mask = pd.notna(series)
        vals = series[mask].unique()

def get_boolean_cols(df) -> set[str]:
    cols = set()
    for col in table:
        series = table[col]
        mask = pd.notna(series)
        vals = series[mask].unique()
        if is_bool(vals):
            cols.add(col)
    return cols
        
def get_integer_cols(table) -> set[str]:
    cols = set()
    for col in table:
        if np.issubdtype(table[col].dtype, np.integer):
            print(f"Integer column                       : {col}")
            cols.add(col)
        elif np.issubdtype(table[col].dtype, np.floating) and float_is_int(table[col]):
            print(f"Integer column pretending to be float: {col}")
            cols.add(col)
    return cols

def get_useless_cols(table, slices, strict: bool=False) -> set[str]:
    useless_cols = set()
    for col in table:
        s = table[col]
        if col in ("run_id", "experiment_id"):
            continue
        if contains_no_information(s):
            print(f"No information in      {col}")
            useless_cols.add(col)
        elif contains_nan_slice(s, slices, two_enough=(not strict)):
            print(f"Missing for some run   {col}")
            useless_cols.add(col)
    return useless_cols

def get_μ_set(s: str):
    if pd.isna(s):
        return s
    s = s.strip().lstrip("µ_set: ").strip()
    percent, s = s.split(", ")
    value = s.strip().rstrip("mM IPTG").strip()
    return percent, value

### MetaData Preprocessing

In [9]:
table = metadata = tables["metadata"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

table_columns = set(table.columns)
useless_cols = get_useless_cols(table, run_masks) | {
    "folder_id_y",
    "ph_Base_conc",
    "ph_Ki",
    "ph_Kp",
    "ph_Tolerance",
    "pms_id",
}
integer_cols = get_integer_cols(table)
remaining_cols = table_columns - useless_cols;

No information in      starter_culture_id
No information in      inactivation_method_id
description_x: data missing in 8/9 slices!
Missing for some run   description_x
No information in      folder_id_x
No information in      plasmid_id
No information in      medium_id
No information in      description_y
No information in      Stir_Max_Restarts
No information in      Stir_Min_pO2
No information in      Stir_pO2_Threshold
No information in      ph_Max_ul
No information in      ph_Min_ul
No information in      ph_Timesetpoint
No information in      status_id
No information in      description
No information in      conclusion
No information in      container_label
No information in      is_template
No information in      Acetate_Dilution
No information in      InducerConcentration
Integer column                       : experiment_id
Integer column                       : bioreactor_id
Integer column                       : container_number
Integer column pretending to be float: profile_id
Integer column pretending to be float: inactivation_method_id
Integer column pretending to be float: folder_id_x
Integer column pretending to be float: organism_id
Integer column pretending to be float: plasmid_id
Integer column pretending to be float: medium_id
Integer column pretending to be float: run_id
Integer column                       : folder_id_y
Integer column                       : pms_id
Integer column                       : status_id
Integer column                       : is_template

In [10]:
selected_columns = {
    "experiment_id": "UInt32",
    "bioreactor_id": "UInt32",
    "container_number": "UInt32",
    "profile_id": "UInt32",
    "color": "string",
    "profile_name": "string",
    "organism_id": "UInt32",
    "run_id": "UInt32",
    "OD_Dilution": "float32",
    "Feed_concentration_glc": "float32",
    "run_name": "string",
    "pH_correction_factor": "float32",
    "start_time": "datetime64[ns]",
    "end_time": "datetime64[ns]",
}

categorical_columns = {
    "pH_correction_factor": "Float32",
    "Feed_concentration_glc": "Int16",
    "profile_name": "category",
    "run_name": "category",
    "color": "category",
    "OD_Dilution": "Float32",
}

assert (
    selected_columns.keys() >= table_columns - useless_cols
), f"You forgot to check {remaining_cols - selected_columns.keys()}"

assert (
    selected_columns.keys() <= table_columns - useless_cols
), f"Superfluous {selected_columns.keys() - remaining_cols}"

assert set(categorical_columns) <= set(
    selected_columns
), f"Superfluous encoing {set(categorical_columns) - set(selected_columns)}"

In [11]:
table = table[selected_columns]
table = table.astype(selected_columns)
table = table.astype(categorical_columns)
metadata = table.set_index(["run_id", "experiment_id"])

                      bioreactor_id  container_number  profile_id      color  \
run_id experiment_id
355    11722                    397                 9        6449  #FFFF6404
       11723                    397                10        6450  #FFFFF400
       11724                    397                11        6451  #FFAFFF00
       11725                    397                12        6452  #FF00FFAB
       11726                    397                13        6453  #FF00ABFF
...                             ...               ...         ...        ...
484    16349                    588                28       11028  #FFE7298A
       16350                    588                29       11029  #FF66A61E
       16351                    588                30       11030  #FFE6AB02
       16352                    588                31       11031  #FFA6761D
       16353                    588                32       11032  #FF666666

                     profile_name  organism_id  OD_Dilution  \
run_id experiment_id
355    11722                   A2            3        100.0
       11723                   B2            8        100.0
       11724                   C2           21        100.0
       11725                   D2           32        100.0
       11726                   E2           14        100.0
...                           ...          ...          ...
484    16349                   D4           41         20.0
       16350                   E4           41         20.0
       16351                   F4           41         20.0
       16352                   G4           41         20.0
       16353                   H4           41         20.0

                      Feed_concentration_glc            run_name  \
run_id experiment_id
355    11722                            <NA>   20190409_SWORD_II
       11723                            <NA>   20190409_SWORD_II
       11724                            <NA>   20190409_SWORD_II
       11725                            <NA>   20190409_SWORD_II
       11726                            <NA>   20190409_SWORD_II
...                                      ...                 ...
484    16349                             200  20210707_MHE_MPC_6
       16350                             200  20210707_MHE_MPC_6
       16351                             200  20210707_MHE_MPC_6
       16352                             200  20210707_MHE_MPC_6
       16353                             200  20210707_MHE_MPC_6

                      pH_correction_factor          start_time  \
run_id experiment_id
355    11722                          <NA> 2019-04-09 18:31:53
       11723                          <NA> 2019-04-09 18:31:53
       11724                          <NA> 2019-04-09 18:31:53
       11725                          <NA> 2019-04-09 18:31:53
       11726                          <NA> 2019-04-09 18:31:53
...                                    ...                 ...
484    16349                           0.2 2021-07-28 08:56:22
       16350                           0.2 2021-07-28 08:56:22
       16351                           0.2 2021-07-28 08:56:22
       16352                           0.2 2021-07-28 08:56:22
       16353                           0.2 2021-07-28 08:56:22

                                end_time
run_id experiment_id
355    11722         2019-04-10 07:43:33
       11723         2019-04-10 07:43:33
       11724         2019-04-10 07:43:33
       11725         2019-04-10 07:43:33
       11726         2019-04-10 07:43:33
...                                  ...
484    16349         2021-07-28 22:37:27
       16350         2021-07-28 22:37:27
       16351         2021-07-28 22:37:27
       16352         2021-07-28 22:37:27
       16353         2021-07-28 22:37:27

[240 rows x 12 columns]

## Setpoint Preprocessing

In [12]:
table = setpoints = tables["setpoints"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

table_columns = set(table.columns)
useless_cols = get_useless_cols(table, run_masks)
integer_cols = get_integer_cols(table)
remaining_cols = table_columns - useless_cols

No information in      Puls_AceticAcid
No information in      Puls_Medium
No information in      pH
No information in      Flow_Nitrogen
No information in      Flow_O2
No information in      Feed_dextrine_cum_setpoints
Integer column                       : run_id
Integer column                       : experiment_id
Integer column                       : cultivation_age
Integer column                       : setpoint_id
Integer column pretending to be float: Puls_AceticAcid
Integer column pretending to be float: Puls_Glucose
Integer column pretending to be float: Puls_Medium
Integer column pretending to be float: StirringSpeed
Integer column pretending to be float: pH
Integer column pretending to be float: Feed_glc_cum_setpoints
Integer column pretending to be float: Flow_Air
Integer column pretending to be float: Flow_Nitrogen
Integer column pretending to be float: Flow_O2
Integer column pretending to be float: Feed_dextrine_cum_setpoints

{'Feed_glc_cum_setpoints',
 'Flow_Air',
 'InducerConcentration',
 'Puls_Glucose',
 'StirringSpeed',
 'cultivation_age',
 'experiment_id',
 'run_id',
 'setpoint_id',
 'unit'}

In [13]:
setpoints["unit"].unique()

array(['-', 'µL', 'U/min', 'Ln/min', 'mM'], dtype=object)

In [14]:
selected_columns = {
    "experiment_id": "UInt32",
    "run_id": "UInt32",
    "cultivation_age": "UInt32",
    "setpoint_id": "UInt32",
    "unit": "string",
    # "Puls_AceticAcid": "Float32",
    "Puls_Glucose": "Float32",
    # "Puls_Medium": "Float32",
    "StirringSpeed": "UInt16",
    # "pH": "Float32",
    "Feed_glc_cum_setpoints": "UInt16",
    "Flow_Air": "UInt8",
    "InducerConcentration": "Float32",
    # "Flow_Nitrogen": "Float32",
    # "Flow_O2": "Float32",
    # "Feed_dextrine_cum_setpoints": "Float32",
}

categorical_columns = {
    "unit": "category",
}

assert (
    selected_columns.keys() >= table_columns - useless_cols
), f"You forgot to check {remaining_cols - selected_columns.keys()}"

assert (
    selected_columns.keys() <= table_columns - useless_cols
), f"Superfluous {selected_columns.keys() - remaining_cols}"

assert set(categorical_columns) <= set(
    selected_columns
), f"Superfluous encoing {set(categorical_columns) - set(selected_columns)}"

In [15]:
table["unit"] = table["unit"].replace(to_replace="-", value=pd.NA)
table = table[selected_columns]
table = table.astype(selected_columns)
table = table.astype(categorical_columns)
setpoints = table.set_index(["run_id", "experiment_id"])

                      cultivation_age  setpoint_id   unit  Puls_Glucose  \
run_id experiment_id
355    11722                        0       470579    NaN          <NA>
       11722                        0       470581     µL          <NA>
       11722                        0       470582     µL          <NA>
       11722                        0       470675  U/min          <NA>
       11722                        0       470580     µL           0.0
...                               ...          ...    ...           ...
484    16353                    46583       742149     µL          <NA>
       16353                    47183       742150     µL          <NA>
       16353                    47783       742151     µL          <NA>
       16353                    48383       742152     µL          <NA>
       16353                    48983       742153     µL          <NA>

                      StirringSpeed  Feed_glc_cum_setpoints  Flow_Air  \
run_id experiment_id
355    11722                   <NA>                    <NA>      <NA>
       11722                   <NA>                    <NA>      <NA>
       11722                   <NA>                    <NA>      <NA>
       11722                   3000                    <NA>      <NA>
       11722                   <NA>                    <NA>      <NA>
...                             ...                     ...       ...
484    16353                   <NA>                     906      <NA>
       16353                   <NA>                     926      <NA>
       16353                   <NA>                     946      <NA>
       16353                   <NA>                     966      <NA>
       16353                   <NA>                     986      <NA>

                      InducerConcentration
run_id experiment_id
355    11722                          <NA>
       11722                          <NA>
       11722                          <NA>
       11722                          <NA>
       11722                          <NA>
...                                    ...
484    16353                          <NA>
       16353                          <NA>
       16353                          <NA>
       16353                          <NA>
       16353                          <NA>

[23126 rows x 8 columns]

##  Measurements Reactor

In [17]:
table = reactor = tables["measurements_reactor"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

table_columns = set(table.columns)
useless_cols = get_useless_cols(table, run_masks)
integer_cols = get_integer_cols(table)
remaining_cols = table_columns - useless_cols

No information in      Acid
Fluo_CFP: data missing in 8/9 slices!
Missing for some run   Fluo_CFP
Fluo_RFP: data missing in 8/9 slices!
Missing for some run   Fluo_RFP
Fluo_YFP: data missing in 8/9 slices!
Missing for some run   Fluo_YFP
No information in      remark
Integer column                       : run_id
Integer column                       : experiment_id
Integer column pretending to be float: measurement_id
Integer column pretending to be float: Acid
Integer column pretending to be float: Base
Integer column pretending to be float: Cumulated_feed_volume_glucose
Integer column pretending to be float: Probe_Volume

{'Acetate',
 'Base',
 'Cumulated_feed_volume_glucose',
 'Cumulated_feed_volume_medium',
 'DOT',
 'Fluo_GFP',
 'Glucose',
 'InducerConcentration',
 'OD600',
 'Probe_Volume',
 'Volume',
 'experiment_id',
 'measurement_id',
 'measurement_time',
 'pH',
 'run_id',
 'unit'}

In [18]:
selected_columns = {
    "Acetate"                       : "Float32",
    "Base"                          : "Int16",
    "Cumulated_feed_volume_glucose" : "Int16",
    "Cumulated_feed_volume_medium"  : "Float32",
    "DOT"                           : "Float32",
    "Fluo_GFP"                      : "Float32",
    "Glucose"                       : "Float32",
    "InducerConcentration"          : "Float32",
    "OD600"                         : "Float32",
    "Probe_Volume"                  : "Int16",
    "Volume"                        : "Float32",
    "experiment_id"                 : "UInt32",
    "measurement_id"                : "UInt32",
    "measurement_time"              : "datetime64[ns]",
    "pH"                            : "Float32",
    "run_id"                        : "UInt32",
    "unit"                          : "string",
}

categorical_columns = {
    "unit": "category",
}

assert (
    selected_columns.keys() >= table_columns - useless_cols
), f"You forgot to check {remaining_cols - selected_columns.keys()}"

assert (
    selected_columns.keys() <= table_columns - useless_cols
), f"Superfluous {selected_columns.keys() - remaining_cols}"

assert set(categorical_columns) <= set(
    selected_columns
), f"Superfluous encoing {set(categorical_columns) - set(selected_columns)}"

In [19]:
table["unit"] = table["unit"].replace(to_replace="-", value=pd.NA)
table = table[selected_columns]
table = table.astype(selected_columns)
table = table.astype(categorical_columns)
reactor = table.set_index(["run_id", "experiment_id"])

                      Acetate  Base  Cumulated_feed_volume_glucose  \
run_id experiment_id
355    11722             <NA>  <NA>                           <NA>
       11722             <NA>  <NA>                           <NA>
       11722             <NA>  <NA>                           <NA>
       11722             <NA>  <NA>                           <NA>
       11722             <NA>  <NA>                           <NA>
...                       ...   ...                            ...
484    16353             <NA>  <NA>                           <NA>
       16353             <NA>  <NA>                           <NA>
       16353             <NA>  <NA>                           <NA>
       16353             <NA>  <NA>                           <NA>
       16353             <NA>  <NA>                           <NA>

                      Cumulated_feed_volume_medium        DOT  Fluo_GFP  \
run_id experiment_id
355    11722                                  <NA>  89.660004      <NA>
       11722                                  <NA>       <NA>      <NA>
       11722                                  <NA>  89.440002      <NA>
       11722                                  <NA>       <NA>      <NA>
       11722                                  <NA>  89.589996      <NA>
...                                            ...        ...       ...
484    16353                                  <NA>       <NA>      <NA>
       16353                                  <NA>  69.889999      <NA>
       16353                                  <NA>       <NA>      <NA>
       16353                                  <NA>      45.77      <NA>
       16353                                  <NA>       <NA>      <NA>

                      Glucose  InducerConcentration  OD600  Probe_Volume  \
run_id experiment_id
355    11722             <NA>                  <NA>   <NA>          <NA>
       11722             <NA>                  <NA>   <NA>          <NA>
       11722             <NA>                  <NA>   <NA>          <NA>
       11722             <NA>                  <NA>   <NA>          <NA>
       11722             <NA>                  <NA>   <NA>          <NA>
...                       ...                   ...    ...           ...
484    16353             <NA>                  <NA>   <NA>          <NA>
       16353             <NA>                  <NA>   <NA>          <NA>
       16353             <NA>                  <NA>   <NA>          <NA>
       16353             <NA>                  <NA>   <NA>          <NA>
       16353             <NA>                   2.0   <NA>          <NA>

                      Volume  measurement_id    measurement_time    pH unit
run_id experiment_id
355    11722            <NA>        18358520 2019-04-09 18:32:18  <NA>  NaN
       11722            <NA>        18358544 2019-04-09 18:32:19  6.86  NaN
       11722            <NA>        18358568 2019-04-09 18:32:28  <NA>  NaN
       11722            <NA>        18358592 2019-04-09 18:32:29  6.86  NaN
       11722            <NA>        18358616 2019-04-09 18:32:38  <NA>  NaN
...                      ...             ...                 ...   ...  ...
484    16353            <NA>        23138083 2021-07-28 22:33:26  6.88  NaN
       16353            <NA>        23138082 2021-07-28 22:33:26  <NA>  NaN
       16353            <NA>        23138131 2021-07-28 22:33:38  6.87  NaN
       16353            <NA>        23138130 2021-07-28 22:33:38  <NA>  NaN
       16353            <NA>            <NA> 2021-07-28 17:26:22  <NA>   mM

[429799 rows x 15 columns]

## Measurements_Array

In [20]:
table = array = tables["measurements_array"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

table_columns = set(table.columns)
useless_cols = get_useless_cols(table, run_masks)
integer_cols = get_integer_cols(table)
remaining_cols = table_columns - useless_cols

No information in      Flow_Nitrogen
No information in      Flow_O2
Integer column                       : run_id
Integer column                       : experiment_id
Integer column                       : measurement_id
Integer column pretending to be float: Flow_Nitrogen
Integer column pretending to be float: Flow_O2
Integer column pretending to be float: StirringSpeed

{'Flow_Air',
 'StirringSpeed',
 'Temperature',
 'experiment_id',
 'measurement_id',
 'measurement_time',
 'run_id',
 'unit'}

In [21]:
selected_columns = {
    "run_id"             :           "UInt32",
    "experiment_id"      :           "UInt32",
    "measurement_time"   :   "datetime64[ns]",
    "measurement_id"     :           "UInt32",
    "unit"               :           "string",
    "Flow_Air"           :         "Float32",
    # "Flow_Nitrogen"      :         "float64",
    # "Flow_O2"            :         "float64",
    "StirringSpeed"      :         "Int16",
    "Temperature"        :         "Float32",
}

categorical_columns = {
    "unit": "category",
}

assert (
    selected_columns.keys() >= table_columns - useless_cols
), f"You forgot to check {remaining_cols - selected_columns.keys()}"

assert (
    selected_columns.keys() <= table_columns - useless_cols
), f"Superfluous {selected_columns.keys() - remaining_cols}"

assert set(categorical_columns) <= set(
    selected_columns
), f"Superfluous encoing {set(categorical_columns) - set(selected_columns)}"

In [22]:
table["unit"] = table["unit"].replace(to_replace="-", value=pd.NA)
table = table[selected_columns]
table = table.astype(selected_columns)
table = table.astype(categorical_columns)
array = table.set_index(["run_id", "experiment_id"])

                        measurement_time  measurement_id    unit  Flow_Air  \
run_id experiment_id
355    11722         2019-04-09 18:32:12         1072518      °C      <NA>
       11722         2019-04-09 18:32:21         1072521  Ln/min      <NA>
       11722         2019-04-09 18:32:21         1072520  Ln/min  4.997213
       11722         2019-04-09 18:32:21         1072519  Ln/min      <NA>
       11722         2019-04-09 18:32:22         1072522      °C      <NA>
...                                  ...             ...     ...       ...
484    16353         2021-07-28 22:33:28         1410622   U/min      <NA>
       16353         2021-07-28 22:33:42         1410625  Ln/min       0.0
       16353         2021-07-28 22:33:42         1410624  Ln/min      <NA>
       16353         2021-07-28 22:33:42         1410626  Ln/min      <NA>
       16353         2021-07-28 22:33:43         1410627   U/min      <NA>

                      StirringSpeed  Temperature
run_id experiment_id
355    11722                   <NA>    36.990002
       11722                   <NA>         <NA>
       11722                   <NA>         <NA>
       11722                   <NA>         <NA>
       11722                   <NA>        36.98
...                             ...          ...
484    16353                   2400         <NA>
       16353                   <NA>         <NA>
       16353                   <NA>         <NA>
       16353                   <NA>         <NA>
       16353                   2400         <NA>

[205992 rows x 6 columns]

In [23]:
array.dropna(how="all").groupby(["run_id", "experiment_id", "measurement_time"]).mean()

                                          measurement_id  Flow_Air  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       1072518.0      <NA>
                     2019-04-09 18:32:21       1072520.0  4.997213
                     2019-04-09 18:32:22       1072522.0      <NA>
                     2019-04-09 18:32:30       1072523.0      <NA>
                     2019-04-09 18:32:31       1072524.5  5.002163
...                                                  ...       ...
484    16353         2021-07-28 22:33:04       1410619.0       0.0
                     2021-07-28 22:33:17       1410621.0      <NA>
                     2021-07-28 22:33:28       1410622.5      <NA>
                     2021-07-28 22:33:42       1410625.0       0.0
                     2021-07-28 22:33:43       1410627.0      <NA>

                                          StirringSpeed  Temperature
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12           <NA>    36.990002
                     2019-04-09 18:32:21           <NA>         <NA>
                     2019-04-09 18:32:22           <NA>        36.98
                     2019-04-09 18:32:30           <NA>         <NA>
                     2019-04-09 18:32:31           <NA>         <NA>
...                                                 ...          ...
484    16353         2021-07-28 22:33:04           <NA>         <NA>
                     2021-07-28 22:33:17           <NA>    37.529999
                     2021-07-28 22:33:28         2400.0        37.57
                     2021-07-28 22:33:42           <NA>         <NA>
                     2021-07-28 22:33:43         2400.0         <NA>

[171432 rows x 4 columns]

## Measurements Aggregated

In [41]:
table = aggregated = tables["measurements_aggregated"]
runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

table_columns = set(table.columns)
useless_cols = get_useless_cols(table,run_masks)
integer_cols = get_integer_cols(table)
remaining_cols = table_columns - useless_cols

No information in      Flow_Nitrogen
No information in      Flow_O2
No information in      Acid
Fluo_CFP: data missing in 8/9 slices!
Missing for some run   Fluo_CFP
Fluo_RFP: data missing in 8/9 slices!
Missing for some run   Fluo_RFP
Fluo_YFP: data missing in 8/9 slices!
Missing for some run   Fluo_YFP
No information in      remark
Integer column                       : run_id
Integer column                       : experiment_id
Integer column pretending to be float: Flow_Nitrogen
Integer column pretending to be float: Flow_O2
Integer column pretending to be float: StirringSpeed
Integer column pretending to be float: Acid
Integer column pretending to be float: Base
Integer column pretending to be float: Cumulated_feed_volume_glucose
Integer column pretending to be float: Probe_Volume

{'Acetate',
 'Base',
 'Cumulated_feed_volume_glucose',
 'Cumulated_feed_volume_medium',
 'DOT',
 'Flow_Air',
 'Fluo_GFP',
 'Glucose',
 'InducerConcentration',
 'OD600',
 'Probe_Volume',
 'StirringSpeed',
 'Temperature',
 'Volume',
 'experiment_id',
 'measurement_time',
 'pH',
 'run_id',
 'unit'}

In [42]:
selected_columns = {
    "run_id"                        :            "UInt32",
    "experiment_id"                 :            "UInt32",
    "measurement_time"              :   "datetime64[ns]",
    "unit"                          :           "string",
    "Flow_Air"                      :          "Float32",
    # "Flow_Nitrogen"                 :          "Float32",
    # "Flow_O2"                       :          "Int32",
    "StirringSpeed"                 :          "Int16",
    "Temperature"                   :          "Float32",
    "Acetate"                       :          "Float32",
    # "Acid"                          :          "Float32",
    "Base"                          :          "Int16",
    "Cumulated_feed_volume_glucose" :          "Int16",
    "Cumulated_feed_volume_medium"  :          "Float32",
    "DOT"                           :          "Float32",
    # "Fluo_CFP"                      :          "Float32",
    # "Fluo_RFP"                      :          "Float32",
    # "Fluo_YFP"                      :          "Float32",
    "Glucose"                       :          "Float32",
    "OD600"                         :          "Float32",
    "Probe_Volume"                  :          "Int16",
    "pH"                            :          "Float32",
    "Fluo_GFP"                      :          "Float32",
    "InducerConcentration"          :          "Float32",
    # "remark"                        :           "string",
    "Volume"                        :          "Float32",
}

categorical_columns = {
    "unit": "category"
}

assert (
    selected_columns.keys() >= table_columns - useless_cols
), f"You forgot to check {remaining_cols - selected_columns.keys()}"

assert (
    selected_columns.keys() <= table_columns - useless_cols
), f"Superfluous {selected_columns.keys() - remaining_cols}"

assert set(categorical_columns) <= set(
    selected_columns
), f"Superfluous encoing {set(categorical_columns) - set(selected_columns)}"

In [43]:
table["unit"] = table["unit"].replace(to_replace="-", value=pd.NA)
# aggregated = aggregated.astype(aggregated_dtypes)
# aggregated = aggregated.astype(aggregated_categoricals)
table = table[selected_columns].astype(selected_columns)
aggregated = table.set_index(["run_id", "experiment_id"])

/home/rscholz/miniconda3/envs/kiwi/lib/python3.9/site-packages/pandas/core/missing.py:94: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= arr == x

                        measurement_time    unit  Flow_Air  StirringSpeed  \
run_id experiment_id
355    11722         2019-04-09 18:32:12      °C      <NA>           <NA>
       11722         2019-04-09 18:32:18    <NA>      <NA>           <NA>
       11722         2019-04-09 18:32:19    <NA>      <NA>           <NA>
       11722         2019-04-09 18:32:21  Ln/min      <NA>           <NA>
       11722         2019-04-09 18:32:21  Ln/min  4.997213           <NA>
...                                  ...     ...       ...            ...
484    16353         2021-07-28 22:33:38    <NA>      <NA>           <NA>
       16353         2021-07-28 22:33:42  Ln/min       0.0           <NA>
       16353         2021-07-28 22:33:42  Ln/min      <NA>           <NA>
       16353         2021-07-28 22:33:42  Ln/min      <NA>           <NA>
       16353         2021-07-28 22:33:43   U/min      <NA>           2400

                      Temperature  Acetate  Base  \
run_id experiment_id
355    11722            36.990002     <NA>  <NA>
       11722                 <NA>     <NA>  <NA>
       11722                 <NA>     <NA>  <NA>
       11722                 <NA>     <NA>  <NA>
       11722                 <NA>     <NA>  <NA>
...                           ...      ...   ...
484    16353                 <NA>     <NA>  <NA>
       16353                 <NA>     <NA>  <NA>
       16353                 <NA>     <NA>  <NA>
       16353                 <NA>     <NA>  <NA>
       16353                 <NA>     <NA>  <NA>

                      Cumulated_feed_volume_glucose  \
run_id experiment_id
355    11722                                   <NA>
       11722                                   <NA>
       11722                                   <NA>
       11722                                   <NA>
       11722                                   <NA>
...                                             ...
484    16353                                   <NA>
       16353                                   <NA>
       16353                                   <NA>
       16353                                   <NA>
       16353                                   <NA>

                      Cumulated_feed_volume_medium        DOT  Glucose  OD600  \
run_id experiment_id
355    11722                                  <NA>       <NA>     <NA>   <NA>
       11722                                  <NA>  89.660004     <NA>   <NA>
       11722                                  <NA>       <NA>     <NA>   <NA>
       11722                                  <NA>       <NA>     <NA>   <NA>
       11722                                  <NA>       <NA>     <NA>   <NA>
...                                            ...        ...      ...    ...
484    16353                                  <NA>       <NA>     <NA>   <NA>
       16353                                  <NA>       <NA>     <NA>   <NA>
       16353                                  <NA>       <NA>     <NA>   <NA>
       16353                                  <NA>       <NA>     <NA>   <NA>
       16353                                  <NA>       <NA>     <NA>   <NA>

                      Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
run_id experiment_id
355    11722                  <NA>  <NA>      <NA>                  <NA>
       11722                  <NA>  <NA>      <NA>                  <NA>
       11722                  <NA>  6.86      <NA>                  <NA>
       11722                  <NA>  <NA>      <NA>                  <NA>
       11722                  <NA>  <NA>      <NA>                  <NA>
...                            ...   ...       ...                   ...
484    16353                  <NA>  6.87      <NA>                  <NA>
       16353                  <NA>  <NA>      <NA>                  <NA>
       16353                  <NA>  <NA>      <NA>                  <NA>
       16353                  <NA>  <NA>      <NA>                  <NA>
       16353                  <NA>  <NA>      <NA>                  <NA>

                      Volume
run_id experiment_id
355    11722            <NA>
       11722            <NA>
       11722            <NA>
       11722            <NA>
       11722            <NA>
...                      ...
484    16353            <NA>
       16353            <NA>
       16353            <NA>
       16353            <NA>
       16353            <NA>

[635791 rows x 17 columns]

## TimeSeries

In [44]:
table = aggregated.copy()
table = table.drop(columns="unit")
table = table.groupby(["run_id", "experiment_id", "measurement_time"]).mean()

                                          Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12      <NA>           <NA>
                     2019-04-09 18:32:18      <NA>           <NA>
                     2019-04-09 18:32:19      <NA>           <NA>
                     2019-04-09 18:32:21  4.997213           <NA>
                     2019-04-09 18:32:22      <NA>           <NA>
...                                            ...            ...
484    16353         2021-07-28 22:33:26      <NA>           <NA>
                     2021-07-28 22:33:28      <NA>         2400.0
                     2021-07-28 22:33:38      <NA>           <NA>
                     2021-07-28 22:33:42       0.0           <NA>
                     2021-07-28 22:33:43      <NA>         2400.0

                                          Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    36.990002     <NA>  <NA>
                     2019-04-09 18:32:18         <NA>     <NA>  <NA>
                     2019-04-09 18:32:19         <NA>     <NA>  <NA>
                     2019-04-09 18:32:21         <NA>     <NA>  <NA>
                     2019-04-09 18:32:22        36.98     <NA>  <NA>
...                                               ...      ...   ...
484    16353         2021-07-28 22:33:26         <NA>     <NA>  <NA>
                     2021-07-28 22:33:28        37.57     <NA>  <NA>
                     2021-07-28 22:33:38         <NA>     <NA>  <NA>
                     2021-07-28 22:33:42         <NA>     <NA>  <NA>
                     2021-07-28 22:33:43         <NA>     <NA>  <NA>

                                          Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                           <NA>
                     2019-04-09 18:32:18                           <NA>
                     2019-04-09 18:32:19                           <NA>
                     2019-04-09 18:32:21                           <NA>
                     2019-04-09 18:32:22                           <NA>
...                                                                 ...
484    16353         2021-07-28 22:33:26                           <NA>
                     2021-07-28 22:33:28                           <NA>
                     2021-07-28 22:33:38                           <NA>
                     2021-07-28 22:33:42                           <NA>
                     2021-07-28 22:33:43                           <NA>

                                          Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                          <NA>
                     2019-04-09 18:32:18                          <NA>
                     2019-04-09 18:32:19                          <NA>
                     2019-04-09 18:32:21                          <NA>
                     2019-04-09 18:32:22                          <NA>
...                                                                ...
484    16353         2021-07-28 22:33:26                          <NA>
                     2021-07-28 22:33:28                          <NA>
                     2021-07-28 22:33:38                          <NA>
                     2021-07-28 22:33:42                          <NA>
                     2021-07-28 22:33:43                          <NA>

                                                DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>     <NA>   <NA>
                     2019-04-09 18:32:18  89.660004     <NA>   <NA>
                     2019-04-09 18:32:19       <NA>     <NA>   <NA>
                     2019-04-09 18:32:21       <NA>     <NA>   <NA>
                     2019-04-09 18:32:22       <NA>     <NA>   <NA>
...                                             ...      ...    ...
484    16353         2021-07-28 22:33:26  69.889999     <NA>   <NA>
                     2021-07-28 22:33:28       <NA>     <NA>   <NA>
                     2021-07-28 22:33:38      45.77     <NA>   <NA>
                     2021-07-28 22:33:42       <NA>     <NA>   <NA>
                     2021-07-28 22:33:43       <NA>     <NA>   <NA>

                                          Probe_Volume    pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12          <NA>  <NA>      <NA>
                     2019-04-09 18:32:18          <NA>  <NA>      <NA>
                     2019-04-09 18:32:19          <NA>  6.86      <NA>
                     2019-04-09 18:32:21          <NA>  <NA>      <NA>
                     2019-04-09 18:32:22          <NA>  <NA>      <NA>
...                                                ...   ...       ...
484    16353         2021-07-28 22:33:26          <NA>  6.88      <NA>
                     2021-07-28 22:33:28          <NA>  <NA>      <NA>
                     2021-07-28 22:33:38          <NA>  6.87      <NA>
                     2021-07-28 22:33:42          <NA>  <NA>      <NA>
                     2021-07-28 22:33:43          <NA>  <NA>      <NA>

                                          InducerConcentration  Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                  <NA>    <NA>
                     2019-04-09 18:32:18                  <NA>    <NA>
                     2019-04-09 18:32:19                  <NA>    <NA>
                     2019-04-09 18:32:21                  <NA>    <NA>
                     2019-04-09 18:32:22                  <NA>    <NA>
...                                                        ...     ...
484    16353         2021-07-28 22:33:26                  <NA>    <NA>
                     2021-07-28 22:33:28                  <NA>    <NA>
                     2021-07-28 22:33:38                  <NA>    <NA>
                     2021-07-28 22:33:42                  <NA>    <NA>
                     2021-07-28 22:33:43                  <NA>    <NA>

[423460 rows x 15 columns]

In [46]:
table = table.astype(selected_columns.pop("unit"))

                                           Flow_Air StirringSpeed Temperature  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>          <NA>       36.99
                     2019-04-09 18:32:18       <NA>          <NA>        <NA>
                     2019-04-09 18:32:19       <NA>          <NA>        <NA>
                     2019-04-09 18:32:21  4.9972134          <NA>        <NA>
                     2019-04-09 18:32:22       <NA>          <NA>       36.98
...                                             ...           ...         ...
484    16353         2021-07-28 22:33:26       <NA>          <NA>        <NA>
                     2021-07-28 22:33:28       <NA>        2400.0       37.57
                     2021-07-28 22:33:38       <NA>          <NA>        <NA>
                     2021-07-28 22:33:42        0.0          <NA>        <NA>
                     2021-07-28 22:33:43       <NA>        2400.0        <NA>

                                         Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    <NA>  <NA>
                     2019-04-09 18:32:18    <NA>  <NA>
                     2019-04-09 18:32:19    <NA>  <NA>
                     2019-04-09 18:32:21    <NA>  <NA>
                     2019-04-09 18:32:22    <NA>  <NA>
...                                          ...   ...
484    16353         2021-07-28 22:33:26    <NA>  <NA>
                     2021-07-28 22:33:28    <NA>  <NA>
                     2021-07-28 22:33:38    <NA>  <NA>
                     2021-07-28 22:33:42    <NA>  <NA>
                     2021-07-28 22:33:43    <NA>  <NA>

                                         Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                          <NA>
                     2019-04-09 18:32:18                          <NA>
                     2019-04-09 18:32:19                          <NA>
                     2019-04-09 18:32:21                          <NA>
                     2019-04-09 18:32:22                          <NA>
...                                                                ...
484    16353         2021-07-28 22:33:26                          <NA>
                     2021-07-28 22:33:28                          <NA>
                     2021-07-28 22:33:38                          <NA>
                     2021-07-28 22:33:42                          <NA>
                     2021-07-28 22:33:43                          <NA>

                                         Cumulated_feed_volume_medium    DOT  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                         <NA>   <NA>
                     2019-04-09 18:32:18                         <NA>  89.66
                     2019-04-09 18:32:19                         <NA>   <NA>
                     2019-04-09 18:32:21                         <NA>   <NA>
                     2019-04-09 18:32:22                         <NA>   <NA>
...                                                               ...    ...
484    16353         2021-07-28 22:33:26                         <NA>  69.89
                     2021-07-28 22:33:28                         <NA>   <NA>
                     2021-07-28 22:33:38                         <NA>  45.77
                     2021-07-28 22:33:42                         <NA>   <NA>
                     2021-07-28 22:33:43                         <NA>   <NA>

                                         Glucose OD600 Probe_Volume    pH  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    <NA>  <NA>         <NA>  <NA>
                     2019-04-09 18:32:18    <NA>  <NA>         <NA>  <NA>
                     2019-04-09 18:32:19    <NA>  <NA>         <NA>  6.86
                     2019-04-09 18:32:21    <NA>  <NA>         <NA>  <NA>
                     2019-04-09 18:32:22    <NA>  <NA>         <NA>  <NA>
...                                          ...   ...          ...   ...
484    16353         2021-07-28 22:33:26    <NA>  <NA>         <NA>  6.88
                     2021-07-28 22:33:28    <NA>  <NA>         <NA>  <NA>
                     2021-07-28 22:33:38    <NA>  <NA>         <NA>  6.87
                     2021-07-28 22:33:42    <NA>  <NA>         <NA>  <NA>
                     2021-07-28 22:33:43    <NA>  <NA>         <NA>  <NA>

                                         Fluo_GFP InducerConcentration Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:18     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:19     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:21     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:22     <NA>                 <NA>   <NA>
...                                           ...                  ...    ...
484    16353         2021-07-28 22:33:26     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:28     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:38     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:42     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:43     <NA>                 <NA>   <NA>

[423460 rows x 15 columns]

In [48]:
table.dropna(how="all")

                                           Flow_Air StirringSpeed Temperature  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>          <NA>       36.99
                     2019-04-09 18:32:18       <NA>          <NA>        <NA>
                     2019-04-09 18:32:19       <NA>          <NA>        <NA>
                     2019-04-09 18:32:21  4.9972134          <NA>        <NA>
                     2019-04-09 18:32:22       <NA>          <NA>       36.98
...                                             ...           ...         ...
484    16353         2021-07-28 22:33:26       <NA>          <NA>        <NA>
                     2021-07-28 22:33:28       <NA>        2400.0       37.57
                     2021-07-28 22:33:38       <NA>          <NA>        <NA>
                     2021-07-28 22:33:42        0.0          <NA>        <NA>
                     2021-07-28 22:33:43       <NA>        2400.0        <NA>

                                         Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    <NA>  <NA>
                     2019-04-09 18:32:18    <NA>  <NA>
                     2019-04-09 18:32:19    <NA>  <NA>
                     2019-04-09 18:32:21    <NA>  <NA>
                     2019-04-09 18:32:22    <NA>  <NA>
...                                          ...   ...
484    16353         2021-07-28 22:33:26    <NA>  <NA>
                     2021-07-28 22:33:28    <NA>  <NA>
                     2021-07-28 22:33:38    <NA>  <NA>
                     2021-07-28 22:33:42    <NA>  <NA>
                     2021-07-28 22:33:43    <NA>  <NA>

                                         Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                          <NA>
                     2019-04-09 18:32:18                          <NA>
                     2019-04-09 18:32:19                          <NA>
                     2019-04-09 18:32:21                          <NA>
                     2019-04-09 18:32:22                          <NA>
...                                                                ...
484    16353         2021-07-28 22:33:26                          <NA>
                     2021-07-28 22:33:28                          <NA>
                     2021-07-28 22:33:38                          <NA>
                     2021-07-28 22:33:42                          <NA>
                     2021-07-28 22:33:43                          <NA>

                                         Cumulated_feed_volume_medium    DOT  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                         <NA>   <NA>
                     2019-04-09 18:32:18                         <NA>  89.66
                     2019-04-09 18:32:19                         <NA>   <NA>
                     2019-04-09 18:32:21                         <NA>   <NA>
                     2019-04-09 18:32:22                         <NA>   <NA>
...                                                               ...    ...
484    16353         2021-07-28 22:33:26                         <NA>  69.89
                     2021-07-28 22:33:28                         <NA>   <NA>
                     2021-07-28 22:33:38                         <NA>  45.77
                     2021-07-28 22:33:42                         <NA>   <NA>
                     2021-07-28 22:33:43                         <NA>   <NA>

                                         Glucose OD600 Probe_Volume    pH  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    <NA>  <NA>         <NA>  <NA>
                     2019-04-09 18:32:18    <NA>  <NA>         <NA>  <NA>
                     2019-04-09 18:32:19    <NA>  <NA>         <NA>  6.86
                     2019-04-09 18:32:21    <NA>  <NA>         <NA>  <NA>
                     2019-04-09 18:32:22    <NA>  <NA>         <NA>  <NA>
...                                          ...   ...          ...   ...
484    16353         2021-07-28 22:33:26    <NA>  <NA>         <NA>  6.88
                     2021-07-28 22:33:28    <NA>  <NA>         <NA>  <NA>
                     2021-07-28 22:33:38    <NA>  <NA>         <NA>  6.87
                     2021-07-28 22:33:42    <NA>  <NA>         <NA>  <NA>
                     2021-07-28 22:33:43    <NA>  <NA>         <NA>  <NA>

                                         Fluo_GFP InducerConcentration Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:18     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:19     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:21     <NA>                 <NA>   <NA>
                     2019-04-09 18:32:22     <NA>                 <NA>   <NA>
...                                           ...                  ...    ...
484    16353         2021-07-28 22:33:26     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:28     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:38     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:42     <NA>                 <NA>   <NA>
                     2021-07-28 22:33:43     <NA>                 <NA>   <NA>

[408628 rows x 15 columns]

In [30]:
table = table.astype("float32")
table = table.reset_index()
table = table.astype("float32")

runs = table["run_id"].dropna().unique()
run_masks = [table["run_id"] == run for run in runs]

table_columns = set(table.columns)
useless_cols = get_useless_cols(table,run_masks)
integer_cols = get_integer_cols(table)
remaining_cols = table_columns - useless_cols

Integer column                       : run_id
Integer column                       : experiment_id
Integer column pretending to be float: StirringSpeed
Integer column pretending to be float: Base
Integer column pretending to be float: Cumulated_feed_volume_glucose
Integer column pretending to be float: Probe_Volume

{'Acetate',
 'Base',
 'Cumulated_feed_volume_glucose',
 'Cumulated_feed_volume_medium',
 'DOT',
 'Flow_Air',
 'Fluo_GFP',
 'Glucose',
 'InducerConcentration',
 'OD600',
 'Probe_Volume',
 'StirringSpeed',
 'Temperature',
 'Volume',
 'experiment_id',
 'measurement_time',
 'pH',
 'run_id'}

In [ ]:
aggregated.drop(columns="unit").groupby(["run_id", "experiment_id", "measurement_time"]).mean()