# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [21]:
import numpy as np
import modin.pandas as pd
df = pd.DataFrame(np.random.randn(10, 5), columns=list("abcde"))

UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.

          a         b         c         d         e
0  0.419648  0.777825  0.170361 -1.029170  0.505220
1 -0.847918 -0.511058  0.490561  0.725890 -1.281193
2  0.759401  1.418514 -1.296542  0.164421 -0.843339
3 -0.024629 -1.710207  0.075492  1.091615  0.393564
4  3.582264  1.994384  0.411813 -1.700247 -1.436760
5  0.936572  0.518687 -0.408396 -0.913153 -0.473188
6 -1.267100 -1.805069  1.603862  0.427899  0.461358
7  0.364015 -1.594596  0.325206 -0.069368  0.812305
8 -0.006633 -0.818804 -1.331910 -0.610244 -0.032460
9  0.746316 -0.412862  0.822646  0.380847 -0.253190

In [26]:
columns = pd.MultiIndex.from_tuples(enumerate("abc"), names=["NUMBER", "LETTER"])
cols = list("abc")
d = pd.DataFrame(df[cols])

          a         b         c
0  0.419648  0.777825  0.170361
1 -0.847918 -0.511058  0.490561
2  0.759401  1.418514 -1.296542
3 -0.024629 -1.710207  0.075492
4  3.582264  1.994384  0.411813
5  0.936572  0.518687 -0.408396
6 -1.267100 -1.805069  1.603862
7  0.364015 -1.594596  0.325206
8 -0.006633 -0.818804 -1.331910
9  0.746316 -0.412862  0.822646