In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from tsdm.datasets import BaseDataset

In [3]:
class ETTH(BaseDataset):
    url = "https://github.com/zhouhaoyi/ETDataset/tree/main/ETT-small"

In [4]:
ETTH.download()

svn: E155000: Destination directory exists; please remove the directory or use --force to overwrite
svn: E155000: '/home/rscholz/.tsdm/rawdata/ETTH' already exists

CalledProcessError: Command 'svn export https://github.com/zhouhaoyi/ETDataset/trunk/ETT-small /home/rscholz/.tsdm/rawdata/ETTH' returned non-zero exit status 1.

In [4]:
ETTH.rawdata_path

PosixPath('/home/rscholz/.tsdm/rawdata/ETTH')

In [5]:
import pandas

In [8]:
with open(ETTH.rawdata_path.joinpath("ETTm1.csv"), "r") as file:
    df = pandas.read_csv(file, parse_dates=[0], index_col=0)
display(df)
df.dtypes

                       HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
date
2016-07-01 00:00:00   5.827  2.009  1.599  0.462  4.203  1.340  30.531000
2016-07-01 00:15:00   5.760  2.076  1.492  0.426  4.264  1.401  30.459999
2016-07-01 00:30:00   5.760  1.942  1.492  0.391  4.234  1.310  30.038000
2016-07-01 00:45:00   5.760  1.942  1.492  0.426  4.234  1.310  27.013000
2016-07-01 01:00:00   5.693  2.076  1.492  0.426  4.142  1.371  27.787001
...                     ...    ...    ...    ...    ...    ...        ...
2018-06-26 18:45:00   9.310  3.550  5.437  1.670  3.868  1.462   9.567000
2018-06-26 19:00:00  10.114  3.550  6.183  1.564  3.716  1.462   9.567000
2018-06-26 19:15:00  10.784  3.349  7.000  1.635  3.746  1.432   9.426000
2018-06-26 19:30:00  11.655  3.617  7.533  1.706  4.173  1.523   9.426000
2018-06-26 19:45:00  12.994  3.818  8.244  1.777  4.721  1.523   9.778000

[69680 rows x 7 columns]

HUFL    float64
HULL    float64
MUFL    float64
MULL    float64
LUFL    float64
LULL    float64
OT      float64
dtype: object

In [3]:
from tsdm.datasets import ETTH1

In [4]:
ETTH1.dataset

                       HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
date
2016-07-01 00:00:00   5.827  2.009  1.599  0.462  4.203  1.340  30.531000
2016-07-01 01:00:00   5.693  2.076  1.492  0.426  4.142  1.371  27.787001
2016-07-01 02:00:00   5.157  1.741  1.279  0.355  3.777  1.218  27.787001
2016-07-01 03:00:00   5.090  1.942  1.279  0.391  3.807  1.279  25.044001
2016-07-01 04:00:00   5.358  1.942  1.492  0.462  3.868  1.279  21.948000
...                     ...    ...    ...    ...    ...    ...        ...
2018-06-26 15:00:00  -1.674  3.550 -5.615  2.132  3.472  1.523  10.904000
2018-06-26 16:00:00  -5.492  4.287 -9.132  2.274  3.533  1.675  11.044000
2018-06-26 17:00:00   2.813  3.818 -0.817  2.097  3.716  1.523  10.271000
2018-06-26 18:00:00   9.243  3.818  5.472  2.097  3.655  1.432   9.778000
2018-06-26 19:00:00  10.114  3.550  6.183  1.564  3.716  1.462   9.567000

[17420 rows x 7 columns]