# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import logging
logging.basicConfig(level=logging.INFO)

In [3]:
import tsdm

INFO:tsdm.config:Available Models: {'BRITS', 'N-BEATS', 'SET-TS', 'TFT', 'GRU-ODE-Bayes', 'Latent-ODE', 'M-RNN', 'Informer', 'IP-Net', 'NCDE', 'ODE-RNN', 'mTAN', 'NODE', 'TPA'}
INFO:tsdm.config:Available Datasets: {'Physionet 2019', 'Air Quality Multi-Site', 'Physionet 2012', 'M4', 'tourism2', 'M3', 'Electricity', 'Human Activity', 'M5', 'USHCN', 'UWAVE', 'Traffic', 'Air Quality', 'Household Consumption', 'Character Trajectories', 'tourism1', 'MuJoCo'}
INFO:tsdm.config:Initializing Folder Structure
INFO:tsdm.config:creating folder /home/rscholz/.tsdm/datasets
INFO:tsdm.config:creating folder /home/rscholz/.tsdm/models
INFO:tsdm.config:creating folder /home/rscholz/.tsdm/logs
INFO:tsdm.config:creating folder /home/rscholz/.tsdm/rawdata
INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [4]:
ds = tsdm.datasets.USHCN

tsdm.datasets.ushcn.USHCN

In [5]:
# ds.download()

In [6]:
ds.clean()

INFO:tsdm.datasets.ushcn:Starting ray cluster.
2021-10-04 03:48:11,033	INFO services.py:1263 -- View the Ray dashboard at http://127.0.0.1:8265
INFO:tsdm.datasets.ushcn:USHCN preparation done, loading main file
INFO:tsdm.datasets.ushcn:USHCN main data file loaded.
INFO:tsdm.datasets.ushcn:USHCN finished dataframe stacking.
2021-10-04 03:53:09,153	WARNING worker.py:1215 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 4879320fbc180bf8926fc12ef34e7058604fe2ff17941504 Worker ID: 5ade7237ea0a277a87bb48b849ac1ec5f5df50ff5b86bf27f352e651 Node ID: 7d47c1f0dc438aaeb077d6d0663cba2f5cdfce1253a2a649454f3613 Worker IP address: 192.168.1.121 Worker port: 35883 Worker PID: 88708
INFO:tsdm.datasets.ushcn:USHCN finished dataframe merging.
UserWarning: sort_values defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
INFO:tsdm.datasets.ushcn:USHCN finished sorting.
UserWarning: `DataFrame.to_feather` defaulting to pandas implementation.
UserWarning: Distributing <class 'pandas.core.frame.DataFrame'> object. This may take some time.
INFO:tsdm.datasets.ushcn:USHCN: Finished cleaning 'us_daily' DataFrame
INFO:tsdm.datasets.ushcn:Finished cleaning dataset 'USHCN'

In [7]:
ds.dataset

          COOP_ID  YEAR  MONTH  DAY ELEMENT MFLAG QFLAG SFLAG  VALUE
0          381310  1849      5    1    PRCP   NaN   NaN     F     50
1          381310  1849      5    2    PRCP   NaN   NaN     F      0
2          381310  1849      5    3    PRCP   NaN   NaN     F      0
3          381310  1849      5    4    PRCP   NaN   NaN     F      0
4          381310  1849      5    5    PRCP   NaN   NaN     F      0
...           ...   ...    ...  ...     ...   ...   ...   ...    ...
208575404  489905  2014     12   31    PRCP   NaN   NaN     7      0
208575405  489905  2014     12   31    SNOW   NaN   NaN     7      0
208575406  489905  2014     12   31    SNWD   NaN   NaN     7      7
208575407  489905  2014     12   31    TMAX   NaN   NaN     7      1
208575408  489905  2014     12   31    TMIN   NaN   NaN     7    -18

[208575409 rows x 9 columns]

In [15]:
%%time
pandas.DataFrame(ds.dataset)

CPU times: user 19 µs, sys: 0 ns, total: 19 µs
Wall time: 21.2 µs

          COOP_ID  YEAR  MONTH  DAY ELEMENT MFLAG QFLAG SFLAG  VALUE
0          381310  1849      5    1    PRCP   NaN   NaN     F     50
1          381310  1849      5    2    PRCP   NaN   NaN     F      0
2          381310  1849      5    3    PRCP   NaN   NaN     F      0
3          381310  1849      5    4    PRCP   NaN   NaN     F      0
4          381310  1849      5    5    PRCP   NaN   NaN     F      0
...           ...   ...    ...  ...     ...   ...   ...   ...    ...
208575404  489905  2014     12   31    PRCP   NaN   NaN     7      0
208575405  489905  2014     12   31    SNOW   NaN   NaN     7      0
208575406  489905  2014     12   31    SNWD   NaN   NaN     7      7
208575407  489905  2014     12   31    TMAX   NaN   NaN     7      1
208575408  489905  2014     12   31    TMIN   NaN   NaN     7    -18

[208575409 rows x 9 columns]

In [17]:
ds.info()