# USHCN Dataset

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
logging.basicConfig(level=logging.INFO)

In [39]:
import pandas

In [ ]:
pandas.concat

In [69]:
from tsdm.datasets import USHCN
ds = USHCN(reset=True)

INFO:tsdm.datasets.base._base:USHCN: START downloading dataset!
INFO:tsdm.datasets.base._base:USHCN/metadata: START downloading dataset!
INFO:tsdm.datasets.base._base:USHCN: Obtaining dataset from https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/data_format.txt
--2021-12-02 21:15:54--  https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/data_format.txt
Resolving cdiac.ess-dive.lbl.gov (cdiac.ess-dive.lbl.gov)... 128.55.206.26, 128.55.206.24
Connecting to cdiac.ess-dive.lbl.gov (cdiac.ess-dive.lbl.gov)|128.55.206.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘/home/rscholz/.tsdm/rawdata/USHCN/data_format.txt’

     0K .....                                                  1,46G=0s

2021-12-02 21:15:55 (1,46 GB/s) - ‘/home/rscholz/.tsdm/rawdata/USHCN/data_format.txt’ saved [6067]

FINISHED --2021-12-02 21:15:55--
Total wall clock time: 1,2s
Downloaded: 1 files, 5,9K in 0s (1,46 GB/s)
INFO:tsdm.datasets.base._base:USHCN: Finished importing dataset from https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/data_format.txt
INFO:tsdm.datasets.base._base:USHCN/metadata: DONE downloading dataset!
INFO:tsdm.datasets.base._base:USHCN/states: Rawdata files already exist, skipping.
INFO:tsdm.datasets.base._base:USHCN/stations: Rawdata files already exist, skipping.
INFO:tsdm.datasets.base._base:USHCN/stations_metadata: START downloading dataset!
INFO:tsdm.datasets.base._base:USHCN: Obtaining dataset from https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/station_file_format.txt
--2021-12-02 21:15:55--  https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/station_file_format.txt
Resolving cdiac.ess-dive.lbl.gov (cdiac.ess-dive.lbl.gov)... 128.55.206.26, 128.55.206.24
Connecting to cdiac.ess-dive.lbl.gov (cdiac.ess-dive.lbl.gov)|128.55.206.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘/home/rscholz/.tsdm/rawdata/USHCN/station_file_format.txt’

     0K ..                                                      948M=0s

2021-12-02 21:15:56 (948 MB/s) - ‘/home/rscholz/.tsdm/rawdata/USHCN/station_file_format.txt’ saved [2971]

FINISHED --2021-12-02 21:15:56--
Total wall clock time: 0,8s
Downloaded: 1 files, 2,9K in 0s (948 MB/s)
INFO:tsdm.datasets.base._base:USHCN: Finished importing dataset from https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/station_file_format.txt
INFO:tsdm.datasets.base._base:USHCN/stations_metadata: DONE downloading dataset!
INFO:tsdm.datasets.base._base:USHCN/us_daily: Rawdata files already exist, skipping.
INFO:tsdm.datasets.base._base:USHCN: DONE downloading dataset!
INFO:tsdm.datasets.base._base:USHCN/None already exists, skipping.
INFO:tsdm.datasets.base._base:USHCN: START loading dataset!
INFO:tsdm.datasets.base._base:USHCN/us_daily: START loading dataset!
INFO:tsdm.datasets.base._base:USHCN/us_daily: DONE loading dataset!
INFO:tsdm.datasets.base._base:USHCN/states: START loading dataset!
INFO:tsdm.datasets.base._base:USHCN/states: DONE loading dataset!
INFO:tsdm.datasets.base._base:USHCN/stations: START loading dataset!
INFO:tsdm.datasets.base._base:USHCN/stations: DONE loading dataset!
INFO:tsdm.datasets.base._base:USHCN: DONE loading dataset!

USHCN['us_daily', 'states', 'stations']

In [68]:
ds.download()

WARNING:tsdm.datasets.ushcn:Using Modin with Ray Backend
INFO:tsdm.datasets.base._base:USHCN/: Rawdata files already exist, skipping.

In [67]:
ds.us_daily

                   ELEMENT MFLAG QFLAG SFLAG  VALUE
time       COOP_ID
1849-05-01 381310     PRCP   NaN   NaN     F     50
1849-05-02 381310     PRCP   NaN   NaN     F      0
1849-05-03 381310     PRCP   NaN   NaN     F      0
1849-05-04 381310     PRCP   NaN   NaN     F      0
1849-05-05 381310     PRCP   NaN   NaN     F      0
...                    ...   ...   ...   ...    ...
2014-12-31 489905     PRCP   NaN   NaN     7      0
           489905     SNOW   NaN   NaN     7      0
           489905     SNWD   NaN   NaN     7      7
           489905     TMAX   NaN   NaN     7      1
           489905     TMIN   NaN   NaN     7    -18

[208575409 rows x 5 columns]

In [64]:
df = ds._load(key="stations")

,COOP_ID,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,COMPONENT_1,COMPONENT_2,COMPONENT_3,UTC_OFFSET
0,11084,31.0581,-87.054703,25.9,AL,BREWTON 3 SSE,<NA>,<NA>,<NA>,0 days 06:00:00
1,12813,30.5467,-87.880798,7.0,AL,FAIRHOPE 2 NE,<NA>,<NA>,<NA>,0 days 06:00:00
2,13160,32.834702,-88.134201,38.099998,AL,GAINESVILLE LOCK,11694,<NA>,<NA>,0 days 06:00:00
3,13511,32.701698,-87.580803,67.099998,AL,GREENSBORO,<NA>,<NA>,<NA>,0 days 06:00:00
4,13816,31.870001,-86.254204,132.0,AL,HIGHLAND HOME,<NA>,<NA>,<NA>,0 days 06:00:00
...,...,...,...,...,...,...,...,...,...,...
1213,488160,44.840599,-106.838303,1143.0,WY,SHERIDAN FLD STN,<NA>,<NA>,<NA>,0 days 07:00:00
1214,488995,42.080299,-104.223602,1249.099976,WY,TORRINGTON EXP FARM,<NA>,<NA>,<NA>,0 days 07:00:00
1215,489615,42.1106,-104.949203,1413.699951,WY,WHEATLAND 4 N,<NA>,<NA>,<NA>,0 days 07:00:00
1216,489770,44.010799,-107.968597,1237.5,WY,WORLAND,<NA>,<NA>,<NA>,0 days 07:00:00
1217,489905,44.9767,-110.696404,1898.900024,WY,YELLOWSTONE PK MAMMOTH,<NA>,<NA>,<NA>,0 days 07:00:00

In [46]:
df.COMPONENT_1.replace(to_replace="------", value=pandas.NA)

0         <NA>
1         <NA>
2       011694
3         <NA>
4         <NA>
         ...
1213      <NA>
1214      <NA>
1215      <NA>
1216      <NA>
1217      <NA>
Name: COMPONENT_1, Length: 1218, dtype: string

,COOP_ID,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,COMPONENT_1,COMPONENT_2,COMPONENT_3,UTC_OFFSET
0,011084,31.0581,-87.054703,25.9,AL,BREWTON 3 SSE,------,------,------,0 days 06:00:00
1,012813,30.5467,-87.880798,7.0,AL,FAIRHOPE 2 NE,------,------,------,0 days 06:00:00
2,013160,32.834702,-88.134201,38.099998,AL,GAINESVILLE LOCK,011694,------,------,0 days 06:00:00
3,013511,32.701698,-87.580803,67.099998,AL,GREENSBORO,------,------,------,0 days 06:00:00
4,013816,31.870001,-86.254204,132.0,AL,HIGHLAND HOME,------,------,------,0 days 06:00:00
...,...,...,...,...,...,...,...,...,...,...
1213,488160,44.840599,-106.838303,1143.0,WY,SHERIDAN FLD STN,------,------,------,0 days 07:00:00
1214,488995,42.080299,-104.223602,1249.099976,WY,TORRINGTON EXP FARM,------,------,------,0 days 07:00:00
1215,489615,42.1106,-104.949203,1413.699951,WY,WHEATLAND 4 N,------,------,------,0 days 07:00:00
1216,489770,44.010799,-107.968597,1237.5,WY,WORLAND,------,------,------,0 days 07:00:00
1217,489905,44.9767,-110.696404,1898.900024,WY,YELLOWSTONE PK MAMMOTH,------,------,------,0 days 07:00:00

In [3]:
ds.stations

,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,COMPONENT_1,COMPONENT_2,COMPONENT_3,UTC_OFFSET
COOP_ID,,,,,,,,,
NaN,31.0581,-87.054703,25.9,AL,BREWTON 3 SSE,NaN,NaN,NaN,0 days 06:00:00
NaN,30.5467,-87.880798,7.0,AL,FAIRHOPE 2 NE,NaN,NaN,NaN,0 days 06:00:00
NaN,32.834702,-88.134201,38.099998,AL,GAINESVILLE LOCK,NaN,NaN,NaN,0 days 06:00:00
NaN,32.701698,-87.580803,67.099998,AL,GREENSBORO,NaN,NaN,NaN,0 days 06:00:00
NaN,31.870001,-86.254204,132.0,AL,HIGHLAND HOME,NaN,NaN,NaN,0 days 06:00:00
...,...,...,...,...,...,...,...,...,...
NaN,44.840599,-106.838303,1143.0,WY,SHERIDAN FLD STN,NaN,NaN,NaN,0 days 07:00:00
NaN,42.080299,-104.223602,1249.099976,WY,TORRINGTON EXP FARM,NaN,NaN,NaN,0 days 07:00:00
NaN,42.1106,-104.949203,1413.699951,WY,WHEATLAND 4 N,NaN,NaN,NaN,0 days 07:00:00
NaN,44.010799,-107.968597,1237.5,WY,WORLAND,NaN,NaN,NaN,0 days 07:00:00
NaN,44.9767,-110.696404,1898.900024,WY,YELLOWSTONE PK MAMMOTH,NaN,NaN,NaN,0 days 07:00:00

In [20]:
ds.stations

,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,COMPONENT_1,COMPONENT_2,COMPONENT_3,UTC_OFFSET
COOP_ID,,,,,,,,,
011084,31.0581,-87.054703,25.9,NaN,BREWTON 3 SSE,NaN,NaN,NaN,0 days 06:00:00
012813,30.5467,-87.880798,7.0,NaN,FAIRHOPE 2 NE,NaN,NaN,NaN,0 days 06:00:00
013160,32.834702,-88.134201,38.099998,NaN,GAINESVILLE LOCK,NaN,NaN,NaN,0 days 06:00:00
013511,32.701698,-87.580803,67.099998,NaN,GREENSBORO,NaN,NaN,NaN,0 days 06:00:00
013816,31.870001,-86.254204,132.0,NaN,HIGHLAND HOME,NaN,NaN,NaN,0 days 06:00:00
...,...,...,...,...,...,...,...,...,...
488160,44.840599,-106.838303,1143.0,NaN,SHERIDAN FLD STN,NaN,NaN,NaN,0 days 07:00:00
488995,42.080299,-104.223602,1249.099976,NaN,TORRINGTON EXP FARM,NaN,NaN,NaN,0 days 07:00:00
489615,42.1106,-104.949203,1413.699951,NaN,WHEATLAND 4 N,NaN,NaN,NaN,0 days 07:00:00
489770,44.010799,-107.968597,1237.5,NaN,WORLAND,NaN,NaN,NaN,0 days 07:00:00
489905,44.9767,-110.696404,1898.900024,NaN,YELLOWSTONE PK MAMMOTH,NaN,NaN,NaN,0 days 07:00:00

In [3]:
import os
os.environ["MODIN_ENGINE"] = "dask"  # Modin will use Dask
from modin import pandas as pd
import ray
ray.init()

{'node_ip_address': '192.168.0.50',
 'raylet_ip_address': '192.168.0.50',
 'redis_address': '192.168.0.50:6379',
 'object_store_address': '/tmp/ray/session_2021-12-02_14-10-50_942531_21336/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2021-12-02_14-10-50_942531_21336/sockets/raylet',
 'webui_url': None,
 'session_dir': '/tmp/ray/session_2021-12-02_14-10-50_942531_21336',
 'metrics_export_port': 43151,
 'node_id': '32a39374286fa4aedad790530fa7f4eb1565ce32192cf7c5ba05afdc'}

In [4]:
ds.us_daily

          COOP_ID  YEAR  MONTH  DAY ELEMENT MFLAG QFLAG SFLAG  VALUE
0          381310  1849      5    1    PRCP   NaN   NaN     F     50
1          381310  1849      5    2    PRCP   NaN   NaN     F      0
2          381310  1849      5    3    PRCP   NaN   NaN     F      0
3          381310  1849      5    4    PRCP   NaN   NaN     F      0
4          381310  1849      5    5    PRCP   NaN   NaN     F      0
...           ...   ...    ...  ...     ...   ...   ...   ...    ...
208575404  489905  2014     12   31    PRCP   NaN   NaN     7      0
208575405  489905  2014     12   31    SNOW   NaN   NaN     7      0
208575406  489905  2014     12   31    SNWD   NaN   NaN     7      7
208575407  489905  2014     12   31    TMAX   NaN   NaN     7      1
208575408  489905  2014     12   31    TMIN   NaN   NaN     7    -18

[208575409 rows x 9 columns]

In [15]:
dir(dd)

['Aggregation',
 'DataFrame',
 'Index',
 'Series',
 '_Frame',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_accessor',
 '_compat',
 '_dtypes',
 'accessor',
 'assert_eq',
 'backends',
 'categorical',
 'compute',
 'concat',
 'core',
 'demo',
 'dispatch',
 'extensions',
 'from_array',
 'from_bcolz',
 'from_dask_array',
 'from_delayed',
 'from_pandas',
 'get_dummies',
 'groupby',
 'io',
 'isna',
 'map_partitions',
 'melt',
 'merge',
 'merge_asof',
 'methods',
 'multi',
 'numeric',
 'optimize',
 'pivot_table',
 'read_csv',
 'read_fwf',
 'read_hdf',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_sql_table',
 'read_table',
 'repartition',
 'reshape',
 'rolling',
 'shuffle',
 'to_bag',
 'to_csv',
 'to_datetime',
 'to_hdf',
 'to_json',
 'to_numeric',
 'to_orc',
 'to_parquet',
 'to_records',
 'to_sql',
 'to_timedelta',
 'utils']

In [29]:
import os
import dask.dataframe as dd
df = dd.from_pandas(ds.us_daily[["YEAR", "MONTH", "DAY"]], name="ts", npartitions=os.cpu_count())

Dask DataFrame Structure:
                  YEAR  MONTH    DAY
npartitions=24
0               UInt16  UInt8  UInt8
8690643            ...    ...    ...
...                ...    ...    ...
199884789          ...    ...    ...
208575408          ...    ...    ...
Dask Name: ts, 24 tasks

In [31]:
time = dd.to_datetime(df, errors="coerce").compute()

0           1849-05-01
1           1849-05-02
2           1849-05-03
3           1849-05-04
4           1849-05-05
               ...
208575404   2014-12-31
208575405   2014-12-31
208575406   2014-12-31
208575407   2014-12-31
208575408   2014-12-31
Length: 208575409, dtype: datetime64[ns]

In [43]:
ds.stations

,COOP_ID,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,COMPONENT_1,COMPONENT_2,COMPONENT_3,UTC_OFFSET
0,011084,31.0581,-87.054703,25.9,NaN,BREWTON 3 SSE,NaN,NaN,NaN,0 days 06:00:00
1,012813,30.5467,-87.880798,7.0,NaN,FAIRHOPE 2 NE,NaN,NaN,NaN,0 days 06:00:00
2,013160,32.834702,-88.134201,38.099998,NaN,GAINESVILLE LOCK,NaN,NaN,NaN,0 days 06:00:00
3,013511,32.701698,-87.580803,67.099998,NaN,GREENSBORO,NaN,NaN,NaN,0 days 06:00:00
4,013816,31.870001,-86.254204,132.0,NaN,HIGHLAND HOME,NaN,NaN,NaN,0 days 06:00:00
...,...,...,...,...,...,...,...,...,...,...
1213,488160,44.840599,-106.838303,1143.0,NaN,SHERIDAN FLD STN,NaN,NaN,NaN,0 days 07:00:00
1214,488995,42.080299,-104.223602,1249.099976,NaN,TORRINGTON EXP FARM,NaN,NaN,NaN,0 days 07:00:00
1215,489615,42.1106,-104.949203,1413.699951,NaN,WHEATLAND 4 N,NaN,NaN,NaN,0 days 07:00:00
1216,489770,44.010799,-107.968597,1237.5,NaN,WORLAND,NaN,NaN,NaN,0 days 07:00:00
1217,489905,44.9767,-110.696404,1898.900024,NaN,YELLOWSTONE PK MAMMOTH,NaN,NaN,NaN,0 days 07:00:00

In [34]:
ds.us_daily["time"] = time

In [41]:
ds.us_daily

,COOP_ID,YEAR,MONTH,DAY,ELEMENT,MFLAG,QFLAG,SFLAG,VALUE,time
0,381310,1849,5,1,PRCP,NaN,NaN,F,50,1849-05-01
1,381310,1849,5,2,PRCP,NaN,NaN,F,0,1849-05-02
2,381310,1849,5,3,PRCP,NaN,NaN,F,0,1849-05-03
3,381310,1849,5,4,PRCP,NaN,NaN,F,0,1849-05-04
4,381310,1849,5,5,PRCP,NaN,NaN,F,0,1849-05-05
...,...,...,...,...,...,...,...,...,...,...
208575404,489905,2014,12,31,PRCP,NaN,NaN,7,0,2014-12-31
208575405,489905,2014,12,31,SNOW,NaN,NaN,7,0,2014-12-31
208575406,489905,2014,12,31,SNWD,NaN,NaN,7,7,2014-12-31
208575407,489905,2014,12,31,TMAX,NaN,NaN,7,1,2014-12-31
208575408,489905,2014,12,31,TMIN,NaN,NaN,7,-18,2014-12-31

In [5]:
pd.to_datetime(ds.us_daily[["YEAR", "MONTH", "DAY"]].iloc[:100_000_000], errors='coerce', cache=False, infer_datetime_format=True)

KeyboardInterrupt:

In [8]:
ds.us_daily

          COOP_ID  YEAR  MONTH  DAY ELEMENT MFLAG QFLAG SFLAG  VALUE
0          381310  1849      5    1    PRCP   NaN   NaN     F     50
1          381310  1849      5    2    PRCP   NaN   NaN     F      0
2          381310  1849      5    3    PRCP   NaN   NaN     F      0
3          381310  1849      5    4    PRCP   NaN   NaN     F      0
4          381310  1849      5    5    PRCP   NaN   NaN     F      0
...           ...   ...    ...  ...     ...   ...   ...   ...    ...
208575404  489905  2014     12   31    PRCP   NaN   NaN     7      0
208575405  489905  2014     12   31    SNOW   NaN   NaN     7      0
208575406  489905  2014     12   31    SNWD   NaN   NaN     7      7
208575407  489905  2014     12   31    TMAX   NaN   NaN     7      1
208575408  489905  2014     12   31    TMIN   NaN   NaN     7    -18

[208575409 rows x 9 columns]