In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import pandas
from io import StringIO

table = """   
i j  A         B         C
0 0  2.400417  0.698638  1.231540
  1 -0.023154 -2.110450  0.774964
  2 -1.282392 -0.062794  1.471655
1 0 -1.081853  0.261876 -1.771075
  1 -2.013747 -0.377957 -0.393802
  2  1.711172 -0.552468  1.018727
2 0  0.155821 -0.222691  0.496586
  1  0.563638 -0.756709  1.050212
  2 -1.446159 -0.891549  0.256695
"""

df = pandas.read_fwf(StringIO(table), dtype={"i": "UInt8", "j": "UInt8"})
df = df.ffill().set_index(["i", "j"])

i, j = df.index.levels
idx = pandas.IndexSlice
perm = [2, 0, 1]
df.loc[i[perm]]

            A         B         C
i j
2 0  0.155821 -0.222691  0.496586
  1  0.563638 -0.756709  1.050212
  2 -1.446159 -0.891549  0.256695
0 0  2.400417  0.698638  1.231540
  1 -0.023154 -2.110450  0.774964
  2 -1.282392 -0.062794  1.471655
1 0 -1.081853  0.261876 -1.771075
  1 -2.013747 -0.377957 -0.393802
  2  1.711172 -0.552468  1.018727

# Shuffling first index

In [3]:
df.loc[idx[i[perm], :], :]

            A         B         C
i j
2 0  0.155821 -0.222691  0.496586
  1  0.563638 -0.756709  1.050212
  2 -1.446159 -0.891549  0.256695
0 0  2.400417  0.698638  1.231540
  1 -0.023154 -2.110450  0.774964
  2 -1.282392 -0.062794  1.471655
1 0 -1.081853  0.261876 -1.771075
  1 -2.013747 -0.377957 -0.393802
  2  1.711172 -0.552468  1.018727

In [4]:
df.loc[idx[i[perm], j], :]

            A         B         C
i j
2 0  0.155821 -0.222691  0.496586
  1  0.563638 -0.756709  1.050212
  2 -1.446159 -0.891549  0.256695
0 0  2.400417  0.698638  1.231540
  1 -0.023154 -2.110450  0.774964
  2 -1.282392 -0.062794  1.471655
1 0 -1.081853  0.261876 -1.771075
  1 -2.013747 -0.377957 -0.393802
  2  1.711172 -0.552468  1.018727

# Shuffling second index

In [5]:
df.loc[idx[i, j[perm]], :]

            A         B         C
i j
0 2 -1.282392 -0.062794  1.471655
  0  2.400417  0.698638  1.231540
  1 -0.023154 -2.110450  0.774964
1 2  1.711172 -0.552468  1.018727
  0 -1.081853  0.261876 -1.771075
  1 -2.013747 -0.377957 -0.393802
2 2 -1.446159 -0.891549  0.256695
  0  0.155821 -0.222691  0.496586
  1  0.563638 -0.756709  1.050212

In [6]:
df.loc[idx[:, j[perm]], :]

            A         B         C
i j
0 2 -1.282392 -0.062794  1.471655
1 2  1.711172 -0.552468  1.018727
2 2 -1.446159 -0.891549  0.256695
0 0  2.400417  0.698638  1.231540
1 0 -1.081853  0.261876 -1.771075
2 0  0.155821 -0.222691  0.496586
0 1 -0.023154 -2.110450  0.774964
1 1 -2.013747 -0.377957 -0.393802
2 1  0.563638 -0.756709  1.050212

# Shuffling both

In [7]:
df.loc[idx[i[perm], j[perm]], :]

            A         B         C
i j
2 2 -1.446159 -0.891549  0.256695
  0  0.155821 -0.222691  0.496586
  1  0.563638 -0.756709  1.050212
0 2 -1.282392 -0.062794  1.471655
  0  2.400417  0.698638  1.231540
  1 -0.023154 -2.110450  0.774964
1 2  1.711172 -0.552468  1.018727
  0 -1.081853  0.261876 -1.771075
  1 -2.013747 -0.377957 -0.393802