# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
logging.basicConfig(level=logging.INFO)

In [2]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, floatmode='fixed', suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7FBA842B63C0

In [3]:
from tsdm.tasks import KIWI_FINAL_PRODUCT, KIWI_RUNS_TASK

INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:tsdm.config._config:Available Models: {'M-RNN', 'NCDE', 'ODE-RNN', 'GRU-ODE-Bayes', 'N-BEATS', 'IP-Net', 'mTAN', 'Informer', 'NODE', 'SET-TS', 'TFT', 'TPA', 'Latent-ODE', 'BRITS'}
INFO:tsdm.config._config:Available Datasets: {'UWAVE', 'Air Quality Multi-Site', 'Household Consumption', 'Physionet 2012', 'Electricity', 'M5', 'M3', 'MuJoCo', 'Air Quality', 'Character Trajectories', 'Traffic', 'tourism1', 'Human Activity', 'USHCN', 'Physionet 2019', 'tourism2', 'M4'}
INFO:tsdm.config._config:Initializing folder structure
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/datasets
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/models
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/logs
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/rawdata
INFO:tsdm.config._config:Created folder structure in /home/rscholz/.tsdm

In [ ]:
task = KIWI_FINAL_PRODUCT()

INFO:tsdm.datasets.base._base:KIWI_RUNS: START cleaning dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/units already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE cleaning dataset
INFO:tsdm.datasets.base._base:KIWI_RUNS: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: START loading dataset!

In [5]:
type(task.splits[0, "train"])

tuple

In [6]:
task.final_vec

run_id  experiment_id  measurement_time
439     15325          2020-12-09 21:53:59    200472.921875
        15326          2020-12-09 21:53:59    453289.593750
        15327          2020-12-09 21:53:59    193914.578125
        15328          2020-12-09 21:53:59    326772.906250
        15329          2020-12-09 21:53:59    211447.921875
                                                  ...
510     16867          2021-10-26 22:20:42     26900.000000
        16868          2021-10-26 22:20:42    193025.000000
        16869          2021-10-26 22:20:42     14625.000000
        16870          2021-10-26 22:20:42    268450.000000
        16871          2021-10-26 22:20:42     28800.000000
Name: Fluo_GFP, Length: 168, dtype: float64

In [7]:
task.split_idx

split                     0      1      2      3      4
run_id experiment_id
439    15325          train  train  train   test   test
       15326          train  train  train  train  train
       15327          train   test  train  train   test
       15328          train  train  train  train  train
       15329          train  train  train  train  train
...                     ...    ...    ...    ...    ...
510    16867          train  train  train  train  train
       16868          train  train  train   test  train
       16869          train  train  train   test  train
       16870          train  train  train   test  train
       16871          train  train  train  train  train

[168 rows x 5 columns]

In [8]:
from tsdm.util.decorators import IterItems

In [29]:
splits = task.split_idx_sparse

split                     0            1             2            3         \
partition              test train   test  train   test train   test  train
run_id experiment_id
439    15325          False  True  False   True  False  True   True  False
       15326          False  True  False   True  False  True  False   True
       15327          False  True   True  False  False  True  False   True
       15328          False  True  False   True  False  True  False   True
       15329          False  True  False   True  False  True  False   True
...                     ...   ...    ...    ...    ...   ...    ...    ...
510    16867          False  True  False   True  False  True  False   True
       16868          False  True  False   True  False  True   True  False
       16869          False  True  False   True  False  True   True  False
       16870          False  True  False   True  False  True   True  False
       16871          False  True  False   True  False  True  False   True

split                     4
partition              test  train
run_id experiment_id
439    15325           True  False
       15326          False   True
       15327           True  False
       15328          False   True
       15329          False   True
...                     ...    ...
510    16867          False   True
       16868          False   True
       16869          False   True
       16870          False   True
       16871          False   True

[168 rows x 10 columns]

In [37]:
import pandas
S = pandas.Series(task.DS.data);

[variable             Flow_Air  StirringSpeed  Temperature  Acetate  Base  \
 measurement_time
 2020-12-09 09:10:09       0.0            0.0    36.389999      NaN   NaN
 2020-12-09 09:10:19       0.0            0.0          NaN      NaN   NaN
 2020-12-09 09:10:24       0.0          100.0          NaN      NaN   NaN
 2020-12-09 09:10:25       0.0          100.0    36.130001      NaN   NaN
 2020-12-09 09:10:34       0.0          100.0          NaN      NaN   NaN
 ...                       ...            ...          ...      ...   ...
 2020-12-09 23:31:40      10.0            0.0          NaN      NaN   NaN
 2020-12-09 23:31:42       0.0            0.0          NaN      NaN   NaN
 2020-12-09 23:31:51       0.0            0.0          NaN      NaN   NaN
 2020-12-09 23:32:02       0.0            0.0          NaN      NaN   NaN
 2020-12-09 23:32:05       0.0            0.0          NaN      NaN   NaN

 variable             Cumulated_feed_volume_glucose  \
 measurement_time
 2020-12-09 09:10:09                            0.0
 2020-12-09 09:10:19                            0.0
 2020-12-09 09:10:24                            0.0
 2020-12-09 09:10:25                            0.0
 2020-12-09 09:10:34                            0.0
 ...                                            ...
 2020-12-09 23:31:40                         2431.0
 2020-12-09 23:31:42                         2431.0
 2020-12-09 23:31:51                         2431.0
 2020-12-09 23:32:02                         2431.0
 2020-12-09 23:32:05                         2431.0

 variable             Cumulated_feed_volume_medium        DOT  Glucose  OD600  \
 measurement_time
 2020-12-09 09:10:09                      0.000000        NaN      NaN    NaN
 2020-12-09 09:10:19                      0.000000   0.000000      NaN    NaN
 2020-12-09 09:10:24                      0.000000        NaN      NaN    NaN
 2020-12-09 09:10:25                      0.000000        NaN      NaN    NaN
 2020-12-09 09:10:34                      0.000000   0.000000      NaN    NaN
 ...                                           ...        ...      ...    ...
 2020-12-09 23:31:40                   2188.030029  52.720001      NaN    NaN
 2020-12-09 23:31:42                   2188.030029        NaN      NaN    NaN
 2020-12-09 23:31:51                   2188.030029  52.950001      NaN    NaN
 2020-12-09 23:32:02                   2188.030029  53.240002      NaN    NaN
 2020-12-09 23:32:05                   2188.030029        NaN      NaN    NaN

 variable             Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
 measurement_time
 2020-12-09 09:10:09           0.0   NaN       NaN                  0.00
 2020-12-09 09:10:19           0.0  7.27       NaN                  0.00
 2020-12-09 09:10:24           0.0   NaN       NaN                  0.00
 2020-12-09 09:10:25           0.0   NaN       NaN                  0.00
 2020-12-09 09:10:34           0.0  7.28       NaN                  0.00
 ...                           ...   ...       ...                   ...
 2020-12-09 23:31:40        3600.0  6.44       NaN                  0.05
 2020-12-09 23:31:42        3600.0   NaN       NaN                  0.05
 2020-12-09 23:31:51        3600.0  6.44       NaN                  0.05
 2020-12-09 23:32:02        3600.0  6.44       NaN                  0.05
 2020-12-09 23:32:05        3600.0   NaN       NaN                  0.05

 variable             Volume
 measurement_time
 2020-12-09 09:10:09     NaN
 2020-12-09 09:10:19     NaN
 2020-12-09 09:10:24     NaN
 2020-12-09 09:10:25     NaN
 2020-12-09 09:10:34     NaN
 ...                     ...
 2020-12-09 23:31:40     NaN
 2020-12-09 23:31:42     NaN
 2020-12-09 23:31:51     NaN
 2020-12-09 23:32:02     NaN
 2020-12-09 23:32:05     NaN

 [1529 rows x 15 columns],
 (Feed_concentration_glc                    400
  OD_Dilution                              50.0
  bioreactor_id                             495
  color                               #FF1B9E77
  container_number                            9
  end_time                  2020-12-09 23:34:23
  organism_id                                41
  pH_correction_factor                      0.5
  profile_id                              10068
  profile_name                               A2
  run_name                      20201209_01_MHE
  start_time                2020-12-09 09:09:58
  Name: (439, 15325), dtype: object,
  measurement_time
  2020-12-09 21:53:59    200472.921875
  Name: Fluo_GFP, dtype: float64)]

In [22]:
task.DS[439, 15325]

TimeSeriesDataset[DataFrame[1529, 15], metadata=(Series[12], Series[1])]

In [10]:
IterItems(task.DS)

IterItems@MappingDataset(
  (439, 15325): ((439, 15325), TimeSeriesDataset[DataFrame[1529, 15], metadata=(Series[12], Series[1])])
  (439, 15326): ((439, 15326), TimeSeriesDataset[DataFrame[1521, 15], metadata=(Series[12], Series[1])])
  (439, 15327): ((439, 15327), TimeSeriesDataset[DataFrame[1546, 15], metadata=(Series[12], Series[1])])
  ...
  (510, 16869): ((510, 16869), TimeSeriesDataset[DataFrame[1502, 15], metadata=(Series[12], Series[1])])
  (510, 16870): ((510, 16870), TimeSeriesDataset[DataFrame[1519, 15], metadata=(Series[12], Series[1])])
  (510, 16871): ((510, 16871), TimeSeriesDataset[DataFrame[1544, 15], metadata=(Series[12], Series[1])])
)

In [11]:
task.DS[439, 15325]

TimeSeriesDataset[DataFrame[1529, 15], metadata=(Series[12], Series[1])]

In [12]:
dloader = task.batchloaders[0, "train"]

In [13]:
from pandas import Timestamp
key, (a,b) = ((510, 16864), (Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 09:55:08')))

In [14]:
key, slc = next(iter(dloader.sampler))

In [15]:
# dloader.dataset[key][Timestamp('2021-10-26 09:50:08'):Timestamp('2021-10-26 09:55:08')]

In [21]:
dloader.dataset

IterItems@MappingDataset(
  (439, 15325): ((439, 15325), TimeSeriesDataset[DataFrame[1529, 15], metadata=(Series[12], Series[1])])
  (439, 15326): ((439, 15326), TimeSeriesDataset[DataFrame[1521, 15], metadata=(Series[12], Series[1])])
  (439, 15327): ((439, 15327), TimeSeriesDataset[DataFrame[1546, 15], metadata=(Series[12], Series[1])])
  ...
  (510, 16869): ((510, 16869), TimeSeriesDataset[DataFrame[1502, 15], metadata=(Series[12], Series[1])])
  (510, 16870): ((510, 16870), TimeSeriesDataset[DataFrame[1519, 15], metadata=(Series[12], Series[1])])
  (510, 16871): ((510, 16871), TimeSeriesDataset[DataFrame[1544, 15], metadata=(Series[12], Series[1])])
)

In [17]:
batch = next(iter(dloader))

Batch(
  index     : [[[510, 16848], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 11:50:08'), None)], [[468, 15996], slice(Timestamp('2021-04-07 10:21:09'), Timestamp('2021-04-07 13:06:09'), None)], [[475, 16139], slice(Timestamp('2021-05-05 10:03:44'), Timestamp('2021-05-05 10:48:44'), None)], [[484, 16330], slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 15:02:30'), None)], [[449, 15649], slice(Timestamp('2021-02-10 09:55:55'), Timestamp('2021-02-10 12:10:55'), None)], [[484, 16337], slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 16:47:30'), None)], [[439, 15334], slice(Timestamp('2020-12-09 09:46:09'), Timestamp('2020-12-09 10:01:09'), None)], [[510, 16870], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 17:25:08'), None)], [[474, 16128], slice(Timestamp('2021-04-20 10:03:55'), Timestamp('2021-04-20 13:23:55'), None)], [[510, 16853], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 10:35:08'), None)], [[439, 15328], slice(Timestamp('2020-12-09 09:46:09'), Timestamp('2020-12-09 15:16:09'), None)], [[474, 16110], slice(Timestamp('2021-04-20 10:03:55'), Timestamp('2021-04-20 12:13:55'), None)], [[510, 16870], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 14:40:08'), None)], [[474, 16123], slice(Timestamp('2021-04-20 10:03:55'), Timestamp('2021-04-20 15:43:55'), None)], [[468, 16007], slice(Timestamp('2021-04-07 10:21:09'), Timestamp('2021-04-07 15:26:09'), None)], [[474, 16122], slice(Timestamp('2021-04-20 10:03:55'), Timestamp('2021-04-20 13:33:55'), None)], [[510, 16866], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 19:25:08'), None)], [[484, 16335], slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 10:52:30'), None)], [[510, 16865], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 18:50:08'), None)], [[484, 16353], slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 16:22:30'), None)], [[439, 15336], slice(Timestamp('2020-12-09 09:46:09'), Timestamp('2020-12-09 09:51:09'), None)], [[484, 16330], slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 15:57:30'), None)], [[449, 15662], slice(Timestamp('2021-02-10 09:55:55'), Timestamp('2021-02-10 15:50:55'), None)], [[439, 15337], slice(Timestamp('2020-12-09 09:46:09'), Timestamp('2020-12-09 13:26:09'), None)], [[510, 16871], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 20:40:08'), None)], [[484, 16353], slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 11:32:30'), None)], [[439, 15330], slice(Timestamp('2020-12-09 09:46:09'), Timestamp('2020-12-09 14:16:09'), None)], [[510, 16857], slice(Timestamp('2021-10-26 09:50:08'), Timestamp('2021-10-26 11:50:08'), None)], [[475, 16150], slice(Timestamp('2021-05-05 10:03:44'), Timestamp('2021-05-05 14:08:44'), None)], [[468, 15996], slice(Timestamp('2021-04-07 10:21:09'), Timestamp('2021-04-07 13:51:09'), None)], [[475, 16150], slice(Timestamp('2021-05-05 10:03:44'), Timestamp('2021-05-05 12:18:44'), None)], [[468, 16004], slice(Timestamp('2021-04-07 10:21:09'), Timestamp('2021-04-07 15:51:09'), None)]]
  timeseries: [DataFrame[214, 15], DataFrame[255, 15], DataFrame[77, 15], DataFrame[1165, 15], DataFrame[212, 15], DataFrame[1557, 15], DataFrame[25, 15], DataFrame[847, 15], DataFrame[318, 15], DataFrame[82, 15], DataFrame[554, 15], DataFrame[205, 15], DataFrame[525, 15], DataFrame[563, 15], DataFrame[487, 15], DataFrame[334, 15], DataFrame[1049, 15], DataFrame[271, 15], DataFrame[973, 15], DataFrame[1472, 15], DataFrame[9, 15], DataFrame[1364, 15], DataFrame[549, 15], DataFrame[369, 15], DataFrame[1241, 15], DataFrame[414, 15], DataFrame[449, 15], DataFrame[218, 15], DataFrame[405, 15], DataFrame[333, 15], DataFrame[223, 15], DataFrame[528, 15]]
  metadata  : [Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12], Series[12]]
  targets   : [Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1], Series[1]]
)

In [18]:
batch[0][0][-1].start

Timestamp('2021-10-26 09:50:08')

In [19]:
batch[0][0][-1].indices

In [20]:
ts, (md, target) = batch[0]

ValueError: too many values to unpack (expected 2)

In [ ]:
target

In [ ]:
len(dloader.dataset)

In [ ]:
isinstance(KIWI_RUNS_TASK(), type)