# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
logging.basicConfig(level=logging.DEBUG)

In [2]:
from tsdm.tasks import KIWI_RUNS_TASK
from tsdm.encoders.modular import MinMaxScaler
import numpy as np

INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:tsdm.config._config:Available Models: {'TFT', 'SET-TS', 'NODE', 'GRU-ODE-Bayes', 'ODE-RNN', 'BRITS', 'TPA', 'M-RNN', 'Informer', 'Latent-ODE', 'mTAN', 'N-BEATS', 'IP-Net', 'NCDE'}
INFO:tsdm.config._config:Available Datasets: {'Electricity', 'Household Consumption', 'M4', 'MuJoCo', 'M5', 'Traffic', 'Air Quality Multi-Site', 'UWAVE', 'USHCN', 'tourism1', 'Physionet 2019', 'Air Quality', 'tourism2', 'M3', 'Human Activity', 'Physionet 2012', 'Character Trajectories'}
INFO:tsdm.config._config:Initializing folder structure
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/datasets
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/models
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/logs
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/rawdata
INFO:tsdm.config._config:Created folder structure in /home/rscholz/.tsdm
WARNING:tsdm.datasets.ushcn:Using Modin with Ray Backend
DEBUG:matplotlib.pyplot:Loaded backend pgf version unknown.

In [9]:
task = KIWI_RUNS_TASK()

INFO:tsdm.datasets.base._base:KIWI_RUNS: START cleaning dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/units already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE cleaning dataset
INFO:tsdm.datasets.base._base:KIWI_RUNS: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE loading dataset!

In [25]:
task.dataset.timeseries.index.to_frame(index=False)

        run_id  experiment_id    measurement_time
0          355          11722 2019-04-09 18:32:12
1          355          11722 2019-04-09 18:32:18
2          355          11722 2019-04-09 18:32:19
3          355          11722 2019-04-09 18:32:21
4          355          11722 2019-04-09 18:32:22
...        ...            ...                 ...
440907     510          16871 2021-10-26 22:41:26
440908     510          16871 2021-10-26 22:42:11
440909     510          16871 2021-10-26 22:42:20
440910     510          16871 2021-10-26 22:43:22
440911     510          16871 2021-10-26 22:43:31

[440912 rows x 3 columns]

In [17]:
task.batchloaders

LazyDict(
  (0, 'train'): <LazyFunction: get_dataloader>
  (0, 'test') : <LazyFunction: get_dataloader>
  (1, 'train'): <LazyFunction: get_dataloader>
  (1, 'test') : <LazyFunction: get_dataloader>
  (2, 'train'): <LazyFunction: get_dataloader>
  (2, 'test') : <LazyFunction: get_dataloader>
  (3, 'train'): <LazyFunction: get_dataloader>
  (3, 'test') : <LazyFunction: get_dataloader>
  (4, 'train'): <LazyFunction: get_dataloader>
  (4, 'test') : <LazyFunction: get_dataloader>
)

In [21]:
dataloader.preprocessor[-1]

,,col,encoder
section,partition,,
index,0,<NA>,"(MinMaxScaler, DateTimeEncoder)"
columns,0,"[Flow_Air, StirringSpeed, Temperature, Acetate...","(Standardizer([-1]), FloatEncoder())"

In [6]:
dataloader = task.batchloaders[(0, "train")]
dataloader.preprocessor[-1]

DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([       0.0,       10.0,       15.0,       16.0,       25.0,
                    30.0,       39.0,       43.0,       44.0,       53.0,
              ...
              27782981.0, 27782990.0, 27783051.0, 27783060.0, 27783075.0,
              27783077.0, 27783122.0, 27783131.0, 27783193.0, 27783202.0],
             dtype='float64', name='measurement_time', length=260293)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([       0.0,       10.0,       15.0,       16.0,       25.0,
                    30.0,       39.0,       43.0,       44.0,       53.0,
              ...
              27782981.0, 27782990.0, 27783051.0, 27783060.0, 27783075.0,
              27783077.0, 27783122.0, 27783131.0, 27783193.0, 27783202.0],
             dtype='float64', name='measurement_time', length=260293)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1529)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1521)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1546)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1541)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1517)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1528)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1538)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1531)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1528)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1556)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1549)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1525)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1543)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1549)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1537)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1532)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1552)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1550)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1534)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1560)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1558)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1165)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1162)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1169)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1160)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1164)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1161)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1164)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1161)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1177)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1172)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1177)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1176)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1176)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1154)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1154)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1154)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1159)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1175)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1175)

DataFrameEncoder(
                                                                                                                                                                                                                 col                                                                                                                                              encoder
section partition
index   0                                                                                                                                                                                                       <NA>  (<tsdm.encoders.modular._modular.MinMaxScaler object at 0x7fe3041143d0>, <tsdm.encoders.modular._modular.DateTimeEncoder object at 0x7fe304114430>)
columns 0          [Flow_Air, StirringSpeed, Temperature, Acetate, Base, Cumulated_feed_volume_glucose, Cumulated_feed_volume_medium, DOT, Glucose, OD600, Probe_Volume, pH, Fluo_GFP, InducerConcentration, Volume]                                                                                                                 (Standardizer([-1]), FloatEncoder())
)

In [5]:
dataloader = task.batchloaders[(0, "train")]
batch = next(iter(dataloader))

DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([       0.0,       10.0,       15.0,       16.0,       25.0,
                    30.0,       39.0,       43.0,       44.0,       53.0,
              ...
              27782981.0, 27782990.0, 27783051.0, 27783060.0, 27783075.0,
              27783077.0, 27783122.0, 27783131.0, 27783193.0, 27783202.0],
             dtype='float64', name='measurement_time', length=260293)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([       0.0,       10.0,       15.0,       16.0,       25.0,
                    30.0,       39.0,       43.0,       44.0,       53.0,
              ...
              27782981.0, 27782990.0, 27783051.0, 27783060.0, 27783075.0,
              27783077.0, 27783122.0, 27783131.0, 27783193.0, 27783202.0],
             dtype='float64', name='measurement_time', length=260293)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1529)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1521)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1546)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1541)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1517)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1528)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1538)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1531)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1528)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1556)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1549)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1525)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1543)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1549)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1537)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1532)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1552)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1550)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1534)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1560)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([    0.0,    10.0,    15.0,    16.0,    25.0,    30.0,    39.0,
                 43.0,    44.0,    53.0,
              ...
              51478.0, 51540.0, 51549.0, 51620.0, 51681.0, 51691.0, 51693.0,
              51702.0, 51713.0, 51716.0],
             dtype='float64', name='measurement_time', length=1558)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1165)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1162)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1169)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1160)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1164)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1161)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1164)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1161)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1177)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1172)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1177)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1176)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1176)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1154)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1154)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1154)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1153)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1159)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1175)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1171)
DEBUG:tsdm.encoders.modular._modular:Encoding data Float64Index([3029096.0, 3029131.0, 3029191.0, 3029258.0, 3029318.0, 3029379.0,
              3029439.0, 3029482.0, 3029486.0, 3029488.0,
              ...
              3076846.0, 3076865.0, 3076926.0, 3076945.0, 3076986.0, 3077026.0,
              3077087.0, 3077106.0, 3077108.0, 3077127.0],
             dtype='float64', name='measurement_time', length=1175)

[tensor([[0.1100, 0.1100, 0.1100,  ..., 0.1102, 0.1102, 0.1102],
         [0.0013, 0.0013, 0.0013,  ..., 0.0014, 0.0014, 0.0014],
         [0.1091, 0.1091, 0.1091,  ..., 0.1092, 0.1092, 0.1092],
         ...,
         [0.1093, 0.1093, 0.1093,  ..., 0.1095, 0.1095, 0.1095],
         [0.7190, 0.7190, 0.7190,  ..., 0.7190, 0.7190, 0.7190],
         [0.4106, 0.4106, 0.4106,  ..., 0.4107, 0.4107, 0.4107]],
        device='cuda:0'),
 tensor([[[-0.3161, -0.6185, -0.0414,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185, -0.1147,  ...,     nan, -0.4440,     nan],
          ...,
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185, -0.5179,  ...,     nan, -0.4440,     nan]],

         [[ 2.5219, -0.6185,     nan,  ...,     nan, -0.3678,     nan],
          [ 2.5219, -0.6185, -0.5912,  ...,     nan, -0.3678,     nan],
          [ 2.5219, -0.6185,     nan,  ...,     nan, -0.3678,     nan],
          ...,
          [ 2.5219, -0.6185, -0.6096,  ...,     nan, -0.3678,     nan],
          [ 2.5219, -0.6185,     nan,  ...,     nan, -0.3678,     nan],
          [ 2.5219, -0.6185,     nan,  ...,     nan, -0.3678,     nan]],

         [[-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185, -0.1880,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          ...,
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185, -0.7012,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan]],

         ...,

         [[-0.3161, -0.6185, -0.6646,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185, -0.6096,  ...,     nan, -0.4440,     nan],
          ...,
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185, -0.5546,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan]],

         [[-0.3161,  1.6171,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161,  1.6171,  0.0502,  ...,     nan, -0.4440,     nan],
          [-0.3161,  1.6171,     nan,  ...,     nan, -0.4440,     nan],
          ...,
          [-0.3161,  1.6171,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161,  1.6171,  0.2702,  ...,     nan, -0.4440,     nan],
          [-0.3161,  1.6171,     nan,  ...,     nan, -0.4440,     nan]],

         [[-3.1541,  1.6171,     nan,  ...,     nan, -0.4440,     nan],
          [-3.1541,  1.6171,     nan,  ...,     nan, -0.4440,     nan],
          [-3.1541,  1.6171,  1.9198,  ...,     nan, -0.4440,     nan],
          ...,
          [-0.3161, -0.6185,  0.5818,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,     nan,  ...,     nan, -0.4440,     nan],
          [-0.3161, -0.6185,  0.5635,  ...,     nan, -0.4440,     nan]]],
        device='cuda:0')]

In [9]:
dataloader.preprocessor.decode(batch)

DEBUG:tsdm.encoders.modular._modular:Decoding data [[0.11004034 0.11004106 0.11004326 ... 0.11020627 0.11020918 0.11021138]
 [0.00127473 0.00127692 0.00127728 ... 0.00141701 0.00141737 0.00141917]
 [0.10907169 0.10907389 0.10907458 ... 0.10924385 0.10924504 0.10924572]
 ...
 [0.10926826 0.10926894 0.10927117 ... 0.10946608 0.10946827 0.10946899]
 [0.71897644 0.7189773  0.71897763 ... 0.71903914 0.7190399  0.7190403 ]
 [0.41056442 0.4105646  0.41056523 ... 0.41068232 0.41068268 0.41068488]]
DEBUG:tsdm.encoders.modular._modular:Decoding <class 'numpy.ndarray'>

s

TypeError: arg must be a string, timedelta, list, tuple, 1-d array, or Series