# Title

In [85]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [86]:
import pickle
import pandas
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [88]:
from cross_validate_kiwi_runs import ReplicateBasedSplitter, create_replicate_dict

with open("kiwi_experiments_and_run_355.pk", "rb") as f:
    experiments_per_run = pickle.load(f)

col_run_to_exp = dict(create_replicate_dict(experiments_per_run))

splitter = ReplicateBasedSplitter()

stefan_splits = []

for train_keys, test_keys in splitter.split(col_run_to_exp):
    stefan_splits.append( (train_keys, test_keys) )
stefan_splits

[([(474, 16111),
   (474, 16119),
   (474, 16127),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (474, 16109),
   (474, 16117),
   (474, 16125),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (484, 16335),
   (484, 16343),
   (484, 16351),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (474, 16112),
   (474, 16120),
   (474, 16128)],
  [(449, 15647),
   (449, 15655),
   (449, 15663),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (484, 16336),
   (484, 16344),
   (484, 16352),
   (484, 16330),
   (484, 16338),
   (484, 16346)]),
 ([(468, 15997),
   (468, 16005),
   (468, 16013),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (449, 15647),
   (449, 15655),
   (449, 15663),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (474, 16112),
   (474, 16120),
   (474, 16128),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (474, 16109),
   (474, 16117),
   (474, 16125),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (484, 16336),
   (484, 16344),
   (484, 16352),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (355, 11722),
   (355, 11730),
   (355, 11738)],
  [(474, 16113),
   (474, 16121),
   (474, 16129),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (484, 16335),
   (484, 16343),
   (484, 16351),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540)]),
 ([(474, 16109),
   (474, 16117),
   (474, 16125),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (484, 16336),
   (484, 16344),
   (484, 16352),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (474, 16112),
   (474, 16120),
   (474, 16128),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (449, 15647),
   (449, 15655),
   (449, 15663),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (484, 16335),
   (484, 16343),
   (484, 16351),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (482, 16284),
   (482, 16292),
   (482, 16300)],
  [(468, 15999),
   (468, 16007),
   (468, 16015),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (474, 16106),
   (474, 16114),
   (474, 16122)]),
 ([(449, 15643),
   (449, 15651),
   (449, 15659),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (474, 16112),
   (474, 16120),
   (474, 16128),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (449, 15647),
   (449, 15655),
   (449, 15663),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (474, 16109),
   (474, 16117),
   (474, 16125),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (484, 16336),
   (484, 16344),
   (484, 16352),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (482, 16289),
   (482, 16297),
   (482, 16305)],
  [(439, 15330),
   (439, 15338),
   (439, 15346),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (484, 16335),
   (484, 16343),
   (484, 16351),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (475, 16136),
   (475, 16144),
   (475, 16152)]),
 ([(484, 16331),
   (484, 16339),
   (484, 16347),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (474, 16109),
   (474, 16117),
   (474, 16125),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (474, 16112),
   (474, 16120),
   (474, 16128),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (355, 11724),
   (355, 11732),
   (355, 11740)],
  [(484, 16335),
   (484, 16343),
   (484, 16351),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (482, 16285),
   (482, 16293),

In [89]:
from tsdm.datasets import KIWI_RUNS

KIWI_RUNS.clean()

In [90]:
metadata = KIWI_RUNS.metadata
timeseries = KIWI_RUNS.dataset

                                          Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12      <NA>           <NA>
                     2019-04-09 18:32:18      <NA>           <NA>
                     2019-04-09 18:32:19      <NA>           <NA>
                     2019-04-09 18:32:21  4.997213           <NA>
                     2019-04-09 18:32:22      <NA>           <NA>
...                                            ...            ...
484    16353         2021-07-28 22:33:26      <NA>           <NA>
                     2021-07-28 22:33:28      <NA>         2400.0
                     2021-07-28 22:33:38      <NA>           <NA>
                     2021-07-28 22:33:42       0.0           <NA>
                     2021-07-28 22:33:43      <NA>         2400.0

                                          Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    36.990002     <NA>  <NA>
                     2019-04-09 18:32:18         <NA>     <NA>  <NA>
                     2019-04-09 18:32:19         <NA>     <NA>  <NA>
                     2019-04-09 18:32:21         <NA>     <NA>  <NA>
                     2019-04-09 18:32:22        36.98     <NA>  <NA>
...                                               ...      ...   ...
484    16353         2021-07-28 22:33:26         <NA>     <NA>  <NA>
                     2021-07-28 22:33:28        37.57     <NA>  <NA>
                     2021-07-28 22:33:38         <NA>     <NA>  <NA>
                     2021-07-28 22:33:42         <NA>     <NA>  <NA>
                     2021-07-28 22:33:43         <NA>     <NA>  <NA>

                                          Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                           <NA>
                     2019-04-09 18:32:18                           <NA>
                     2019-04-09 18:32:19                           <NA>
                     2019-04-09 18:32:21                           <NA>
                     2019-04-09 18:32:22                           <NA>
...                                                                 ...
484    16353         2021-07-28 22:33:26                           <NA>
                     2021-07-28 22:33:28                           <NA>
                     2021-07-28 22:33:38                           <NA>
                     2021-07-28 22:33:42                           <NA>
                     2021-07-28 22:33:43                           <NA>

                                          Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                          <NA>
                     2019-04-09 18:32:18                          <NA>
                     2019-04-09 18:32:19                          <NA>
                     2019-04-09 18:32:21                          <NA>
                     2019-04-09 18:32:22                          <NA>
...                                                                ...
484    16353         2021-07-28 22:33:26                          <NA>
                     2021-07-28 22:33:28                          <NA>
                     2021-07-28 22:33:38                          <NA>
                     2021-07-28 22:33:42                          <NA>
                     2021-07-28 22:33:43                          <NA>

                                                DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>     <NA>   <NA>
                     2019-04-09 18:32:18  89.660004     <NA>   <NA>
                     2019-04-09 18:32:19       <NA>     <NA>   <NA>
                     2019-04-09 18:32:21       <NA>     <NA>   <NA>
                     2019-04-09 18:32:22       <NA>     <NA>   <NA>
...                                             ...      ...    ...
484    16353         2021-07-28 22:33:26  69.889999     <NA>   <NA>
                     2021-07-28 22:33:28       <NA>     <NA>   <NA>
                     2021-07-28 22:33:38      45.77     <NA>   <NA>
                     2021-07-28 22:33:42       <NA>     <NA>   <NA>
                     2021-07-28 22:33:43       <NA>     <NA>   <NA>

                                          Probe_Volume    pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12          <NA>  <NA>      <NA>
                     2019-04-09 18:32:18          <NA>  <NA>      <NA>
                     2019-04-09 18:32:19          <NA>  6.86      <NA>
                     2019-04-09 18:32:21          <NA>  <NA>      <NA>
                     2019-04-09 18:32:22          <NA>  <NA>      <NA>
...                                                ...   ...       ...
484    16353         2021-07-28 22:33:26          <NA>  6.88      <NA>
                     2021-07-28 22:33:28          <NA>  <NA>      <NA>
                     2021-07-28 22:33:38          <NA>  6.87      <NA>
                     2021-07-28 22:33:42          <NA>  <NA>      <NA>
                     2021-07-28 22:33:43          <NA>  <NA>      <NA>

                                          InducerConcentration  Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                  <NA>    <NA>
                     2019-04-09 18:32:18                  <NA>    <NA>
                     2019-04-09 18:32:19                  <NA>    <NA>
                     2019-04-09 18:32:21                  <NA>    <NA>
                     2019-04-09 18:32:22                  <NA>    <NA>
...                                                        ...     ...
484    16353         2021-07-28 22:33:26                  <NA>    <NA>
                     2021-07-28 22:33:28                  <NA>    <NA>
                     2021-07-28 22:33:38                  <NA>    <NA>
                     2021-07-28 22:33:42                  <NA>    <NA>
                     2021-07-28 22:33:43                  <NA>    <NA>

[408628 rows x 15 columns]

In [91]:
reverse_lookup = {}

for run_id in metadata.index.unique("run_id"):
    colors = metadata["color"][[run_id]]
    for color in colors.unique():
        mask = colors == color
        indices = colors[colors == color].index.tolist()
        reverse_lookup[(color, run_id)] = indices
        
assert reverse_lookup == col_run_to_exp

## groupby solution

https://stackoverflow.com/a/51329888/9318372

In [71]:
rev = metadata.groupby(["color", "run_id"]).groups
rev = {key:idx.tolist() for key, idx in rev.items()}
assert rev == col_run_to_exp

## Custom splitting logic

In [72]:
from sklearn.model_selection import ShuffleSplit
from itertools import chain

splitter = ShuffleSplit(n_splits=5, random_state=0, test_size=0.25)
groups = metadata.groupby(["color", "run_id"])
rev_idx = groups.ngroup()
groups = metadata.groupby(["color", "run_id"])
group_idx = groups.ngroup()

splits = DataFrame(index=metadata.index)
for i, (train, test) in enumerate(splitter.split(groups)):
    splits[i] = group_idx.isin(train).map({False: "test", True: "train"})

splits.columns.name = "split"
splits.astype("string").astype("category")

split                     0      1      2      3      4
run_id experiment_id
355    11722           test  train  train  train   test
       11723           test  train  train  train   test
       11724          train  train  train  train  train
       11725          train  train  train  train  train
       11726          train   test   test  train   test
...                     ...    ...    ...    ...    ...
484    16349          train   test  train  train  train
       16350          train   test  train  train  train
       16351          train  train  train   test  train
       16352          train  train  train  train  train
       16353          train  train  train   test  train

[240 rows x 5 columns]

## Loss function

Divide 'Glucose' by 10, 'OD600' by 20, 'DOT' by 100, 'Base' by 200, then use RMSE.

In [73]:
targets = {"Glucose", "OD600", "DOT", "Base"}
assert targets <= set(timeseries.columns)

In [74]:
timeseries.min()

Flow_Air                           0.000000
StirringSpeed                      0.000000
Temperature                       32.689999
Acetate                           -0.257518
Base                               0.000000
Cumulated_feed_volume_glucose      3.000000
Cumulated_feed_volume_medium       5.882958
DOT                                0.000000
Glucose                           -0.094553
OD600                             -0.962500
Probe_Volume                     200.000000
pH                                 0.000000
Fluo_GFP                        -250.000000
InducerConcentration               0.000000
Volume                            -2.235569
dtype: float32

In [75]:
timeseries.max()

Flow_Air                             10.000000
StirringSpeed                      2600.000000
Temperature                          41.380001
Acetate                               1.183919
Base                               4070.000000
Cumulated_feed_volume_glucose      4101.000000
Cumulated_feed_volume_medium       4742.057129
DOT                                 498.160004
Glucose                               6.931556
OD600                               127.882500
Probe_Volume                       5200.000000
pH                                    8.600000
Fluo_GFP                         586421.875000
InducerConcentration                  2.000000
Volume                             2551.117188
dtype: float32

In [76]:
timeseries.max() - timeseries.min()

Flow_Air                             10.000000
StirringSpeed                      2600.000000
Temperature                           8.690002
Acetate                               1.441437
Base                               4070.000000
Cumulated_feed_volume_glucose      4098.000000
Cumulated_feed_volume_medium       4736.174316
DOT                                 498.160004
Glucose                               7.026109
OD600                               128.845001
Probe_Volume                       5000.000000
pH                                    8.600000
Fluo_GFP                         586671.875000
InducerConcentration                  2.000000
Volume                             2553.352783
dtype: float32

In [77]:
from itertools import product

In [12]:
list(product(range(5), ("train", "test")))

[(0, 'train'),
 (0, 'test'),
 (1, 'train'),
 (1, 'test'),
 (2, 'train'),
 (2, 'test'),
 (3, 'train'),
 (3, 'test'),
 (4, 'train'),
 (4, 'test')]

In [13]:
timeseries.dtypes

Flow_Air                         Float32
StirringSpeed                    Float32
Temperature                      Float32
Acetate                          Float32
Base                             Float32
Cumulated_feed_volume_glucose    Float32
Cumulated_feed_volume_medium     Float32
DOT                              Float32
Glucose                          Float32
OD600                            Float32
Probe_Volume                     Float32
pH                               Float32
Fluo_GFP                         Float32
InducerConcentration             Float32
Volume                           Float32
dtype: object

In [14]:
mask  = splits[0] == "train"
idx = splits[0][mask].index

MultiIndex([(355, 11724),
            (355, 11725),
            (355, 11726),
            (355, 11727),
            (355, 11728),
            (355, 11729),
            (355, 11732),
            (355, 11733),
            (355, 11734),
            (355, 11735),
            ...
            (484, 16343),
            (484, 16344),
            (484, 16345),
            (484, 16346),
            (484, 16347),
            (484, 16349),
            (484, 16350),
            (484, 16351),
            (484, 16352),
            (484, 16353)],
           names=['run_id', 'experiment_id'], length=171)

In [15]:
timeseries.reset_index(level=2).loc[idx].set_index(["measurement_time"], append=True)

                                          Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12      <NA>           <NA>
                     2019-04-09 18:32:18      <NA>           <NA>
                     2019-04-09 18:32:19      <NA>           <NA>
                     2019-04-09 18:32:21  4.997213           <NA>
                     2019-04-09 18:32:22      <NA>           <NA>
...                                            ...            ...
484    16353         2021-07-28 22:33:26      <NA>           <NA>
                     2021-07-28 22:33:28      <NA>         2400.0
                     2021-07-28 22:33:38      <NA>           <NA>
                     2021-07-28 22:33:42       0.0           <NA>
                     2021-07-28 22:33:43      <NA>         2400.0

                                          Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12    36.990002     <NA>  <NA>
                     2019-04-09 18:32:18         <NA>     <NA>  <NA>
                     2019-04-09 18:32:19         <NA>     <NA>  <NA>
                     2019-04-09 18:32:21         <NA>     <NA>  <NA>
                     2019-04-09 18:32:22        36.98     <NA>  <NA>
...                                               ...      ...   ...
484    16353         2021-07-28 22:33:26         <NA>     <NA>  <NA>
                     2021-07-28 22:33:28        37.57     <NA>  <NA>
                     2021-07-28 22:33:38         <NA>     <NA>  <NA>
                     2021-07-28 22:33:42         <NA>     <NA>  <NA>
                     2021-07-28 22:33:43         <NA>     <NA>  <NA>

                                          Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                           <NA>
                     2019-04-09 18:32:18                           <NA>
                     2019-04-09 18:32:19                           <NA>
                     2019-04-09 18:32:21                           <NA>
                     2019-04-09 18:32:22                           <NA>
...                                                                 ...
484    16353         2021-07-28 22:33:26                           <NA>
                     2021-07-28 22:33:28                           <NA>
                     2021-07-28 22:33:38                           <NA>
                     2021-07-28 22:33:42                           <NA>
                     2021-07-28 22:33:43                           <NA>

                                          Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                          <NA>
                     2019-04-09 18:32:18                          <NA>
                     2019-04-09 18:32:19                          <NA>
                     2019-04-09 18:32:21                          <NA>
                     2019-04-09 18:32:22                          <NA>
...                                                                ...
484    16353         2021-07-28 22:33:26                          <NA>
                     2021-07-28 22:33:28                          <NA>
                     2021-07-28 22:33:38                          <NA>
                     2021-07-28 22:33:42                          <NA>
                     2021-07-28 22:33:43                          <NA>

                                                DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12       <NA>     <NA>   <NA>
                     2019-04-09 18:32:18  90.110001     <NA>   <NA>
                     2019-04-09 18:32:19       <NA>     <NA>   <NA>
                     2019-04-09 18:32:21       <NA>     <NA>   <NA>
                     2019-04-09 18:32:22       <NA>     <NA>   <NA>
...                                             ...      ...    ...
484    16353         2021-07-28 22:33:26  69.889999     <NA>   <NA>
                     2021-07-28 22:33:28       <NA>     <NA>   <NA>
                     2021-07-28 22:33:38      45.77     <NA>   <NA>
                     2021-07-28 22:33:42       <NA>     <NA>   <NA>
                     2021-07-28 22:33:43       <NA>     <NA>   <NA>

                                          Probe_Volume    pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12          <NA>  <NA>      <NA>
                     2019-04-09 18:32:18          <NA>  <NA>      <NA>
                     2019-04-09 18:32:19          <NA>  6.86      <NA>
                     2019-04-09 18:32:21          <NA>  <NA>      <NA>
                     2019-04-09 18:32:22          <NA>  <NA>      <NA>
...                                                ...   ...       ...
484    16353         2021-07-28 22:33:26          <NA>  6.88      <NA>
                     2021-07-28 22:33:28          <NA>  <NA>      <NA>
                     2021-07-28 22:33:38          <NA>  6.87      <NA>
                     2021-07-28 22:33:42          <NA>  <NA>      <NA>
                     2021-07-28 22:33:43          <NA>  <NA>      <NA>

                                          InducerConcentration  Volume
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                  <NA>    <NA>
                     2019-04-09 18:32:18                  <NA>    <NA>
                     2019-04-09 18:32:19                  <NA>    <NA>
                     2019-04-09 18:32:21                  <NA>    <NA>
                     2019-04-09 18:32:22                  <NA>    <NA>
...                                                        ...     ...
484    16353         2021-07-28 22:33:26                  <NA>    <NA>
                     2021-07-28 22:33:28                  <NA>    <NA>
                     2021-07-28 22:33:38                  <NA>    <NA>
                     2021-07-28 22:33:42                  <NA>    <NA>
                     2021-07-28 22:33:43                  <NA>    <NA>

[299755 rows x 15 columns]

# Implementation

In [78]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Splits

In [79]:
from tsdm.tasks import KIWI_RUNS_TASK
TASK = KIWI_RUNS_TASK()

In [18]:
TASK.splits((4, "train"))[0]

                                          Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12       NaN            NaN
                     2019-04-09 18:32:18       NaN            NaN
                     2019-04-09 18:32:19       NaN            NaN
                     2019-04-09 18:32:21  4.997213            NaN
                     2019-04-09 18:32:22       NaN            NaN
...                                            ...            ...
484    16353         2021-07-28 22:33:26       NaN            NaN
                     2021-07-28 22:33:28       NaN         2400.0
                     2021-07-28 22:33:38       NaN            NaN
                     2021-07-28 22:33:42  0.000000            NaN
                     2021-07-28 22:33:43       NaN         2400.0

                                          Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12    36.990002      NaN   NaN
                     2019-04-09 18:32:18          NaN      NaN   NaN
                     2019-04-09 18:32:19          NaN      NaN   NaN
                     2019-04-09 18:32:21          NaN      NaN   NaN
                     2019-04-09 18:32:22    36.980000      NaN   NaN
...                                               ...      ...   ...
484    16353         2021-07-28 22:33:26          NaN      NaN   NaN
                     2021-07-28 22:33:28    37.570000      NaN   NaN
                     2021-07-28 22:33:38          NaN      NaN   NaN
                     2021-07-28 22:33:42          NaN      NaN   NaN
                     2021-07-28 22:33:43          NaN      NaN   NaN

                                          Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                            NaN
                     2019-04-09 18:32:18                            NaN
                     2019-04-09 18:32:19                            NaN
                     2019-04-09 18:32:21                            NaN
                     2019-04-09 18:32:22                            NaN
...                                                                 ...
484    16353         2021-07-28 22:33:26                            NaN
                     2021-07-28 22:33:28                            NaN
                     2021-07-28 22:33:38                            NaN
                     2021-07-28 22:33:42                            NaN
                     2021-07-28 22:33:43                            NaN

                                          Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                           NaN
                     2019-04-09 18:32:18                           NaN
                     2019-04-09 18:32:19                           NaN
                     2019-04-09 18:32:21                           NaN
                     2019-04-09 18:32:22                           NaN
...                                                                ...
484    16353         2021-07-28 22:33:26                           NaN
                     2021-07-28 22:33:28                           NaN
                     2021-07-28 22:33:38                           NaN
                     2021-07-28 22:33:42                           NaN
                     2021-07-28 22:33:43                           NaN

                                                DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12        NaN      NaN    NaN
                     2019-04-09 18:32:18  90.110001      NaN    NaN
                     2019-04-09 18:32:19        NaN      NaN    NaN
                     2019-04-09 18:32:21        NaN      NaN    NaN
                     2019-04-09 18:32:22        NaN      NaN    NaN
...                                             ...      ...    ...
484    16353         2021-07-28 22:33:26  69.889999      NaN    NaN
                     2021-07-28 22:33:28        NaN      NaN    NaN
                     2021-07-28 22:33:38  45.770000      NaN    NaN
                     2021-07-28 22:33:42        NaN      NaN    NaN
                     2021-07-28 22:33:43        NaN      NaN    NaN

                                          Probe_Volume    pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12           NaN   NaN       NaN
                     2019-04-09 18:32:18           NaN   NaN       NaN
                     2019-04-09 18:32:19           NaN  6.86       NaN
                     2019-04-09 18:32:21           NaN   NaN       NaN
                     2019-04-09 18:32:22           NaN   NaN       NaN
...                                                ...   ...       ...
484    16353         2021-07-28 22:33:26           NaN  6.88       NaN
                     2021-07-28 22:33:28           NaN   NaN       NaN
                     2021-07-28 22:33:38           NaN  6.87       NaN
                     2021-07-28 22:33:42           NaN   NaN       NaN
                     2021-07-28 22:33:43           NaN   NaN       NaN

                                          InducerConcentration  Volume
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                   NaN     NaN
                     2019-04-09 18:32:18                   NaN     NaN
                     2019-04-09 18:32:19                   NaN     NaN
                     2019-04-09 18:32:21                   NaN     NaN
                     2019-04-09 18:32:22                   NaN     NaN
...                                                        ...     ...
484    16353         2021-07-28 22:33:26                   NaN     NaN
                     2021-07-28 22:33:28                   NaN     NaN
                     2021-07-28 22:33:38                   NaN     NaN
                     2021-07-28 22:33:42                   NaN     NaN
                     2021-07-28 22:33:43                   NaN     NaN

[298276 rows x 15 columns]

## Preprocessing

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
preprocessor = StandardScaler()
ts, md = TASK.splits((4, "train"))

In [21]:
preprocessor.fit(ts)
preprocessor.transform(ts, copy=False)
ts

                                          Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12       NaN            NaN
                     2019-04-09 18:32:18       NaN            NaN
                     2019-04-09 18:32:19       NaN            NaN
                     2019-04-09 18:32:21  0.217497            NaN
                     2019-04-09 18:32:22       NaN            NaN
...                                            ...            ...
484    16353         2021-07-28 22:33:26       NaN            NaN
                     2021-07-28 22:33:28       NaN       1.151098
                     2021-07-28 22:33:38       NaN            NaN
                     2021-07-28 22:33:42 -3.956055            NaN
                     2021-07-28 22:33:43       NaN       1.151098

                                          Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12    -0.634212      NaN   NaN
                     2019-04-09 18:32:18          NaN      NaN   NaN
                     2019-04-09 18:32:19          NaN      NaN   NaN
                     2019-04-09 18:32:21          NaN      NaN   NaN
                     2019-04-09 18:32:22    -0.653638      NaN   NaN
...                                               ...      ...   ...
484    16353         2021-07-28 22:33:26          NaN      NaN   NaN
                     2021-07-28 22:33:28     0.492247      NaN   NaN
                     2021-07-28 22:33:38          NaN      NaN   NaN
                     2021-07-28 22:33:42          NaN      NaN   NaN
                     2021-07-28 22:33:43          NaN      NaN   NaN

                                          Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                            NaN
                     2019-04-09 18:32:18                            NaN
                     2019-04-09 18:32:19                            NaN
                     2019-04-09 18:32:21                            NaN
                     2019-04-09 18:32:22                            NaN
...                                                                 ...
484    16353         2021-07-28 22:33:26                            NaN
                     2021-07-28 22:33:28                            NaN
                     2021-07-28 22:33:38                            NaN
                     2021-07-28 22:33:42                            NaN
                     2021-07-28 22:33:43                            NaN

                                          Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                           NaN
                     2019-04-09 18:32:18                           NaN
                     2019-04-09 18:32:19                           NaN
                     2019-04-09 18:32:21                           NaN
                     2019-04-09 18:32:22                           NaN
...                                                                ...
484    16353         2021-07-28 22:33:26                           NaN
                     2021-07-28 22:33:28                           NaN
                     2021-07-28 22:33:38                           NaN
                     2021-07-28 22:33:42                           NaN
                     2021-07-28 22:33:43                           NaN

                                               DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12       NaN      NaN    NaN
                     2019-04-09 18:32:18  0.464974      NaN    NaN
                     2019-04-09 18:32:19       NaN      NaN    NaN
                     2019-04-09 18:32:21       NaN      NaN    NaN
                     2019-04-09 18:32:22       NaN      NaN    NaN
...                                            ...      ...    ...
484    16353         2021-07-28 22:33:26 -0.068548      NaN    NaN
                     2021-07-28 22:33:28       NaN      NaN    NaN
                     2021-07-28 22:33:38 -0.704976      NaN    NaN
                     2021-07-28 22:33:42       NaN      NaN    NaN
                     2021-07-28 22:33:43       NaN      NaN    NaN

                                          Probe_Volume        pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12           NaN       NaN       NaN
                     2019-04-09 18:32:18           NaN       NaN       NaN
                     2019-04-09 18:32:19           NaN -0.157835       NaN
                     2019-04-09 18:32:21           NaN       NaN       NaN
                     2019-04-09 18:32:22           NaN       NaN       NaN
...                                                ...       ...       ...
484    16353         2021-07-28 22:33:26           NaN -0.103092       NaN
                     2021-07-28 22:33:28           NaN       NaN       NaN
                     2021-07-28 22:33:38           NaN -0.130464       NaN
                     2021-07-28 22:33:42           NaN       NaN       NaN
                     2021-07-28 22:33:43           NaN       NaN       NaN

                                          InducerConcentration  Volume
run_id experiment_id measurement_time
355    11724         2019-04-09 18:32:12                   NaN     NaN
                     2019-04-09 18:32:18                   NaN     NaN
                     2019-04-09 18:32:19                   NaN     NaN
                     2019-04-09 18:32:21                   NaN     NaN
                     2019-04-09 18:32:22                   NaN     NaN
...                                                        ...     ...
484    16353         2021-07-28 22:33:26                   NaN     NaN
                     2021-07-28 22:33:28                   NaN     NaN
                     2021-07-28 22:33:38                   NaN     NaN
                     2021-07-28 22:33:42                   NaN     NaN
                     2021-07-28 22:33:43                   NaN     NaN

[298276 rows x 15 columns]

## Encoding in torch

In [22]:
import torch
from tsdm.encoders.functional import time2float

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32
ts = ts.reset_index(level=2)  # make measurements regular col

                        measurement_time  Flow_Air  StirringSpeed  \
run_id experiment_id
355    11724         2019-04-09 18:32:12       NaN            NaN
       11724         2019-04-09 18:32:18       NaN            NaN
       11724         2019-04-09 18:32:19       NaN            NaN
       11724         2019-04-09 18:32:21  0.217497            NaN
       11724         2019-04-09 18:32:22       NaN            NaN
...                                  ...       ...            ...
484    16353         2021-07-28 22:33:26       NaN            NaN
       16353         2021-07-28 22:33:28       NaN       1.151098
       16353         2021-07-28 22:33:38       NaN            NaN
       16353         2021-07-28 22:33:42 -3.956055            NaN
       16353         2021-07-28 22:33:43       NaN       1.151098

                      Temperature  Acetate  Base  \
run_id experiment_id
355    11724            -0.634212      NaN   NaN
       11724                  NaN      NaN   NaN
       11724                  NaN      NaN   NaN
       11724                  NaN      NaN   NaN
       11724            -0.653638      NaN   NaN
...                           ...      ...   ...
484    16353                  NaN      NaN   NaN
       16353             0.492247      NaN   NaN
       16353                  NaN      NaN   NaN
       16353                  NaN      NaN   NaN
       16353                  NaN      NaN   NaN

                      Cumulated_feed_volume_glucose  \
run_id experiment_id
355    11724                                    NaN
       11724                                    NaN
       11724                                    NaN
       11724                                    NaN
       11724                                    NaN
...                                             ...
484    16353                                    NaN
       16353                                    NaN
       16353                                    NaN
       16353                                    NaN
       16353                                    NaN

                      Cumulated_feed_volume_medium       DOT  Glucose  OD600  \
run_id experiment_id
355    11724                                   NaN       NaN      NaN    NaN
       11724                                   NaN  0.464974      NaN    NaN
       11724                                   NaN       NaN      NaN    NaN
       11724                                   NaN       NaN      NaN    NaN
       11724                                   NaN       NaN      NaN    NaN
...                                            ...       ...      ...    ...
484    16353                                   NaN -0.068548      NaN    NaN
       16353                                   NaN       NaN      NaN    NaN
       16353                                   NaN -0.704976      NaN    NaN
       16353                                   NaN       NaN      NaN    NaN
       16353                                   NaN       NaN      NaN    NaN

                      Probe_Volume        pH  Fluo_GFP  InducerConcentration  \
run_id experiment_id
355    11724                   NaN       NaN       NaN                   NaN
       11724                   NaN       NaN       NaN                   NaN
       11724                   NaN -0.157835       NaN                   NaN
       11724                   NaN       NaN       NaN                   NaN
       11724                   NaN       NaN       NaN                   NaN
...                            ...       ...       ...                   ...
484    16353                   NaN -0.103092       NaN                   NaN
       16353                   NaN       NaN       NaN                   NaN
       16353                   NaN -0.130464       NaN                   NaN
       16353                   NaN       NaN       NaN                   NaN
       16353                   NaN       NaN       NaN                   NaN

                      Volume
run_id experiment_id
355    11724             NaN
       11724             NaN
       11724             NaN
       11724             NaN
       11724             NaN
...                      ...
484    16353             NaN
       16353             NaN
       16353             NaN
       16353             NaN
       16353             NaN

[298276 rows x 16 columns]

In [23]:
time2float(ts["measurement_time"].values)

array([0.0000000e+00, 6.0000000e+00, 7.0000000e+00, ..., 7.2676886e+07,
       7.2676890e+07, 7.2676891e+07])

In [24]:
T = torch.tensor(time2float(ts["measurement_time"].values), device=device, dtype=dtype)
X = torch.tensor(
    ts.drop(columns=["measurement_time"]).values, device=device, dtype=dtype
)

tensor([[    nan,     nan, -0.6342,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        ...,
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [-3.9561,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,  1.1511,     nan,  ...,     nan,     nan,     nan]],
       device='cuda:0')

## Creating DataSetCollection Object

In [25]:
from tsdm.datasets import DataSetCollection
from torch.utils.data import TensorDataset

In [26]:
shared_index = ts.index.unique().values
masks = {idx:(ts.index==idx) for idx in shared_index}
datasets = {idx: TensorDataset(T[masks[idx]], X[masks[idx]]) for idx in shared_index}

{(355, 11724): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4f1580>,
 (355, 11725): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4f1910>,
 (355, 11727): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4f12b0>,
 (355, 11729): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc5473a0>,
 (355, 11732): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc547a00>,
 (355, 11733): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc547f10>,
 (355, 11735): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc547fd0>,
 (355, 11737): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a5b0>,
 (355, 11740): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28af10>,
 (355, 11741): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a3d0>,
 (355, 11743): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a490>,
 (355, 11745): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a310>,
 (439, 15326): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28afd0>,
 (439, 15327): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a250>,
 (439, 15329): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a040>,
 (439, 15330): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a910>,
 (439, 15332): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a700>,
 (439, 15334): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28ab50>,
 (439, 15335): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a430>,
 (439, 15337): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a9a0>,
 (439, 15338): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a220>,
 (439, 15340): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a880>,
 (439, 15342): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a8e0>,
 (439, 15343): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a7f0>,
 (439, 15345): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a160>,
 (439, 15346): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28acd0>,
 (439, 15348): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28ad60>,
 (445, 15493): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28ac10>,
 (445, 15494): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28ac70>,
 (445, 15495): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a5e0>,
 (445, 15497): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28aac0>,
 (445, 15498): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28aeb0>,
 (445, 15499): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28ab80>,
 (445, 15500): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a7c0>,
 (445, 15501): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a190>,
 (445, 15502): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a940>,
 (445, 15503): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a100>,
 (445, 15505): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a730>,
 (445, 15506): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28adf0>,
 (445, 15507): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a400>,
 (445, 15509): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28aa90>,
 (445, 15510): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28a850>,
 (445, 15511): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc28ae20>,
 (445, 15513): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50df10>,
 (445, 15514): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d190>,
 (445, 15515): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d1c0>,
 (445, 15517): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50dfd0>,
 (445, 15518): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d3d0>,
 (445, 15519): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d0d0>,
 (445, 15521): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50de20>,
 (445, 15522): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d820>,
 (445, 15523): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d9a0>,
 (445, 15524): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50ddc0>,
 (445, 15525): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50dfa0>,
 (445, 15526): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d850>,
 (445, 15527): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d940>,
 (445, 15529): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d2b0>,
 (445, 15530): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d1f0>,
 (445, 15531): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d0a0>,
 (445, 15532): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d040>,
 (445, 15533): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50da90>,
 (445, 15534): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50d970>,
 (445, 15535): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc50dcd0>,
 (445, 15537): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc56d0a0>,
 (445, 15538): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc56da90>,
 (445, 15539): <torch.utils.data.dataset.TensorDataset at 0x7f3ebbe8f610>,
 (445, 15540): <torch.utils.data.dataset.TensorDataset at 0x7f3ebbe8f760>,
 (449, 15644): <torch.utils.data.dataset.TensorDataset at 0x7f3ebbe8f6a0>,
 (449, 15645): <torch.utils.data.dataset.TensorDataset at 0x7f3ebbe8f700>,
 (449, 15646): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9490>,
 (449, 15647): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9ac0>,
 (449, 15650): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9940>,
 (449, 15652): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9cd0>,
 (449, 15653): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9dc0>,
 (449, 15654): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b94f0>,
 (449, 15655): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9eb0>,
 (449, 15658): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9e80>,
 (449, 15660): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9f10>,
 (449, 15661): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9a90>,
 (449, 15662): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9be0>,
 (449, 15663): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9b20>,
 (449, 15666): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9b80>,
 (468, 15994): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9850>,
 (468, 15995): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9fd0>,
 (468, 15996): <torch.utils.data.dataset.TensorDataset at 0x7f3ec15b9c10>,
 (468, 15997): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc883850>,
 (468, 15998): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162670>,
 (468, 15999): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162c10>,
 (468, 16000): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162f70>,
 (468, 16001): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162ca0>,
 (468, 16002): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162d90>,
 (468, 16003): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162b20>,
 (468, 16004): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162b80>,
 (468, 16005): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162820>,
 (468, 16006): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162850>,
 (468, 16007): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc1623d0>,
 (468, 16008): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc1621f0>,
 (468, 16009): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc1626d0>,
 (468, 16010): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162370>,
 (468, 16011): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162c70>,
 (468, 16012): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162220>,
 (468, 16013): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc1620d0>,
 (468, 16014): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162100>,
 (468, 16015): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc1622b0>,
 (468, 16016): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162dc0>,
 (468, 16017): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162280>,
 (474, 16106): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162c40>,
 (474, 16107): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162730>,
 (474, 16108): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162a30>,
 (474, 16109): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162ac0>,
 (474, 16110): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162490>,
 (474, 16111): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162550>,
 (474, 16112): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162610>,
 (474, 16114): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc1628e0>,
 (474, 16115): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162940>,
 (474, 16116): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162430>,
 (474, 16117): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162bb0>,
 (474, 16118): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162eb0>,
 (474, 16119): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162fd0>,
 (474, 16120): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162700>,
 (474, 16122): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162790>,
 (474, 16123): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162760>,
 (474, 16124): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162310>,
 (474, 16125): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162250>,
 (474, 16126): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162190>,
 (474, 16127): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc162040>,
 (474, 16128): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc1628b0>,
 (475, 16130): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a670>,
 (475, 16133): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a640>,
 (475, 16134): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a340>,
 (475, 16135): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a7c0>,
 (475, 16137): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a0d0>,
 (475, 16138): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23afa0>,
 (475, 16141): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23aca0>,
 (475, 16142): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23ac70>,
 (475, 16143): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a4f0>,
 (475, 16145): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a2e0>,
 (475, 16146): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a220>,
 (475, 16149): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a160>,
 (475, 16150): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a0a0>,
 (475, 16151): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a280>,
 (475, 16153): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a520>,
 (482, 16282): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a1c0>,
 (482, 16283): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23aa00>,
 (482, 16284): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a730>,
 (482, 16286): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a6d0>,
 (482, 16288): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a3d0>,
 (482, 16289): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a970>,
 (482, 16290): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a910>,
 (482, 16291): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a250>,
 (482, 16292): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23abb0>,
 (482, 16294): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a6a0>,
 (482, 16296): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a850>,
 (482, 16297): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23aeb0>,
 (482, 16298): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a9a0>,
 (482, 16299): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23aac0>,
 (482, 16300): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23ab80>,
 (482, 16302): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23ac40>,
 (482, 16304): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23af10>,
 (482, 16305): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23af70>,
 (484, 16331): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a550>,
 (484, 16332): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a5b0>,
 (484, 16333): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23aa30>,
 (484, 16334): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23aa90>,
 (484, 16335): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a460>,
 (484, 16336): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a790>,
 (484, 16337): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23aee0>,
 (484, 16339): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc23a760>,
 (484, 16340): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fcbe0>,
 (484, 16341): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc0a0>,
 (484, 16342): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc0d0>,
 (484, 16343): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc190>,
 (484, 16344): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc550>,
 (484, 16345): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc610>,
 (484, 16347): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc850>,
 (484, 16348): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc8e0>,
 (484, 16349): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc2b0>,
 (484, 16350): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc370>,
 (484, 16351): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc430>,
 (484, 16352): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc700>,
 (484, 16353): <torch.utils.data.dataset.TensorDataset at 0x7f3dbc4fc760>}

In [27]:
from pandas import Series

In [28]:
s = Series(datasets)

355  11724    ((tensor(0., device='cuda:0'), [tensor(nan, de...
     11725    ((tensor(0., device='cuda:0'), [tensor(nan, de...
     11727    ((tensor(0., device='cuda:0'), [tensor(nan, de...
     11729    ((tensor(0., device='cuda:0'), [tensor(nan, de...
     11732    ((tensor(0., device='cuda:0'), [tensor(nan, de...
                                    ...
484  16349    ((tensor(72627624., device='cuda:0'), [tensor(...
     16350    ((tensor(72627624., device='cuda:0'), [tensor(...
     16351    ((tensor(72627624., device='cuda:0'), [tensor(...
     16352    ((tensor(72627624., device='cuda:0'), [tensor(...
     16353    ((tensor(72627624., device='cuda:0'), [tensor(...
Length: 181, dtype: object

In [29]:
dataset = DataSetCollection(datasets)

In [30]:
some_index = ts.index.values[42]
dataset[some_index]

In [31]:
dataset[some_index][:10]

(tensor([ 0.,  6.,  7.,  9., 10., 16., 17., 19., 20., 26.], device='cuda:0'),
 tensor([[    nan,     nan, -0.6342,     nan,     nan,     nan,     nan,     nan,
              nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan,  0.4650,
              nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
              nan,     nan,     nan, -0.1578,     nan,     nan,     nan],
         [ 0.2175,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
              nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan, -0.6536,     nan,     nan,     nan,     nan,     nan,
              nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan,  0.4676,
              nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
              nan,     nan,     nan, -0.1578,     nan,     nan,     nan],
         [ 0.2216,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
              nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan, -0.6536,     nan,     nan,     nan,     nan,     nan,
              nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan,  0.4613,
              nan,     nan,     nan,     nan,     nan,     nan,     nan]],
        device='cuda:0'))

## Creating CollectionSampler Object

In [34]:
from tsdm.util.samplers import CollectionSampler, SequenceSampler
from torch.utils.data import TensorDataset
from functools import partial

subsampler = partial(SequenceSampler, seq_len=100, shuffle=True)
sampler = CollectionSampler(dataset, subsampler=subsampler)

In [35]:
sample = next(iter(sampler))
element = dataset[sample]

(tensor([70212072., 70212080., 70212096., 70212112., 70212128., 70212144.,
         70212152., 70212176., 70212184., 70212216., 70212240., 70212248.,
         70212272., 70212280., 70212304., 70212312., 70212328., 70212336.,
         70212368., 70212392., 70212400., 70212424., 70212432., 70212456.,
         70212464., 70212488., 70212496., 70212512., 70212528., 70212544.,
         70212560., 70212576., 70212584., 70212608., 70212616., 70212640.,
         70212648., 70212672., 70212680., 70212704., 70212712., 70212744.,
         70212760., 70212776., 70212800., 70212832., 70212856., 70212864.,
         70212888., 70212896., 70212928., 70212960., 70212976., 70212992.,
         70213008., 70213024., 70213048., 70213072., 70213080., 70213104.,
         70213112., 70213144., 70213168., 70213176., 70213192., 70213200.,
         70213224., 70213232., 70213264., 70213288., 70213296., 70213320.,
         70213328., 70213352., 70213360., 70213376., 70213392., 70213416.,
         70213424., 70213440., 70213456., 70213472., 70213488., 70213504.,
         70213520., 70213544., 70213568., 70213576., 70213600., 70213608.,
         70213640., 70213672., 70213688., 70213696., 70213728., 70213760.,
         70213784., 70213792., 70213816., 70213824.], device='cuda:0'),
 tensor([[    nan,     nan,     nan,  ...,     nan,     nan, -0.8535],
         [    nan,     nan,  0.2009,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,  1.0361,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],
        device='cuda:0'))

In [36]:
from tqdm.auto import tqdm
for b in tqdm(sampler):
    ...

  0%|          | 0/181 [00:00<?, ?it/s]

## DataLoader Object

In [37]:
from torch.utils.data import DataLoader

In [38]:
dloader = DataLoader(dataset, sampler=sampler, batch_size=32)

In [39]:
next(iter(dloader))

[tensor([[5.8149e+07, 5.8149e+07, 5.8149e+07,  ..., 5.8152e+07, 5.8152e+07,
          5.8153e+07],
         [7.2631e+07, 7.2631e+07, 7.2631e+07,  ..., 7.2633e+07, 7.2633e+07,
          7.2633e+07],
         [6.2993e+07, 6.2993e+07, 6.2993e+07,  ..., 6.2997e+07, 6.2997e+07,
          6.2997e+07],
         ...,
         [2.2710e+04, 2.2712e+04, 2.2713e+04,  ..., 2.3914e+04, 2.3942e+04,
          2.3965e+04],
         [7.2674e+07, 7.2674e+07, 7.2674e+07,  ..., 7.2676e+07, 7.2676e+07,
          7.2676e+07],
         [6.5401e+07, 6.5401e+07, 6.5401e+07,  ..., 6.5404e+07, 6.5404e+07,
          6.5404e+07]], device='cuda:0'),
 tensor([[[    nan,     nan, -0.5565,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan, -0.5371,  ...,     nan,     nan,     nan],
          ...,
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan, -0.5954,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],

         [[    nan,     nan,  0.5505,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,  0.5699,  ...,     nan,     nan,     nan],
          ...,
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,  0.4146,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],

         [[    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,  0.4146,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          ...,
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,  0.3175,  ...,     nan,     nan,     nan]],

         ...,

         [[    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [ 0.2208,     nan,     nan,  ...,     nan,     nan,     nan],
          ...,
          [ 0.2207,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan, -0.5759,  ...,     nan,     nan,     nan]],

         [[    nan,     nan,  0.4534,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,  0.4728,  ...,     nan,     nan,     nan],
          ...,
          [    nan,     nan,  0.4146,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],

         [[    nan,     nan,  0.3175,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,  0.3563,  ...,     nan,     nan,     nan],
          ...,
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
          [    nan,     nan,  0.3175,  ...,     nan,     nan,     nan],
          [    nan,     nan,     nan,  ...,     nan,     nan,     nan]]],
        device='cuda:0')]

In [40]:
for batch in tqdm(dloader):
    ...

  0%|          | 0/6 [00:00<?, ?it/s]

## Testing implemented variant

In [53]:
from tsdm.tasks import KIWI_RUNS_TASK
task = KIWI_RUNS_TASK()

In [59]:
task.dataloaders

{(0, 'train'): <torch.utils.data.dataloader.DataLoader at 0x7f3d4039e1f0>,
 (0, 'test'): <torch.utils.data.dataloader.DataLoader at 0x7f3d403f6c40>,
 (1, 'train'): <torch.utils.data.dataloader.DataLoader at 0x7f3d401001f0>,
 (1, 'test'): <torch.utils.data.dataloader.DataLoader at 0x7f3d411b7c40>,
 (2, 'train'): <torch.utils.data.dataloader.DataLoader at 0x7f3d2b306fd0>,
 (2, 'test'): <torch.utils.data.dataloader.DataLoader at 0x7f3d411ffa60>,
 (3, 'train'): <torch.utils.data.dataloader.DataLoader at 0x7f3d40202850>,
 (3, 'test'): <torch.utils.data.dataloader.DataLoader at 0x7f3d4139b2e0>,
 (4, 'train'): <torch.utils.data.dataloader.DataLoader at 0x7f3d4050f670>,
 (4, 'test'): <torch.utils.data.dataloader.DataLoader at 0x7f3d41244100>}

In [81]:
dloader = task.batchloader[0]

In [83]:
T, X = next(iter(dloader))

In [84]:
T.shape, X.shape

(torch.Size([32, 120]), torch.Size([32, 120, 15]))

In [61]:
for batch in tqdm(dloader):
    ...

  0%|          | 0/5 [00:00<?, ?it/s]

In [60]:
for batch in tqdm(task.dataloaders[(0, "train")]):
    ...

  0%|          | 0/2 [00:00<?, ?it/s]