# Kiwi Runs - conceptual

Conceptually, this dataset is a `Mapping[TimeSeriesDataset]`, or even a `Mapping[Mapping[TimeSeriesDataset]]`, depending on how we treat the `run_id`, `exp_id` Multi-Index.

Where a `TimeSeriesDataset` consists of 
  - time series data (typically `tuple[TimeTensor]`)
  - and static metadata (typically `tuple[Tensor]`)

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging

logging.basicConfig(level=logging.INFO)

In [2]:
import matplotlib.pyplot as plt
import numpy as np

np.set_printoptions(precision=4, floatmode="fixed", suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7F3AB7F93660

## imports

In [3]:
import logging
from collections.abc import *
from functools import cached_property
from itertools import chain, count
from types import SimpleNamespace
from typing import Any, Literal, NamedTuple, Optional, TypeVar, Union

import numpy as np
import pandas
import pandas as pd
import torch
from numpy.typing import ArrayLike
from pandas import DataFrame, Index, Interval, MultiIndex, Series, Timedelta, Timestamp
from torch import Tensor, jit, nn
from torch.utils.data import Dataset as Torch_Dataset
from torch.utils.data import *
from tqdm.auto import tqdm

from tsdm.datasets import KIWI_RUNS
from tsdm.datasets.base import DatasetCollection, TimeSeriesDataset, TimeTensor
from tsdm.tasks import KIWI_RUNS_TASK, BaseTask
from tsdm.util.strings import repr_mapping, repr_sequence

IndexedArray = Union[Series, DataFrame, TimeTensor]
r"""Type Hint for IndexedArrays."""

_IndexedArray = (Series, DataFrame, TimeTensor)
r"""TODO: replace with python 3.10"""

INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:tsdm.config._config:Available Models: {'ODE-RNN', 'SET-TS', 'IP-Net', 'NODE', 'N-BEATS', 'Latent-ODE', 'TFT', 'GRU-ODE-Bayes', 'M-RNN', 'mTAN', 'NCDE', 'TPA', 'BRITS', 'Informer'}
INFO:tsdm.config._config:Available Datasets: {'Physionet 2012', 'tourism1', 'Air Quality Multi-Site', 'Air Quality', 'M5', 'Electricity', 'M4', 'tourism2', 'Human Activity', 'USHCN', 'MuJoCo', 'Physionet 2019', 'Character Trajectories', 'Traffic', 'Household Consumption', 'UWAVE', 'M3'}
INFO:tsdm.config._config:Initializing folder structure
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/datasets
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/models
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/logs
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/rawdata
INFO:tsdm.config._config:Created folder structure in /home/rscholz/.tsdm

'TODO: replace with python 3.10'

# Implementation of Dataset Objects

In [4]:
a = torch.randn(14, 3)
b = torch.randn(14, 5)
TensorDataset(a, b)[0]

(tensor([-0.8212, -0.9730, -0.8409]),
 tensor([ 0.8372, -0.0035,  0.5080, -0.6008,  0.7783]))

## DatasetMapping

In [5]:
class DatasetMapping(Mapping, Torch_Dataset):
    r"""Represents a ``mapping[index → torch.Datasets]``.

    All tensors must have a shared index,
    in the sense that index.unique() is identical for all inputs.
    """

    dataset: dict[Any, Torch_Dataset]
    """The dataset"""

    def __init__(self, indexed_datasets: Mapping[Any, Torch_Dataset]):
        super().__init__()
        self.dataset = dict(indexed_datasets)
        self.index = self.dataset.keys()
        self.keys = self.dataset.keys  # type: ignore[assignment]
        self.values = self.dataset.values  # type: ignore[assignment]
        self.items = self.dataset.items  # type: ignore[assignment]

    def __len__(self):
        r"""Length of the dataset."""
        return len(self.dataset)

    def __getitem__(self, item):
        r"""Hierarchical lookup."""
        # test for hierarchical indexing
        if isinstance(item, Sequence):
            first, rest = item[0], item[1:]
            if isinstance(first, (Iterable, slice)):
                # pass remaining indices to sub-object
                value = self.dataset[first]
                return value[rest]

        # no hierarchical indexing
        return self.dataset[item]

    def __iter__(self):
        r"""Iterate over the dataset."""
        for key in self.index:
            yield self.dataset[key]

    def __repr__(self):
        r"""Representation of the dataset."""
        return repr_mapping(self)

## TimeSeriesDataset

In [6]:
TimeLikeTensor = Any
StaticTensor = Any


def repr_array(obj, title: Optional[str] = None):   
    if hasattr(obj, "shape"):
        return type(obj).__name__ + "[" + str(obj.shape) + "]"
    return f"[" + ", ".join(repr_array(x) for x in obj) + "]"

def repr_singleton_or_tuple(obj, repr_fun: Optional[Callable] = None):
    to_string = repr if repr_fun is None else repr_fun

    if isinstance(obj, tuple):
        return repr_sequence(obj, repr_fun=to_string)
    return to_string(obj)


class TimeSeriesSlice(NamedTuple):
    timeseries: tuple[TimeLikeTensor, ...]
    metadata: tuple[StaticTensor, ...]

    def __repr__(self):
        pad = " " * 2
        string = type(self).__name__ + "("
        string += (
            "\n"
            + pad
            + "timeseries="
            + repr_singleton_or_tuple(self.timeseries, repr_array)
        )
        string += (
            "\n"
            + pad
            + "metadata="
            + repr_singleton_or_tuple(self.metadata, repr_array)
        )
        string += "\n)"
        return string


def tensor_info(x: Tensor) -> str:
    r"""Print useful information about Tensor."""
    return f"{x.__class__.__name__}[{tuple(x.shape)}]"

In [7]:
class TimeSeriesDataset(TensorDataset):
    """A general Time Series Dataset.

    Consists of 2 things
    - timeseries: TimeTensor / tuple[TimeTensor]
    - metadata: Tensor / tuple[Tensor]

    When retrieving items, we generally use slices:

    - ds[timestamp] = ds[timestamp:timestamp]
    - ds[t₀:t₁] = tuple[X[t₀:t₁] for X in self.timeseries], metadata
    """

    timeseries: Union[TimeLikeTensor, tuple[TimeLikeTensor, ...]]
    metadata: Optional[Union[StaticTensor, tuple[StaticTensor, ...]]] = None

    def __init__(
        self,
        timeseries: Union[IndexedArray, Collection[IndexedArray]],
        *timetensors: IndexedArray,
        metadata: Optional[Union[Tensor, Collection[Tensor]]] = None,
    ):
        super().__init__()

        ts_tensors = (
            [timeseries] if isinstance(timeseries, _IndexedArray) else list(timeseries)
        )
        ts_tensors.extend(timetensors)
        self.timeseries = ts_tensors[0] if len(ts_tensors) == 1 else tuple(ts_tensors)
        self.metadata = metadata

    def __repr__(self) -> str:
        r"""Pretty print."""
        pad = r"  "

        if isinstance(self.timeseries, tuple):
            ts_lines = [tensor_info(tensor) for tensor in self.timeseries]
        else:
            ts_lines = [tensor_info(self.timeseries)]

        if self.metadata is None:
            md_lines = [f"{None}"]
        elif isinstance(self.metadata, tuple):
            md_lines = [tensor_info(tensor) for tensor in self.metadata]
        else:
            md_lines = [tensor_info(self.metadata)]

        return (
            f"{self.__class__.__name__}("
            + "".join(["\n" + 2 * pad + line for line in ts_lines])
            + "\n"
            + pad
            + "metadata:"
            + "".join(["\n" + 2 * pad + line for line in md_lines])
            + "\n"
            + ")"
        )

    def __len__(self) -> int:
        r"""Return the length of the longest timeseries."""
        if isinstance(self.timeseries, tuple):
            minval = min(min(ts.index) for ts in self.timeseries)
            maxval = max(max(ts.index) for ts in self.timeseries)
            return maxval - minval
        minval = min(self.timeseries.index)
        maxval = max(self.timeseries.index)
        return maxval - minval

    def __getitem__(self, item):
        r"""Return corresponding slice from each tensor."""
        if isinstance(self.timeseries, tuple):
            ts = tuple(tensor.loc[item] for tensor in self.timeseries)
        else:
            ts = self.timeseries.loc[item]
        md = self.metadata
        return TimeSeriesSlice(ts, md)

## MappingDataset

In [8]:
class MappingDataset(Torch_Dataset, Mapping):
    r"""Represents a Mapping[Key, Dataset]."""

    def __init__(self, data: Mapping):
        super().__init__()
        assert isinstance(data, Mapping)
        if isinstance(data, Mapping):
            self.index = data.keys()
            self.data = data

    def __iter__(self) -> Iterator:
        return iter(self.index)

    def __len__(self):
        return len(self.index)

    def __getitem__(self, key):
        if not isinstance(key, tuple):
            return self.data[key]
        try:
            outer = self.data[key[0]]
            return outer[key[1:]]
        except KeyError:
            return self.data[key]

    @staticmethod
    def from_dataframe(df: DataFrame, levels: Optional[list[str]] = None):
        if levels is not None:
            mindex = df.index.to_frame()
            subidx = MultiIndex.from_frame(mindex[levels])
            index = subidx.unique()
        else:
            index = df.index

        return MappingDataset({idx: df.loc[idx] for idx in index})

    def __repr__(self):
        r"""Representation of the dataset."""
        return repr_mapping(self)#, repr_fun=repr_array)

# Implementation of Sampler Objects

## MappingSampler

In [9]:
class MappingSampler(Sampler):
    def __init__(self, data_source: Mapping, shuffle: bool = True):
        # super().__init__(data_source)
        self.data = data_source

    def __len__(self) -> int:
        return len(self.data)

    def __iter__(self):
        perm = np.random.permutation(list(self.data.keys()))
        for k in perm:
            yield self.data[k]

## IntervalSampler

In [10]:
TimedeltaLike = TypeVar("TimedeltaLike", int, float, Timedelta)
TimestampLike = TypeVar("TimestampLike", int, float, Timestamp)


def grid(
    xmin: TimestampLike,
    xmax: TimestampLike,
    delta: TimedeltaLike,
    xoffset: Optional[TimestampLike] = None,
) -> list[int]:
    """Computes `\{k∈ℤ∣ xₘᵢₙ ≤ x₀+k⋅Δ ≤ xₘₐₓ\}`.

    Special case: if Δ=0, returns [0]
    """

    xo = xmin if xoffset is None else xoffset
    zero = type(delta)(0)

    if delta == zero:
        return [0]

    assert delta > zero, "Assumption delta>0 violated!"
    assert xmin <= xoffset <= xmax, "Assumption: xmin≤xoffset≤xmax violated!"

    a = xmin - xoffset
    b = xmax - xoffset
    kmax = b // delta
    kmin = a // delta

    assert xmin <= xo + kmin * delta
    assert xmin > xo + (kmin - 1) * delta
    assert xmax >= xo + kmax * delta
    assert xmax < xo + (kmax + 1) * delta

    return list(range(kmin, kmax + 1))

In [11]:
V = TypeVar("V")

Boxed = Union[
    Sequence[V],
    Mapping[int, V],
    Callable[[int], V],
]

dt_type = Union[
    TimedeltaLike,
    Sequence[TimedeltaLike],
    Mapping[int, TimedeltaLike],
    Callable[[int], TimedeltaLike],
]

import numpy as np
from torch.utils.data import Sampler


class IntervalSampler(
    Sampler,
):
    """Returns all intervals `[a, b]` such that:

    - `a = t₀ + i⋅sₖ`
    - `b = t₀ + i⋅sₖ + Δtₖ`
    - `i, k ∈ ℤ`
    - `a ≥ t_min`
    - `b ≤ t_max`
    - `sₖ` is the stride corresponding to intervals of size `Δtₖ`
    """

    def __init__(
        self,
        xmin,
        xmax,
        deltax: dt_type,
        stride: Optional[dt_type] = None,
        levels: Optional[Sequence[int]] = None,
        offset: Optional[dt_type] = None,
        multiples: bool = True,
        shuffle: bool = True,
    ) -> None:

        # set stride and offset
        zero = 0 * (xmax - xmin)
        stride = zero if stride is None else stride
        offset = xmin if offset is None else offset

        # validate bounds
        assert xmin <= offset <= xmax, "Assumption: xmin≤xoffset≤xmax violated!"

        # determine delta_max
        delta_max = max(offset - xmin, xmax - offset)

        # determine levels
        if levels is None:
            if isinstance(deltax, Mapping):
                levels = [k for k in deltax.keys() if deltax[l] <= delta_max]
            elif isinstance(deltax, Sequence):
                levels = [k for k in range(len(deltax)) if deltax[k] <= delta_max]
            elif isinstance(deltax, Callable):
                levels = []
                for k in count():
                    dt = self._get_value(deltax, k)
                    if dt == zero:
                        continue
                    if dt > delta_max:
                        break
                    levels.append(k)
            else:
                levels = [0]
        else:
            levels = [k for k in levels if self._get_value(deltax, k) <= delta_max]

        # validate levels
        assert all(self._get_value(deltax, k) <= delta_max for k in levels)

        # compute valid intervals
        intervals: list[Interval] = []

        # for each level, get all intervals
        for k in levels:
            dt = self._get_value(deltax, k)
            st = self._get_value(stride, k)
            x0 = self._get_value(offset, k)

            # get valid interval bounds, probably there is an easier way to do it...
            stridesa = grid(xmin, xmax, st, x0)
            stridesb = grid(xmin, xmax, st, x0 + dt)
            valid_strides = set.intersection(set(stridesa), set(stridesb))

            if not valid_strides:
                break

            intervals.extend(
                [(x0 + i * st, x0 + i * st + dt, dt, st) for i in valid_strides]
            )

        # set variables
        self.offset = offset
        self.deltax = deltax
        self.stride = stride
        self.shuffle = shuffle
        self.intervals = DataFrame(
            intervals, columns=["left", "right", "delta", "stride"]
        )

    def __iter__(self) -> Iterator:
        if self.shuffle:
            perm = np.random.permutation(len(self))
        else:
            perm = np.arange(len(self))

        for k in perm:
            yield slice(self.loc[k, "left"], self.loc[k, "right"])

    def __len__(self) -> int:
        return len(self.intervals)

    def __getattr__(self, key):
        return self.intervals.__getattr__(key)

    def __getitem__(self, key):
        return self.intervals[key]

    @staticmethod
    def _get_value(obj: Union[V, Boxed[V]], k: int) -> V:
        if isinstance(obj, Callable):
            return obj(k)
        if isinstance(obj, Sequence):
            return obj[k]
        # Fallback: multiple!
        return obj

## HierarchicalSampler

In [12]:
class HierarchicalSampler(Sampler):
    r"""Samples a single random dataset from a collection of dataset.

    Optionally, we can delegate a subsampler to then sample from the randomly drawn dataset.
    """

    idx: Index
    r"""The shared index."""
    subsamplers: Mapping[Any, Sampler]
    r"""The subsamplers to sample from the collection."""
    early_stop: bool = False
    r"""Whether to stop sampling when the index is exhausted."""
    shuffle: bool = True
    r"""Whether to sample in random order."""
    sizes: Series
    r"""The sizes of the subsamplers."""
    partition: Series
    r"""Contains each key a number of times equal to the size of the subsampler."""

    def __init__(
        self,
        data_source: Dataset,
        subsamplers: Mapping[Any, Sampler],
        shuffle: bool = True,
        early_stop: bool = False,
    ):
        super().__init__(data_source)
        self.data = data_source
        self.idx = data_source.keys()
        self.subsamplers = dict(subsamplers)
        self.sizes = Series({key: len(self.subsamplers[key]) for key in self.idx})
        self.shuffle = shuffle
        self.early_stop = early_stop

        if early_stop:
            partition = list(chain(*([key] * min(self.sizes) for key in self.idx)))
        else:
            partition = list(chain(*([key] * self.sizes[key] for key in self.idx)))
        self.partition = Series(partition)

    def __len__(self):
        r"""Return the maximum allowed index."""
        if self.early_stop:
            return min(self.sizes) * len(self.subsamplers)
        return sum(self.sizes)

    def __iter__(self):
        r"""Return indices of the samples.

        When ``early_stop=True``, it will sample precisely min() * len(subsamplers) samples.
        When ``early_stop=False``, it will sample all samples.
        """
        activate_iterators = {
            key: iter(sampler) for key, sampler in self.subsamplers.items()
        }
        
        if self.shuffle:
            perm = np.random.permutation(self.partition)
        else:
            perm = self.partition

        for key in perm:
            yield key, next(activate_iterators[key])

    def __getitem__(self, key: Any) -> Sampler:
        r"""Return the subsampler for the given key."""
        return self.subsamplers[key]
    
    
    def __repr__(self):
        return repr_mapping(self.subsamplers)

# Plugging everything together

In [13]:
ds = KIWI_RUNS()
ts = ds.timeseries.drop([355, 445, 482]).astype(float)
md = ds.metadata.drop([355, 445, 482])

INFO:tsdm.datasets.base._base:KIWI_RUNS: START cleaning dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/units already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE cleaning dataset
INFO:tsdm.datasets.base._base:KIWI_RUNS: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE loading dataset!

                      Feed_concentration_glc  OD_Dilution  bioreactor_id  \
run_id experiment_id
439    15325                             400         50.0            495
       15326                             400         50.0            495
       15327                             400         50.0            495
       15328                             400         50.0            495
       15329                             400         50.0            495
...                                      ...          ...            ...
510    16867                             200         50.0            614
       16868                             200         50.0            614
       16869                             200         50.0            614
       16870                             200         50.0            614
       16871                             200         50.0            614

                          color  container_number            end_time  \
run_id experiment_id
439    15325          #FF1B9E77                 9 2020-12-09 23:34:23
       15326          #FFD95F02                10 2020-12-09 23:34:23
       15327          #FF7570B3                11 2020-12-09 23:34:23
       15328          #FFE7298A                12 2020-12-09 23:34:23
       15329          #FF66A61E                13 2020-12-09 23:34:23
...                         ...               ...                 ...
510    16867          #FFE7298A                28 2021-10-26 23:14:23
       16868          #FF66A61E                29 2021-10-26 23:14:23
       16869          #FFE6AB02                30 2021-10-26 23:14:23
       16870          #FFA6761D                31 2021-10-26 23:14:23
       16871          #FF666666                32 2021-10-26 23:14:23

                      organism_id  pH_correction_factor  profile_id  \
run_id experiment_id
439    15325                   41                   0.5       10068
       15326                   41                   0.5       10069
       15327                   41                   0.5       10070
       15328                   41                   0.5       10071
       15329                   41                   0.5       10072
...                           ...                   ...         ...
510    16867                   41                   0.3       11527
       16868                   41                   0.3       11528
       16869                   41                   0.3       11529
       16870                   41                   0.3       11530
       16871                   41                   0.3       11531

                     profile_name                      run_name  \
run_id experiment_id
439    15325                   A2               20201209_01_MHE
       15326                   B2               20201209_01_MHE
       15327                   C2               20201209_01_MHE
       15328                   D2               20201209_01_MHE
       15329                   E2               20201209_01_MHE
...                           ...                           ...
510    16867                   D4  20211020_Pre_experiment_KIWI
       16868                   E4  20211020_Pre_experiment_KIWI
       16869                   F4  20211020_Pre_experiment_KIWI
       16870                   G4  20211020_Pre_experiment_KIWI
       16871                   H4  20211020_Pre_experiment_KIWI

                              start_time
run_id experiment_id
439    15325         2020-12-09 09:09:58
       15326         2020-12-09 09:09:58
       15327         2020-12-09 09:09:58
       15328         2020-12-09 09:09:58
       15329         2020-12-09 09:09:58
...                                  ...
510    16867         2021-10-26 09:13:47
       16868         2021-10-26 09:13:47
       16869         2021-10-26 09:13:47
       16870         2021-10-26 09:13:47
       16871         2021-10-26 09:13:47

[168 rows x 12 columns]

## Preprocessing

In [14]:
# d = {}
# for idx, slc in ts.groupby(["run_id", "experiment_id"]):
#     slc = slc.reset_index([0, 1], drop=True)
#     lower = slc.index[0]
#     slc.index = slc.index - slc.index[0]
#     d[idx] = slc
# ts = pandas.concat(d, names=["run_id", "experiment_id"])

## Dataset Object

In [15]:
outer_index = md.index
TSDs = {idx: TimeSeriesDataset(ts.loc[idx], metadata=md.loc[idx]) for idx in md.index}
DS = MappingDataset(TSDs)

MappingDataset(
  (439, 15325): TimeSeriesDataset(
      DataFrame[(1529, 15)]
    metadata:
      Series[(12,)]
  )
  (439, 15326): TimeSeriesDataset(
      DataFrame[(1521, 15)]
    metadata:
      Series[(12,)]
  )
  (439, 15327): TimeSeriesDataset(
      DataFrame[(1546, 15)]
    metadata:
      Series[(12,)]
  )
  ...
  (510, 16869): TimeSeriesDataset(
      DataFrame[(1502, 15)]
    metadata:
      Series[(12,)]
  )
  (510, 16870): TimeSeriesDataset(
      DataFrame[(1519, 15)]
    metadata:
      Series[(12,)]
  )
  (510, 16871): TimeSeriesDataset(
      DataFrame[(1544, 15)]
    metadata:
      Series[(12,)]
  )
)

In [16]:
class BatchElement(NamedTuple):
    index: None
    data: None
    targets: None
    
    def __repr__(self):
        return repr_mapping(self._asdict(), title=self.__class__.__name__)
    

class Kiwi_Final_ProductDataset(MappingDataset): 
    def __getitem__(self, key):
        # display(key)
        
        t_target = final_product_times.loc[key[0], "t_target"]
        y_target = self.data[key[0]]
        
        y_target = y_target.timeseries.loc[t_target, target]
        
        return BatchElement(key, super().__getitem__(key), (t_target, y_target))

In [17]:
target="Fluo_GFP"
DS = Kiwi_Final_ProductDataset(TSDs);

## Samplers

### setup nonsense

In [18]:
def get_induction_time(s: Series) -> Timestamp:
    # Compute the induction time
    # s = ts.loc[run_id, exp_id]
    inducer = s["InducerConcentration"]
    total_induction = inducer[-1] - inducer[0]

    if pd.isna(total_induction) or total_induction == 0:
        return pd.NA

    diff = inducer.diff()
    mask = pd.notna(diff) & (diff != 0.0)
    inductions = inducer[mask]
    assert len(inductions) == 1, "Multiple Inductions occur!"
    return inductions.first_valid_index()

In [19]:
def get_final_product(s: Series, target) -> Timestamp:
    # Final and target times
    targets = s[target]
    mask = pd.notna(targets)
    targets = targets[mask]
    assert len(targets) >= 1, f"not enough target observations {targets}"
    return targets.index[-1]

In [20]:
def get_time_table(ts: DataFrame, target="Fluo_GFP", t_min="0.6h", delta_t="5m"):
    columns = [
        "slice",
        "t_min",
        "t_induction",
        "t_max",
        "t_target",
    ]
    index = ts.reset_index(level=[2]).index.unique()
    df = DataFrame(index=index, columns=columns)

    min_wait = Timedelta(t_min)

    for idx, slc in tqdm(ts.groupby(level=[0, 1])):
        slc = slc.reset_index(level=[0, 1], drop=True)
        # display(slc)
        t_induction = get_induction_time(slc)
        t_target = get_final_product(slc, target=target)
        if pd.isna(t_induction):
            print(f"{idx}: no t_induction!")
            t_max = get_final_product(slc.loc[slc.index < t_target], target=target)
            assert t_max < t_target
        else:
            assert t_induction < t_target, f"{t_induction=} after {t_target}!"
            t_max = t_induction
        df.loc[idx, "t_max"] = t_max
        
        df.loc[idx, "t_min"] = t_min = slc.index[0] + min_wait
        df.loc[idx, "t_induction"] = t_induction
        df.loc[idx, "t_target"] = t_target
        df.loc[idx, "slice"] = slice(t_min, t_max)
        # = t_final
    return df

In [21]:
final_product_times = get_time_table(ts)

  0%|          | 0/168 [00:00<?, ?it/s]

(510, 16849): no t_induction!
(510, 16851): no t_induction!
(510, 16853): no t_induction!
(510, 16855): no t_induction!
(510, 16857): no t_induction!
(510, 16859): no t_induction!
(510, 16861): no t_induction!
(510, 16863): no t_induction!
(510, 16865): no t_induction!
(510, 16867): no t_induction!
(510, 16869): no t_induction!
(510, 16871): no t_induction!

                                                                  slice  \
run_id experiment_id
439    15325          slice(Timestamp('2020-12-09 09:46:09'), Timest...
       15326          slice(Timestamp('2020-12-09 09:46:09'), Timest...
       15327          slice(Timestamp('2020-12-09 09:46:09'), Timest...
       15328          slice(Timestamp('2020-12-09 09:46:09'), Timest...
       15329          slice(Timestamp('2020-12-09 09:46:09'), Timest...
...                                                                 ...
510    16867          slice(Timestamp('2021-10-26 09:50:08'), Timest...
       16868          slice(Timestamp('2021-10-26 09:50:08'), Timest...
       16869          slice(Timestamp('2021-10-26 09:50:08'), Timest...
       16870          slice(Timestamp('2021-10-26 09:50:08'), Timest...
       16871          slice(Timestamp('2021-10-26 09:50:08'), Timest...

                                    t_min          t_induction  \
run_id experiment_id
439    15325          2020-12-09 09:46:09  2020-12-09 18:39:58
       15326          2020-12-09 09:46:09  2020-12-09 18:39:58
       15327          2020-12-09 09:46:09  2020-12-09 18:09:58
       15328          2020-12-09 09:46:09  2020-12-09 18:09:58
       15329          2020-12-09 09:46:09  2020-12-09 18:39:58
...                                   ...                  ...
510    16867          2021-10-26 09:50:08                 <NA>
       16868          2021-10-26 09:50:08  2021-10-26 19:28:47
       16869          2021-10-26 09:50:08                 <NA>
       16870          2021-10-26 09:50:08  2021-10-26 19:28:47
       16871          2021-10-26 09:50:08                 <NA>

                                    t_max             t_target
run_id experiment_id
439    15325          2020-12-09 18:39:58  2020-12-09 21:53:59
       15326          2020-12-09 18:39:58  2020-12-09 21:53:59
       15327          2020-12-09 18:09:58  2020-12-09 21:53:59
       15328          2020-12-09 18:09:58  2020-12-09 21:53:59
       15329          2020-12-09 18:39:58  2020-12-09 21:53:59
...                                   ...                  ...
510    16867          2021-10-26 21:20:46  2021-10-26 22:20:42
       16868          2021-10-26 19:28:47  2021-10-26 22:20:42
       16869          2021-10-26 21:20:46  2021-10-26 22:20:42
       16870          2021-10-26 19:28:47  2021-10-26 22:20:42
       16871          2021-10-26 21:20:46  2021-10-26 22:20:42

[168 rows x 5 columns]

### the subsampler dictionary

In [22]:
delta_t = Timedelta("5m")

subsamplers = {}

for key in TSDs:
    subsampler = IntervalSampler(
        xmin=final_product_times.loc[key, "t_min"],
        xmax=final_product_times.loc[key, "t_max"],
        # offset=t_0,
        deltax=lambda k: k * delta_t,
        stride=None,
        shuffle=True,
    )
    subsamplers[key] = subsampler
sampler = HierarchicalSampler(TSDs, subsamplers, shuffle=True)

dict(
  (439, 15325): <__main__.IntervalSampler object at 0x7f38eb429a30>
  (439, 15326): <__main__.IntervalSampler object at 0x7f38eb40b160>
  (439, 15327): <__main__.IntervalSampler object at 0x7f38eb429640>
  ...
  (510, 16869): <__main__.IntervalSampler object at 0x7f38e8aa4970>
  (510, 16870): <__main__.IntervalSampler object at 0x7f38e8aa46d0>
  (510, 16871): <__main__.IntervalSampler object at 0x7f38e8aa4430>
)

In [23]:
ts.loc[439].loc[15325]#.loc[Timedelta('0 days 00:32:18'): Timedelta('0 days 01:28:47')]

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2020-12-09 09:10:09,0.0,0.0,36.389999,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:19,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.27,NaN,0.00,NaN
2020-12-09 09:10:24,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:25,0.0,100.0,36.130001,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:34,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.28,NaN,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-09 23:31:40,10.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,52.720001,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:31:42,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN
2020-12-09 23:31:51,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,52.950001,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:32:02,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,53.240002,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:32:05,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN

In [24]:
idx = next(iter(sampler))
ts.loc[(439, 15325)]

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2020-12-09 09:10:09,0.0,0.0,36.389999,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:19,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.27,NaN,0.00,NaN
2020-12-09 09:10:24,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:25,0.0,100.0,36.130001,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:34,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.28,NaN,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-09 23:31:40,10.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,52.720001,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:31:42,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN
2020-12-09 23:31:51,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,52.950001,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:32:02,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,53.240002,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:32:05,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN

### store indices to .csv

In [25]:
# df = DataFrame(list(iter(sampler)), columns=["idx", "slice"])
# df["start"] = df["slice"].apply(lambda x: x.start) / Timedelta("1h")
# df["stop"] = df["slice"].apply(lambda x: x.stop) / Timedelta("1h")
# df["run_id"], df["experiment_id"] = zip(*df.idx)
# df = df[["run_id", "experiment_id", "start", "stop"]].round(2)
# df = df.sort_values(["run_id", "experiment_id", "start", "stop"])

# DataLoader

## Simple (no collate_fn)

In [26]:
collate = lambda x: x

dloader = DataLoader(DS, sampler=sampler, collate_fn = collate, batch_size=8)

In [27]:
batch = next(iter(dloader))

[BatchElement(
   index  : ((449, 15647), slice(Timestamp('2021-02-10 09:55:55'), Timestamp('2021-02-10 11:05:55'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(110, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2021-02-10 22:02:12'), 263275.0)
 ),
 BatchElement(
   index  : ((484, 16353), slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 09:57:30'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(90, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2021-07-28 21:38:25'), 92416.25)
 ),
 BatchElement(
   index  : ((475, 16146), slice(Timestamp('2021-05-05 10:03:44'), Timestamp('2021-05-05 12:33:44'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(245, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2021-05-05 20:14:54'), 59522.5)
 ),
 BatchElement(
   index  : ((439, 15336), slice(Timestamp('2020-12-09 09:46:09'), Timestamp('2020-12-09 16:01:09'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(634, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2020-12-09 22:23:55'), 825.0)
 ),
 BatchElement(
   index  : ((449, 15644), slice(Timestamp('2021-02-10 09:55:55'), Timestamp('2021-02-10 16:25:55'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(620, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2021-02-10 22:02:12'), 380965.0)
 ),
 BatchElement(
   index  : ((484, 16350), slice(Timestamp('2021-07-28 09:32:30'), Timestamp('2021-07-28 14:12:30'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(991, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2021-07-28 21:38:25'), 92146.25)
 ),
 BatchElement(
   index  : ((468, 16002), slice(Timestamp('2021-04-07 10:21:09'), Timestamp('2021-04-07 11:51:09'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(138, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2021-04-07 21:27:26'), 194168.75)
 ),
 BatchElement(
   index  : ((468, 16010), slice(Timestamp('2021-04-07 10:21:09'), Timestamp('2021-04-07 12:16:09'), None))
   data   : TimeSeriesSlice(
     timeseries=DataFrame[(177, 15)]
     metadata=Series[(12,)]
   )
   targets: (Timestamp('2021-04-07 21:58:35'), 326628.75)
 )]

## With PreProcessing

In [28]:
ts

variable                                  Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09       0.0            0.0
                     2020-12-09 09:10:19       0.0            0.0
                     2020-12-09 09:10:24       0.0          100.0
                     2020-12-09 09:10:25       0.0          100.0
                     2020-12-09 09:10:34       0.0          100.0
...                                            ...            ...
510    16871         2021-10-26 22:41:26       5.0            0.0
                     2021-10-26 22:42:11       5.0            0.0
                     2021-10-26 22:42:20       5.0            0.0
                     2021-10-26 22:43:22       5.0            0.0
                     2021-10-26 22:43:31       5.0            0.0

variable                                  Temperature  Acetate  Base  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09    36.389999      NaN   NaN
                     2020-12-09 09:10:19          NaN      NaN   NaN
                     2020-12-09 09:10:24          NaN      NaN   NaN
                     2020-12-09 09:10:25    36.130001      NaN   NaN
                     2020-12-09 09:10:34          NaN      NaN   NaN
...                                               ...      ...   ...
510    16871         2021-10-26 22:41:26          NaN      NaN   NaN
                     2021-10-26 22:42:11    37.450001      NaN   NaN
                     2021-10-26 22:42:20          NaN      NaN   NaN
                     2021-10-26 22:43:22    37.439999      NaN   NaN
                     2021-10-26 22:43:31          NaN      NaN   NaN

variable                                  Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09                            0.0
                     2020-12-09 09:10:19                            0.0
                     2020-12-09 09:10:24                            0.0
                     2020-12-09 09:10:25                            0.0
                     2020-12-09 09:10:34                            0.0
...                                                                 ...
510    16871         2021-10-26 22:41:26                         1061.0
                     2021-10-26 22:42:11                         1061.0
                     2021-10-26 22:42:20                         1061.0
                     2021-10-26 22:43:22                         1061.0
                     2021-10-26 22:43:31                         1061.0

variable                                  Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09                      0.000000
                     2020-12-09 09:10:19                      0.000000
                     2020-12-09 09:10:24                      0.000000
                     2020-12-09 09:10:25                      0.000000
                     2020-12-09 09:10:34                      0.000000
...                                                                ...
510    16871         2021-10-26 22:41:26                   3787.307373
                     2021-10-26 22:42:11                   3787.307373
                     2021-10-26 22:42:20                   3787.307373
                     2021-10-26 22:43:22                   3787.307373
                     2021-10-26 22:43:31                   3787.307373

variable                                        DOT  Glucose  OD600  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09        NaN      NaN    NaN
                     2020-12-09 09:10:19   0.000000      NaN    NaN
                     2020-12-09 09:10:24        NaN      NaN    NaN
                     2020-12-09 09:10:25        NaN      NaN    NaN
                     2020-12-09 09:10:34   0.000000      NaN    NaN
...                                             ...      ...    ...
510    16871         2021-10-26 22:41:26        NaN      NaN    NaN
                     2021-10-26 22:42:11        NaN      NaN    NaN
                     2021-10-26 22:42:20  79.459999      NaN    NaN
                     2021-10-26 22:43:22        NaN      NaN    NaN
                     2021-10-26 22:43:31  78.860001      NaN    NaN

variable                                  Probe_Volume        pH  Fluo_GFP  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09           0.0       NaN       NaN
                     2020-12-09 09:10:19           0.0  7.270000       NaN
                     2020-12-09 09:10:24           0.0       NaN       NaN
                     2020-12-09 09:10:25           0.0       NaN       NaN
                     2020-12-09 09:10:34           0.0  7.280000       NaN
...                                                ...       ...       ...
510    16871         2021-10-26 22:41:26        5500.0       NaN       NaN
                     2021-10-26 22:42:11        5500.0       NaN       NaN
                     2021-10-26 22:42:20        5500.0  7.320229       NaN
                     2021-10-26 22:43:22        5500.0       NaN       NaN
                     2021-10-26 22:43:31        5500.0  7.336412       NaN

variable                                  InducerConcentration      Volume
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09                   0.0         NaN
                     2020-12-09 09:10:19                   0.0         NaN
                     2020-12-09 09:10:24                   0.0         NaN
                     2020-12-09 09:10:25                   0.0         NaN
                     2020-12-09 09:10:34                   0.0         NaN
...                                                        ...         ...
510    16871         2021-10-26 22:41:26                   0.0 -312.692749
                     2021-10-26 22:42:11                   0.0         NaN
                     2021-10-26 22:42:20                   0.0         NaN
                     2021-10-26 22:43:22                   0.0         NaN
                     2021-10-26 22:43:31                   0.0         NaN

[269004 rows x 15 columns]

## With Post-Processing

Batch ⟶ Post-Processed Batch

- convert things to `tensor`s if not already done
- combine `list[Tensor]` to `Tensor` / `PaddedTensor` / `PackedTensor`

In [114]:
from tsdm.encoders.modular import *
ds = KIWI_RUNS()
ts = ds.timeseries.drop([355, 445, 482]).astype("float64")
md = ds.metadata.drop([355, 445, 482])
ModularEncoders

INFO:tsdm.datasets.base._base:KIWI_RUNS: START cleaning dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/units already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE cleaning dataset
INFO:tsdm.datasets.base._base:KIWI_RUNS: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE loading dataset!

{'ChainedEncoder': tsdm.encoders.modular._modular.ChainedEncoder,
 'DataFrameEncoder': tsdm.encoders.modular._modular.DataFrameEncoder,
 'DateTimeEncoder': tsdm.encoders.modular._modular.DateTimeEncoder,
 'FloatEncoder': tsdm.encoders.modular._modular.FloatEncoder,
 'IdentityEncoder': tsdm.encoders.modular._modular.IdentityEncoder,
 'MinMaxScaler': tsdm.encoders.modular._modular.MinMaxScaler,
 'Standardizer': tsdm.encoders.modular._modular.Standardizer,
 'TensorEncoder': tsdm.encoders.modular._modular.TensorEncoder,
 'Time2Float': tsdm.encoders.modular._modular.Time2Float,
 'IntEncoder': tsdm.encoders.modular._modular.IntEncoder,
 'TripletEncoder': tsdm.encoders.modular._modular.TripletEncoder,
 'ConcatEncoder': tsdm.encoders.modular._modular.ConcatEncoder}

In [116]:
ts.reset_index([0,1], drop=True)

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2020-12-09 09:10:09,0.0,0.0,36.389999,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
2020-12-09 09:10:19,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.270000,NaN,0.0,NaN
2020-12-09 09:10:24,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
2020-12-09 09:10:25,0.0,100.0,36.130001,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
2020-12-09 09:10:34,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.280000,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-26 22:41:26,5.0,0.0,NaN,NaN,NaN,1061.0,3787.307373,NaN,NaN,NaN,5500.0,NaN,NaN,0.0,-312.692749
2021-10-26 22:42:11,5.0,0.0,37.450001,NaN,NaN,1061.0,3787.307373,NaN,NaN,NaN,5500.0,NaN,NaN,0.0,NaN
2021-10-26 22:42:20,5.0,0.0,NaN,NaN,NaN,1061.0,3787.307373,79.459999,NaN,NaN,5500.0,7.320229,NaN,0.0,NaN
2021-10-26 22:43:22,5.0,0.0,37.439999,NaN,NaN,1061.0,3787.307373,NaN,NaN,NaN,5500.0,NaN,NaN,0.0,NaN
2021-10-26 22:43:31,5.0,0.0,NaN,NaN,NaN,1061.0,3787.307373,78.860001,NaN,NaN,5500.0,7.336412,NaN,0.0,NaN

In [117]:
preprocessor = ChainedEncoder(
    ConcatEncoder(axis=-1),
    TensorEncoder(),
    DataFrameEncoder(
        Standardizer() @ FloatEncoder("float64"),
        index_encoders = MinMaxScaler() @ DateTimeEncoder(unit="h"),
    ),
    TripletEncoder(),
)

ChainedEncoder[ConcatEncoder, TensorEncoder(), DataFrameEncoder(                    col                               encoder
section partition
index   0          <NA>       (MinMaxScaler, DateTimeEncoder)
columns 0          <NA>  (Standardizer([-1]), FloatEncoder())
), TripletEncoder]

In [147]:
original.index = original.index.round("s")

In [148]:
original = ts.loc[439,15325].round(2)
preprocessor.fit(ts.reset_index([0,1], drop=True))
original

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2020-12-09 09:10:09,0.0,0.0,36.39,NaN,NaN,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:19,0.0,0.0,NaN,NaN,NaN,0.0,0.00,0.00,NaN,NaN,0.0,7.27,NaN,0.00,NaN
2020-12-09 09:10:24,0.0,100.0,NaN,NaN,NaN,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:25,0.0,100.0,36.13,NaN,NaN,0.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
2020-12-09 09:10:34,0.0,100.0,NaN,NaN,NaN,0.0,0.00,0.00,NaN,NaN,0.0,7.28,NaN,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-09 23:31:40,10.0,0.0,NaN,NaN,NaN,2431.0,2188.03,52.72,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:31:42,0.0,0.0,NaN,NaN,NaN,2431.0,2188.03,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN
2020-12-09 23:31:51,0.0,0.0,NaN,NaN,NaN,2431.0,2188.03,52.95,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:32:02,0.0,0.0,NaN,NaN,NaN,2431.0,2188.03,53.24,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
2020-12-09 23:32:05,0.0,0.0,NaN,NaN,NaN,2431.0,2188.03,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN

In [149]:
encoded = preprocessor.encode(original)

tensor([[ 0.0000e+00, -2.3308e-01,  3.7417e+00,  ..., -2.6726e-01,
         -2.6726e-01, -2.6726e-01],
        [ 0.0000e+00, -2.3308e-01, -2.6726e-01,  ..., -2.6726e-01,
         -2.6726e-01, -2.6726e-01],
        [ 0.0000e+00, -2.1963e-01, -2.6726e-01,  ..., -2.6726e-01,
         -2.6726e-01, -2.6726e-01],
        ...,
        [ 1.8614e-03,         nan, -2.6726e-01,  ...,  3.7417e+00,
         -2.6726e-01, -2.6726e-01],
        [ 1.8614e-03, -2.3306e-01, -2.6726e-01,  ..., -2.6726e-01,
          3.7417e+00, -2.6726e-01],
        [ 1.8614e-03,         nan, -2.6726e-01,  ..., -2.6726e-01,
         -2.6726e-01,  3.7417e+00]])

In [164]:
reconstructed = preprocessor.decode(encoded).round(2).values.clip(min=-0.0)

array([[ -0.0000,  -0.0000,  36.3900, ...,      nan,  -0.0000,      nan],
       [ -0.0000,  -0.0000,      nan, ...,      nan,  -0.0000,      nan],
       [ -0.0000, 100.0000,      nan, ...,      nan,  -0.0000,      nan],
       ...,
       [ -0.0000,  -0.0000,      nan, ...,      nan,   0.0500,      nan],
       [ -0.0000,  -0.0000,      nan, ...,      nan,   0.0500,      nan],
       [ -0.0000,  -0.0000,      nan, ...,      nan,   0.0500,      nan]])

In [166]:
arr = reconstructed = preprocessor.decode(encoded).round(2).values

In [ ]:
reconstructed = preprocessor.decode(encoded).round(2).clip

In [153]:
(original.index == reconstructed.index).mean(), (original.columns == reconstructed.columns).mean()

(1.0, 1.0)

In [155]:
np.mean(np.mean(np.abs(original -reconstructed)))

7.936507943899386e-05

In [143]:
mask = ~pd.isna(original["Fluo_GFP"])
original.loc[mask, "Fluo_GFP"]

measurement_time
2020-12-09 09:48:38      1012.500000
2020-12-09 11:18:43      1042.500000
2020-12-09 12:48:48       872.500000
2020-12-09 14:18:48      1022.500000
2020-12-09 15:49:34       842.500000
2020-12-09 17:19:29     19028.125000
2020-12-09 18:51:39     44928.125000
2020-12-09 20:23:46    538946.875000
2020-12-09 21:53:59    200472.921875
Name: Fluo_GFP, dtype: float64

In [144]:
reconstructed.loc[mask, "Fluo_GFP"]

time
2020-12-09 09:48:38      1012.500018
2020-12-09 11:18:43      1042.500008
2020-12-09 12:48:48       872.499996
2020-12-09 14:18:48      1022.499987
2020-12-09 15:49:34       842.500006
2020-12-09 17:19:29     19028.124696
2020-12-09 18:51:39     44928.122910
2020-12-09 20:23:46    538946.887979
2020-12-09 21:53:59    200472.916012
Name: Fluo_GFP, dtype: float64

In [37]:
class Batch(NamedTuple):
    index: Tensor
    timeseries: Tensor
    metadata: Tensor
    targets: Tensor
    
    def __repr__(self):
        return repr_mapping(self._asdict(), title=self.__class__.__name__, repr_fun = repr_array)

    

def mycollate(batch: list):
    index : list[Tensor] = []
    timeseries: list[Tensor] = []
    metadata:   list[Tensor] = []
    targets: list[Tensor] = []
    
    for idx, (ts, md), (t, y) in batch:
        index.append(torch.tensor(idx[0], dtype=int))
        timeseries.append( preprocessor.encode(ts) )
        metadata.append(md)
        targets.append(torch.tensor(y))
    return Batch(torch.stack(index), timeseries, metadata, torch.stack(targets) )

In [38]:
dloader = DataLoader(DS, sampler=sampler, collate_fn = mycollate, batch_size=8)
batch = next(iter(dloader))

Batch(
  index     : Tensor[torch.Size([8, 2])]
  timeseries: [Tensor[torch.Size([2700, 17])], Tensor[torch.Size([10365, 17])], Tensor[torch.Size([8790, 17])], Tensor[torch.Size([4605, 17])], Tensor[torch.Size([5730, 17])], Tensor[torch.Size([20565, 17])], Tensor[torch.Size([825, 17])], Tensor[torch.Size([7530, 17])]]
  metadata  : [Series[(12,)], Series[(12,)], Series[(12,)], Series[(12,)], Series[(12,)], Series[(12,)], Series[(12,)], Series[(12,)]]
  targets   : Tensor[torch.Size([8])]
)

In [39]:
index

NameError: name 'index' is not defined