In [1]:
import tsdm
import numpy as np

In [2]:
x = tsdm.load_dataset('electricity')
x

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 01:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,2.538071,22.048364,1.737619,150.406504,85.365854,303.571429,11.305822,282.828283,68.181818,72.043011,...,276.945039,28200.0,1616.033755,1363.636364,29.986962,5.851375,697.102722,176.961603,651.026393,7621.621622
2014-12-31 23:15:00,2.538071,21.337127,1.737619,166.666667,81.707317,324.404762,11.305822,252.525253,64.685315,72.043011,...,279.800143,28300.0,1569.620253,1340.909091,29.986962,9.947338,671.641791,168.614357,669.354839,6702.702703
2014-12-31 23:30:00,2.538071,20.625889,1.737619,162.601626,82.926829,318.452381,10.175240,242.424242,61.188811,74.193548,...,284.796574,27800.0,1556.962025,1318.181818,27.379400,9.362200,670.763828,153.589316,670.087977,6864.864865
2014-12-31 23:45:00,1.269036,21.337127,1.737619,166.666667,85.365854,285.714286,10.175240,225.589226,64.685315,72.043011,...,246.252677,28000.0,1443.037975,909.090909,26.075619,4.095963,664.618086,146.911519,646.627566,6540.540541
2015-01-01 00:00:00,2.538071,19.914651,1.737619,178.861789,84.146341,279.761905,10.175240,249.158249,62.937063,69.892473,...,188.436831,27800.0,1409.282700,954.545455,27.379400,4.095963,628.621598,131.886477,673.020528,7135.135135

In [3]:
observed = np.random.choice([True, False], size=x.shape)
x = x.where(observed)
display(observed, x)

array([[False, False,  True, ..., False, False,  True],
       [False, False,  True, ...,  True,  True, False],
       [ True, False,  True, ...,  True,  True, False],
       ...,
       [False, False, False, ...,  True, False, False],
       [ True, False,  True, ...,  True,  True,  True],
       [ True, False,  True, ..., False, False, False]])

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,NaN,NaN,0.000000,0.000000,NaN,0.0000,0.0,NaN,NaN,0.000000
2011-01-01 00:30:00,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,...,0.000000,NaN,NaN,0.000000,0.000000,NaN,0.0,0.000000,0.000000,NaN
2011-01-01 00:45:00,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000,NaN,...,0.000000,0.0,0.000000,0.000000,NaN,0.0000,0.0,0.000000,0.000000,NaN
2011-01-01 01:00:00,0.000000,NaN,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,NaN,...,0.000000,0.0,0.000000,0.000000,NaN,0.0000,0.0,NaN,NaN,NaN
2011-01-01 01:15:00,0.000000,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,...,0.000000,NaN,0.000000,NaN,0.000000,0.0000,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,NaN,NaN,1.737619,NaN,NaN,NaN,NaN,282.828283,68.181818,NaN,...,NaN,NaN,1616.033755,1363.636364,NaN,NaN,NaN,176.961603,651.026393,NaN
2014-12-31 23:15:00,NaN,21.337127,1.737619,166.666667,NaN,NaN,11.305822,252.525253,64.685315,72.043011,...,279.800143,NaN,1569.620253,1340.909091,29.986962,NaN,NaN,168.614357,NaN,NaN
2014-12-31 23:30:00,NaN,NaN,NaN,NaN,82.926829,318.452381,NaN,242.424242,NaN,NaN,...,NaN,27800.0,1556.962025,1318.181818,27.379400,9.3622,NaN,153.589316,NaN,NaN
2014-12-31 23:45:00,1.269036,NaN,1.737619,166.666667,NaN,NaN,NaN,NaN,64.685315,72.043011,...,NaN,28000.0,NaN,NaN,NaN,NaN,NaN,146.911519,646.627566,6540.540541
2015-01-01 00:00:00,2.538071,NaN,1.737619,178.861789,84.146341,NaN,NaN,NaN,62.937063,NaN,...,NaN,27800.0,1409.282700,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2.1 Triplet Format

The data is represented as a set of triplets (time, variable, value). All NaNs are dropped.

In [4]:
dense_x = tsdm.make_dense_triplets(x)
dense_x

                    variable         value
time
2011-01-01 00:15:00   MT_003      0.000000
2011-01-01 00:15:00   MT_004      0.000000
2011-01-01 00:15:00   MT_005      0.000000
2011-01-01 00:15:00   MT_006      0.000000
2011-01-01 00:15:00   MT_007      0.000000
...                      ...           ...
2015-01-01 00:00:00   MT_352     23.255814
2015-01-01 00:00:00   MT_356     16.472868
2015-01-01 00:00:00   MT_359     28.490028
2015-01-01 00:00:00   MT_362  27800.000000
2015-01-01 00:00:00   MT_363   1409.282700

[25947501 rows x 2 columns]

### 2.2 Sparse Triplet format

The same as before, but the variable tensor is encoded in a one-hot fashion, and the tensor is stored as a sparse tensor

In [5]:
sparse_x = tsdm.make_sparse_triplets(x)
sparse_x

,value,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-01-01 00:00:00,23.255814,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2015-01-01 00:00:00,16.472868,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2015-01-01 00:00:00,28.490028,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2015-01-01 00:00:00,27800.000000,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2015-01-01 00:00:00,1409.282700,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

### 2.3 Masked Format

Here we get 3 tensors:

- x: the original data
- m: a boolean mask, 1: value observed, 0: value not observed (NaN)
- d: time since the channel was last observed

In [6]:
x, m, d = tsdm.make_masked_format(x)
display(x, m, d)

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,NaN,NaN,0.000000,0.000000,NaN,0.0000,0.0,NaN,NaN,0.000000
2011-01-01 00:30:00,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,...,0.000000,NaN,NaN,0.000000,0.000000,NaN,0.0,0.000000,0.000000,NaN
2011-01-01 00:45:00,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000,NaN,...,0.000000,0.0,0.000000,0.000000,NaN,0.0000,0.0,0.000000,0.000000,NaN
2011-01-01 01:00:00,0.000000,NaN,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,NaN,...,0.000000,0.0,0.000000,0.000000,NaN,0.0000,0.0,NaN,NaN,NaN
2011-01-01 01:15:00,0.000000,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,...,0.000000,NaN,0.000000,NaN,0.000000,0.0000,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,NaN,NaN,1.737619,NaN,NaN,NaN,NaN,282.828283,68.181818,NaN,...,NaN,NaN,1616.033755,1363.636364,NaN,NaN,NaN,176.961603,651.026393,NaN
2014-12-31 23:15:00,NaN,21.337127,1.737619,166.666667,NaN,NaN,11.305822,252.525253,64.685315,72.043011,...,279.800143,NaN,1569.620253,1340.909091,29.986962,NaN,NaN,168.614357,NaN,NaN
2014-12-31 23:30:00,NaN,NaN,NaN,NaN,82.926829,318.452381,NaN,242.424242,NaN,NaN,...,NaN,27800.0,1556.962025,1318.181818,27.379400,9.3622,NaN,153.589316,NaN,NaN
2014-12-31 23:45:00,1.269036,NaN,1.737619,166.666667,NaN,NaN,NaN,NaN,64.685315,72.043011,...,NaN,28000.0,NaN,NaN,NaN,NaN,NaN,146.911519,646.627566,6540.540541
2015-01-01 00:00:00,2.538071,NaN,1.737619,178.861789,84.146341,NaN,NaN,NaN,62.937063,NaN,...,NaN,27800.0,1409.282700,NaN,NaN,NaN,NaN,NaN,NaN,NaN

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0,0,1,1,1,1,1,1,1,0,...,0,0,1,1,0,1,1,0,0,1
2011-01-01 00:30:00,0,0,1,1,1,0,0,0,1,0,...,1,0,0,1,1,0,1,1,1,0
2011-01-01 00:45:00,1,0,1,0,1,0,1,1,1,0,...,1,1,1,1,0,1,1,1,1,0
2011-01-01 01:00:00,1,0,1,1,1,0,1,1,1,0,...,1,1,1,1,0,1,1,0,0,0
2011-01-01 01:15:00,1,0,1,1,0,1,0,0,0,0,...,1,0,1,0,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,0,0,1,0,0,0,0,1,1,0,...,0,0,1,1,0,0,0,1,1,0
2014-12-31 23:15:00,0,1,1,1,0,0,1,1,1,1,...,1,0,1,1,1,0,0,1,0,0
2014-12-31 23:30:00,0,0,0,0,1,1,0,1,0,0,...,0,1,1,1,1,1,0,1,0,0
2014-12-31 23:45:00,1,0,1,1,0,0,0,0,1,1,...,0,1,0,0,0,0,0,1,1,1
2015-01-01 00:00:00,1,0,1,1,1,0,0,0,1,0,...,0,1,1,0,0,0,0,0,0,0

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
2011-01-01 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2011-01-01 00:45:00,0 days 00:30:00,0 days 00:15:00,0 days 00:30:00,0 days 00:15:00,0 days 00:30:00,0 days 00:15:00,0 days 00:30:00,0 days 00:30:00,0 days 00:30:00,0 days 00:15:00,...,0 days 00:30:00,0 days 00:30:00,0 days 00:30:00,0 days 00:30:00,0 days 00:15:00,0 days 00:30:00,0 days 00:30:00,0 days 00:30:00,0 days 00:30:00,0 days 00:15:00
2011-01-01 01:00:00,0 days 00:45:00,0 days 00:15:00,0 days 00:45:00,0 days 00:30:00,0 days 00:45:00,0 days 00:15:00,0 days 00:45:00,0 days 00:45:00,0 days 00:45:00,0 days 00:15:00,...,0 days 00:45:00,0 days 00:45:00,0 days 00:45:00,0 days 00:45:00,0 days 00:15:00,0 days 00:45:00,0 days 00:45:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2011-01-01 01:15:00,0 days 01:00:00,0 days 00:15:00,0 days 01:00:00,0 days 00:45:00,0 days 00:15:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 01:00:00,0 days 00:15:00,0 days 01:00:00,0 days 00:15:00,0 days 00:30:00,0 days 01:00:00,0 days 01:00:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,0 days 00:15:00,0 days 00:15:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:30:00,0 days 01:00:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 01:00:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:30:00,0 days 01:30:00,0 days 00:15:00
2014-12-31 23:15:00,0 days 00:15:00,0 days 00:30:00,0 days 00:45:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:30:00,0 days 00:45:00,0 days 01:15:00,0 days 00:30:00,...,0 days 00:30:00,0 days 00:15:00,0 days 01:15:00,0 days 00:45:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:45:00,0 days 00:15:00,0 days 00:15:00
2014-12-31 23:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:30:00,0 days 00:30:00,0 days 00:15:00,0 days 01:00:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:30:00,0 days 01:30:00,0 days 01:00:00,0 days 00:45:00,0 days 00:30:00,0 days 00:15:00,0 days 01:00:00,0 days 00:15:00,0 days 00:15:00
2014-12-31 23:45:00,0 days 00:30:00,0 days 00:15:00,0 days 00:30:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:30:00,0 days 00:30:00,...,0 days 00:15:00,0 days 00:45:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 01:15:00,0 days 00:30:00,0 days 00:30:00
2015-01-01 00:00:00,0 days 00:45:00,0 days 00:15:00,0 days 00:45:00,0 days 00:45:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:45:00,0 days 00:15:00,...,0 days 00:15:00,0 days 01:00:00,0 days 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00

## 3. Visualizing the data

In [6]:
import tsdm
import numpy as np
from pandas import NA, DataFrame, testing
x = [[47, 49, NA, 40, NA, 43, 55],
     [NA, 15, 14, NA, NA, NA, 15]]
t = [0, 0.1, 0.6, 1.6, 2.2, 2.5, 3.1]

d = [[0.0, 0.1, 0.5, 1.5, 0.6, 0.9, 0.6],
     [0.0, 0.1, 0.5, 1.0, 1.6, 1.9, 2.5]]

m = [[1, 1, 0, 1, 0, 1, 1],
     [0, 1, 1, 0, 0, 0, 1]]

data = DataFrame(x, columns=t).T
mask = DataFrame(m, columns=t).T
diff = DataFrame(d, columns=t).T

x, m, d = tsdm.make_masked_format(data)
testing.assert_frame_equal(x, data, check_dtype=False)
testing.assert_frame_equal(m, mask, check_dtype=False)
testing.assert_frame_equal(d, diff, check_dtype=False)

    0.0   0.1   0.6   1.6    2.2    2.5    3.1
0  True  True  True  True  False  False  False
1  True  True  True  True   True   True   True

   0.0  0.1  0.6  1.6  2.2  2.5  3.1
0  0.0  0.1  0.5  1.5  0.6  0.9  0.6
1  0.0  0.1  0.5  1.0  1.6  1.9  2.5

   0.0  0.1  0.6  1.6  2.2  2.5  3.1
0  0.0  0.1  0.5  1.5  0.6  0.9  0.6
1  0.0  0.1  0.5  1.0  1.6  1.9  2.5

In [10]:
x = np.array([[47, 49, np.nan, 40, np.nan, 43, 55],
              [np.nan, 15, 14, np.nan, ]] )

<ipython-input-10-87ec92209d97>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[47, 49, np.nan, 40, np.nan, 43, 55],

In [11]:
pd.NA

NameError: name 'pd' is not defined