# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
import pandas

logging.basicConfig(level=logging.DEBUG)
pandas.options.display.max_rows = 6

In [2]:
from tsdm.datasets import USHCN

INFO:tsdm.config._config.Config:Available Models: {'mTAN', 'Latent-ODE', 'IP-Net', 'NODE', 'Informer', 'GRU-ODE-Bayes', 'ODE-RNN', 'BRITS', 'TPA', 'M-RNN', 'SET-TS', 'NCDE', 'N-BEATS', 'TFT'}
INFO:tsdm.config._config.Config:Available Datasets: {'Household Consumption', 'M5', 'Physionet 2019', 'Traffic', 'Air Quality', 'UWAVE', 'Physionet 2012', 'Character Trajectories', 'M4', 'tourism2', 'MuJoCo', 'USHCN', 'Electricity', 'tourism1', 'Human Activity', 'Air Quality Multi-Site', 'M3'}
DEBUG:tsdm.config._config.Config:Initializing folder structure
DEBUG:tsdm.config._config.Config:Created folder structure in /home/rscholz/.tsdm

Creating folder PosixPath('/home/rscholz/.tsdm/datasets').
Creating folder PosixPath('/home/rscholz/.tsdm/models').
Creating folder PosixPath('/home/rscholz/.tsdm/logs').
Creating folder PosixPath('/home/rscholz/.tsdm/rawdata').

DEBUG:tsdm.utils.decorators._decorators:>>>>> Creating decorator <function timefun at 0x7f4e388fc180> <<<<<
DEBUG:tsdm.utils.decorators._decorators:DETECTED SIGNATURE:
	1 POSITIONAL_ONLY       (mandatory)
	0 POSITIONAL_ONLY       (optional)
	0 POSITIONAL_OR_KEYWORD (mandatory)
	0 POSITIONAL_OR_KEYWORD (optional)
	0 VAR_POSITIONAL
	0 KEYWORD_ONLY          (mandatory)
	2 KEYWORD_ONLY          (optional)
	0 VAR_KEYWORD
DEBUG:tsdm.utils.decorators._decorators:>>>>> Creating decorator <function vectorize at 0x7f4e388fc5e0> <<<<<
DEBUG:tsdm.utils.decorators._decorators:DETECTED SIGNATURE:
	1 POSITIONAL_ONLY       (mandatory)
	0 POSITIONAL_ONLY       (optional)
	0 POSITIONAL_OR_KEYWORD (mandatory)
	0 POSITIONAL_OR_KEYWORD (optional)
	0 VAR_POSITIONAL
	1 KEYWORD_ONLY          (mandatory)
	0 KEYWORD_ONLY          (optional)
	0 VAR_KEYWORD
DEBUG:tsdm.utils.decorators._decorators:>>>>> Creating decorator <function wrap_func at 0x7f4e388fcc20> <<<<<
DEBUG:tsdm.utils.decorators._decorators:DETECTED SIGNATURE:
	1 POSITIONAL_ONLY       (mandatory)
	0 POSITIONAL_ONLY       (optional)
	0 POSITIONAL_OR_KEYWORD (mandatory)
	0 POSITIONAL_OR_KEYWORD (optional)
	0 VAR_POSITIONAL
	0 KEYWORD_ONLY          (mandatory)
	3 KEYWORD_ONLY          (optional)
	0 VAR_KEYWORD
DEBUG:tsdm.utils.decorators._decorators:>>>>> Creating decorator <function wrap_method at 0x7f4e388fcd60> <<<<<
DEBUG:tsdm.utils.decorators._decorators:DETECTED SIGNATURE:
	1 POSITIONAL_ONLY       (mandatory)
	0 POSITIONAL_ONLY       (optional)
	0 POSITIONAL_OR_KEYWORD (mandatory)
	0 POSITIONAL_OR_KEYWORD (optional)
	0 VAR_POSITIONAL
	0 KEYWORD_ONLY          (mandatory)
	3 KEYWORD_ONLY          (optional)
	0 VAR_KEYWORD
DEBUG:tsdm.utils.decorators._decorators:>>>>> Creating decorator <function return_namedtuple at 0x7f4e388fccc0> <<<<<
DEBUG:tsdm.utils.decorators._decorators:DETECTED SIGNATURE:
	1 POSITIONAL_ONLY       (mandatory)
	0 POSITIONAL_ONLY       (optional)
	0 POSITIONAL_OR_KEYWORD (mandatory)
	0 POSITIONAL_OR_KEYWORD (optional)
	0 VAR_POSITIONAL
	0 KEYWORD_ONLY          (mandatory)
	2 KEYWORD_ONLY          (optional)
	0 VAR_KEYWORD
/home/rscholz/Projects/KIWI/tsdm/src/tsdm/utils/remote.py:15: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function BaseEncoder.fit at 0x7f4e0e25a520>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function IdentityEncoder.encode at 0x7f4e0e25aa20>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function IdentityEncoder.decode at 0x7f4e0e25aac0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function ProductEncoder.fit at 0x7f4e0e25b560>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function ProductEncoder.encode at 0x7f4e0e25b600>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function ProductEncoder.decode at 0x7f4e0e25b6a0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function ChainedEncoder.fit at 0x7f4e0e25bf60>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function ChainedEncoder.encode at 0x7f4e0df44040>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function ChainedEncoder.decode at 0x7f4e0df440e0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function MappingEncoder.fit at 0x7f4e0df447c0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function MappingEncoder.encode at 0x7f4e0df44860>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function MappingEncoder.decode at 0x7f4e0df44900>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function DuplicateEncoder.fit at 0x7f4e0df44c20>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function DuplicateEncoder.encode at 0x7f4e0df44cc0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function DuplicateEncoder.decode at 0x7f4e0df44d60>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function CloneEncoder.fit at 0x7f4e0e25a8e0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function CloneEncoder.encode at 0x7f4e0df44ea0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function CloneEncoder.decode at 0x7f4e0df45080>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function BoundaryEncoder.fit at 0x7f4e0df45d00>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function BoundaryEncoder.encode at 0x7f4e0df45da0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function BoundaryEncoder.decode at 0x7f4e0df45e40>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function Standardizer.fit at 0x7f4e0df46de0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function Standardizer.encode at 0x7f4e0df46e80>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function Standardizer.decode at 0x7f4e0df46f20>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function LinearScaler.fit at 0x7f4e0df477e0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function LinearScaler.encode at 0x7f4e0df47880>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function LinearScaler.decode at 0x7f4e0df47920>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function MinMaxScaler.fit at 0x7f4e0df47e20>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function MinMaxScaler.encode at 0x7f4e0df64040>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function MinMaxScaler.decode at 0x7f4e0df640e0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function LogEncoder.fit at 0x7f4e0df64400>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function LogEncoder.encode at 0x7f4e0df644a0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function LogEncoder.decode at 0x7f4e0df64540>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function BaseEncoder.fit at 0x7f4e0e25a520>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0> to <function LogitEncoder.encode at 0x7f4e0df647c0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding pre hook <function BaseEncoder._pre_decode_hook at 0x7f4e0e25a840> to <function LogitEncoder.decode at 0x7f4e0df64860>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'after': <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700>}
DEBUG:tsdm.utils.decorators._decorators:<function wrap_method at 0x7f4e388fcd60>: Decorator in FUNCTIONAL/BARE mode.
DEBUG:tsdm.utils.decorators._decorators:Adding post hook <function BaseEncoder._post_fit_hook at 0x7f4e0e25a700> to <function FloatEncoder.fit at 0x7f4e0df64ae0>
DEBUG:tsdm.utils.decorators._decorators:DECORATING
	func=<function wrap_method at 0x7f4e388fcd60>:
	args=(),
	kwargs={'before': <function BaseEncoder._pre_encode_hook at 0x7f4e0e25a7a0>}

In [2]:
d = dict(zip("abc", range(3)))

In [19]:
[x for pair in [(k, v) for k, v in d.items()] for x in pair]

['a', 0, 'b', 1, 'c', 2]

In [16]:
l =

In [15]:
[x for (z:=(k, v)) for k, v in d.items() for x in z]

SyntaxError: cannot assign to named expression (1069730840.py, line 1)

In [5]:
self.dataset_paths

{'timeseries': PosixPath('/home/rscholz/.tsdm/datasets/USHCN/timeseries.parquet'),
 'metadata': PosixPath('/home/rscholz/.tsdm/datasets/USHCN/metadata.parquet'),
 'state_codes': PosixPath('/home/rscholz/.tsdm/datasets/USHCN/state_codes.parquet')}

In [6]:
self.dataset_files_exist(key="timeseries")

True

In [7]:
self = USHCN()

INFO:tsdm.datasets.ushcn.USHCN:Adding keys as attributes.
DEBUG:tsdm.datasets.ushcn.USHCN:Starting to load  dataset.
DEBUG:tsdm.datasets.ushcn.USHCN:Dataset already exists, skipping! <timeseries>
DEBUG:tsdm.datasets.ushcn.USHCN:Dataset already exists, skipping! <metadata>
DEBUG:tsdm.datasets.ushcn.USHCN:Dataset already exists, skipping! <state_codes>
DEBUG:tsdm.datasets.ushcn.USHCN:Finished loading  dataset.
DEBUG:tsdm.utils.strings:config={'object': 'list', 'size': 5, 'align': True, 'identifier': '', 'indent': 0, 'linebreaks': False, 'maxitems': 5, 'padding': 4, 'recursive': 1, 'repr_fun': <function repr_object at 0x7f4e38a4e5c0>, 'title': ''}
DEBUG:tsdm.utils.strings:config={'object': 'list', 'size': 9, 'align': True, 'identifier': '', 'indent': 0, 'linebreaks': False, 'maxitems': 5, 'padding': 4, 'recursive': 1, 'repr_fun': <function repr_object at 0x7f4e38a4e5c0>, 'title': ''}
DEBUG:tsdm.utils.strings:config={'object': 'list', 'size': 3, 'align': True, 'identifier': '', 'indent': 0, 'linebreaks': False, 'maxitems': 5, 'padding': 4, 'recursive': 1, 'repr_fun': <function repr_object at 0x7f4e38a4e5c0>, 'title': ''}
DEBUG:tsdm.utils.strings:config={'object': 'LazyDict', 'size': 3, 'align': True, 'identifier': '<mapping>', 'indent': 0, 'linebreaks': True, 'maxitems': 20, 'padding': 4, 'recursive': 1, 'repr_fun': <function repr_object at 0x7f4e38a4e5c0>, 'title': 'USHCN'}

USHCN<mapping>(
    timeseries : DataFrame[(199370091, 5), [category, category, category, category, int16[pyarrow]]],
    metadata   : DataFrame[(1218, 9), [float32, float32, ..., Int32, Int32, timedelta64[ns]]],
    state_codes: DataFrame[(48, 3), [category, category, string]]
)

In [4]:
self = USHCN(initialize=False)

INFO:tsdm.datasets.ushcn.USHCN:Adding keys as attributes.
DEBUG:tsdm.utils.strings:config={'object': 'LazyDict', 'size': 3, 'align': True, 'identifier': '<mapping>', 'indent': 0, 'linebreaks': True, 'maxitems': 20, 'padding': 4, 'recursive': 1, 'repr_fun': <function repr_object at 0x7f4e38a4e5c0>, 'title': 'USHCN'}

USHCN<mapping>(
    timeseries : LazyFunction<pandas.core.series.Series | pandas.core.frame.DataFrame>(),
    metadata   : LazyFunction<pandas.core.series.Series | pandas.core.frame.DataFrame>(),
    state_codes: LazyFunction<pandas.core.series.Series | pandas.core.frame.DataFrame>()
)

In [2]:
ts = self._clean_timeseries()

In [7]:
md = self._clean_metadata()

AttributeError: 'tuple' object has no attribute 'exists'

In [3]:
ts

                   ELEMENT MFLAG QFLAG SFLAG  VALUE
COOP_ID DATE
011084  1926-01-01    SNOW   NaN   NaN     6      0
        1926-01-02    SNOW   NaN   NaN     6      0
        1926-01-03    SNOW   NaN   NaN     6      0
        1926-01-04    SNOW   NaN   NaN     6      0
        1926-01-05    SNOW   NaN   NaN     6      0
...                    ...   ...   ...   ...    ...
489905  2014-12-31    PRCP   NaN   NaN     7      0
        2014-12-31    SNOW   NaN   NaN     7      0
        2014-12-31    SNWD   NaN   NaN     7      7
        2014-12-31    TMAX   NaN   NaN     7      1
        2014-12-31    TMIN   NaN   NaN     7    -18

[199370091 rows x 5 columns]

In [8]:
ts = ts.reset_index().astype({"COOP_ID" : "string"})

          COOP_ID       DATE ELEMENT MFLAG QFLAG SFLAG  VALUE
0          011084 1926-01-01    SNOW   NaN   NaN     6      0
1          011084 1926-01-02    SNOW   NaN   NaN     6      0
2          011084 1926-01-03    SNOW   NaN   NaN     6      0
...           ...        ...     ...   ...   ...   ...    ...
199370088  489905 2014-12-31    SNWD   NaN   NaN     7      7
199370089  489905 2014-12-31    TMAX   NaN   NaN     7      1
199370090  489905 2014-12-31    TMIN   NaN   NaN     7    -18

[199370091 rows x 7 columns]

In [4]:
ts.to_parquet("test")

In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("test")

In [9]:
df.set_index(["COOP_ID", "DATE"]).to_parquet("demo")

In [3]:
import pyarrow.parquet

In [5]:
pyarrow.parquet.read_table("demo")

pyarrow.Table
ELEMENT: dictionary<values=string, indices=int32, ordered=0>
MFLAG: dictionary<values=string, indices=int32, ordered=0>
QFLAG: dictionary<values=string, indices=int32, ordered=0>
SFLAG: dictionary<values=string, indices=int32, ordered=0>
VALUE: int16
COOP_ID: dictionary<values=string, indices=int32, ordered=0>
DATE: timestamp[us]
----
ELEMENT: [  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[1,1,1,1,1,...,1,2,1,2,1],  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[2,1,2,0,1,...,4,0,1,2,3],...,  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[1,2,3,4,0,...,1,2,3,4,0],  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[1,2,3,4,0,...,0,1,2,3,4]]
MFLAG: [  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[null,null,null,null,null,...,6,6,6,6,6],  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[6,6,6,null,6,...,null,6,6,6,null],...,  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null]]
QFLAG: [  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],...,  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null]]
SFLAG: [  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[1,1,1,1,1,...,0,0,0,0,0],  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0],...,  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[8,8,8,8,8,...,0,0,0,0,0],  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[0,0,0,0,0,...,2,2,2,2,2]]
VALUE: [[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,38,0,...,55,0,0,0,69],...,[0,0,96,52,0,...,0,0,80,38,0],[0,0,78,41,0,...,0,0,7,1,-18]]
COOP_ID: [  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0],  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[0,0,0,0,0,...,1,1,1,1,1],...,  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[1216,1216,1216,1216,1216,...,1217,1217,1217,1217,1217],  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[1217,1217,1217,1217,1217,...,1217,1217,1217,1217,1217]]
DATE: [[1926-01-01 00:00:00.000000,1926-01-02 00:00:00.000000,1926-01-03 00:00:00.000000,1926-01-04 00:00:00.000000,1926-01-05 00:00:00.000000,...,1999-09-01 00:00:00.000000,1999-09-01 00:00:00.000000,1999-09-02 00:00:00.000000,1999-09-02 00:00:00.000000,1999-09-03 00:00:00.000000],[1999-09-03 00:00:00.000000,1999-09-04 00:00:00.000000,1999-09-04 00:00:00.000000,1999-09-05 00:00:00.000000,1999-09-05 00:00:00.000000,...,1990-11-17 00:00:00.000000,1990-11-18 00:00:00.000000,1990-11-18 00:00:00.000000,1990-11-18 00:00:00.000000,1990-11-18 00:00:00.000000],...,[2011-08-24 00:00:00.000000,2011-08-24 00:00:00.000000,2011-08-24 00:00:00.000000,2011-08-24 00:00:00.000000,2011-08-25 00:00:00.000000,...,2009-09-25 00:00:00.000000,2009-09-25 00:00:00.000000,2009-09-25 00:00:00.000000,2009-09-25 00:00:00.000000,2009-09-26 00:00:00.000000],[2009-09-26 00:00:00.000000,2009-09-26 00:00:00.000000,2009-09-26 00:00:00.000000,2009-09-26 00:00:00.000000,2009-09-27 00:00:00.000000,...,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000]]

In [4]:
pyarrow.parquet.read_table("test")

pyarrow.Table
COOP_ID: dictionary<values=string, indices=int32, ordered=0>
DATE: timestamp[us]
ELEMENT: dictionary<values=string, indices=int32, ordered=0>
MFLAG: dictionary<values=string, indices=int32, ordered=0>
QFLAG: dictionary<values=string, indices=int32, ordered=0>
SFLAG: dictionary<values=string, indices=int32, ordered=0>
VALUE: int16
----
COOP_ID: [  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0],  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[0,0,0,0,0,...,1,1,1,1,1],...,  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[1216,1216,1216,1216,1216,...,1217,1217,1217,1217,1217],  -- dictionary:
["011084","012813","013160","013511","013816",...,"488160","488995","489615","489770","489905"]  -- indices:
[1217,1217,1217,1217,1217,...,1217,1217,1217,1217,1217]]
DATE: [[1926-01-01 00:00:00.000000,1926-01-02 00:00:00.000000,1926-01-03 00:00:00.000000,1926-01-04 00:00:00.000000,1926-01-05 00:00:00.000000,...,1999-09-01 00:00:00.000000,1999-09-01 00:00:00.000000,1999-09-02 00:00:00.000000,1999-09-02 00:00:00.000000,1999-09-03 00:00:00.000000],[1999-09-03 00:00:00.000000,1999-09-04 00:00:00.000000,1999-09-04 00:00:00.000000,1999-09-05 00:00:00.000000,1999-09-05 00:00:00.000000,...,1990-11-17 00:00:00.000000,1990-11-18 00:00:00.000000,1990-11-18 00:00:00.000000,1990-11-18 00:00:00.000000,1990-11-18 00:00:00.000000],...,[2011-08-24 00:00:00.000000,2011-08-24 00:00:00.000000,2011-08-24 00:00:00.000000,2011-08-24 00:00:00.000000,2011-08-25 00:00:00.000000,...,2009-09-25 00:00:00.000000,2009-09-25 00:00:00.000000,2009-09-25 00:00:00.000000,2009-09-25 00:00:00.000000,2009-09-26 00:00:00.000000],[2009-09-26 00:00:00.000000,2009-09-26 00:00:00.000000,2009-09-26 00:00:00.000000,2009-09-26 00:00:00.000000,2009-09-27 00:00:00.000000,...,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000,2014-12-31 00:00:00.000000]]
ELEMENT: [  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[1,1,1,1,1,...,1,2,1,2,1],  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[2,1,2,0,1,...,4,0,1,2,3],...,  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[1,2,3,4,0,...,1,2,3,4,0],  -- dictionary:
["PRCP","SNOW","SNWD","TMAX","TMIN"]  -- indices:
[1,2,3,4,0,...,0,1,2,3,4]]
MFLAG: [  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[null,null,null,null,null,...,6,6,6,6,6],  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[6,6,6,null,6,...,null,6,6,6,null],...,  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],  -- dictionary:
["B","D","H","K","L","O","P","T","W"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null]]
QFLAG: [  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],...,  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null],  -- dictionary:
["D","G","I","K","L",...,"S","T","W","X","Z"]  -- indices:
[null,null,null,null,null,...,null,null,null,null,null]]
SFLAG: [  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[1,1,1,1,1,...,0,0,0,0,0],  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0],...,  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[8,8,8,8,8,...,0,0,0,0,0],  -- dictionary:
["0","6","7","A","B",...,"T","U","W","X","Z"]  -- indices:
[0,0,0,0,0,...,2,2,2,2,2]]
VALUE: [[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,38,0,...,55,0,0,0,69],...,[0,0,96,52,0,...,0,0,80,38,0],[0,0,78,41,0,...,0,0,7,1,-18]]

In [ ]:
class USHCN(BaseDataset):
    url = "https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/"

# USHCN.download()

# State Codes

In [ ]:
# Best viewed with elastic tabstops!
from io import StringIO

STATE_CODES = r"""
ID	Abbr.	State
01	AL	Alabama
02	AZ	Arizona
03	AR	Arkansas
04	CA	California
05	CO	Colorado
06	CT	Connecticut
07	DE	Delaware
08	FL	Florida
09	GA	Georgia
10	ID	Idaho
11	IL	Idaho
12	IN	Indiana
13	IA	Iowa
14	KS	Kansas
15	KY	Kentucky
16	LA	Louisiana
17	ME	Maine
18	MD	Maryland
19	MA	Massachusetts
20	MI	Michigan
21	MN	Minnesota
22	MS	Mississippi
23	MO	Missouri
24	MT	Montana
25	NE	Nebraska
26	NV	Nevada
27	NH	NewHampshire
28	NJ	NewJersey
29	NM	NewMexico
30	NY	NewYork
31	NC	NorthCarolina
32	ND	NorthDakota
33	OH	Ohio
34	OK	Oklahoma
35	OR	Oregon
36	PA	Pennsylvania
37	RI	RhodeIsland
38	SC	SouthCarolina
39	SD	SouthDakota
40	TN	Tennessee
41	TX	Texas
42	UT	Utah
43	VT	Vermont
44	VA	Virginia
45	WA	Washington
46	WV	WestVirginia
47	WI	Wisconsin
48	WY	Wyoming
"""


state_dtypes = {
    "ID": pandas.CategoricalDtype(ordered=True),
    "Abbr.": pandas.CategoricalDtype(ordered=True),
    "State": pandas.StringDtype(),
}
states = pandas.read_csv(StringIO(STATE_CODES), sep="\t", dtype=state_dtypes)

In [ ]:
states.to_parquet("a.pq")
states2 = pandas.read_parquet("a.pq")
pandas.testing.assert_frame_equal(states, states2)

# Stations Meta-Data

In [ ]:
station_colspecs = {
    "COOP_ID": (1, 6),
    "LATITUDE": (8, 15),
    "LONGITUDE": (17, 25),
    "ELEVATION": (27, 32),
    "STATE": (34, 35),
    "NAME": (37, 66),
    "COMPONENT_1": (68, 73),
    "COMPONENT_2": (75, 80),
    "COMPONENT_3": (82, 87),
    "UTC_OFFSET": (89, 90),
}

# fix colspec to 0-index, half open interval
station_colspecs = {key: (a - 1, b) for key, (a, b) in station_colspecs.items()}

station_dtypes = {
    "COOP_ID": pandas.CategoricalDtype(ordered=True),
    "LATITUDE": pandas.Float32Dtype(),
    "LONGITUDE": pandas.Float32Dtype(),
    "ELEVATION": pandas.Float32Dtype(),
    "STATE": states.ID.dtype,
    "NAME": pandas.StringDtype(),
    "COMPONENT_1": pandas.CategoricalDtype(ordered=True),
    "COMPONENT_2": pandas.CategoricalDtype(ordered=True),
    "COMPONENT_3": pandas.CategoricalDtype(ordered=True),
    "UTC_OFFSET": "timedelta64[h]",
}

station_na_values = {
    "ELEVATION": -999.9,
    "COMPONENT_1": "------",
    "COMPONENT_2": "------",
    "COMPONENT_3": "------",
}

In [ ]:
stations_filename = "ushcn-stations.txt"
stations_filepath = USHCN.rawdata_dir.joinpath(stations_filename)
stations = pandas.read_fwf(
    stations_filepath,
    na_values=station_na_values,
    colspecs=list(station_colspecs.values()),
    header=0,
    names=station_colspecs,
    dtype=station_dtypes,
)
COOP_IDS = pandas.CategoricalDtype(stations.COOP_ID, ordered=True)
stations.astype(
    {
        "COOP_ID": COOP_IDS,
        "COMPONENT_1": COOP_IDS,
        "COMPONENT_2": COOP_IDS,
        "COMPONENT_3": COOP_IDS,
    }
)

# Station Data

In [ ]:
MFLAGS = pandas.CategoricalDtype(("B", "D", "H", "K", "L", "O", "P", "T", "W"))
QFLAGS = pandas.CategoricalDtype(
    ("D", "G", "I", "K", "L", "M", "N", "O", "R", "S", "T", "W", "X", "Z")
)
SFLAGS = pandas.CategoricalDtype(
    (
        "0",
        "6",
        "7",
        "A",
        "B",
        "F",
        "G",
        "H",
        "K",
        "M",
        "N",
        "R",
        "S",
        "T",
        "U",
        "W",
        "X",
        "Z",
    )
)
ELEMENTS = pandas.CategoricalDtype(("PRCP", "SNOW", "SNWD", "TMAX", "TMIN"))


dtypes = {
    "COOP_ID": COOP_IDS,
    "YEAR": pandas.UInt16Dtype(),
    "MONTH": pandas.UInt8Dtype(),
    "ELEMENT": ELEMENTS,
    "VALUE": pandas.Int16Dtype(),
    "MFLAG": MFLAGS,
    "QFLAG": QFLAGS,
    "SFLAG": SFLAGS,
}

# column start, stop, dtype
colspecs = {
    "COOP_ID": (1, 6),
    "YEAR": (7, 10),
    "MONTH": (11, 12),
    "ELEMENT": (13, 16),
}

for k, i in enumerate(range(17, 258, 8)):
    colspecs |= {
        ("VALUE", k + 1): (i, i + 4),
        ("MFLAG", k + 1): (i + 5, i + 5),
        ("QFLAG", k + 1): (i + 6, i + 6),
        ("SFLAG", k + 1): (i + 7, i + 7),
    }

    # dtype |= {
    #     f"VALUE-{k+1}" : integer,
    #     f"MFLAG-{k+1}" : mflag_types,
    #     f"QFLAG-{k+1}" : qflag_types,
    #     f"SFLAG-{k+1}" : sflag_types,
    # }


# These should coincide with the description in data_format.txt
widths = [b - a + 1 for a, b in colspecs.values()]
dtype = {
    key: (dtypes[key[0]] if isinstance(key, tuple) else dtypes[key]) for key in colspecs
}

cspec = [(a - 1, b - 1) for a, b in colspecs.values()]
na_values = {("VALUE", k): -9999 for k in range(1, 32)}
# ds = pandas.read_fwf("state32.txt", names=colspecs, widths=widths, header=None, dtype=dtype, na_values=-9999)

In [ ]:
from zipfile import ZipFile
import gzip

fname = "state01_AL.txt"
fpath = USHCN.rawdata_dir.joinpath("us.txt")

In [ ]:
from modin import pandas as pd

In [ ]:
%%time
ds = pd.read_fwf(
    fpath, names=colspecs, widths=widths, header=None, dtype=dtype, na_values=-9999
)

In [ ]:
times = ds[["YEAR", "MONTH"]]

In [ ]:
pd.to_datetime(times, errors="coerce")

In [ ]:
daskframe.from_pandas(ds._to_pandas(), chunksize=12)

In [ ]:
%%time
with gzip.open(fpath) as file:
    ds = pandas.read_fwf(
        file, names=colspecs, widths=widths, header=None, dtype=dtype, na_values=-9999
    )

ds

In [ ]:
ds[("QFLAG", 1)].fill_na

# preprocessing the data

In [ ]:
id_cols = ["COOP_ID", "YEAR", "MONTH", "ELEMENT"]
data_cols = ["VALUE", "MFLAG", "QFLAG", "SFLAG"]
data_cols = [col for col in ds.columns if col not in id_cols]
columns = pandas.MultiIndex.from_tuples(ds[data_cols], names=["VAR", "DAY"])
data = pandas.DataFrame(ds[data_cols], columns=columns)
data.index.name = "INDEX"
data

In [ ]:
%%time
# Pure magic https://stackoverflow.com/a/27044843/9318372
data = data.stack(level="DAY", dropna=False).reset_index(level="DAY")

In [ ]:
%%time
data = ds[id_cols].join(data, how="inner").reset_index()
data = data.astype(dtypes | {"DAY": integer})
data = data[
    ["COOP_ID", "YEAR", "MONTH", "DAY", "ELEMENT", "MFLAG", "QFLAG", "SFLAG", "VALUE"]
]

In [ ]:
%%time
mask = pandas.isna(data[["MFLAG", "QFLAG", "SFLAG", "VALUE"]]).sum(axis=1) < 4
data = data[mask]
data = data.sort_values(by=["YEAR", "MONTH", "DAY", "COOP_ID", "ELEMENT"]).reset_index(
    drop=True
)
data

# ALternative: Use Modin for speedup

In [ ]:
import os

os.environ["MODIN_ENGINE"] = "ray"
from modin import pandas as pd

In [ ]:
import sys

In [ ]:
{"ray", "modin"} <= sys.modules.keys()

In [ ]:
import os
import ray

In [ ]:
ray.init(num_cpus=os.cpu_count() - 2)

os.environ["MODIN_ENGINE"] = "ray"  # Modin will use Ray
# os.environ["MODIN_ENGINE"] = "dask"  # Modin will use Dask

In [ ]:
# problem: currently only works uncompressed.

from modin import pandas as pd

fname = "us.txt"
fpath2 = USHCN.rawdata_path.joinpath(fname)

In [ ]:
%%time
ds = pd.read_fwf(
    fpath2, names=colspecs, widths=widths, header=None, na_values=-9999, dtype=dtype
)

In [ ]:
id_cols = ["COOP_ID", "YEAR", "MONTH", "ELEMENT"]
data_cols = ["VALUE", "MFLAG", "QFLAG", "SFLAG"]
data_cols = [col for col in ds.columns if col not in id_cols]
columns = pd.MultiIndex.from_tuples(ds[data_cols], names=["VAR", "DAY"])
data = pd.DataFrame(ds[data_cols])
data.columns = columns
data

In [ ]:
%%time
# Pure magic https://stackoverflow.com/a/27044843/9318372
data = data.stack(level="DAY", dropna=True).reset_index(level="DAY")

In [ ]:
%%time
_dtypes = {k: v for k, v in dtypes.items() if k in data.columns} | {
    "DAY": pandas.UInt8Dtype()
}
data = data.astype(_dtypes)

In [ ]:
%%time
data = ds[id_cols].join(data, how="inner")

In [ ]:
data.info()

In [ ]:
data[["COOP_ID"]].info()

In [ ]:
data = data.reset_index(drop=True)

In [ ]:
data.to_parquet(USHCN.dataset_file)

In [ ]:
%%time
data = data[
    ["COOP_ID", "YEAR", "MONTH", "DAY", "ELEMENT", "MFLAG", "QFLAG", "SFLAG", "VALUE"]
]
data = data.sort_values(by=["YEAR", "MONTH", "DAY", "COOP_ID", "ELEMENT"]).reset_index(
    drop=True
)

In [ ]:
%%time
df2 = pd.read_feather(USHCN.dataset_path.joinpath("USHCN.feather"))

In [ ]:
%%time
df2 = pd.read_parquet(USHCN.dataset_path.joinpath("USHCN.parquet"))

In [ ]:
%%time
mask = pandas.isna(data[["MFLAG", "QFLAG", "SFLAG", "VALUE"]]).sum(axis=1) < 4
data = data[mask]
data