# SocialTimeEncoder

This encoder converts a datetime to categoricals (day, weekday, month, year)
Optionally one may add categorical indicators for holidays etc.

In [3]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging

import matplotlib.pyplot as plt
import numpy as np

np.set_printoptions(precision=4, floatmode="fixed", suppress=True)
rng = np.random.default_rng()
logging.basicConfig(level=logging.INFO)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [149]:
import pandas as pd

datetimes = pd.date_range("1970", "1973", freq="4h").to_series()
datetimes = datetimes.reset_index(drop=True)

0      1970-01-01 00:00:00
1      1970-01-01 04:00:00
2      1970-01-01 08:00:00
3      1970-01-01 12:00:00
4      1970-01-01 16:00:00
               ...
6572   1972-12-31 08:00:00
6573   1972-12-31 12:00:00
6574   1972-12-31 16:00:00
6575   1972-12-31 20:00:00
6576   1973-01-01 00:00:00
Length: 6577, dtype: datetime64[ns]

In [113]:
weekdays = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6,
}
weekday_type = pd.CategoricalDtype(pd.Series(weekdays.keys(), dtype="string"), ordered=True)

CategoricalDtype(categories=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
                  'Saturday', 'Sunday'],
, ordered=True)

In [114]:
months = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12,
}

month_type = pd.CategoricalDtype(pd.Series(months.keys(), dtype="string"), ordered=True)

CategoricalDtype(categories=['January', 'February', 'March', 'April', 'May', 'June',
                  'July', 'August', 'September', 'October', 'November',
                  'December'],
, ordered=True)

In [115]:
pd.Series(months, dtype="string")

January       1
February      2
March         3
April         4
May           5
June          6
July          7
August        8
September     9
October      10
November     11
December     12
dtype: string

In [155]:
import inspect

In [217]:
timedeltas

0         0 days 00:00:00
1         0 days 04:00:00
2         0 days 08:00:00
3         0 days 12:00:00
4         0 days 16:00:00
              ...
6572   1095 days 08:00:00
6573   1095 days 12:00:00
6574   1095 days 16:00:00
6575   1095 days 20:00:00
6576   1096 days 00:00:00
Length: 6577, dtype: timedelta64[ns]

In [170]:
timedeltas = datetimes - datetimes[0]

0         0 days 00:00:00
1         0 days 04:00:00
2         0 days 08:00:00
3         0 days 12:00:00
4         0 days 16:00:00
              ...
6572   1095 days 08:00:00
6573   1095 days 12:00:00
6574   1095 days 16:00:00
6575   1095 days 20:00:00
6576   1096 days 00:00:00
Length: 6577, dtype: timedelta64[ns]

In [222]:
str(vars(timedeltas)).split(",")[1:]

[" '_mgr': SingleBlockManager\nItems: RangeIndex(start=0",
 ' stop=6577',
 ' step=1)\nDatetimeLikeBlock: 6577 dtype: timedelta64[ns]',
 " '_item_cache': {}",
 " '_attrs': {}",
 " '_flags': <Flags(allows_duplicate_labels=True)>",
 " '_name': None",
 " '_index': RangeIndex(start=0",
 ' stop=6577',
 ' step=1)',
 " 'dt': <pandas.core.indexes.accessors.TimedeltaProperties object at 0x7f1643f37550>}"]

In [216]:
timedeltas.dt.components

      days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0        0      0        0        0             0             0            0
1        0      4        0        0             0             0            0
2        0      8        0        0             0             0            0
3        0     12        0        0             0             0            0
4        0     16        0        0             0             0            0
...    ...    ...      ...      ...           ...           ...          ...
6572  1095      8        0        0             0             0            0
6573  1095     12        0        0             0             0            0
6574  1095     16        0        0             0             0            0
6575  1095     20        0        0             0             0            0
6576  1096      0        0        0             0             0            0

[6577 rows x 7 columns]

In [206]:
datetimes.dt.nanosecond

0       0
1       0
2       0
3       0
4       0
       ..
6572    0
6573    0
6574    0
6575    0
6576    0
Length: 6577, dtype: int64

In [174]:
set(dir(timedeltas.dt)) - set(dir(datetimes.dt))

{'components',
 'days',
 'microseconds',
 'nanoseconds',
 'seconds',
 'to_pytimedelta',
 'total_seconds'}

In [187]:
set(dir(datetimes.dt)) - set(dir(timedeltas.dt))

{'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'microsecond',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'quarter',
 'second',
 'strftime',
 'time',
 'timetz',
 'to_period',
 'to_pydatetime',
 'tz',
 'tz_convert',
 'tz_localize',
 'week',
 'weekday',
 'weekofyear',
 'year'}

In [184]:
td = pd.Index(timedeltas)
dt = pd.Index(datetimes)

DatetimeIndex(['1970-01-01 00:00:00', '1970-01-01 04:00:00',
               '1970-01-01 08:00:00', '1970-01-01 12:00:00',
               '1970-01-01 16:00:00', '1970-01-01 20:00:00',
               '1970-01-02 00:00:00', '1970-01-02 04:00:00',
               '1970-01-02 08:00:00', '1970-01-02 12:00:00',
               ...
               '1972-12-30 12:00:00', '1972-12-30 16:00:00',
               '1972-12-30 20:00:00', '1972-12-31 00:00:00',
               '1972-12-31 04:00:00', '1972-12-31 08:00:00',
               '1972-12-31 12:00:00', '1972-12-31 16:00:00',
               '1972-12-31 20:00:00', '1973-01-01 00:00:00'],
              dtype='datetime64[ns]', length=6577, freq=None)

In [185]:
set(dir(td)) - set(dir(dt))

{'components',
 'days',
 'median',
 'microseconds',
 'nanoseconds',
 'seconds',
 'sum',
 'to_pytimedelta',
 'total_seconds'}

In [186]:
set(dir(dt)) - set(dir(td))

{'_datetimelike_methods',
 '_datetimelike_ops',
 '_deprecate_mismatched_indexing',
 '_get_time_micros',
 '_has_same_tz',
 '_is_dates_only',
 '_maybe_cast_for_get_loc',
 '_object_ops',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'hour',
 'indexer_at_time',
 'indexer_between_time',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_normalized',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'microsecond',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'quarter',
 'second',
 'snap',
 'strftime',
 'time',
 'timetz',
 'to_julian_date',
 'to_period',
 'to_perioddelta',
 'to_pydatetime',
 'tz',
 'tz_convert',
 'tz_localize',
 'tzinfo',
 'union_many',
 'week',
 'weekday',
 'weekofyear',
 'year'}

In [161]:
inspect.getsource(datetimes.__dict__["dt"])

TypeError: module, class, method, function, traceback, frame, or code object was expected, got DatetimeProperties

In [159]:
datetimes.dt

In [152]:
dir(datetimes.dt)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_add_delegate_accessors',
 '_constructor',
 '_delegate_method',
 '_delegate_property_get',
 '_delegate_property_set',
 '_dir_additions',
 '_dir_deletions',
 '_freeze',
 '_get_values',
 '_hidden_attrs',
 '_parent',
 '_reset_cache',
 'ceil',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'floor',
 'freq',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'microsecond',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'quarter',
 'round',
 'second',
 'strftime',
 'time',
 'timetz',
 'to_period',
 'to_pydatetime',
 'tz',
 'tz_convert',
 'tz_localize',
 'week',
 'weekday',
 'weekofyear',
 'year']

In [142]:
ns = datetimes.dt.components

AttributeError: 'DatetimeProperties' object has no attribute 'components'

In [140]:
ms = datetimes.dt.microsecond

1970-01-01 00:00:00    0
1970-01-01 04:00:00    0
1970-01-01 08:00:00    0
1970-01-01 12:00:00    0
1970-01-01 16:00:00    0
                      ..
1972-12-31 08:00:00    0
1972-12-31 12:00:00    0
1972-12-31 16:00:00    0
1972-12-31 20:00:00    0
1973-01-01 00:00:00    0
Freq: 4H, Length: 6577, dtype: int64

In [116]:
second = datetimes.dt.second

1970-01-01 00:00:00    0
1970-01-01 04:00:00    0
1970-01-01 08:00:00    0
1970-01-01 12:00:00    0
1970-01-01 16:00:00    0
                      ..
1972-12-31 08:00:00    0
1972-12-31 12:00:00    0
1972-12-31 16:00:00    0
1972-12-31 20:00:00    0
1973-01-01 00:00:00    0
Freq: 4H, Length: 6577, dtype: int64

In [117]:
minute = datetimes.dt.minute

1970-01-01 00:00:00    0
1970-01-01 04:00:00    0
1970-01-01 08:00:00    0
1970-01-01 12:00:00    0
1970-01-01 16:00:00    0
                      ..
1972-12-31 08:00:00    0
1972-12-31 12:00:00    0
1972-12-31 16:00:00    0
1972-12-31 20:00:00    0
1973-01-01 00:00:00    0
Freq: 4H, Length: 6577, dtype: int64

In [41]:
hour = datetimes.dt.hour

1970-01-01 00:00:00     0
1970-01-01 04:00:00     4
1970-01-01 08:00:00     8
1970-01-01 12:00:00    12
1970-01-01 16:00:00    16
                       ..
1972-12-31 08:00:00     8
1972-12-31 12:00:00    12
1972-12-31 16:00:00    16
1972-12-31 20:00:00    20
1973-01-01 00:00:00     0
Freq: 4H, Length: 6577, dtype: int64

In [121]:
day = datetimes.dt.day

1970-01-01 00:00:00     1
1970-01-01 04:00:00     1
1970-01-01 08:00:00     1
1970-01-01 12:00:00     1
1970-01-01 16:00:00     1
                       ..
1972-12-31 08:00:00    31
1972-12-31 12:00:00    31
1972-12-31 16:00:00    31
1972-12-31 20:00:00    31
1973-01-01 00:00:00     1
Freq: 4H, Length: 6577, dtype: int64

In [122]:
weekday = datetimes.dt.day_name().astype(weekday_type)

1970-01-01 00:00:00    Thursday
1970-01-01 04:00:00    Thursday
1970-01-01 08:00:00    Thursday
1970-01-01 12:00:00    Thursday
1970-01-01 16:00:00    Thursday
                         ...
1972-12-31 08:00:00      Sunday
1972-12-31 12:00:00      Sunday
1972-12-31 16:00:00      Sunday
1972-12-31 20:00:00      Sunday
1973-01-01 00:00:00      Monday
Freq: 4H, Length: 6577, dtype: category
Categories (7, object): ['Monday' < 'Tuesday' < 'Wednesday' < 'Thursday' < 'Friday' < 'Saturday' < 'Sunday']

In [136]:
weekend = weekday.isin(["Saturday", "Sunday"])

1970-01-01 00:00:00    False
1970-01-01 04:00:00    False
1970-01-01 08:00:00    False
1970-01-01 12:00:00    False
1970-01-01 16:00:00    False
                       ...
1972-12-31 08:00:00     True
1972-12-31 12:00:00     True
1972-12-31 16:00:00     True
1972-12-31 20:00:00     True
1973-01-01 00:00:00    False
Freq: 4H, Length: 6577, dtype: bool

In [123]:
month = datetimes.dt.month_name().astype(month_type)

1970-01-01 00:00:00     January
1970-01-01 04:00:00     January
1970-01-01 08:00:00     January
1970-01-01 12:00:00     January
1970-01-01 16:00:00     January
                         ...
1972-12-31 08:00:00    December
1972-12-31 12:00:00    December
1972-12-31 16:00:00    December
1972-12-31 20:00:00    December
1973-01-01 00:00:00     January
Freq: 4H, Length: 6577, dtype: category
Categories (12, object): ['January' < 'February' < 'March' < 'April' ... 'September' < 'October' < 'November' < 'December']

In [124]:
year = datetimes.dt.year

1970-01-01 00:00:00    1970
1970-01-01 04:00:00    1970
1970-01-01 08:00:00    1970
1970-01-01 12:00:00    1970
1970-01-01 16:00:00    1970
                       ...
1972-12-31 08:00:00    1972
1972-12-31 12:00:00    1972
1972-12-31 16:00:00    1972
1972-12-31 20:00:00    1972
1973-01-01 00:00:00    1973
Freq: 4H, Length: 6577, dtype: int64

In [125]:
levels = [
    "year",
    "month",
    "day",
    "hour",
    "minute",
    "second",
    "ms",
    "us",
    "ns",
]

levels = pd.CategoricalDtype(pd.Series(levels, dtype="string"), ordered=True)

CategoricalDtype(categories=['year', 'month', 'day', 'hour', 'minute', 'second', 'ms',
                  'us', 'ns'],
, ordered=True)

In [138]:
columns = {
    "year": year,
    "month": month,
    "day": day,
    "hour": hour,
    "minute": minute,
    "second": second,
    "weekday" : weekday,
    "weekend" : weekend,
    # "ms": ms,
    # "us": us,
    # "ns": ns,
    # weekend: bool
}

converted = pd.DataFrame(columns).reset_index(drop=True)

      year     month  day  hour  minute  second   weekday  weekend
0     1970   January    1     0       0       0  Thursday    False
1     1970   January    1     4       0       0  Thursday    False
2     1970   January    1     8       0       0  Thursday    False
3     1970   January    1    12       0       0  Thursday    False
4     1970   January    1    16       0       0  Thursday    False
...    ...       ...  ...   ...     ...     ...       ...      ...
6572  1972  December   31     8       0       0    Sunday     True
6573  1972  December   31    12       0       0    Sunday     True
6574  1972  December   31    16       0       0    Sunday     True
6575  1972  December   31    20       0       0    Sunday     True
6576  1973   January    1     0       0       0    Monday    False

[6577 rows x 8 columns]

In [134]:
converted.month = converted.month.map(months)

pd.to_datetime(converted[["year", "month", "day"]], infer_datetime_format=True)

0      1970-01-01
1      1970-01-01
2      1970-01-01
3      1970-01-01
4      1970-01-01
          ...
6572   1972-12-31
6573   1972-12-31
6574   1972-12-31
6575   1972-12-31
6576   1973-01-01
Length: 6577, dtype: datetime64[ns]

In [104]:
converted[["year", "month", "day"]]

      year month day
0     1970     0   3
1     1970     0   3
2     1970     0   3
3     1970     0   3
4     1970     0   3
...    ...   ...  ..
6572  1972    11   6
6573  1972    11   6
6574  1972    11   6
6575  1972    11   6
6576  1973     0   0

[6577 rows x 3 columns]

ValueError: Unable to parse string "January" at position 0

In [101]:
df = pd.DataFrame({'year': [2015, 2016],

                   'month': [2, 3],

                   'day': [4, 5]})

   year  month  day
0  2015      2    4
1  2016      3    5

In [106]:
df = pd.to_datetime(df)

0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

In [112]:
df.dt.day?

Type:        property
String form: <property object at 0x7f16455dfae0>
Docstring:
The day of the datetime.

Examples
--------
>>> datetime_series = pd.Series(
...     pd.date_range("2000-01-01", periods=3, freq="D")
... )
>>> datetime_series
0   2000-01-01
1   2000-01-02
2   2000-01-03
dtype: datetime64[ns]
>>> datetime_series.dt.day
0    1
1    2
2    3
dtype: int64